Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2018-10, with the labels that each got.

#2778 Refactor entry processor
  app/models/product_import/entry_processor.rb
  app/models/product_import/inventory_reset_strategy.rb
  app/models/product_import/products_reset_strategy.rb
  app/models/product_import/reset_absent.rb
  app/models/product_import/settings.rb
  spec/models/product_import/entry_processor_spec.rb
  spec/models/product_import/inventory_reset_strategy_spec.rb
  spec/models/product_import/products_reset_strategy_spec.rb
  spec/models/product_import/reset_absent_spec.rb
  spec/models/product_import/settings_spec.rb
Labels: tech debt

#2826 [README] Updated build status badge
  README.md
Labels: pr-no-test

#2858 Increase rubocop line limit to 100
  .rubocop.yml
Labels: pr-no-test

#2521 [OFN Domains] Breaking OFN into domains - POC cookies inside an engine
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/darkswarm/all.scss
  app/controllers/angular_templates_controller.rb
  app/controllers/api/cookies_consent_controller.rb
  app/helpers/cookies_policy_helper.rb
  app/helpers/footer_links_helper.rb
  app/services/cookies_consent.rb
  app/views/layouts/darkswarm.html.haml
  app/views/shared/_footer.html.haml
  config/application.rb
  config/routes.rb
  engines/web/README.md
  engines/web/app/assets/javascripts/web/all.js
  engines/web/app/assets/javascripts/web/cookies_banner/cookies_banner_controller.js.coffee
  engines/web/app/assets/javascripts/web/cookies_banner/cookies_banner_directive.js.coffee
  engines/web/app/assets/javascripts/web/cookies_banner/cookies_banner_service.js.coffee
  engines/web/app/assets/javascripts/web/cookies_policy/cookies_policy_modal_controller.js.coffee
  engines/web/app/assets/javascripts/web/cookies_policy/cookies_policy_modal_directive.js.coffee
  engines/web/app/assets/javascripts/web/cookies_policy/cookies_policy_modal_service.js.coffee
  engines/web/app/assets/javascripts/web/web.js
  engines/web/app/assets/stylesheets/web/all.css.scss
  engines/web/app/assets/stylesheets/web/pages/cookies_banner.css.scss
  engines/web/app/assets/stylesheets/web/pages/cookies_policy_modal.css.scss
  engines/web/app/controllers/web/angular_templates_controller.rb
  engines/web/app/controllers/web/api/cookies_consent_controller.rb
  engines/web/app/controllers/web/application_controller.rb
  engines/web/app/helpers/web/cookies_policy_helper.rb
  engines/web/app/views/web/angular_templates/_cookies_policy_entry.html.haml
  engines/web/app/views/web/angular_templates/cookies_banner.html.haml
  engines/web/app/views/web/angular_templates/cookies_policy.html.haml
  engines/web/config/routes.rb
  engines/web/lib/web.rb
  engines/web/lib/web/cookies_consent.rb
  engines/web/lib/web/engine.rb
  engines/web/lib/web/version.rb
  engines/web/spec/helpers/cookies_policy_helper_spec.rb
  engines/web/spec/spec_helper.rb
  engines/web/web.gemspec
  spec/helpers/cookies_policy_helper_spec.rb
Labels: tech debt

#2872 2765 Fix geocoding to display enterprises on map
  .rubocop_todo.yml
  app/models/spree/address_decorator.rb
  config/initializers/geocoder.rb
  spec/models/spree/addresses_spec.rb
Labels: pr-staged-au

#2818 Move query from variant_overrides_controller to its model scope
  app/controllers/admin/variant_overrides_controller.rb
  app/models/variant_override.rb
  spec/models/variant_override_spec.rb
Labels: tech debt

#2922 Update rubocop todo list
  .rubocop_todo.yml
Labels: pr-no-review, pr-no-test

#2928 Reorganize LineItemsController's destroy line item specs
  spec/controllers/line_items_controller_spec.rb
Labels: pr-no-test

#2949 Fix new preferences migration
  db/migrate/20120327000645_new_preferences.rb
Labels: pr-no-test
