Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2018-06, with the labels that each got.

#2322 Fixed issue #1913 with expand/collapse of list of producers of a shop
  app/views/shops/_fat.html.haml
Labels: pr-ready-to-go

#2337 Fix guest checkout login modal
  app/assets/javascripts/darkswarm/services/checkout.js.coffee
  app/assets/javascripts/darkswarm/services/navigation.js.coffee
Labels: pr-ready-to-go

#2348 Provide specific tab widths for shop tabs when screen width > medium
  app/helpers/shop_helper.rb
  app/views/shopping_shared/_tabs.html.haml
Labels: pr-ready-to-go

#2343 2212 remove report default filters
  .rubocop_todo.yml
  app/controllers/spree/admin/reports_controller_decorator.rb
  spec/lib/open_food_network/xero_invoices_report_spec.rb
Labels: pr-ready-to-go

#1969 Do not upcase State abbreviation
  app/serializers/api/state_serializer.rb
  spec/features/consumer/registration_spec.rb
Labels: bug-s4, pr-ready-to-go

#2293 Subs: retain open orders
  lib/open_food_network/proxy_order_syncer.rb
  spec/lib/open_food_network/proxy_order_syncer_spec.rb
Labels: pr-staged-au

#2361 2356 report search hint
  .rubocop_todo.yml
  app/assets/stylesheets/admin/reports.css.scss
  app/controllers/spree/admin/reports_controller_decorator.rb
  app/views/spree/admin/reports/_link_order.html.haml
  app/views/spree/admin/reports/_table.html.haml
  app/views/spree/admin/reports/bulk_coop.html.haml
  app/views/spree/admin/reports/customers.html.haml
  app/views/spree/admin/reports/order_cycle_management.html.haml
  app/views/spree/admin/reports/orders_and_distributors.html.haml
  app/views/spree/admin/reports/orders_and_fulfillment.html.haml
  app/views/spree/admin/reports/packing.html.haml
  app/views/spree/admin/reports/payments.html.haml
  app/views/spree/admin/reports/products_and_inventory.html.haml
  app/views/spree/admin/reports/sales_tax.html.haml
  app/views/spree/admin/reports/users_and_enterprises.html.haml
  app/views/spree/admin/reports/xero_invoices.html.haml
  config/locales/en.yml
  spec/features/admin/reports_spec.rb
Labels: pr-ready-to-go

#2341 fixed country_state selectors on checkout
  app/assets/javascripts/darkswarm/controllers/checkout/country_controller.js.coffee
  app/helpers/checkout_helper.rb
  app/views/checkout/_billing.html.haml
  app/views/checkout/_shipping_ship_address.html.haml
  app/views/checkout/edit.html.haml
Labels: pr-staged-au

#2335 Fixed missing translations on shops filter - delivery option
  app/assets/javascripts/darkswarm/directives/shipping_type_selector.js.coffee
  app/assets/javascripts/templates/shipping_type_selector.html.haml
Labels: pr-ready-to-go

#2345 removed uppercase from state on shops and producers lists in the frontoffice
  app/views/producers/_skinny.html.haml
  app/views/shops/_skinny.html.haml
Labels: pr-ready-to-go
