Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2018-05, with the labels that each got.

#2259 Remove Heroku references since nobody is using it
  .gitignore
  config/database.yml
  config/environments/development.rb
Labels: pr-no-test, tech debt

#2258 Fix initial password setting
  app/controllers/admin/manager_invitations_controller.rb
  spec/features/consumer/confirm_invitation_spec.rb
Labels: pr-staged-au

#2260 Improve order_and_distributor report's readability
  lib/open_food_network/order_and_distributor_report.rb
Labels: tech debt

#2261 Lowercase tag when adding a tag to the array
  app/assets/javascripts/admin/utils/directives/tags_with_translation.js.coffee
  app/assets/javascripts/templates/admin/tags_input.html.haml
Labels: pr-staged-au

#2269 Closes issue 1926, Changed package screen text from choose your start…
  config/locales/en.yml
Labels: pr-staged-au

#2270 Update activemerchant to v1.78 with new root cert
  Gemfile
  Gemfile.lock
Labels: pr-staged-au

#2268 Set response headers to disable cache - to avoid back button emptying…
  app/controllers/application_controller.rb
Labels: pr-staged-au

#2305 Ensure domain in SSL header matches request with or without www prefix
  app/controllers/application_controller.rb
  spec/requests/embedded_shopfronts_headers_spec.rb
Labels: pr-ready-to-go

#2298 Fix enterprise description display formatting
  app/assets/javascripts/templates/partials/enterprise_details.html.haml
Labels: pr-ready-to-go

#2317 Added missing translation key for no results in admin orders page
  config/locales/en.yml
Labels: pr-ready-to-go

#2318 Fixed broken translation keys in "new order cycle" screen
  app/views/admin/order_cycles/_name_and_timing_form.html.haml
  config/locales/en.yml
Labels: pr-ready-to-go

#2299 Add phone number to shopfront contact info
  app/views/shopping_shared/_contact.html.haml
Labels: pr-ready-to-go

#2332 Correct 'Next Order Closing' text in shopfront when switching OCs
  app/controllers/shop_controller.rb
  spec/controllers/shop_controller_spec.rb
Labels: pr-ready-to-go
