Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2019-01, with the labels that each got.

#3273 Fix menu_1_url translation for fr_BE
  config/locales/fr_BE.yml
Labels: pr-no-test

#3295 Update all locales with the latest Transifex translations
  config/locales/de_DE.yml
  config/locales/en_BE.yml
  config/locales/en_GB.yml
  config/locales/es.yml
  config/locales/fr.yml
  config/locales/fr_BE.yml
  config/locales/fr_CA.yml
  config/locales/it.yml
  config/locales/nb.yml
  config/locales/pt.yml
  config/locales/sv.yml
Labels: pr-no-test

#2988 Pi/utf8
  app/controllers/admin/product_import_controller.rb
  app/models/product_import/product_importer.rb
  config/locales/en.yml
Labels: pr-staged-au

#3072 Fix bug on calculator_decorator line_items_for where input is line_item with a nil order
  app/models/calculator/weight.rb
  app/models/spree/calculator_decorator.rb
  spec/features/consumer/shopping/cart_spec.rb
  spec/lib/open_food_network/enterprise_fee_calculator_spec.rb
  spec/models/calculator/weight_spec.rb
  spec/models/spree/calculator/flat_percent_item_total_spec.rb
  spec/models/spree/calculator/flexi_rate_spec.rb
  spec/models/spree/calculator/per_item_spec.rb
Labels: pr-staged-au

#3302 Add script to install required bundler version
  script/install-bundler
  script/setup
Labels: pr-no-test

#3326 Cleanup specs
  spec/features/admin/bulk_order_management_spec.rb
  spec/features/admin/bulk_product_update_spec.rb
  spec/features/admin/customers_spec.rb
  spec/features/admin/enterprise_user_spec.rb
  spec/features/admin/order_cycles_spec.rb
  spec/features/admin/product_import_spec.rb
  spec/features/admin/subscriptions_spec.rb
  spec/features/admin/variant_overrides_spec.rb
  spec/support/request/admin_helper.rb
  spec/support/request/web_helper.rb
Labels: pr-no-test

#3312 3217 [Enterprise Fee Summary] Move setup code in tests to factories
  engines/order_management/spec/services/order_management/reports/enterprise_fee_summary/report_service_spec.rb
  spec/factories/calculated_adjustment_factory.rb
  spec/factories/order_factory.rb
  spec/factories/variant_factory.rb
Labels: pr-no-test

#3339 [Headless Chrome] Fix embedded_shopfront_spec unhandled alert
  spec/features/consumer/shopping/embedded_shopfronts_spec.rb
Labels: pr-no-test

#3354 New Knapsack report
  knapsack_rspec_report.json
  spec/models/proxy_order_spec.rb
Labels: pr-no-test

#2833 Add tests for permissions for variant overrides
  spec/models/spree/ability_spec.rb
Labels: pr-no-test, tech debt
