Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2019-11, with the labels that each got.

#4400 Task to remove limit of ent. that can be created
  lib/tasks/users.rake
  spec/lib/tasks/users_rake_spec.rb
Labels: pr-no-test

#4418 Improve readability of README.md
  README.md
Labels: pr-no-test

#4397 Remove option types menu entry
  app/views/spree/admin/shared/_product_sub_menu.html.haml
Labels: easy-test

#4225 Add missing translations on product edit page
  app/views/spree/admin/product_properties/index.html.haml
  app/views/spree/admin/products/_seo_form.html.haml
  app/views/spree/admin/products/seo.html.haml
  app/views/spree/admin/shared/_edit_resource_links.html.haml
  app/views/spree/admin/shared/_product_tabs.html.haml
  app/views/spree/admin/variants/_form.html.haml
  app/views/spree/admin/variants/index.html.haml
  app/views/spree/admin/variants/new.html.haml
  config/locales/en.yml
Labels: easy-test

#4431 Fix migration mismatch
  db/schema.rb
Labels: pr-no-test

#4301 Use Ruby 2.2.10
  .ruby-version
  Gemfile
  Gemfile.lock
  lib/open_food_network/xero_invoices_report.rb
Labels: blocked

#4434 Don't test existence of a field used in next spec
  spec/features/admin/bulk_order_management_spec.rb
Labels: pr-no-test

#4371 Move Payment methods from spree_backend to OFN
  .rubocop_manual_todo.yml
  app/controllers/spree/admin/payment_methods_controller.rb
  spec/controllers/spree/admin/payment_methods_controller_spec.rb
Labels: easy-test

#4372 Move Images from spree_backend to OFN
  app/controllers/spree/admin/images_controller.rb
  app/controllers/spree/admin/images_controller_decorator.rb
  app/views/spree/admin/images/_form.html.haml
  app/views/spree/admin/images/edit.html.haml
  app/views/spree/admin/images/index.html.haml
  app/views/spree/admin/images/new.html.haml
  spec/features/admin/products_spec.rb
Labels: easy-test

#4415 Update end date on delivery report
  lib/open_food_network/order_cycle_management_report.rb
  spec/lib/open_food_network/order_cycle_management_report_spec.rb
Labels: easy-test

#4448 Update rubocop todo lists and regenrate knapsack report
  .rubocop_manual_todo.yml
  .rubocop_todo.yml
  knapsack_rspec_report.json
Labels: pr-no-test

#4446 Remove unused dependency listen
  Gemfile
  Gemfile.lock
Labels: pr-no-test

#4408 Remove dead code from OC edit page code
  app/assets/javascripts/templates/admin/panels/exchange_supplied_products.html.haml
  app/views/admin/order_cycles/_exchange_supplied_products_form.html.haml
  config/locales/en.yml
  spec/features/admin/order_cycles_spec.rb
Labels: easy-test

#4425 Eager-load variant associations in admin ProductsController
  app/controllers/api/products_controller.rb
Labels: easy-test

#4459 Temporarily disable flaky line item spec
  spec/models/spree/line_item_spec.rb
Labels: pr-no-test

#4449 Move properties and product properties from spree_backend to OFN
  app/controllers/spree/admin/product_properties_controller.rb
  app/controllers/spree/admin/properties_controller.rb
  app/models/spree/property.rb
  app/views/spree/admin/properties/_form.html.haml
  app/views/spree/admin/properties/edit.html.haml
  app/views/spree/admin/properties/index.html.haml
  app/views/spree/admin/properties/new.html.haml
  app/views/spree/admin/properties/new.js.erb
  config/locales/en.yml
Labels: easy-test

#4470 Improve readability of OC permissions...
  lib/open_food_network/order_cycle_permissions.rb
Labels: pr-no-test

#4430 Variant option_values
  app/controllers/admin/bulk_line_items_controller.rb
  app/controllers/admin/enterprises_controller.rb
  app/controllers/api/products_controller.rb
  app/controllers/api/variants_controller.rb
  app/mailers/producer_mailer.rb
  lib/open_food_network/bulk_coop_report.rb
  lib/open_food_network/orders_and_fulfillments_report/customer_totals_report.rb
  lib/open_food_network/orders_and_fulfillments_report/distributor_totals_by_supplier_report.rb
  lib/open_food_network/orders_and_fulfillments_report/supplier_totals_by_distributor_report.rb
  lib/open_food_network/orders_and_fulfillments_report/supplier_totals_report.rb
  lib/open_food_network/packing_report.rb
  lib/open_food_network/products_and_inventory_report_base.rb
  lib/open_food_network/scope_variants_for_search.rb
  lib/open_food_network/variant_and_line_item_naming.rb
  lib/open_food_network/xero_invoices_report.rb
Labels: performance, pr-staged-uk

#4463 Use .ruby-version when building Docker container
  Dockerfile
Labels: dev-test

#4136 Lock variants during checkout to avoid race condition
  app/controllers/checkout_controller.rb
  app/services/current_order_locker.rb
  spec/controllers/checkout_controller_concurrency_spec.rb
  spec/controllers/checkout_controller_spec.rb
  spec/spec_helper.rb
Labels: easy-test, pr-staged-es

#4454 Sort products alphabetically in OC edit page
  app/assets/javascripts/templates/admin/panels/exchange_distributed_products.html.haml
  app/serializers/api/admin/for_order_cycle/enterprise_serializer.rb
Labels: easy-test

#4522 4239 Do one thing at a time in feature spec for product cloning
  spec/features/admin/bulk_product_update_spec.rb
Labels: pr-no-test

#4520 4238 Do not assume order in spec for taxons list
  spec/controllers/api/taxons_controller_spec.rb
Labels: pr-no-test
