Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2019-02, with the labels that each got.

#3334 3332 [Enterprise Fee Summary] Disable report for non-superadmin users
  app/models/feature_flags.rb
  app/models/spree/ability_decorator.rb
  spec/controllers/spree/admin/reports/enterprise_fee_summaries_controller_spec.rb
  spec/features/admin/reports/enterprise_fee_summaries_spec.rb
  spec/models/feature_flags_spec.rb
  spec/models/spree/ability_spec.rb
  spec/support/ability_helper.rb
Labels: pr-staged-au

#3424 3415 [Enterprise Fee Summary] Address Rubocop layout violation in Spree::Ability decorator
  app/models/spree/ability_decorator.rb
Labels: pr-no-test, tech debt

#3412 3059 [Flaky Spec] Fix race condition in enterprise image feature specs
  spec/features/admin/enterprises/images_spec.rb
Labels: pr-no-test

#3432 3327 [Flaky Spec] Fix shop accidentally becoming order coordinator
  spec/controllers/api/orders_controller_spec.rb
Labels: pr-no-test

#3418 Update Rake task namespace
  .travis.yml
  GETTING_STARTED.md
  config/schedule.rb
  lib/tasks/billing.rake
  lib/tasks/cache.rake
  lib/tasks/data.rake
  lib/tasks/dev.rake
  lib/tasks/enterprises.rake
  lib/tasks/specs.rake
  script/setup
Labels: pr-staged-au

#3400 [Spree Upgrade] Change app config to keep using ofn customized spree v1 shipping method calculators, not the new spree v2 ones
  app/models/spree/shipping_method_decorator.rb
  config/application.rb
  db/seeds.rb
  spec/serializers/api/shipping_method_serializer_spec.rb
Labels: pr-staged-fr

#3469 3468 [Flaky Spec] Check for presence of flash div before trying to get its text
  spec/features/admin/shipping_methods_spec.rb
  spec/support/matchers/flash_message_matchers.rb
Labels: pr-no-test

#3467 3455 [Flaky Spec] Do not expect modal still open when checking that the spinner is gone
  spec/features/admin/bulk_product_update_spec.rb
Labels: pr-no-test

#3474 Fix broken spec from refactored method
  spec/features/admin/product_import_spec.rb
Labels: pr-no-test

#3481 Simplify specs with stripe factory
  spec/controllers/admin/subscriptions_controller_spec.rb
  spec/controllers/spree/admin/payments_controller_spec.rb
  spec/factories.rb
  spec/features/admin/subscriptions_spec.rb
  spec/features/consumer/shopping/checkout_spec.rb
  spec/models/spree/order_spec.rb
  spec/requests/checkout/stripe_connect_spec.rb
Labels: pr-no-test

#3444 3437 supplier name on invoice
  app/controllers/spree/admin/orders_controller_decorator.rb
  app/services/bulk_invoice_service.rb
  app/services/invoice_renderer.rb
  app/views/spree/admin/orders/_invoice_table.html.haml
  app/views/spree/admin/orders/_invoice_table2.html.haml
  spec/services/bulk_invoice_service_spec.rb
  spec/services/invoice_renderer_spec.rb
Labels: pr-staged-au

#3470 3426 [Flaky Spec] Address timing issues in enterprise users feature specs
  spec/features/admin/enterprise_roles_spec.rb
Labels: pr-no-test

#3494 Break order_cycle_spec.js in specific files and remove reference to product.count_on_hand in bulk_product_update_spec.js
  spec/javascripts/unit/admin/bulk_product_update_spec.js.coffee
  spec/javascripts/unit/admin/order_cycles/controllers/create_spec.js.coffee
  spec/javascripts/unit/admin/order_cycles/controllers/edit_spec.js.coffee
  spec/javascripts/unit/admin/order_cycles/services/enterprise_fee_spec.js.coffee
  spec/javascripts/unit/admin/order_cycles/services/enterprise_spec.js.coffee
  spec/javascripts/unit/admin/order_cycles/services/order_cycle_spec.js.coffee
  spec/javascripts/unit/order_cycle_spec.js.coffee
Labels: pr-no-test

#3536 Wait for angular to load in BOM spec
  spec/features/admin/bulk_order_management_spec.rb
  spec/support/request/web_helper.rb
Labels: pr-no-test

#3531 Document stock validation of variant overrides
  app/models/concerns/stock_settings_override_validation.rb
Labels: pr-no-test
