Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2019-06, with the labels that each got.

#3847 Allow unauthenticated access to OFN API endpoints
  app/controllers/api/base_controller.rb
  app/controllers/api/customers_controller.rb
  app/controllers/api/enterprises_controller.rb
  spec/controllers/api/enterprises_controller_spec.rb
Labels: pr-staged-uk

#3880 3792 Optimize saving Order Cycle changes
  Gemfile
  Gemfile.lock
  app/services/exchange_variant_bulk_updater.rb
  lib/open_food_network/order_cycle_form_applicator.rb
  spec/lib/open_food_network/order_cycle_form_applicator_spec.rb
  spec/services/exchange_variant_bulk_updater_spec.rb
Labels: pr-staged-uk

#3915 Consider deleted products when creating permalinks
  app/models/spree/product_decorator.rb
  lib/open_food_network/permalink_generator.rb
  spec/models/spree/product_spec.rb
Labels: pr-staged-uk

#3935 Update rubocop style
  .rubocop_manual_todo.yml
  .rubocop_styleguide.yml
  spec/features/admin/caching_spec.rb
  spec/features/admin/enterprise_relationships_spec.rb
  spec/models/spree/credit_card_spec.rb
Labels: pr-no-test

#3942 Exit script/setup if node is not found
  script/setup
Labels: pr-no-test

#3955 No need to keep old and used Travis config file
  .travis.yml
Labels: pr-no-test

#3006 Raise error on missing translation keys
  spec/support/i18n_error_raising.rb
Labels: pr-no-test, tech debt

#3887 Add docker configuration for quick local setup
  .dockerignore
  DOCKER.md
  Dockerfile
  config/database.yml
  docker-compose.yml
  lib/tasks/dev.rake
Labels: pr-no-test
