Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2019-09, with the labels that each got.

#4155 Fix Rubocop violations in Stripe connect tests
  .rubocop_manual_todo.yml
  spec/requests/checkout/stripe_connect_spec.rb
Labels: pr-no-test

#4223 Lower integrity checker job interval
  config/schedule.rb
Labels: pr-no-test

#4202 Remove Skylight
  Gemfile
  Gemfile.lock
  README.md
  app/views/shared/_footer.html.haml
  config/application.rb
  config/application.yml.example
  config/locales/en.yml
Labels: pr-no-test

#4253 Update Slack invite link
  README.md
Labels: pr-no-test

#4232 Remove Guard and Guard-related gems
  Gemfile
  Gemfile.lock
  Guardfile
Labels: pr-no-test

#4258 Fix test example name
  spec/lib/open_food_network/subscription_summarizer_spec.rb
Labels: pr-no-test

#4260 Add default date range to Delivery Report
  lib/open_food_network/order_cycle_management_report.rb
  spec/lib/open_food_network/order_cycle_management_report_spec.rb
Labels: easy-test

#4263 Index spree_orders on various columns
  db/migrate/20190916105416_add_long_compound_index_on_spree_orders.rb
  db/migrate/20190916110029_drop_completed_at_index_on_spree_orders.rb
  db/schema.rb
Labels: dev-test

#4286 Finish transpec
  spec/controllers/api/taxonomies_controller_spec.rb
  spec/controllers/api/taxons_controller_spec.rb
  spec/features/consumer/authentication_spec.rb
  spec/features/consumer/producers_spec.rb
  spec/features/consumer/registration_spec.rb
  spec/features/consumer/shopping/cart_spec.rb
  spec/features/consumer/shopping/products_spec.rb
  spec/features/consumer/shopping/shopping_spec.rb
  spec/features/consumer/shopping/variant_overrides_spec.rb
  spec/models/enterprise_spec.rb
  spec/performance/shop_controller_spec.rb
  spec/serializers/api/admin/for_order_cycle/supplied_product_serializer_spec.rb
  spec/spec_helper.rb
Labels: pr-no-test

#4287 Replace therubyracer with mini_racer.
  Gemfile
  Gemfile.lock
Labels: dev-test

#4295 Enable trace & search analytics in Datadog
  config/initializers/datadog.rb
Labels: dev-test

#4293 Improve user email change flash alert message
  app/controllers/spree/admin/users_controller.rb
  config/locales/en.yml
  spec/features/admin/users_spec.rb
Labels: easy-test

#4300 Translation: "Add new credit card"
  app/views/spree/users/_cards.html.haml
Labels: easy-test
