Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2019-10, with the labels that each got.

#4297 Remove all usages of Spree Config track_inventory_levels
  app/models/concerns/variant_stock.rb
  app/models/spree/shipment_decorator.rb
  app/views/spree/admin/products/_form.html.haml
  app/views/spree/admin/variants/_form.html.haml
  spec/models/concerns/variant_stock_spec.rb
Labels: pr-no-test

#4335 Remove deprecation warnings from VariantStock methods
  app/models/concerns/variant_stock.rb
Labels: pr-no-test

#4281 Add memcached APM
  config/initializers/datadog.rb
Labels: dev-test

#4305 Make translations in new product page relative and specific to the page
  app/views/spree/admin/products/new.html.haml
  config/locales/en.yml
Labels: easy-test

#4303 Add missing translation for order.shipment.state "on hand" (with a space between on and hand)
  config/locales/en.yml
Labels: easy-test

#4254 Update API swagger docs to reflect current API state
  swagger.yaml
Labels: dev-test

#4269 Move shipping_methods and shipping categories from spree_backend to OFN
  app/controllers/spree/admin/shipping_categories_controller.rb
  app/controllers/spree/admin/shipping_methods_controller.rb
  app/controllers/spree/admin/shipping_methods_controller_decorator.rb
Labels: easy-test

#4325 4312 Use association instead of OrderAndFulfillmentsReport#find_variant
  lib/open_food_network/orders_and_fulfillments_report.rb
  lib/open_food_network/orders_and_fulfillments_report/default_report.rb
Labels: easy-test

#4324 Reports memoization
  app/controllers/spree/admin/reports_controller_decorator.rb
  lib/open_food_network/orders_and_fulfillments_report.rb
  lib/open_food_network/reports/line_items.rb
  spec/lib/open_food_network/orders_and_fulfillments_report_spec.rb
Labels: easy-test

#4271 Remove logic related to master variants in Exchanges and migrate data
  app/services/order_cycle_distributed_products.rb
  db/migrate/20190918105234_remove_all_master_variants_from_exchanges.rb
  db/schema.rb
Labels: pr-no-test

#4340 Delete ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE.md
Labels: pr-no-test

#4321 Delete old pt-BR translations file (it's now correctly called pt_BR)
  config/locales/pt-BR.yml
Labels: pr-no-test

#4262 Prefill shipping category forms with default values
  app/controllers/spree/admin/products_controller_decorator.rb
  app/controllers/spree/admin/shipping_methods_controller.rb
  app/services/default_shipping_category.rb
  app/views/spree/admin/products/_shipping_category_form.html.haml
  db/seeds.rb
  lib/tasks/sample_data/product_factory.rb
  spec/factories.rb
  spec/features/admin/products_spec.rb
  spec/features/admin/shipping_methods_spec.rb
  spec/models/stock/package_spec.rb
  spec/services/default_shipping_category_spec.rb
Labels: easy-test

#4363 Fix error during first run of docker-compose
  docker-compose.yml
Labels: dev-test

#4356 4256 Configure dalli store value max bytes from env variable
  config/application.yml.example
  config/environments/production.rb
  config/environments/staging.rb
Labels: dev-test

#4364 4308 Refactor Orders and Fulfillment report subtypes
  .rubocop_manual_todo.yml
  lib/open_food_network/orders_and_fulfillments_report.rb
  lib/open_food_network/orders_and_fulfillments_report/customer_totals_report.rb
  lib/open_food_network/orders_and_fulfillments_report/distributor_totals_by_supplier_report.rb
  lib/open_food_network/orders_and_fulfillments_report/supplier_totals_by_distributor_report.rb
  lib/open_food_network/orders_and_fulfillments_report/supplier_totals_report.rb
  spec/lib/open_food_network/orders_and_fulfillments_report/customer_totals_report_spec.rb
  spec/lib/open_food_network/orders_and_fulfillments_report/distributor_totals_by_supplier_report_spec.rb
  spec/lib/open_food_network/orders_and_fulfillments_report/supplier_totals_by_distributor_report_spec.rb
  spec/lib/open_food_network/orders_and_fulfillments_report/supplier_totals_report_spec.rb
Labels: easy-test

#4289 Move general_settings, mail_methods and image_settings from spree_backend to OFN
  app/controllers/spree/admin/general_settings_controller.rb
  app/controllers/spree/admin/general_settings_controller_decorator.rb
  app/controllers/spree/admin/image_settings_controller.rb
  app/controllers/spree/admin/image_settings_controller_decorator.rb
  app/controllers/spree/admin/mail_methods_controller.rb
  app/helpers/spree/admin/general_settings_helper.rb
  app/views/spree/admin/mail_methods/_form.html.haml
  app/views/spree/admin/mail_methods/edit.html.haml
  config/routes/spree.rb
  spec/controllers/spree/admin/image_settings_controller_spec.rb
  spec/controllers/spree/admin/mail_methods_controller_spec.rb
  spec/features/admin/configuration/general_settings_spec.rb
  spec/features/admin/configuration/image_settings_spec.rb
  spec/features/admin/configuration/mail_methods_spec.rb
Labels: dev-test

#4268 Add api/orders/{order_number} API endpoint
  .rubocop_manual_todo.yml
  app/controllers/api/orders_controller.rb
  app/models/spree/ability_decorator.rb
  app/serializers/api/address_serializer.rb
  app/serializers/api/adjustment_serializer.rb
  app/serializers/api/admin/basic_enterprise_serializer.rb
  app/serializers/api/admin/customer_serializer.rb
  app/serializers/api/admin/enterprise_fee_serializer.rb
  app/serializers/api/admin/enterprise_serializer.rb
  app/serializers/api/admin/exchange_serializer.rb
  app/serializers/api/admin/for_order_cycle/enterprise_serializer.rb
  app/serializers/api/admin/index_enterprise_serializer.rb
  app/serializers/api/admin/index_order_cycle_serializer.rb
  app/serializers/api/admin/line_item_serializer.rb
  app/serializers/api/admin/order_cycle_serializer.rb
  app/serializers/api/admin/order_serializer.rb
  app/serializers/api/admin/subscription_serializer.rb
  app/serializers/api/admin/tag_rule_serializer.rb
  app/serializers/api/admin/variant_override_serializer.rb
  app/serializers/api/admin/variant_serializer.rb
  app/serializers/api/order_detailed_serializer.rb
  app/serializers/api/order_serializer.rb
  app/serializers/api/payment_serializer.rb
  app/serializers/api/variant_serializer.rb
  config/routes/api.rb
  spec/controllers/api/orders_controller_spec.rb
Labels: pr-staged-uk

#4365 4308 Eager-load associations in Orders and Fulfillment reports
  lib/open_food_network/orders_and_fulfillments_report.rb
  lib/open_food_network/orders_and_fulfillments_report/customer_totals_report.rb
  lib/open_food_network/orders_and_fulfillments_report/default_report.rb
  lib/open_food_network/orders_and_fulfillments_report/distributor_totals_by_supplier_report.rb
  lib/open_food_network/orders_and_fulfillments_report/supplier_totals_by_distributor_report.rb
  lib/open_food_network/orders_and_fulfillments_report/supplier_totals_report.rb
  lib/open_food_network/reports/line_items.rb
Labels: easy-test

#4352 Add missing translation in non English enterprise welcome email
  app/views/enterprise_mailer/welcome.html.haml
  config/locales/en.yml
Labels: easy-test

#4390 Fix flaky product import spec
  spec/models/product_importer_spec.rb
Labels: pr-no-test

#4327 4315 Set default date range for Orders and Fulfillment report
  app/controllers/spree/admin/reports_controller_decorator.rb
Labels: easy-test

#4354 #3832 - Added color to links in WYSIWYG editor
  app/assets/stylesheets/admin/openfoodnetwork.css.scss
Labels: easy-test

#4342 makes edit button action open a new tab
  app/assets/javascripts/admin/bulk_product_update.js.coffee
  spec/features/admin/bulk_product_update_spec.rb
Labels: easy-test

#4394 Merge duplicated product_sub_menu partials
  app/views/admin/enterprise_groups/index.html.haml
  app/views/admin/order_cycles/index.html.haml
  app/views/admin/product_import/import.html.haml
  app/views/admin/product_import/index.html.haml
  app/views/admin/shared/_enterprises_sub_menu.html.haml
  app/views/admin/shared/_product_sub_menu.html.haml
  app/views/admin/shared/_users_sub_menu.html.haml
  app/views/admin/variant_overrides/_header.html.haml
  app/views/spree/admin/products/group_buy_options.html.haml
  app/views/spree/admin/products/index/_header.html.haml
  app/views/spree/admin/products/seo.html.haml
  app/views/spree/admin/shared/_product_sub_menu.html.haml
  app/views/spree/admin/shared/_product_tabs.html.haml
  app/views/spree/admin/users/new.html.haml
Labels: easy-test, pr-staged-es

#4359 Add asterisks to required fields in New Order Cycle form
  app/views/admin/order_cycles/_name_and_timing_form.html.haml
  app/views/admin/order_cycles/_simple_form.html.haml
  spec/features/admin/order_cycles_spec.rb
Labels: easy-test

#4395 Delete prototypes tables and all references in pages
  app/views/spree/admin/product_properties/index.html.haml
  app/views/spree/admin/products/new.html.haml
  app/views/spree/admin/shared/_product_sub_menu.html.haml
  app/views/spree/admin/shared/_tabs.html.haml
  config/locales/en.yml
  db/migrate/20191023105006_drop_prototypes_tables.rb
  db/schema.rb
Labels: easy-test
