Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2019-12, with the labels that each got.

#4523 Replace pluck with select in permissions to avoid extra queries and extract Permissions::Orders from Permissions
  .rubocop_manual_todo.yml
  app/controllers/admin/bulk_line_items_controller.rb
  app/controllers/spree/admin/reports_controller_decorator.rb
  app/services/permissions/order.rb
  app/services/search_orders.rb
  lib/open_food_network/bulk_coop_report.rb
  lib/open_food_network/order_and_distributor_report.rb
  lib/open_food_network/orders_and_fulfillments_report.rb
  lib/open_food_network/packing_report.rb
  lib/open_food_network/permissions.rb
  lib/open_food_network/reports/line_items.rb
  lib/open_food_network/sales_tax_report.rb
  lib/open_food_network/xero_invoices_report.rb
  spec/lib/open_food_network/bulk_coop_report_spec.rb
  spec/lib/open_food_network/orders_and_fulfillments_report/customer_totals_report_spec.rb
  spec/lib/open_food_network/orders_and_fulfillments_report/distributor_totals_by_supplier_report_spec.rb
  spec/lib/open_food_network/orders_and_fulfillments_report/supplier_totals_by_distributor_report_spec.rb
  spec/lib/open_food_network/orders_and_fulfillments_report/supplier_totals_report_spec.rb
  spec/lib/open_food_network/orders_and_fulfillments_report_spec.rb
  spec/lib/open_food_network/packing_report_spec.rb
  spec/lib/open_food_network/permissions_spec.rb
  spec/services/permissions/order_spec.rb
Labels: pr-staged-uk

#4525 4489 Improve waiting in feature spec for edit Order Cycle page
  spec/features/admin/order_cycles_spec.rb
Labels: pr-no-test

#4288 Add spec for api/admin/order_cycle_serializer
  spec/serializers/api/admin/order_cycle_serializer_spec.rb
Labels: pr-no-test

#4514 Bring spree_backend overview controller to OFN
  .rubocop_manual_todo.yml
  app/controllers/spree/admin/overview_controller.rb
  app/controllers/spree/admin/overview_controller_decorator.rb
Labels: easy-test

#4546 Cart link in header on mobile leads to cart page instead of checkout …
  app/views/shared/menu/_mobile_menu.html.haml
Labels: easy-test

#4545 Make whenever properly read the S3 bucket
  config/schedule.rb
Labels: dev-test, pr-staged-es

#4550 Remove eager loding of shipping_methods and shipping_rates from customer_totals so that report runs faster
  lib/open_food_network/orders_and_fulfillments_report/customer_totals_report.rb
Labels: pr-staged-uk

#4590 Upgrade capybara and webdrivers
  Gemfile
  Gemfile.lock
Labels: pr-no-test

#4541 Handle validation messages when saving new fees
  app/controllers/admin/enterprise_fees_controller.rb
  config/locales/en.yml
Labels: easy-test
