Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2020-06, with the labels that each got.

#5502 [mobile ux] Fix missing drop-shadow
  app/assets/stylesheets/darkswarm/distributor_header.css.scss
  app/assets/stylesheets/darkswarm/shop_tabs.css.scss
Labels: easy-test

#5383 [Spree 2.1] Fix Update and Calculate Fees button
  app/controllers/spree/admin/orders_controller.rb
  spec/controllers/spree/admin/orders_controller_spec.rb
Labels: pr-staged-uk

#5421 [Spree 2.1] Add missing strong params to less important controllers missed by specs
  app/controllers/spree/admin/countries_controller.rb
  app/controllers/spree/admin/return_authorizations_controller.rb
  app/controllers/spree/admin/shipping_categories_controller.rb
  spec/controllers/spree/admin/countries_controller_spec.rb
  spec/controllers/spree/admin/return_authorizations_controller_spec.rb
  spec/controllers/spree/admin/shipping_categories_controller_spec.rb
Labels: pr-staged-uk

#5263 [Mobile] Restyle product modal
  app/assets/javascripts/darkswarm/controllers/products/product_node_controller.js.coffee
  app/assets/javascripts/templates/product_modal.html.haml
  app/assets/stylesheets/darkswarm/_shop-filters.css.scss
  app/assets/stylesheets/darkswarm/_shop-modals.css.scss
  app/assets/stylesheets/darkswarm/animations.scss
  app/assets/stylesheets/darkswarm/images.css.scss
  app/assets/stylesheets/darkswarm/modals.css.scss
  app/assets/stylesheets/darkswarm/pages/login_modal.css.scss
  app/assets/stylesheets/darkswarm/registration.css.scss
  engines/web/app/assets/stylesheets/web/pages/cookies_policy_modal.css.scss
Labels: pr-staged-au

#5528 Make checkout JS code send bugsnag alert even if there's an error processing an error
  app/assets/javascripts/darkswarm/services/checkout.js.coffee
Labels: bug-s2, pr-no-test

#5543 [Spree 2.1] Fix product_stock spec
  spec/models/concerns/product_stock_spec.rb
Labels: pr-no-test

#5544 [Spree 2.1] Fix specs in Api::EnterprisesController and Api::ShopsController
  spec/controllers/api/enterprises_controller_spec.rb
  spec/controllers/api/shops_controller_spec.rb
Labels: pr-no-test

#5456 [Spree 2.1] Move all spree_core dependencies to OFN so we can upgrade them later
  Gemfile
  Gemfile.lock
Labels: pr-no-test

#5547 Bring the spree_get spec helpers from spree and move them together with the api_get spec helpers
  .rubocop_manual_todo.yml
  spec/controllers/api/shipments_controller_spec.rb
  spec/controllers/api/shops_controller_spec.rb
  spec/controllers/api/variants_controller_spec.rb
  spec/spec_helper.rb
  spec/support/controller_hacks.rb
  spec/support/controller_requests_helper.rb
Labels: pr-no-test

#5564 Improve Dockerfile
  Dockerfile
Labels: dev-test

#5482 created partial for order page title to resolve French translation of…
  app/views/spree/admin/adjustments/edit.html.haml
  app/views/spree/admin/adjustments/index.html.haml
  app/views/spree/admin/adjustments/new.html.haml
  app/views/spree/admin/orders/customer_details/edit.html.haml
  app/views/spree/admin/orders/edit.html.haml
  app/views/spree/admin/orders/new.html.haml
  app/views/spree/admin/orders/set_distribution.html.haml
  app/views/spree/admin/payments/index.html.haml
  app/views/spree/admin/payments/new.html.haml
  app/views/spree/admin/payments/show.html.haml
  app/views/spree/admin/return_authorizations/edit.html.haml
  app/views/spree/admin/return_authorizations/index.html.haml
  app/views/spree/admin/return_authorizations/new.html.haml
  app/views/spree/admin/shared/_order_page_title.html.haml
  app/views/spree/admin/shared/_order_tabs.html.haml
Labels: pr-staged-fr

#5556 Rename Angular Geo service
  app/assets/javascripts/darkswarm/services/enterprises.js.coffee
  app/assets/javascripts/darkswarm/services/gmaps_geo.js.erb.coffee
  spec/javascripts/unit/darkswarm/services/enterprise_spec.js.coffee
  spec/javascripts/unit/darkswarm/services/map_spec.js.coffee
  spec/javascripts/unit/darkswarm/services/products_spec.js.coffee
Labels: pr-staged-es

#5549 [Spree 2.1] Make Variant Overrides spec less flaky and... comment it anyway
  spec/features/admin/variant_overrides_spec.rb
Labels: pr-no-test

#5602 Fix outstanding Rubocop violations
  app/controllers/admin/enterprise_groups_controller.rb
  app/controllers/admin/enterprises_controller.rb
  app/controllers/admin/schedules_controller.rb
  app/controllers/api/enterprise_attachment_controller.rb
  app/controllers/spree/admin/countries_controller.rb
  app/controllers/spree/admin/products_controller.rb
  app/controllers/spree/admin/shipping_categories_controller.rb
  app/models/product_import/entry_processor.rb
  app/models/product_import/entry_validator.rb
  app/models/spree/adjustment_decorator.rb
  app/models/spree/line_item_decorator.rb
  app/models/spree/order_decorator.rb
  app/models/spree/order_updater_decorator.rb
  app/models/spree/payment_decorator.rb
  app/models/spree/user.rb
  app/services/permitted_attributes/checkout.rb
  app/services/permitted_attributes/order_cycle.rb
  engines/order_management/spec/services/order_management/subscriptions/proxy_order_syncer_spec.rb
  lib/open_food_network/order_cycle_form_applicator.rb
  lib/open_food_network/permalink_generator.rb
  lib/open_food_network/variant_and_line_item_naming.rb
Labels: pr-no-test

#5603 Comment out Exchange Products Renderer spec
  spec/services/exchange_products_renderer_spec.rb
Labels: pr-no-test

#5604 Comment out flaky variant overrides spec
  spec/features/admin/variant_overrides_spec.rb
Labels: pr-no-test

#5621 Set flaky caching spec to pending
  spec/features/consumer/caching/darkwarm_caching_spec.rb
Labels: pr-no-test

#5598 Make checkout js error handling a bit more defensive
  app/assets/javascripts/darkswarm/services/checkout.js.coffee
Labels: pr-no-test

#5628 Flaky caching spec
  spec/features/consumer/caching/darkwarm_caching_spec.rb
Labels: pr-no-test

#5595 Remove N+1 fetching payments in report
  lib/open_food_network/payments_report.rb
Labels: feedback-needed

#5530 Remove spinjs-rails dependency and use spinning-circles.svg instead.
  Gemfile
  Gemfile.lock
  app/assets/javascripts/admin/all.js
  app/assets/javascripts/admin/spree/progress.coffee
  app/assets/javascripts/darkswarm/all.js.coffee
  app/assets/stylesheets/admin/components/progress.scss
  app/views/spree/layouts/_admin_body.html.haml
  app/views/spree/layouts/admin/_progress_spinner.html.haml
  app/views/spree/layouts/bare_admin.html.haml
  vendor/assets/javascripts/spin.js
Labels: pr-staged-uk

#5642 Ensure cart page table is full-width
  app/assets/stylesheets/darkswarm/cart-page.css.scss
Labels: v3-regression

#5639 FIx setup seed
  lib/tasks/sample_data/order_factory.rb
Labels: pr-no-test

#5651 [Rails 4.1] Change for xhr rquest to avoid csrf during testing
  spec/controllers/enterprises_controller_spec.rb
Labels: pr-no-test

#5660 Migrate all spree pref. keys to the new format
  db/migrate/20200623140437_fix_preferences_keys.rb
  db/schema.rb
Labels: dev-test, pr-staged-fr

#5693 Reload knapsack report
  knapsack_rspec_report.json
Labels: pr-no-test
