Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2020-09, with the labels that each got.

#5964 Check taxon's attribute instead of object identity
  spec/features/admin/bulk_product_update_spec.rb
Labels: pr-no-test, tech debt

#5748 Add redirect to shop on order cycle change
  app/assets/javascripts/darkswarm/controllers/order_cycle_controller.js.coffee
  app/assets/javascripts/darkswarm/controllers/page_selection_ctrl.js.coffee
  app/assets/javascripts/darkswarm/controllers/products_controller.js.coffee
  app/assets/javascripts/darkswarm/darkswarm.js.coffee
Labels: pr-staged-es

#5990 Do not require view overrides
  config/application.rb
Labels: pr-no-test, tech debt

#5907 Data cleanup
  config/schedule.rb
  lib/tasks/data/remove_transient_data.rake
  lib/tasks/data/remove_transient_data.rb
  lib/tasks/data/truncate_data.rb
  spec/lib/tasks/data/remove_transient_data_spec.rb
  spec/lib/tasks/data/truncate_data_spec.rb
Labels: dev-test, tech debt

#6010 Fix module declaration
  .rubocop_manual_todo.yml
  .rubocop_todo.yml
  app/models/spree/concerns/payment_method_distributors.rb
  app/models/spree/preferences/file_configuration.rb
Labels: pr-no-test

#5827 Bug/4592 - Hide Environment column on Payment Methods page when user is not admin
  app/views/spree/admin/payment_methods/index.html.haml
  spec/views/spree/admin/payment_methods/index.html.haml_spec.rb
Labels: easy-test

#5971 Remove some old spree test helpers that are not needed
  lib/spree/api/testing_support/setup.rb
  spec/controllers/api/product_images_controller_spec.rb
  spec/controllers/api/variants_controller_spec.rb
  spec/spec_helper.rb
Labels: pr-no-test

#5925 [Bye bye spree] Bring classes related to users to OFN
  app/models/spree/role.rb
  app/models/spree/user.rb
  config/routes/admin.rb
  spec/models/spree/user_spec.rb
Labels: feedback-needed

#5996 Fix embedded shops failing javascript because jQuery is try to be accessed before being loaded
  app/views/layouts/_shopfront_script.html.haml
Labels: feedback-needed, prod-test

#5888 Allow US units on products/variants
  app/assets/javascripts/admin/products/services/option_value_namer.js.coffee
  app/assets/javascripts/admin/products/services/variant_unit_manager.js.coffee
  app/models/product_import/unit_converter.rb
  app/models/spree/line_item_decorator.rb
  app/models/spree/variant_decorator.rb
  app/services/variant_units/option_value_namer.rb
  app/services/variant_units/variant_and_line_item_naming.rb
  config/locales/en.yml
  engines/order_management/app/services/order_management/reports/bulk_coop/bulk_coop_report.rb
  lib/open_food_network/lettuce_share_report.rb
  spec/javascripts/unit/admin/services/variant_unit_manager_spec.js.coffee
  spec/models/calculator/weight_spec.rb
  spec/models/spree/line_item_spec.rb
  spec/models/spree/variant_spec.rb
  spec/services/variant_units/option_value_namer_spec.rb
Labels: feedback-needed

#6037 Remove Hash#diff from cancan helper
  spec/support/cancan_helper.rb
Labels: pr-no-test

#6069 Replace `create` with `build` in adjustment metadata model specs
  spec/models/adjustment_metadata_spec.rb
Labels: pr-no-test

#5976 Fix address state selector and "use billing address" checkbox in order customer details page
  app/assets/javascripts/admin/spree/orders/address_states.js
  app/assets/javascripts/admin/spree/orders/use_billing.js
  app/controllers/api/states_controller.rb
  app/serializers/api/state_serializer.rb
  app/views/spree/admin/orders/customer_details/_address_form.html.haml
  app/views/spree/admin/orders/customer_details/_form.html.haml
  app/views/spree/admin/shared/_address_form.html.erb
  app/views/spree/admin/shared/_routes.html.erb
  config/routes/api.rb
  spec/controllers/api/states_controller_spec.rb
Labels: feedback-needed

#6051 Adding the russian language to github
  config/locales/ru.yml
Labels: pr-no-test

#6017 Remove old code
  app/controllers/api/base_controller.rb
  app/controllers/application_controller.rb
Labels: pr-no-test

#6075 Replace `create` with `build_stubbed` in calculator weight model specs
  spec/models/calculator/weight_spec.rb
Labels: pr-no-test

#6076 Replace `build` with `build_stubbed` in flat percent item total specs
  spec/models/calculator/flat_percent_item_total_spec.rb
Labels: pr-no-test

#6077 Replace `build` with `build_stubbed` in price sack model specs
  spec/models/calculator/price_sack_spec.rb
Labels: pr-no-test

#6078 Replace `build` with `build_stubbed` in flexi rate and per item model specs
  spec/models/calculator/flexi_rate_spec.rb
  spec/models/calculator/per_item_spec.rb
Labels: pr-no-test

#6074 Replace `create` with `build_stubbed` in shipping rate model specs
  spec/models/spree/shipping_rate_spec.rb
Labels: pr-no-test

#6067 Remove unnecessary create call in tag rule model specs
  spec/models/tag_rule_spec.rb
Labels: pr-no-test

#6068 Replace `create` with `build_stubbed` in coordinator model specs
  engines/order_management/spec/services/order_management/stock/coordinator_spec.rb
Labels: pr-no-test

#6066 Replace `create` with `build_stubbed` in variant override model specs
  spec/models/variant_override_spec.rb
Labels: pr-no-test

#6065 Replace `create` with `build_stubbed` in address model specs
  spec/models/spree/address_spec.rb
Labels: pr-no-test

#6048 Mobile product listing tweaks 2
  app/assets/javascripts/templates/price_breakdown.html.haml
  app/assets/stylesheets/darkswarm/_shop-popovers.scss
  app/assets/stylesheets/darkswarm/_shop-product-rows.scss
  app/assets/stylesheets/darkswarm/shop_search.scss
  app/serializers/api/product_serializer.rb
Labels: pr-staged-au

#5810 Improve DFC Provider engine to support version 1.3
  Gemfile.lock
  engines/dfc_provider/app/controllers/dfc_provider/api/base_controller.rb
  engines/dfc_provider/app/controllers/dfc_provider/api/catalog_items_controller.rb
  engines/dfc_provider/app/controllers/dfc_provider/api/enterprises_controller.rb
  engines/dfc_provider/app/controllers/dfc_provider/api/persons_controller.rb
  engines/dfc_provider/app/controllers/dfc_provider/api/products_controller.rb
  engines/dfc_provider/app/controllers/dfc_provider/api/supplied_products_controller.rb
  engines/dfc_provider/app/serializers/dfc_provider/address_serializer.rb
  engines/dfc_provider/app/serializers/dfc_provider/catalog_item_serializer.rb
  engines/dfc_provider/app/serializers/dfc_provider/enterprise_serializer.rb
  engines/dfc_provider/app/serializers/dfc_provider/offer_serializer.rb
  engines/dfc_provider/app/serializers/dfc_provider/person_serializer.rb
  engines/dfc_provider/app/serializers/dfc_provider/product_serializer.rb
  engines/dfc_provider/app/serializers/dfc_provider/supplied_product_serializer.rb
  engines/dfc_provider/config/routes.rb
  engines/dfc_provider/dfc_provider.gemspec
  engines/dfc_provider/spec/controllers/dfc_provider/api/catalog_items_controller_spec.rb
  engines/dfc_provider/spec/controllers/dfc_provider/api/enterprises_spec.rb
  engines/dfc_provider/spec/controllers/dfc_provider/api/persons_controller_spec.rb
  engines/dfc_provider/spec/controllers/dfc_provider/api/supplied_products_controller_spec.rb
Labels: pr-staged-fr
