Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2020-05, with the labels that each got.

#5344 Move PROFILE debug assets flag to another ENV var
  config/environments/development.rb
Labels: pr-no-test

#4935 Allow data archiving using the :truncate_data task
  lib/tasks/data/truncate_data.rake
  lib/tasks/data/truncate_data.rb
  spec/lib/tasks/data/truncate_data_rake_spec.rb
  spec/lib/tasks/data/truncate_data_spec.rb
Labels: dev-test

#5289 Cart populate
  app/assets/javascripts/templates/partials/shop_variant_no_group_buy.html.haml
  app/assets/javascripts/templates/partials/shop_variant_with_group_buy.html.haml
  app/controllers/cart_controller.rb
  app/models/concerns/variant_stock.rb
  app/models/order_cycle.rb
  app/models/spree/order_decorator.rb
  app/services/cart_service.rb
  app/services/variants_stock_levels.rb
  spec/features/consumer/shopping/shopping_spec.rb
  spec/models/concerns/variant_stock_spec.rb
  spec/models/spree/order_spec.rb
  spec/services/cart_service_spec.rb
Labels: performance

#5309 Make dockerfile install node and adapt karma browser config to work inside a docker container
  Dockerfile
  config/ng-test.conf.js
Labels: dev-test

#5351 Improve ship methods names on sample data
  lib/tasks/sample_data/shipping_method_factory.rb
Labels: pr-no-test

#5361 Cart with soft-deletion
  app/models/spree/stock/quantifier.rb
  app/services/cart_service.rb
  app/services/variants_stock_levels.rb
  spec/features/consumer/shopping/shopping_spec.rb
  spec/models/order_cycle_spec.rb
  spec/models/spree/stock/quantifier_spec.rb
  spec/models/variant_override_spec.rb
  spec/services/cart_service_spec.rb
Labels: bug-s1

#5371 Cart add error handling
  app/assets/javascripts/darkswarm/services/cart.js.coffee
  config/locales/en.yml
  spec/javascripts/unit/darkswarm/services/cart_spec.js.coffee
  spec/javascripts/unit/darkswarm/services/products_spec.js.coffee
Labels: bug-s1, feedback-needed

#5333 Create a container to run a DJ worker in dev
  docker-compose.yml
Labels: dev-test

#5318 [Caching] API Action Caching on shop filters
  app/controllers/api/order_cycles_controller.rb
  app/models/concerns/api_action_caching.rb
  app/services/cache_service.rb
  spec/features/consumer/caching/shops_caching_spec.rb
  spec/services/cache_service_spec.rb
  spec/spec_helper.rb
Labels: performance

#5343 Make OC selector options color explicitly gray and not white
  app/assets/stylesheets/darkswarm/_shop-navigation.css.scss
Labels: easy-test

#5295 Enterprise serializer optimisations
  app/serializers/api/cached_enterprise_serializer.rb
  app/serializers/api/enterprise_shopfront_serializer.rb
  spec/serializers/api/cached_enterprise_serializer_spec.rb
  spec/serializers/api/enterprise_serializer_spec.rb
Labels: performance

#5332 Add timestamps to OC schedule join table
  app/models/order_cycle.rb
  app/models/order_cycle_schedule.rb
  app/models/schedule.rb
  db/migrate/20200430105459_add_timestamps_to_order_cycle_schedules.rb
  db/schema.rb
Labels: pr-staged-fr

#5395 Skip unreliable caching test
  spec/features/consumer/caching/darkwarm_caching_spec.rb
Labels: pr-no-test

#5317 [Caching] Timed caching on shops data
  app/controllers/home_controller.rb
  app/services/cache_service.rb
  app/views/enterprises/shop.html.haml
  app/views/shops/index.html.haml
  spec/features/consumer/caching/darkwarm_caching_spec.rb
  spec/features/consumer/caching/shops_caching_spec.rb
  spec/services/cache_service_spec.rb
Labels: performance

#5352 Change date displayed on sales_tax reports
  lib/open_food_network/order_and_distributor_report.rb
  lib/open_food_network/sales_tax_report.rb
  spec/lib/open_food_network/order_and_distributor_report_spec.rb
Labels: easy-test

#5231 Add DFC Provider engine
  Gemfile
  Gemfile.lock
  config/routes.rb
  engines/dfc_provider/README.md
  engines/dfc_provider/app/controllers/dfc_provider/api/products_controller.rb
  engines/dfc_provider/app/serializers/dfc_provider/product_serializer.rb
  engines/dfc_provider/app/services/dfc_provider/authorization_control.rb
  engines/dfc_provider/config/routes.rb
  engines/dfc_provider/dfc_provider.gemspec
  engines/dfc_provider/lib/dfc_provider.rb
  engines/dfc_provider/lib/dfc_provider/engine.rb
  engines/dfc_provider/lib/dfc_provider/version.rb
  engines/dfc_provider/spec/controllers/dfc_provider/api/products_controller_spec.rb
  engines/dfc_provider/spec/spec_helper.rb
Labels: dev-test, pr-staged-fr

#5334 Output logs in Delayed Job's log file
  app/jobs/job_logger.rb
  app/jobs/subscription_confirm_job.rb
  app/jobs/subscription_placement_job.rb
  engines/order_management/app/services/order_management/subscriptions/summarizer.rb
  engines/order_management/spec/services/order_management/subscriptions/summarizer_spec.rb
  spec/jobs/job_logger_spec.rb
Labels: dev-test, pr-staged-fr

#5375 [Spree 2.1] OFN v3 comes with sample orders :-)
  lib/tasks/sample_data.rake
  lib/tasks/sample_data/order_factory.rb
Labels: dev-test

#5430 Make JobLogger spec more reliable
  spec/jobs/job_logger_spec.rb
Labels: pr-no-test

#5355 change shop name to be link to shop on transactions page
  app/views/spree/users/_skinny.html.haml
  spec/features/consumer/account_spec.rb
Labels: easy-test

#5410 [Spree 2] Make api/enterprises_controller_spec less flaky
  spec/controllers/api/enterprises_controller_spec.rb
Labels: pr-no-test

#5478 Upgrade bundler, byebug and pry-byebug
  Gemfile
  Gemfile.lock
Labels: pr-no-test

#5450 Changed report_header fields for amount and quantity to reflect corre…
  lib/open_food_network/orders_and_fulfillments_report/customer_totals_report.rb
  lib/open_food_network/orders_and_fulfillments_report/default_report.rb
  lib/open_food_network/orders_and_fulfillments_report/distributor_totals_by_supplier_report.rb
  lib/open_food_network/orders_and_fulfillments_report/supplier_totals_by_distributor_report.rb
  lib/open_food_network/orders_and_fulfillments_report/supplier_totals_report.rb
Labels: feedback-needed

#5424 Add warning to enterprise Shipping Method list and to Shipping method edit page
  app/views/admin/enterprises/form/_shipping_methods.html.haml
  app/views/spree/admin/shipping_methods/_form.html.haml
  app/views/spree/admin/shipping_methods/edit.html.haml
  config/locales/en.yml
Labels: pr-staged-fr

#5485 Rename method refering to phantomjs
  spec/spec_helper.rb
Labels: pr-no-test

#5451 Fix tab-buttons element overlapping order cycle selector
  app/assets/stylesheets/darkswarm/shop_tabs.css.scss
Labels: pr-staged-fr

#5501 Enterprises Controller: reset_distributor must be called before any call to memoized current_distributor
  app/controllers/enterprises_controller.rb
  app/services/order_cart_reset.rb
  spec/controllers/enterprises_controller_spec.rb
  spec/services/order_cart_reset_spec.rb
Labels: pr-staged-fr

#5439 [mobile ux] Fix misplaced paragraph in shop tab
  app/views/shop/messages/_select_oc.html.haml
Labels: easy-test, feedback-needed

#5495 Fix error in dependency requirement specification for byebug and pry-byebug
  Gemfile
  Gemfile.lock
Labels: pr-no-test

#5365 Split order_cycle_spec into smaller specs grouped by theme
  spec/features/admin/order_cycles/complex_creating_specific_time_spec.rb
  spec/features/admin/order_cycles/complex_editing_exchange_same_enterprise_spec.rb
  spec/features/admin/order_cycles/complex_editing_multiple_product_pages_spec.rb
  spec/features/admin/order_cycles/complex_editing_spec.rb
  spec/features/admin/order_cycles/complex_updating_specific_time_spec.rb
  spec/features/admin/order_cycles/list_spec.rb
  spec/features/admin/order_cycles/simple_spec.rb
Labels: pr-no-test

#5465 [Rails 4.1] Rename order_cycle.accessible_by to remove name clash with active record
  app/controllers/admin/order_cycles_controller.rb
  app/controllers/spree/admin/reports_controller.rb
  app/models/order_cycle.rb
  app/models/spree/ability_decorator.rb
  engines/order_management/app/services/order_management/reports/enterprise_fee_summary/permissions.rb
  spec/models/order_cycle_spec.rb
Labels: pr-no-test

#5487 [Spree 2.1] Allow to create order_cycle_schedules
  app/controllers/admin/schedules_controller.rb
  app/models/schedule.rb
  app/services/order_cycle_form.rb
  engines/order_management/spec/services/order_management/subscriptions/count_spec.rb
  engines/order_management/spec/services/order_management/subscriptions/estimator_spec.rb
  engines/order_management/spec/services/order_management/subscriptions/proxy_order_syncer_spec.rb
  engines/order_management/spec/services/order_management/subscriptions/summary_spec.rb
  spec/factories.rb
  spec/features/admin/schedules_spec.rb
Labels: pr-no-test
