Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2020-10, with the labels that each got.

#6110 content_spec.rb improvement
  spec/features/admin/configuration/content_spec.rb
  spec/features/admin/content_spec.rb
Labels: pr-no-test

#6050 Stripe checkout spec
  app/views/layouts/darkswarm.html.haml
  app/views/shared/_stripe_js.html.haml
  app/views/spree/admin/payments/source_forms/_stripe.html.haml
  app/views/spree/admin/payments/source_forms/_stripe_sca.html.haml
  engines/order_management/spec/services/order_management/subscriptions/stripe_payment_setup_spec.rb
  spec/controllers/admin/subscriptions_controller_spec.rb
  spec/controllers/spree/admin/orders/payments/payments_controller_refunds_spec.rb
  spec/controllers/spree/admin/orders/payments/payments_controller_spec.rb
  spec/controllers/spree/admin/payment_methods_controller_spec.rb
  spec/factories/payment_method_factory.rb
  spec/features/admin/subscriptions_spec.rb
  spec/features/consumer/shopping/checkout_stripe_spec.rb
  spec/helpers/enterprises_helper_spec.rb
  spec/lib/stripe/profile_storer_spec.rb
  spec/models/spree/order_spec.rb
  spec/models/spree/payment_spec.rb
  spec/requests/checkout/stripe_connect_spec.rb
  spec/spec_helper.rb
  spec/support/fixtures/stripejs-mock.js
  spec/support/request/stripe_helper.rb
Labels: pr-no-test

#6079 Set up test_prof gem
  Gemfile
  Gemfile.lock
  spec/factories/enterprise_factory.rb
  spec/factories/tag_rule_factory.rb
  spec/models/order_cycle_spec.rb
  spec/models/spree/classification_spec.rb
  spec/models/spree/order/checkout_spec.rb
  spec/models/spree/order_spec.rb
  spec/models/tag_rule/filter_order_cycles_spec.rb
  spec/models/tag_rule/filter_payment_methods_spec.rb
  spec/models/tag_rule/filter_products_spec.rb
  spec/models/tag_rule/filter_shipping_methods_spec.rb
  spec/models/variant_override_spec.rb
Labels: pr-no-test

#6132 Stripe Tests: multiple attempted payments
  spec/features/consumer/shopping/checkout_stripe_spec.rb
Labels: pr-no-test

#6091 Delete dead code brought from spree
  app/controllers/spree/admin/tax_rates_controller.rb
Labels: pr-no-test

#6123 Create an initial Code of Conduct placeholder file
  CODE_OF_CONDUCT.md
Labels: pr-no-test

#6061 Remove sleep calls from select2 helper
  spec/features/admin/bulk_order_management_spec.rb
  spec/features/admin/configuration/states_spec.rb
  spec/features/admin/enterprise_groups_spec.rb
  spec/features/admin/enterprise_roles_spec.rb
  spec/features/admin/enterprises_spec.rb
  spec/features/admin/order_cycles/simple_spec.rb
  spec/features/admin/order_spec.rb
  spec/features/admin/orders_spec.rb
  spec/features/admin/product_import_spec.rb
  spec/features/admin/subscriptions_spec.rb
  spec/features/admin/variant_overrides_spec.rb
  spec/support/matchers/select2_matchers.rb
  spec/support/request/web_helper.rb
Labels: pr-no-test

#6128 Add feature specs to stripe payments in the BackOffice
  app/models/spree/order.rb
  app/models/spree/order/checkout.rb
  spec/features/admin/payments_spec.rb
  spec/features/admin/payments_stripe_spec.rb
  spec/features/consumer/shopping/checkout_stripe_spec.rb
  spec/lib/open_food_network/group_buy_report_spec.rb
  spec/models/spree/calculator_spec.rb
  spec/models/spree/order/checkout_spec.rb
  spec/services/order_checkout_restart_spec.rb
  spec/support/request/stripe_helper.rb
Labels: pr-no-test

#6089 [Bye bye spree] Prepare seed data for bye bye spree
  db/default/countries.rb
  db/default/spree/countries.yml
  db/default/states.yml
  db/default/zones.rb
  db/seeds.rb
Labels: dev-test

#6215 Fix deployments
  db/default/countries.rb
  db/default/spree/states.yml
  db/default/zones.rb
  db/seeds.rb
Labels: dev-test

#6177 Fix docker local environment setup
  Dockerfile
Labels: dev-test

#5729 Remove Image settings page and standardise Paperclip styles
  .rubocop_manual_todo.yml
  .rubocop_todo.yml
  app/assets/javascripts/admin/spree/image_settings.js.erb
  app/assets/stylesheets/admin/all.scss
  app/assets/stylesheets/admin/hacks/ie.scss
  app/assets/stylesheets/admin/sections/image_settings.scss
  app/assets/stylesheets/admin/shared/layout.scss
  app/controllers/spree/admin/image_settings_controller.rb
  app/helpers/admin/image_settings_helper.rb
  app/models/spree/image.rb
  app/views/spree/admin/image_settings/edit.html.haml
  app/views/spree/admin/shared/_configuration_menu.html.haml
  app/views/spree/admin/shared/_tabs.html.haml
  config/initializers/spree.rb
  config/locales/en.yml
  config/routes/spree.rb
  knapsack_rspec_report.json
  spec/controllers/spree/admin/image_settings_controller_spec.rb
  spec/features/admin/configuration/image_settings_spec.rb
  spec/features/admin/image_settings_spec.rb
  spec/models/spree/image_spec.rb
Labels: blocked, pr-staged-uk

#6114 Add matomo tag to admin pages
  app/views/spree/layouts/_admin_body.html.haml
Labels: feedback-needed, pr-staged-fr

#6238 Merge Product Listings to master
  app/assets/images/flag.svg
  app/assets/javascripts/darkswarm/controllers/products/product_node_controller.js.coffee
  app/assets/javascripts/darkswarm/controllers/shop_variant_controller.js.coffee
  app/assets/javascripts/darkswarm/directives/price_breakdown.js.coffee
  app/assets/javascripts/darkswarm/directives/price_percentage.js.coffee
  app/assets/javascripts/darkswarm/directives/shop_variant.js.coffee
  app/assets/javascripts/darkswarm/services/variants.js.coffee
  app/assets/javascripts/templates/bulk_buy_modal.html.haml
  app/assets/javascripts/templates/partials/shop_variant_no_group_buy.html.haml
  app/assets/javascripts/templates/partials/shop_variant_with_group_buy.html.haml
  app/assets/javascripts/templates/price_breakdown.html.haml
  app/assets/javascripts/templates/price_percentage.html.haml
  app/assets/javascripts/templates/shop_variant.html.haml
  app/assets/stylesheets/darkswarm/_shop-inputs.scss
  app/assets/stylesheets/darkswarm/_shop-popovers.scss
  app/assets/stylesheets/darkswarm/_shop-product-rows.scss
  app/assets/stylesheets/darkswarm/_shop-product-thumb.scss
  app/assets/stylesheets/darkswarm/_shop-taxon-flag.scss
  app/assets/stylesheets/darkswarm/branding.scss
  app/assets/stylesheets/darkswarm/embedded_shopfront.scss
  app/assets/stylesheets/darkswarm/mixins.scss
  app/assets/stylesheets/darkswarm/shop.scss
  app/assets/stylesheets/darkswarm/shop_search.scss
  app/assets/stylesheets/darkswarm/ui.scss
  app/serializers/api/product_serializer.rb
  app/views/shop/products/_form.html.haml
  app/views/shop/products/_summary.html.haml
  config/locales/en.yml
  public/noimage/small.png
  spec/features/consumer/shopping/shopping_spec.rb
  spec/features/consumer/shopping/variant_overrides_spec.rb
  spec/javascripts/unit/darkswarm/controllers/checkout/shop_variant_controller_spec.js.coffee
  spec/javascripts/unit/darkswarm/services/variants_spec.js.coffee
  spec/support/request/shop_workflow.rb
  spec/support/request/ui_component_helper.rb
Labels: blocked, pr-staged-au

#6234 Fix minor ordercyle selector layout regression
  app/assets/stylesheets/darkswarm/_shop-navigation.scss
Labels: easy-test

#6125 Fix translation for password reset instruction mailer subject
  app/mailers/spree/user_mailer.rb
  config/locales/en.yml
  spec/mailers/user_mailer_spec.rb
Labels: easy-test

#6256 Relax ModuleLength rubocop rule for specs
  .rubocop_manual_todo.yml
  .rubocop_specs.yml
  engines/catalog/spec/.rubocop.yml
  engines/dfc_provider/spec/.rubocop.yml
  engines/order_management/spec/.rubocop.yml
  engines/web/spec/.rubocop.yml
  spec/.rubocop.yml
  spec/controllers/admin/customers_controller_spec.rb
Labels: pr-no-test

#6155 Improve model specs' performance
  app/models/enterprise.rb
  spec/models/concerns/variant_stock_spec.rb
  spec/models/enterprise_spec.rb
  spec/models/product_import/inventory_reset_strategy_spec.rb
  spec/models/spree/credit_card_spec.rb
  spec/models/spree/line_item_spec.rb
  spec/models/spree/payment_spec.rb
  spec/models/spree/product_spec.rb
  spec/models/spree/shipment_spec.rb
  spec/models/spree/shipping_method_spec.rb
  spec/models/spree/taxon_spec.rb
  spec/models/spree/variant_spec.rb
Labels: pr-no-test

#6267 Removed variant argument from click_add_bulk_max_to_cart
  spec/features/consumer/shopping/shopping_spec.rb
  spec/support/request/shop_workflow.rb
Labels: pr-no-test

#6099 [T&Cs] Messages and tooltips
  app/assets/javascripts/admin/enterprises/directives/terms_and_conditions_warning.js.coffee
  app/assets/javascripts/templates/admin/modals/terms_and_conditions_info.html.haml
  app/assets/javascripts/templates/admin/modals/terms_and_conditions_warning.html.haml
  app/helpers/terms_and_conditions_helper.rb
  app/serializers/api/admin/enterprise_serializer.rb
  app/views/admin/enterprises/form/_business_details.html.haml
  config/locales/en.yml
  spec/features/admin/enterprises/terms_and_conditions_spec.rb
  spec/javascripts/unit/admin/enterprises/directives/terms_and_conditions_warning_spec.js.coffee
Labels: blocked, feedback-needed, pr-staged-es

#5994 Terms and Conditions checkbox on checkout
  app/assets/javascripts/admin/enterprises/directives/terms_and_conditions_warning.js.coffee
  app/assets/javascripts/darkswarm/services/checkout.js.coffee
  app/assets/javascripts/templates/admin/modals/terms_and_conditions_info.html.haml
  app/assets/javascripts/templates/admin/modals/terms_and_conditions_warning.html.haml
  app/helpers/terms_and_conditions_helper.rb
  app/serializers/api/admin/enterprise_serializer.rb
  app/services/checkout/post_checkout_actions.rb
  app/views/admin/enterprises/form/_business_details.html.haml
  app/views/checkout/_form.html.haml
  app/views/checkout/_terms_and_conditions.html.haml
  config/locales/en.yml
  db/migrate/20200907140555_add_customer_terms_and_conditions_accepted.rb
  db/schema.rb
  lib/tasks/sample_data/order_factory.rb
  spec/features/admin/enterprises/terms_and_conditions_spec.rb
  spec/features/consumer/shopping/checkout_spec.rb
  spec/javascripts/unit/admin/enterprises/directives/terms_and_conditions_warning_spec.js.coffee
  spec/javascripts/unit/darkswarm/services/checkout_spec.js.coffee
  spec/services/checkout/post_checkout_actions_spec.rb
Labels: easy-test

#6203 Fix ~80 rubocop issues in serializers/api/admin
  .rubocop_todo.yml
  app/serializers/api/admin/basic_enterprise_fee_serializer.rb
  app/serializers/api/admin/basic_enterprise_serializer.rb
  app/serializers/api/admin/basic_order_cycle_serializer.rb
  app/serializers/api/admin/calculator/flat_percent_item_total_serializer.rb
  app/serializers/api/admin/calculator_serializer.rb
  app/serializers/api/admin/column_preference_serializer.rb
  app/serializers/api/admin/customer_serializer.rb
  app/serializers/api/admin/enterprise_fee_serializer.rb
  app/serializers/api/admin/enterprise_relationship_permission_serializer.rb
  app/serializers/api/admin/enterprise_relationship_serializer.rb
  app/serializers/api/admin/enterprise_role_serializer.rb
  app/serializers/api/admin/enterprise_serializer.rb
  app/serializers/api/admin/exchange_serializer.rb
  app/serializers/api/admin/for_order_cycle/enterprise_serializer.rb
  app/serializers/api/admin/for_order_cycle/supplied_product_serializer.rb
  app/serializers/api/admin/id_email_serializer.rb
  app/serializers/api/admin/id_name_serializer.rb
  app/serializers/api/admin/id_serializer.rb
  app/serializers/api/admin/index_enterprise_serializer.rb
  app/serializers/api/admin/index_order_cycle_serializer.rb
  app/serializers/api/admin/inventory_item_serializer.rb
  app/serializers/api/admin/line_item_serializer.rb
  app/serializers/api/admin/order_cycle_serializer.rb
  app/serializers/api/admin/order_serializer.rb
  app/serializers/api/admin/payment_method/base_serializer.rb
  app/serializers/api/admin/payment_method/stripe_serializer.rb
  app/serializers/api/admin/payment_method_serializer.rb
  app/serializers/api/admin/product_serializer.rb
  app/serializers/api/admin/proxy_order_serializer.rb
  app/serializers/api/admin/schedule_serializer.rb
  app/serializers/api/admin/shipping_method_serializer.rb
  app/serializers/api/admin/subscription_customer_serializer.rb
  app/serializers/api/admin/subscription_line_item_serializer.rb
  app/serializers/api/admin/subscription_serializer.rb
  app/serializers/api/admin/tag_rule_serializer.rb
  app/serializers/api/admin/tax_category_serializer.rb
  app/serializers/api/admin/taxon_serializer.rb
  app/serializers/api/admin/units_product_serializer.rb
  app/serializers/api/admin/units_variant_serializer.rb
  app/serializers/api/admin/user_serializer.rb
  app/serializers/api/admin/variant_override_serializer.rb
  app/serializers/api/admin/variant_serializer.rb
Labels: pr-no-test

#5919 [Rails 4.1, works in master] Convert relations with to_a so that they work in rails 4.1
  .rubocop_manual_todo.yml
  app/controllers/admin/enterprises_controller.rb
  app/controllers/spree/admin/payment_methods_controller.rb
  app/controllers/spree/admin/shipping_methods_controller.rb
  app/helpers/checkout_helper.rb
  app/helpers/injection_helper.rb
  app/mailers/producer_mailer.rb
  app/models/calculator/default_tax.rb
  app/models/calculator/flat_percent_per_item.rb
  app/models/calculator/weight.rb
  app/models/model_set.rb
  app/models/spree/line_item.rb
  app/models/spree/stock/quantifier.rb
  app/views/spree/orders/_bought.html.haml
  lib/open_food_network/available_payment_method_filter.rb
  lib/open_food_network/packing_report.rb
  lib/open_food_network/tag_rule_applicator.rb
  lib/open_food_network/user_balance_calculator.rb
  lib/open_food_network/xero_invoices_report.rb
  spec/features/admin/bulk_product_update_spec.rb
  spec/helpers/injection_helper_spec.rb
  spec/lib/open_food_network/tag_rule_applicator_spec.rb
  spec/models/spree/line_item_spec.rb
Labels: pr-no-test
