Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2020-02, with the labels that each got.

#4744 Make pagination optional in the ExchangeProductsController
  app/assets/javascripts/admin/order_cycles/services/exchange_product.js.coffee
  app/controllers/api/exchange_products_controller.rb
  spec/controllers/api/exchange_products_controller_spec.rb
Labels: pr-staged-au, pr-staged-fr

#4756 4489 Flaky spec when editing outgoing exchanges in OC
  spec/features/admin/order_cycles_spec.rb
Labels: pr-no-test

#4614 Bring some basic js functions and dependencies from spree_backend
  app/assets/javascripts/admin/all.js
  app/assets/javascripts/admin/spree/base.js.erb
  app/assets/javascripts/admin/spree/progress.coffee
  app/assets/javascripts/admin/spree/spree-select2.js.erb
  app/assets/javascripts/admin/util.js.erb
  app/assets/stylesheets/admin/all.scss
  app/assets/stylesheets/admin/components/progress.scss
  app/assets/stylesheets/admin/globals/functions.scss
  app/assets/stylesheets/admin/plugins/select2.scss
  vendor/assets/javascripts/equalize.js
  vendor/assets/javascripts/jquery.horizontalNav.js
  vendor/assets/javascripts/jquery.vAlign.js
  vendor/assets/javascripts/spin.js
Labels: feedback-needed

#4635 Replace use of spree.root_path and root_url with main_app.root_path and main_app.root_url
  .rubocop_manual_todo.yml
  app/controllers/application_controller.rb
  app/controllers/spree/admin/base_controller.rb
  app/controllers/spree/orders_controller.rb
  app/controllers/spree/users_controller.rb
  app/mailers/spree/base_mailer_decorator.rb
  app/views/admin/enterprises/form/_primary_details.html.haml
  app/views/layouts/mailer.html.haml
  app/views/shared/_footer.html.haml
  app/views/shared/menu/_large_menu.html.haml
  app/views/shared/menu/_mobile_menu.html.haml
  app/views/shared/menu/_offcanvas_menu.html.haml
  app/views/shop/_blocked_cookies.html.haml
  app/views/spree/layouts/admin/_login_nav.html.haml
  app/views/spree/layouts/bare_admin.html.haml
  app/views/spree/user_mailer/signup_confirmation.html.haml
  lib/spree/core/controller_helpers/auth_decorator.rb
Labels: pr-staged-uk

#4511 Bring spree_backend search controller to OFN
  .rubocop_manual_todo.yml
  app/controllers/spree/admin/search_controller.rb
  app/controllers/spree/admin/search_controller_decorator.rb
  app/views/spree/admin/shared/_routes.html.erb
  config/routes/spree.rb
Labels: easy-test

#4722 Bump Code Climate's Rubocop version to their latest
  .codeclimate.yml
Labels: pr-no-test

#4548 Improve truncate data process
  lib/tasks/data/truncate_data.rake
Labels: pr-no-test

#4542 Add timestamp to log entries
  config/environments/production.rb
  config/environments/staging.rb
Labels: dev-test, pr-staged-es

#4759 Order admin products
  app/assets/javascripts/admin/bulk_product_update.js.coffee
  app/assets/javascripts/admin/index_utils/services/sort_options.js.coffee
  app/assets/javascripts/admin/orders/controllers/orders_controller.js.coffee
  app/controllers/api/products_controller.rb
  app/views/spree/admin/orders/index.html.haml
  app/views/spree/admin/products/index/_products_head.html.haml
  app/views/spree/admin/shared/_sortable_header.html.haml
  spec/controllers/api/products_controller_spec.rb
Labels: easy-test

#4630 Show counts including all variants in order cycle exchanges
  app/assets/javascripts/admin/order_cycles/controllers/order_cycle_exchanges_controller.js.coffee
  app/assets/javascripts/templates/admin/panels/exchange_products_distributed.html.haml
  app/assets/javascripts/templates/admin/panels/exchange_products_panel_footer.html.haml
  app/assets/javascripts/templates/admin/panels/exchange_products_panel_header.html.haml
  app/assets/javascripts/templates/admin/panels/exchange_products_supplied.html.haml
  app/views/admin/order_cycles/_exchange_form.html.haml
  config/locales/en.yml
  spec/features/admin/order_cycles_spec.rb
Labels: easy-test

#4784 Add Order Cycle Button Tooltips
  app/views/admin/order_cycles/_row.html.haml
Labels: easy-test

#4776 Remove the assets group from the gemfile (taken from spree upgrade branch)
  Gemfile
Labels: easy-test

#4818 Delete dead code after PRs 4512 and 4508
  app/controllers/spree/admin/base_controller.rb
Labels: pr-no-test

#4863 [Spree 2.1] Fix Gemfile.lock
  Gemfile.lock
Labels: pr-no-test
