Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2020-04, with the labels that each got.

#5099 Improve BOM
  app/assets/javascripts/admin/line_items/controllers/line_items_controller.js.coffee
  app/assets/javascripts/admin/resources/resources/line_item_resource.js.coffee
  app/assets/javascripts/admin/resources/services/line_items.js.coffee
  app/controllers/admin/bulk_line_items_controller.rb
  app/views/spree/admin/orders/bulk_management.html.haml
  spec/controllers/admin/bulk_line_items_controller_spec.rb
  spec/features/admin/bulk_order_management_spec.rb
  spec/javascripts/unit/admin/line_items/controllers/line_items_controller_spec.js.coffee
  spec/javascripts/unit/admin/line_items/services/line_items_spec.js.coffee
Labels: feedback-needed, pr-staged-au

#5133 Cache counts used in homepage for 24 hours
  app/controllers/home_controller.rb
Labels: dev-test, pr-staged-au

#4916 [Spree 2.1] Make Spree::OrderUpdater update all adjustments, not just promotions and shipment adjustments
  app/models/spree/order_updater_decorator.rb
Labels: pr-no-test

#5010 Remove simple_form
  Gemfile
  Gemfile.lock
  config/initializers/simple_form.rb
  config/locales/simple_form.en.yml
  lib/templates/erb/scaffold/_form.html.erb
Labels: easy-test

#4995 [Spree 2.1] Staging and Production configs
  config/environments/production.rb
  config/environments/staging.rb
Labels: dev-test

#5064 Fix sample data and custom paper_trail config on order_cycles and schedules on rails 4
  app/models/order_cycle.rb
  app/models/schedule.rb
  lib/tasks/sample_data/group_factory.rb
Labels: dev-test, pr-staged-es

#5163 Enable Ruby Runtime Metrics in Datadog
  config/initializers/datadog.rb
Labels: pr-no-test

#5162 Add optional unicorn-worker-killer configs
  Gemfile
  Gemfile.lock
  config.ru
Labels: dev-test, pr-staged-fr

#5151 Fix Permissions::Order spec in rails 4
  spec/services/permissions/order_spec.rb
Labels: pr-no-test

#5154 [Spree 2.1] Add strong params implementation to properties controller
  Gemfile
  app/controllers/spree/admin/properties_controller.rb
Labels: pr-no-test

#5088 Do not reset the dev env when booting docker
  DOCKER.md
  Dockerfile
  docker-compose.yml
Labels: dev-test

#5142 Don't load distributed properties on inactive distributors
  app/serializers/api/cached_enterprise_serializer.rb
  spec/features/consumer/groups_spec.rb
  spec/serializers/api/cached_enterprise_serializer_spec.rb
Labels: performance

#5175 Memoize ScopeProductToHub in product list
  app/services/products_renderer.rb
Labels: performance

#5169 make shop name a link on /account
  app/views/spree/users/_open_orders.html.haml
  app/views/spree/users/_past_orders.html.haml
  spec/features/consumer/account_spec.rb
Labels: easy-test

#5197 Cart populate performance
  app/services/variants_stock_levels.rb
Labels: performance

#5202 Improve Checkout error handling in JS
  app/assets/javascripts/darkswarm/services/checkout.js.coffee
  spec/javascripts/unit/darkswarm/services/checkout_spec.js.coffee
Labels: bug-s2

#5172 Increase max characters for locale in spree_users
  db/migrate/20200406085833_increase_characters_of_locale_in_spree_users.rb
  db/schema.rb
Labels: dev-test, pr-staged-fr

#5186 Take sku overrides into account in customer totals report
  app/services/variant_overrides_indexed.rb
  lib/open_food_network/orders_and_fulfillments_report.rb
  lib/open_food_network/orders_and_fulfillments_report/customer_totals_report.rb
  spec/lib/open_food_network/orders_and_fulfillments_report/customer_totals_report_spec.rb
  spec/services/variant_overrides_indexed_spec.rb
Labels: easy-test

#5196 Admin Customers performance
  app/controllers/admin/customers_controller.rb
  app/models/spree/user.rb
  app/serializers/api/admin/customer_serializer.rb
  spec/serializers/api/admin/customer_serializer_spec.rb
Labels: performance

#5152 Add missing indexes to spree_orders and spree_products
  db/migrate/20200404080853_add_user_id_index_to_spree_orders.rb
  db/migrate/20200404081018_add_supplier_id_index_to_spree_products.rb
  db/schema.rb
Labels: dev-test, pr-staged-uk

#5283 Fix disappearing tags issue
  app/controllers/admin/customers_controller.rb
Labels: pr-staged-au

#5253 Make edit order page work even if inventory_items dont have a corresponding line_item in the order
  .rubocop_manual_todo.yml
  app/views/spree/admin/orders/_shipment_manifest.html.haml
  spec/features/admin/order_print_ticket_spec.rb
  spec/features/admin/order_spec.rb
  spec/features/admin/orders_spec.rb
Labels: bug-s2, feedback-needed, pr-staged-fr

#5261 [Mobile] Make search box font size be 16px so that no zoom happens on iphone
  app/assets/stylesheets/darkswarm/_shop-inputs.css.scss
Labels: pr-staged-es

#5256 Fix sorting of orders list
  app/assets/javascripts/admin/orders/controllers/orders_controller.js.coffee
  spec/javascripts/unit/admin/customers/controllers/customers_controller_spec.js.coffee
  spec/javascripts/unit/admin/orders/controllers/orders_controller_spec.js.coffee
Labels: easy-test

#5265 [Mobile] Shop product filters
  app/assets/images/icn-search-grey.png
  app/assets/javascripts/darkswarm/controllers/products_controller.js.coffee
  app/assets/javascripts/templates/filter_selector.html.haml
  app/assets/javascripts/templates/price_breakdown_button.html.haml
  app/assets/stylesheets/darkswarm/_shop-filters.css.scss
  app/assets/stylesheets/darkswarm/_shop-inputs.css.scss
  app/assets/stylesheets/darkswarm/_shop-navigation.css.scss
  app/assets/stylesheets/darkswarm/_shop-popovers.css.scss
  app/assets/stylesheets/darkswarm/_shop-product-rows.css.scss
  app/assets/stylesheets/darkswarm/_shop-product-thumb.css.scss
  app/assets/stylesheets/darkswarm/_shop-taxon-flag.css.scss
  app/assets/stylesheets/darkswarm/account.css.scss
  app/assets/stylesheets/darkswarm/active_table.css.scss
  app/assets/stylesheets/darkswarm/active_table_search.css.scss
  app/assets/stylesheets/darkswarm/big-input.scss
  app/assets/stylesheets/darkswarm/branding.css.scss
  app/assets/stylesheets/darkswarm/checkout.css.scss
  app/assets/stylesheets/darkswarm/distributor_header.css.scss
  app/assets/stylesheets/darkswarm/embedded_shopfront.css.scss
  app/assets/stylesheets/darkswarm/home_panes.css.scss
  app/assets/stylesheets/darkswarm/hub_node.css.scss
  app/assets/stylesheets/darkswarm/images.css.scss
  app/assets/stylesheets/darkswarm/map.css.scss
  app/assets/stylesheets/darkswarm/mixins.scss
  app/assets/stylesheets/darkswarm/modal-enterprises.css.scss
  app/assets/stylesheets/darkswarm/page_alert.css.scss
  app/assets/stylesheets/darkswarm/producer_node.css.scss
  app/assets/stylesheets/darkswarm/shop.css.scss
  app/assets/stylesheets/darkswarm/shop_search.css.scss
  app/assets/stylesheets/darkswarm/shop_tabs.css.scss
  app/assets/stylesheets/darkswarm/tabset.css.scss
  app/assets/stylesheets/darkswarm/taxons.css.scss
  app/assets/stylesheets/darkswarm/ui.css.scss
  app/assets/stylesheets/darkswarm/variables.css.scss
  app/views/shop/products/_filters.html.haml
  app/views/shop/products/_form.html.haml
  app/views/shop/products/_search_feedback.haml
  app/views/shop/products/_searchbar.haml
  app/views/shopping_shared/tabs/_shop.html.haml
  config/locales/en.yml
Labels: pr-no-test

#5250 Add cache to mirror_db script
  script/mirror_db.sh
Labels: dev-test

#5146 Add PROFILE var to set production-like settings
  .gitignore
  config/environments/development.rb
Labels: dev-test

#5178 Dont populate empty cart
  app/assets/javascripts/darkswarm/directives/shop_variant.js.coffee
  spec/javascripts/unit/darkswarm/services/cart_spec.js.coffee
Labels: performance

#5315 OrderCylesController tweaks
  app/controllers/api/order_cycles_controller.rb
Labels: performance

#5320 [Spree 2.1] Fix variant overrides specs and shops spec
  app/controllers/admin/variant_overrides_controller.rb
  app/models/enterprise.rb
Labels: pr-no-test

#5247 Added placeholders in variant edit page
  app/views/spree/admin/variants/_form.html.haml
  config/locales/en.yml
Labels: easy-test

#5259 Add extra social media to order confirmation email
  app/assets/stylesheets/mail/email.css.scss
  app/models/content_configuration.rb
  app/views/shared/mailers/_social_and_contact.html.haml
  app/views/spree/order_mailer/confirm_email_for_customer.html.haml
Labels: easy-test
