Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2020-11, with the labels that each got.

#6274 Use rubocop auto correct to fix a number of issues
  .rubocop_manual_todo.yml
  .rubocop_todo.yml
  lib/spree/core/controller_helpers/auth.rb
  lib/spree/core/delegate_belongs_to.rb
  spec/controllers/checkout_controller_spec.rb
  spec/factories.rb
  spec/factories/address_factory.rb
  spec/factories/state_factory.rb
  spec/factories/stock_location_factory.rb
  spec/features/admin/variants_spec.rb
  spec/lib/open_food_network/orders_and_fulfillments_report/customer_totals_report_spec.rb
  spec/lib/open_food_network/packing_report_spec.rb
  spec/lib/stripe/credit_card_cloner_spec.rb
  spec/models/enterprise_spec.rb
  spec/models/product_import/inventory_reset_strategy_spec.rb
  spec/models/spree/address_spec.rb
  spec/models/spree/credit_card_spec.rb
  spec/models/spree/order/checkout_spec.rb
  spec/models/spree/order/payment_spec.rb
  spec/models/spree/order_inventory_spec.rb
  spec/models/spree/order_spec.rb
  spec/models/spree/payment_spec.rb
  spec/models/spree/zone_spec.rb
  spec/requests/api/orders_spec.rb
  spec/services/checkout/form_data_adapter_spec.rb
  spec/services/user_locale_setter_spec.rb
  spec/swagger_helper.rb
  spec/views/spree/admin/payment_methods/index.html.haml_spec.rb
Labels: pr-no-test

#6281 Add missing translation key for enterprise taxon ordering
  app/views/admin/enterprises/form/_shop_preferences.html.haml
  config/locales/en.yml
Labels: pr-no-test

#5885 [Bye bye Spree] Bring models product, variant, price from spree_core
  app/models/concerns/product_stock.rb
  app/models/spree/option_type.rb
  app/models/spree/option_type_decorator.rb
  app/models/spree/option_value.rb
  app/models/spree/price.rb
  app/models/spree/price_decorator.rb
  app/models/spree/product.rb
  app/models/spree/product_decorator.rb
  app/models/spree/product_option_type.rb
  app/models/spree/product_option_type_decorator.rb
  app/models/spree/product_property.rb
  app/models/spree/product_property_decorator.rb
  app/models/spree/variant.rb
  app/models/spree/variant_decorator.rb
  config/locales/en.yml
  lib/spree/core/product_duplicator.rb
  lib/spree/product_duplicator.rb
  spec/factories/price_factory.rb
  spec/lib/spree/core/product_duplicator_spec.rb
  spec/lib/spree/product_duplicator_spec.rb
  spec/models/spree/product_property_spec.rb
  spec/models/spree/product_spec.rb
  spec/models/spree/variant_spec.rb
Labels: blocked

#6134 Improve Webmock debugging
  spec/spec_helper.rb
Labels: pr-no-test

#6324 [Rails 4.1] Update deep_munge patch to rails 4.1, the code is now in Request::Utils
  lib/action_dispatch/request.rb
Labels: pr-no-test

#6186 [Rails-4.1] Some small fixes to the rails 4.1 upgrade branch
  app/controllers/admin/enterprises_controller.rb
  app/models/spree/user.rb
  lib/open_food_network/customers_report.rb
  spec/models/product_importer_spec.rb
Labels: pr-no-test

#6210 Update the base Ubuntu Docker image from 18.04 to 20.04
  Dockerfile
Labels: dev-test

#6373 specify Spree routes for pagination, fix 500 on admin/users
  app/views/spree/admin/users/index.html.haml
  app/views/spree/admin/zones/index.html.haml
Labels: pr-staged-es

#6361 move gateway_error require to lib/spree/core.rb
  app/controllers/checkout_controller.rb
  app/controllers/spree/admin/orders_controller.rb
  lib/spree/core.rb
  spec/controllers/spree/admin/orders/payments/payments_controller_refunds_spec.rb
  spec/controllers/spree/admin/orders/payments/payments_controller_spec.rb
  spec/models/spree/order_spec.rb
  spec/models/spree/payment_spec.rb
Labels: feedback-needed

#6377 Repeat calculator migrations to clean up existing data
  db/migrate/20201113163155_repeat_move_all_calculators_outside_the_spree_namespace.rb
  db/migrate/20201113163227_repeat_move_calculators_preferences_outside_spree_namespace.rb
Labels: dev-test

#6258 Upgrade aws-sdk and switch to S3 virtual host style URLs
  Gemfile
  Gemfile.lock
  app/models/spree/image.rb
  config/initializers/spree.rb
Labels: dev-test, pr-staged-au

#6385 SIMPLE: updated db/schema.rb with 'bundle exec rake db:migrate'
  db/schema.rb
Labels: pr-no-test

#6390 SIMPLE: added scripts for running test suite in quiet mode
  docker/README.md
  docker/qtest
  docker/qtest-log
Labels: pr-no-test

#6409 Added information for testing in README.md
  README.md
Labels: pr-no-test

#6277 Move Spree::Admin::BaseController to Admin::BaseController
  app/controllers/admin/base_controller.rb
  app/controllers/admin/bulk_line_items_controller.rb
  app/controllers/admin/contents_controller.rb
  app/controllers/admin/invoice_settings_controller.rb
  app/controllers/admin/manager_invitations_controller.rb
  app/controllers/admin/matomo_settings_controller.rb
  app/controllers/admin/product_import_controller.rb
  app/controllers/admin/stripe_accounts_controller.rb
  app/controllers/admin/stripe_connect_settings_controller.rb
  app/controllers/spree/admin/base_controller.rb
  app/controllers/spree/admin/general_settings_controller.rb
  app/controllers/spree/admin/invoices_controller.rb
  app/controllers/spree/admin/mail_methods_controller.rb
  app/controllers/spree/admin/orders/customer_details_controller.rb
  app/controllers/spree/admin/orders_controller.rb
  app/controllers/spree/admin/overview_controller.rb
  app/controllers/spree/admin/payments_controller.rb
  app/controllers/spree/admin/reports_controller.rb
  app/controllers/spree/admin/resource_controller.rb
  app/controllers/spree/admin/search_controller.rb
  app/controllers/spree/admin/tax_settings_controller.rb
  app/controllers/spree/admin/taxons_controller.rb
  engines/order_management/app/controllers/order_management/reports/bulk_coop_controller.rb
  engines/order_management/app/controllers/order_management/reports/enterprise_fee_summaries_controller.rb
  spec/controllers/admin/base_controller_spec.rb
  spec/features/admin/variant_overrides_spec.rb
Labels: pr-no-test

#6293 Add task to print Subscriptions debug info
  lib/tasks/subscriptions/debug.rake
Labels: pr-no-test

#6357 Update secret key base
  config/initializers/secret_token.rb
Labels: pr-staged-es
