Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2020-07, with the labels that each got.

#5706 Fix admin enterprises controller spec
  spec/controllers/admin/enterprises_controller_spec.rb
Labels: pr-no-test

#5682 Move default versions of Paperclip-managed images to /public
  app/models/content_configuration.rb
  config/initializers/spree.rb
  public/default_images/home.jpg
  public/default_images/ofn-logo-footer.png
  public/default_images/ofn-logo-mobile.svg
  public/default_images/ofn-logo.png
  spec/models/content_configuration_spec.rb
Labels: v3-regression

#5703 Checkout addresses
  app/services/user_default_address_setter.rb
  db/migrate/20200630070422_require_timestamps.rb
  db/schema.rb
  spec/features/consumer/shopping/checkout_spec.rb
  spec/models/spree/user_spec.rb
Labels: v3-regression

#5709 Replace empty? with blank? and replace unless empty? with if present?
  app/controllers/admin/enterprises_controller.rb
  app/controllers/checkout_controller.rb
  app/controllers/spree/admin/image_settings_controller.rb
  app/controllers/spree/admin/products_controller.rb
  app/controllers/user_registrations_controller.rb
  app/serializers/api/admin/enterprise_serializer.rb
  app/serializers/api/admin/units_variant_serializer.rb
  app/services/permitted_attributes/enterprise.rb
  app/services/permitted_attributes/order_cycle.rb
  app/services/permitted_attributes/subscription.rb
  app/views/admin/producer_properties/_producer_property_fields.html.haml
Labels: pr-no-test, v3-regression

#5701 Noimage
  app/assets/javascripts/darkswarm/services/products.js.coffee
  app/assets/javascripts/templates/product_modal.html.haml
  app/serializers/api/admin/product_serializer.rb
  app/serializers/api/variant_serializer.rb
  app/views/groups/show.html.haml
  app/views/spree/admin/products/new.html.haml
  app/views/spree/admin/variants/_autocomplete.js.erb
  app/views/spree/orders/_bought.html.haml
  app/views/spree/orders/_line_item.html.haml
  app/views/spree/orders/_summary.html.haml
  app/views/spree/shared/_variant_thumbnail.html.haml
  public/noimage/group.png
  public/noimage/large.png
  public/noimage/mini.png
  public/noimage/product.png
  public/noimage/small.png
  spec/features/admin/bulk_product_update_spec.rb
  spec/javascripts/unit/darkswarm/services/products_spec.js.coffee
Labels: v3-regression

#5667 Stabilise shopping specs and open them for change
  spec/features/consumer/shopping/embedded_shopfronts_spec.rb
  spec/features/consumer/shopping/shopping_spec.rb
  spec/features/consumer/shopping/variant_overrides_spec.rb
  spec/support/request/checkout_workflow.rb
  spec/support/request/shop_workflow.rb
  spec/support/request/ui_component_helper.rb
  spec/support/request/web_helper.rb
Labels: pr-no-test

#5601 Enhancement/5454 make links to shops under Groups > Producers open in new tab
  app/views/producers/_fat.html.haml
  app/views/producers/_skinny.html.haml
Labels: easy-test

#5599 Make Enter submit the form on both products and orders admin
  app/views/spree/admin/orders/_filters.html.haml
  app/views/spree/admin/products/index/_filters.html.haml
Labels: easy-test

#5699 Make button border radius consistent
  app/views/spree/orders/form/_update_buttons.html.haml
Labels: easy-test

#5578 Update orders swagger spec and fix api_key access to orders endpoint
  Gemfile
  Gemfile.lock
  app/controllers/api/orders_controller.rb
  config/routes.rb
  spec/requests/api/orders_spec.rb
  spec/swagger_helper.rb
  swagger.yaml
  swagger/v1/swagger.yaml
Labels: dev-test

#5674 Fix flaky caching spec
  spec/features/consumer/caching/darkswarm_caching_spec.rb
Labels: pr-no-test

#5728 Update ams dependency comment
  Gemfile
Labels: pr-no-test

#5742 Fix flaky shopping_spec
  spec/support/request/shop_workflow.rb
Labels: tech debt

#5746 Remove dead specs helper method
  spec/support/request/authentication_workflow.rb
Labels: pr-no-test

#5739 Flaky spec order_cycles/complex_updating_specific_time
  spec/features/admin/order_cycles/complex_updating_specific_time_spec.rb
Labels: pr-no-test

#5759 Comment very flaky spec
  spec/models/variant_override_spec.rb
Labels: pr-no-test

#5766 5764 Provide credit card brand to Pin Payments
  app/services/checkout/form_data_adapter.rb
  spec/services/checkout/form_data_adapter_spec.rb
Labels: feedback-needed

#5756 Make broken spec fail reliably and set it pending
  spec/features/consumer/shopping/shopping_spec.rb
Labels: pr-no-test

#5793 Make charges update method update the first pending payment
  app/models/spree/order_decorator.rb
Labels: pr-staged-fr

#5677 Bring ControllerHelpers from Spree and remove spree root path
  .rubocop_manual_todo.yml
  app/controllers/api/base_controller.rb
  app/controllers/base_controller.rb
  app/controllers/cart_controller.rb
  app/controllers/enterprises_controller.rb
  app/controllers/home_controller.rb
  app/controllers/spree/admin/base_controller.rb
  app/controllers/spree/admin/mail_methods_controller.rb
  app/controllers/spree/admin/orders_controller.rb
  app/controllers/spree/home_controller.rb
  app/controllers/spree/orders_controller.rb
  app/controllers/spree/store_controller.rb
  app/controllers/spree/user_registrations_controller.rb
  app/controllers/user_registrations_controller.rb
  app/views/spree/layouts/_admin_body.html.haml
  config/routes.rb
  config/routes/spree.rb
  lib/spree/core/controller_helpers.rb
  lib/spree/core/controller_helpers/auth.rb
  lib/spree/core/controller_helpers/auth_decorator.rb
  lib/spree/core/controller_helpers/common.rb
  lib/spree/core/controller_helpers/order.rb
  lib/spree/core/controller_helpers/order_decorator.rb
  lib/spree/core/controller_helpers/respond_with.rb
  lib/spree/core/controller_helpers/respond_with_decorator.rb
  lib/spree/core/controller_helpers/ssl.rb
  spec/controllers/admin/bulk_line_items_controller_spec.rb
  spec/controllers/admin/customers_controller_spec.rb
  spec/controllers/admin/enterprises_controller_spec.rb
  spec/controllers/admin/inventory_items_controller_spec.rb
  spec/controllers/admin/proxy_orders_controller_spec.rb
  spec/controllers/admin/schedules_controller_spec.rb
  spec/controllers/admin/stripe_accounts_controller_spec.rb
  spec/controllers/admin/stripe_connect_settings_controller_spec.rb
  spec/controllers/admin/subscriptions_controller_spec.rb
  spec/controllers/admin/tag_rules_controller_spec.rb
  spec/controllers/admin/variant_overrides_controller_spec.rb
  spec/controllers/api/base_controller_spec.rb
  spec/controllers/spree/admin/mail_methods_controller_spec.rb
  spec/controllers/spree/admin/orders_controller_spec.rb
  spec/controllers/spree/admin/products_controller_spec.rb
  spec/controllers/spree/credit_cards_controller_spec.rb
  spec/controllers/spree/orders_controller_spec.rb
  spec/controllers/spree/store_controller_spec.rb
  spec/controllers/stripe/callbacks_controller_spec.rb
  spec/features/admin/authentication_spec.rb
  spec/requests/home_controller_spec.rb
Labels: bug-s2

#5775 Make OC advanced settings work by permitting the extra parameter and make the OC edit page work with that option activated
  app/models/spree/product_decorator.rb
  app/serializers/api/admin/for_order_cycle/enterprise_serializer.rb
  app/services/permitted_attributes/order_cycle.rb
  spec/controllers/admin/order_cycles_controller_spec.rb
  spec/services/exchange_products_renderer_spec.rb
Labels: pr-staged-uk

#5798 Make charges update method update the first pending payment
  app/models/spree/order_decorator.rb
Labels: feedback-needed

#5747 Make keyboard UI close on iOS when done searching
  app/assets/javascripts/darkswarm/directives/disable_enter_with_blur.js.coffee
  app/views/shop/products/_searchbar.haml
Labels: feedback-needed, pr-staged-au

#5799 Add migration to fix calculator preferences
  db/migrate/20200721135726_move_calculators_preferences_outside_spree_namespace.rb
  db/schema.rb
Labels: pr-staged-au

#5826 Update GETTING_STARTED.md
  GETTING_STARTED.md
Labels: pr-no-test

#5833 Add unit tests for order.charge_shipping_and_payment_fees!
  spec/models/spree/order_spec.rb
Labels: pr-no-test
