Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2021-01, with the labels that each got.

#6564 Added translation keys "en.description" "en.display" "en.tags"
  config/locales/en.yml
Labels: pr-no-test

#6595 Remove jsonp request handling logic
  app/controllers/api/base_controller.rb
Labels: pr-no-test

#6555 Extends spec coverage of Tax Rates settings - CRUD operations
  spec/features/admin/configuration/tax_rates_spec.rb
Labels: pr-no-test

#6551 Track request queuing in Datadog
  config/initializers/datadog.rb
Labels: pr-no-test

#6614 API Bugnag errors
  app/controllers/api/base_controller.rb
  app/helpers/admin/injection_helper.rb
Labels: pr-no-test

#6615 Money!
  Gemfile
  Gemfile.lock
  app/helpers/spree/reports_helper.rb
  lib/spree/money.rb
  lib/spree/money_decorator.rb
Labels: pr-no-test

#6627 Delete dead code Spree::Product#available?
  app/models/spree/product.rb
  spec/models/spree/product_spec.rb
Labels: pr-no-test

#6630 Update haml lint config
  .haml-lint.yml
  .hound.yml
Labels: pr-no-test

#6578 Products endpoint content type
  app/assets/javascripts/darkswarm/services/order_cycle_resource.js.coffee
  app/controllers/api/base_controller.rb
  app/controllers/api/order_cycles_controller.rb
  app/controllers/concerns/api_action_caching.rb
  spec/controllers/api/order_cycles_controller_spec.rb
  spec/features/consumer/caching/shops_caching_spec.rb
  spec/javascripts/unit/darkswarm/services/products_spec.js.coffee
Labels: pr-no-test

#6366 Fix customer balance n+1
  app/controllers/admin/customers_controller.rb
  app/serializers/api/admin/customer_serializer.rb
  app/serializers/api/admin/customer_with_balance_serializer.rb
  app/serializers/api/admin/customer_with_calculated_balance_serializer.rb
  app/services/customers_with_balance.rb
  lib/open_food_network/feature_toggle.rb
  spec/controllers/admin/customers_controller_spec.rb
  spec/factories/order_factory.rb
  spec/features/admin/customers_spec.rb
  spec/models/spree/order_spec.rb
  spec/models/spree/payment_spec.rb
  spec/serializers/api/admin/customer_with_balance_serializer_spec.rb
  spec/services/customers_with_balance_spec.rb
Labels: bug-s2

#6633 Adding inverse_of
  app/models/spree/inventory_unit.rb
  app/models/spree/order.rb
  app/models/spree/return_authorization.rb
  app/models/spree/shipping_category.rb
  app/models/spree/shipping_method.rb
  app/models/spree/shipping_method_category.rb
  app/models/spree/shipping_rate.rb
  app/models/spree/stock_item.rb
  app/models/spree/stock_location.rb
  app/models/spree/tax_category.rb
  app/models/spree/tax_rate.rb
  app/models/spree/variant.rb
  app/models/spree/zone.rb
  app/models/spree/zone_member.rb
Labels: pr-no-test

#6642 Doc customer serializer
  app/serializers/api/admin/customer_with_balance_serializer.rb
Labels: pr-no-test

#6653 Dead code: #has_available_payment
  app/models/spree/order.rb
  spec/models/spree/order/checkout_spec.rb
  spec/models/spree/order/state_machine_spec.rb
  spec/models/spree/order_spec.rb
Labels: pr-no-test

#6656 Fix payment identifier generation
  app/models/spree/payment.rb
  spec/models/spree/payment_spec.rb
Labels: pr-no-test

#6442 Rails 5 upgrade with dualboot
  .rubocop_styleguide.yml
  Gemfile
  Gemfile_next.lock
Labels: dev-test

#6641 Ensure ShippingMethod is correctly using soft-deletion
  app/models/spree/shipping_method.rb
  spec/models/spree/shipping_method_spec.rb
Labels: pr-no-test

#6654 Remove #update_attributes_without_callbacks
  app/models/spree/order.rb
  engines/order_management/app/services/order_management/order/updater.rb
  engines/order_management/spec/services/order_management/order/updater_spec.rb
  spec/models/spree/order/updating_spec.rb
Labels: pr-no-test

#6677 Remove debugging code from spec
  spec/controllers/spree/credit_cards_controller_spec.rb
Labels: pr-no-test

#6672 Delete dead code #update_hooks
  app/models/spree/order.rb
  engines/order_management/app/services/order_management/order/updater.rb
  spec/models/spree/order/updating_spec.rb
  spec/models/spree/order_spec.rb
Labels: pr-no-test

#6692 Update mail delivery mocks in subscription specs
  engines/order_management/spec/services/order_management/subscriptions/summarizer_spec.rb
Labels: pr-no-test

#6690 Update old setting to serve static assets
  config/environments/production.rb
  config/environments/staging.rb
  config/environments/test.rb
Labels: pr-no-test

#6688 Remove old deprecation warning
  spec/spec_helper.rb
Labels: pr-no-test

#6706 Fix issue with orphaned adjustments in migration
  db/migrate/20201219120055_add_order_to_adjustments.rb
Labels: dev-test, pr-staged-uk

#6675 Remove ability to create new product from products page, use /admin/products/new instead.
  app/views/spree/admin/products/index/_header.html.haml
  app/views/spree/admin/products/new.js.erb
  spec/features/admin/products_spec.rb
Labels: pr-staged-fr

#6705 Pass request_queuing setting to Rack middleware
  config/initializers/datadog.rb
Labels: dev-test

#6722 Replace spree_get with simple get
  spec/controllers/admin/bulk_line_items_controller_spec.rb
  spec/controllers/admin/customers_controller_spec.rb
  spec/controllers/admin/enterprises_controller_spec.rb
  spec/controllers/admin/order_cycles_controller_spec.rb
  spec/controllers/admin/proxy_orders_controller_spec.rb
  spec/controllers/admin/schedules_controller_spec.rb
  spec/controllers/admin/stripe_accounts_controller_spec.rb
  spec/controllers/admin/stripe_connect_settings_controller_spec.rb
  spec/controllers/admin/subscriptions_controller_spec.rb
  spec/controllers/api/customers_controller_spec.rb
  spec/controllers/api/exchange_products_controller_spec.rb
  spec/controllers/api/shops_controller_spec.rb
  spec/controllers/api/statuses_controller_spec.rb
  spec/controllers/api/variants_controller_spec.rb
  spec/controllers/enterprises_controller_spec.rb
  spec/controllers/shop_controller_spec.rb
Labels: pr-no-test

#6070 Full-width admin layout
  app/assets/javascripts/admin/all.js
  app/assets/javascripts/admin/spree/base.js.erb
  app/assets/stylesheets/admin/all.scss
  app/assets/stylesheets/admin/components/navigation.scss
  app/assets/stylesheets/admin/dashboard_item.scss
  app/assets/stylesheets/admin/grid.scss
  app/assets/stylesheets/admin/shared/forms.scss
  app/views/admin/enterprise_fees/_calculator_settings.html.haml
  app/views/admin/enterprise_groups/_form.html.haml
  app/views/admin/enterprises/form/_payment_methods.html.haml
  app/views/admin/enterprises/form/_shipping_methods.html.haml
  app/views/admin/enterprises/form/_shop_preferences.html.haml
  app/views/admin/enterprises/index.html.haml
  app/views/admin/order_cycles/_name_and_timing_form.html.haml
  app/views/admin/order_cycles/_simple_form.html.haml
  app/views/admin/variant_overrides/_hidden_products.html.haml
  app/views/admin/variant_overrides/_new_products.html.haml
  app/views/spree/admin/orders/bulk_management.html.haml
  app/views/spree/admin/orders/customer_details/_form.html.haml
  app/views/spree/admin/overview/_order_cycles.html.haml
  app/views/spree/admin/overview/_products.html.haml
  app/views/spree/admin/overview/single_enterprise_dashboard.html.haml
  app/views/spree/admin/products/_form.html.haml
  app/views/spree/admin/reports/index.html.haml
  app/views/spree/admin/shared/_hubs_sidebar.html.haml
  app/views/spree/layouts/_admin_body.html.haml
  vendor/assets/javascripts/jquery.adaptivemenu.js
  vendor/assets/javascripts/jquery.horizontalNav.js
  vendor/assets/stylesheets/skeleton.css
Labels: feedback-needed

#6726 Fixes a pending test case and improves the spec run time
  spec/features/admin/shipping_methods_spec.rb
Labels: pr-no-test
