Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2021-04, with the labels that each got.

#7289 Add code coverage reporting to our CI build with Codecov
  .github/workflows/build.yml
  .simplecov
  Gemfile
  Gemfile.lock
  README.md
Labels: pr-no-test

#7213 Make bullet activation optional
  config/initializers/bullet.rb
Labels: pr-no-test

#7236 Update Exchange touch on Enterprise to use #touch_later
  app/models/exchange.rb
  spec/models/enterprise_caching_spec.rb
Labels: pr-no-test

#7321 Remove Bugherd
  app/controllers/spree/admin/general_settings_controller.rb
  app/models/spree/app_configuration.rb
  app/views/layouts/_bugherd_script.html.haml
  app/views/layouts/darkswarm.html.haml
  app/views/layouts/registration.html.haml
  app/views/spree/admin/shared/_head.html.haml
  config/locales/en.yml
  spec/features/admin/external_services_spec.rb
Labels: pr-no-test

#7340 Add test coverage: deleted enterprise fees
  spec/controllers/spree/admin/orders_controller_spec.rb
Labels: pr-no-test

#7288 Use the same Rubocop config on Code Climate as locally
  .codeclimate.yml
  .rubocop.yml
  .rubocop_styleguide.yml
Labels: pr-no-test

#7363 Enable customer_balance feature toggle to all users
  config/initializers/feature_toggles.rb
  spec/initializers/feature_toggles_spec.rb
Labels: feedback-needed

#7396 Enable customer_balance toggle in tests
  config/initializers/feature_toggles.rb
  engines/order_management/spec/services/order_management/subscriptions/payment_setup_spec.rb
  spec/controllers/admin/customers_controller_spec.rb
  spec/mailers/order_mailer_spec.rb
  spec/mailers/subscription_mailer_spec.rb
  spec/models/spree/order_spec.rb
  spec/models/spree/payment_spec.rb
  spec/serializers/api/order_serializer_spec.rb
Labels: pr-no-test

#7362 Fixes Alphabetical Sorting In Packing Reports
  lib/open_food_network/packing_report.rb
  spec/features/admin/reports_spec.rb
Labels: easy-test

#7432 Add tests to customers
  app/models/spree/order.rb
  spec/models/spree/order_spec.rb
Labels: pr-no-test

#7427 Instrument Flipper with ActiveSupport
  config/initializers/flipper.rb
Labels: dev-test

#7436 Replace duplicate #unauthorized method with module inclusion
  app/controllers/spree/admin/base_controller.rb
  config/locales/en.yml
  lib/spree/core/controller_helpers/auth.rb
Labels: pr-no-test

#7433 Notify Bugsnag if customer fails to be created
  app/models/spree/order.rb
  spec/controllers/api/v0/orders_controller_spec.rb
  spec/models/spree/order/checkout_spec.rb
  spec/models/spree/order_spec.rb
  spec/serializers/api/admin/order_serializer_spec.rb
  spec/serializers/api/current_order_serializer_spec.rb
Labels: bug-s2, pr-no-test

#7497 Use capture! if payment is already authorized
  app/models/spree/payment/processing.rb
  spec/factories/payment_factory.rb
  spec/jobs/subscription_confirm_job_spec.rb
  spec/models/spree/gateway/stripe_sca_spec.rb
  spec/models/spree/payment_spec.rb
Labels: feedback-needed

#7476 Increase the width of Stripe Elements fields in admin so they don't overlap
  app/views/spree/admin/payments/source_forms/_stripe.html.haml
  app/views/spree/admin/payments/source_forms/_stripe_sca.html.haml
Labels: easy-test

#7438 Change the position of order_cycle component into a shop front
  app/assets/stylesheets/darkswarm/_shop-navigation.scss
  app/assets/stylesheets/darkswarm/distributor_header.scss
  app/assets/stylesheets/darkswarm/shop_tabs.scss
  app/views/enterprises/shop.html.haml
  app/views/shopping_shared/_tabs.html.haml
Labels: easy-test
