Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2021-05, with the labels that each got.

#7526 Remove currency from OrderContents
  app/controllers/api/v0/shipments_controller.rb
  app/models/spree/order_contents.rb
Labels: pr-no-test

#7528 Reorder has_many relationship with :through option
  app/models/spree/option_type.rb
Labels: pr-no-test

#7552 Upgrade to rails 5.2.5 with "bundle update rails"
  Gemfile.lock
Labels: pr-no-test

#7565 [Rails 6.0] Replace be_success on test_response with status 200
  engines/order_management/spec/controllers/order_management/reports/bulk_coop_controller_spec.rb
  engines/order_management/spec/controllers/order_management/reports/enterprise_fee_summaries_controller_spec.rb
  spec/controllers/api/v0/enterprises_controller_spec.rb
  spec/controllers/api/v0/logos_controller_spec.rb
  spec/controllers/api/v0/promo_images_controller_spec.rb
  spec/controllers/api/v0/statuses_controller_spec.rb
  spec/controllers/api/v0/terms_and_conditions_controller_spec.rb
  spec/controllers/checkout_controller_spec.rb
  spec/controllers/shop_controller_spec.rb
  spec/controllers/spree/orders_controller_spec.rb
  spec/controllers/user_passwords_controller_spec.rb
  spec/performance/shop_controller_spec.rb
Labels: pr-no-test

#7568 [Rails 6.0] Use raw to render stripe mock js file
  app/views/shared/_stripe_js.html.haml
Labels: pr-no-test

#7402 Adds coverage for product deletion and cloning
  spec/controllers/api/v0/products_controller_spec.rb
  spec/features/admin/products_spec.rb
Labels: pr-no-test

#7578 Update things related to some package manager influencing setup process
  .node-version
  script/setup
Labels: pr-no-test

#7571 Properly mock validator and extend tests
  spec/controllers/spree/orders_controller_spec.rb
Labels: pr-no-test

#7593 Add bullet footer
  config/initializers/bullet.rb
Labels: pr-no-test

#7520 Shipment controller: test coverage and improvements
  app/controllers/api/v0/shipments_controller.rb
  engines/order_management/app/services/order_management/order/updater.rb
  spec/controllers/api/v0/shipments_controller_spec.rb
  spec/factories/shipping_method_factory.rb
Labels: feedback-needed

#7566 [Rails 6.0] Fix problem in erb template by explicitly setting format to js
  app/views/spree/admin/orders/_form.html.haml
Labels: dev-test

#7666 Stop Codecov failing good pull requests
  .github/codecov.yml
  .github/workflows/build.yml
Labels: pr-no-test

#7671 Add Spree copyright notice
  lib/spree/licence.md
Labels: pr-no-test

#7563 Adds file and fixture path to test product import
  spec/features/admin/product_import_spec.rb
  spec/fixtures/files/sample_file_120_products.csv
Labels: pr-no-test

#7679 Fix sample_data by filtering params for products
  lib/tasks/sample_data/product_factory.rb
Labels: pr-no-test

#7678 Update schema syntax with Rails 5.2
  db/schema.rb
Labels: pr-no-test

#7605 Products and Inventory import: Items units
  spec/features/admin/product_import_spec.rb
Labels: pr-no-test

#7641 [Rails 6.1] Fix view specs
  app/controllers/spree/orders_controller.rb
  app/views/spree/orders/form/_update_buttons.html.haml
  app/views/spree/shared/_order_details.html.haml
  spec/controllers/spree/orders_controller_spec.rb
  spec/views/spree/admin/payment_methods/index.html.haml_spec.rb
Labels: pr-no-test

#7690 Bump Ruby to 2.5.9
  .ruby-version
  Gemfile
  Gemfile.lock
Labels: pr-staged-es

#7711 Sidekiq!
  Gemfile
  Gemfile.lock
  app/controllers/spree/admin/orders_controller.rb
  app/mailers/spree/order_mailer.rb
  config/application.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/staging.rb
  config/initializers/sidekiq.rb
  config/routes/admin.rb
  config/schedule.rb
  config/sidekiq.yml
  spec/controllers/user_passwords_controller_spec.rb
  spec/jobs/heartbeat_job_spec.rb
  spec/spec_helper.rb
  spec/support/delayed_job_helper.rb
Labels: pr-staged-fr, pr-staged-uk
