Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2021-12, with the labels that each got.

#8526 Revoke transaction fee if payment is cancelled
  app/models/spree/payment.rb
  spec/models/spree/payment_spec.rb
Labels: pr-staged-uk

#8517 Remove references to deprecated application.yml config file.
  .github/workflows/build.yml
  .gitignore
  GETTING_STARTED.md
  config/application.yml.example
  config/environments/development.rb
  config/initializers/geocoder.rb
  config/schedule.rb
  docker-compose.yml
  lib/open_food_network/i18n_config.rb
  script/setup
Labels: pr-staged-fr

#8570 Update Rubocop config
  .rubocop.yml
  .rubocop_manual_todo.yml
  .rubocop_todo.yml
  app/models/spree/credit_card.rb
  app/models/spree/taxon.rb
  lib/open_food_network/orders_and_fulfillments_report/customer_totals_report.rb
  lib/spree/core/controller_helpers/common.rb
Labels: pr-no-test

#8503 Split checkout payment forms
  app/assets/stylesheets/darkswarm/split-checkout.scss
  app/controllers/concerns/checkout_callbacks.rb
  app/helpers/checkout_helper.rb
  app/services/checkout/params.rb
  app/views/split_checkout/_payment.html.haml
  app/views/split_checkout/payment/_check.html.erb
  app/views/split_checkout/payment/_gateway.html.haml
  app/views/split_checkout/payment/_paypal.html.haml
  app/views/split_checkout/payment/_stripe_sca.html.haml
  app/webpacker/controllers/paymentmethod_controller.js
  app/webpacker/controllers/stripe_cards_controller.js
  app/webpacker/controllers/stripe_controller.js
  config/locales/en.yml
  spec/javascripts/stimulus/paymentmethod_controller_test.js
  spec/javascripts/stimulus/stripe_cards_controller_test.js
Labels: feedback-needed

#8521 Confirmation popup on shop change in admin section.
  app/assets/javascripts/templates/partials/producer_details.html.haml
  app/views/producers/_fat.html.haml
Labels: pr-staged-uk

#8631 SplitCheckout - Handle submit on step2
  app/controllers/split_checkout_controller.rb
  app/views/split_checkout/_payment.html.haml
  app/views/split_checkout/payment/_stripe_sca.html.haml
  app/webpacker/controllers/paymentmethod_controller.js
  app/webpacker/controllers/stripe_cards_controller.js
  app/webpacker/controllers/stripe_controller.js
  spec/javascripts/stimulus/paymentmethod_controller_test.js
  spec/javascripts/stimulus/stripe_cards_controller_test.js
Labels: pr-staged-fr

#8555 Searching variants should order results by variant display name
  lib/open_food_network/scope_variants_for_search.rb
  spec/lib/open_food_network/scope_variants_to_search_spec.rb
Labels: pr-staged-uk

#8598 Configuration to automatically notify producers on order cycle close
  app/assets/stylesheets/admin/advanced_settings.scss
  app/assets/stylesheets/admin/components/buttons.scss
  app/assets/stylesheets/admin/openfoodnetwork.scss
  app/assets/stylesheets/admin/shared/forms.scss
  app/jobs/order_cycle_closing_job.rb
  app/models/order_cycle.rb
  app/services/permitted_attributes/order_cycle.rb
  app/views/admin/order_cycles/_advanced_settings.html.haml
  app/views/admin/order_cycles/edit.html.haml
  config/locales/en.yml
  config/sidekiq.yml
  db/migrate/20211129003853_add_processed_at_to_order_cycles.rb
  db/migrate/20211129014614_add_automatic_notifications_to_order_cycles.rb
  db/schema.rb
  spec/controllers/admin/order_cycles_controller_spec.rb
  spec/jobs/order_cycle_closing_job_spec.rb
  spec/models/order_cycle_spec.rb
Labels: pr-staged-uk

#8482 Search enterprises through name + city and state_name
  app/assets/javascripts/darkswarm/controllers/enterprises_controller.js.coffee
  app/assets/javascripts/darkswarm/filters/enterpriseMatchesNameQuery.js.coffee
  app/assets/javascripts/darkswarm/filters/enterpriseMatchesQuery.js.coffee
  app/assets/javascripts/darkswarm/services/enterprises.js.coffee
  spec/javascripts/unit/darkswarm/services/enterprise_spec.js.coffee
Labels: prod-test

#8647 Fix infinite loop in datepicker selection logic
  spec/system/admin/reports_spec.rb
Labels: pr-no-test

#8632 Set default_url_options in all environments
  .env.development
  .env.test
  config/application.rb
  config/environments/test.rb
  spec/base_spec_helper.rb
Labels: pr-no-test
