Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2021-03, with the labels that each got.

#6988 Remove unused RSpec specs filtering
  spec/spec_helper.rb
Labels: pr-no-test

#6987 Remove unnecessary delegation specs
  spec/models/enterprise_spec.rb
  spec/models/spree/addresses_spec.rb
  spec/support/matchers/delegate_matchers.rb
Labels: pr-no-test

#6986 Fix old pending locale-related spec
  spec/features/admin/multilingual_spec.rb
Labels: pr-no-test

#6982 Fix #5018: Allow access to payments tab for canceled orders
  app/controllers/spree/admin/payments_controller.rb
  spec/controllers/spree/admin/orders/payments/payments_controller_spec.rb
Labels: feedback-needed

#6995 Add gem to watch after data migrations
  Gemfile
  Gemfile.lock
  Gemfile_next.lock
Labels: pr-no-test

#7009 Remove subs-related performance specs
  engines/order_management/spec/performance/order_management/subscriptions/proxy_order_syncer_spec.rb
Labels: pr-no-test

#7054 Remove puts debugging in tests
  spec/controllers/spree/admin/users_controller_spec.rb
Labels: pr-no-test

#7001 Set up Bullet for development and testing
  Gemfile
  Gemfile.lock
  Gemfile_next.lock
  config/initializers/bullet.rb
Labels: pr-no-test

#6902 Setup Github Actions as CI
  .github/workflows/build.yml
  .rspec
  README.md
  Rakefile
  app/models/spree/order.rb
  app/models/spree/order/checkout.rb
  config/environments/test.rb
  spec/coverage_helper.rb
  spec/features/admin/enterprises/terms_and_conditions_spec.rb
  spec/features/consumer/multilingual_spec.rb
  spec/spec_helper.rb
  spec/support/request/cookie_helper.rb
  spec/support/request/web_helper.rb
Labels: tech debt

#7099 Rails 5.0 fixes
  app/controllers/spree/admin/payment_methods_controller.rb
  app/controllers/spree/admin/payments_controller.rb
  lib/stripe/authorize_response_patcher.rb
  spec/controllers/spree/admin/payment_methods_controller_spec.rb
Labels: pr-no-test

#7078 Disable code coverage by default
  .simplecov
  spec/coverage_helper.rb
  spec/spec_helper.rb
Labels: pr-no-test

#7102 Update miniracer to 0.3.1
  Gemfile
  Gemfile.lock
Labels: dev-test, pr-staged-uk

#7064 Abstract order balance in a simple PORO
  app/models/order_balance.rb
  spec/models/order_balance_spec.rb
Labels: pr-no-test

#7103 Combine model jobs in CI
  .github/workflows/build.yml
Labels: pr-no-test

#7114 Move invoice-related specs to their own file
  spec/controllers/spree/admin/orders/invoices_spec.rb
  spec/controllers/spree/admin/orders_controller_spec.rb
Labels: pr-no-test

#7125 Run Github CI build on pull_request event
  .github/workflows/build.yml
Labels: tech debt

#7113 Fix deprecation warning related to #reload
  app/models/spree/user.rb
Labels: pr-no-test

#7042 Fix money object deprecation warnings
  config/initializers/money.rb
  lib/spree/money.rb
  spec/features/admin/configuration/general_settings_spec.rb
  spec/lib/spree/money_spec.rb
Labels: tech debt

#7134 Feature-test payments report
  lib/open_food_network/payments_report.rb
  spec/features/admin/reports/payments_report_spec.rb
Labels: pr-no-test

#7135 Update order totals in paypal test setup
  spec/services/paypal_items_builder_spec.rb
Labels: pr-no-test

#7133 Fix `env` deprecated in Rails 5.0
  app/controllers/metal_decorator.rb
Labels: pr-no-test

#6879 Customer balance bulk coop report
  app/models/concerns/balance.rb
  app/models/spree/order.rb
  app/queries/complete_visible_orders.rb
  app/queries/outstanding_balance.rb
  engines/order_management/app/services/order_management/reports/bulk_coop/bulk_coop_report.rb
  engines/order_management/spec/services/order_management/reports/bulk_coop/bulk_coop_report_spec.rb
  lib/open_food_network/order_cycle_management_report.rb
  lib/open_food_network/reports/line_items.rb
  spec/lib/open_food_network/reports/line_items_spec.rb
  spec/models/concerns/balance_spec.rb
  spec/models/spree/order_spec.rb
  spec/queries/complete_visible_orders_spec.rb
  spec/services/order_data_masker_spec.rb
Labels: feedback-needed

#7145 Temporarily skip embedded shopfront flaky spec
  spec/features/consumer/shopping/embedded_shopfronts_spec.rb
Labels: pr-no-test

#7111 Replace assets config with public_file_server
  config/environments/production.rb
  config/environments/staging.rb
  config/environments/test.rb
Labels: pr-no-test

#7140 Rearrange and cover balance in subs mailer specs
  spec/mailers/subscription_mailer_spec.rb
Labels: pr-no-test

#7149 Rearrange order updater tests to make them method-centric
  engines/order_management/spec/services/order_management/order/updater_spec.rb
Labels: pr-no-test

#7116 Better test InvoiceRenderer
  app/services/invoice_renderer.rb
  spec/services/invoice_renderer_spec.rb
Labels: pr-no-test

#7096 Rails 5.2 add T&Cs helper
  app/controllers/checkout_controller.rb
  app/helpers/injection_helper.rb
  app/mailers/spree/order_mailer.rb
  app/mailers/subscription_mailer.rb
Labels: pr-no-test

#7095 Raisl 5 - Render plain and render head
  app/controllers/admin/bulk_line_items_controller.rb
  app/controllers/admin/column_preferences_controller.rb
  app/controllers/admin/enterprise_relationships_controller.rb
  app/controllers/admin/enterprise_roles_controller.rb
  app/controllers/admin/resource_controller.rb
  app/controllers/admin/tag_rules_controller.rb
  app/controllers/admin/variant_overrides_controller.rb
  app/controllers/api/enterprise_fees_controller.rb
  app/controllers/api/enterprises_controller.rb
  app/controllers/api/exchange_products_controller.rb
  app/controllers/api/shops_controller.rb
  app/controllers/discourse_sso_controller.rb
  app/controllers/enterprises_controller.rb
  app/controllers/line_items_controller.rb
  app/controllers/spree/admin/products_controller.rb
  app/controllers/stripe/callbacks_controller.rb
  app/controllers/stripe/webhooks_controller.rb
  lib/spree/core/controller_helpers/common.rb
  spec/controllers/api/base_controller_spec.rb
  spec/controllers/base_controller_spec.rb
  spec/controllers/spree/admin/base_controller_spec.rb
Labels: pr-no-test

#7143 Reduce retention period of Spree state changes and log entries from 6 to 3 months
  lib/tasks/data/remove_transient_data.rb
  spec/lib/tasks/data/remove_transient_data_spec.rb
Labels: pr-no-test

#7142 Tiny improvement of specs using OutstandingBalance class
  spec/controllers/spree/users_controller_spec.rb
  spec/queries/outstanding_balance_spec.rb
Labels: pr-no-test

#7045 add automated tests for unit price in the shopfront
  spec/features/consumer/shopping/unit_price_spec.rb
  spec/views/spree/orders/edit.html.haml_spec.rb
Labels: pr-no-test

#7121 Update adjustments
  db/migrate/20210315163900_update_associations.rb
  db/schema.rb
Labels: pr-staged-uk

#7157 DCOTW: Order#billing_firstname and Order#billing_lastname
  app/models/spree/order.rb
Labels: pr-no-test

#7100 Rails 5-2 - View spec in rails5
  spec/features/consumer/shopping/checkout_auth_spec.rb
  spec/features/consumer/shopping/checkout_paypal_spec.rb
  spec/features/consumer/shopping/checkout_spec.rb
  spec/features/consumer/shopping/checkout_stripe_spec.rb
  spec/features/consumer/shopping/embedded_shopfronts_spec.rb
  spec/features/consumer/shopping/variant_overrides_spec.rb
  spec/spec_helper.rb
  spec/support/request/checkout_request_helper.rb
  spec/support/spree/checkout_helpers.rb
  spec/views/spree/shared/_order_details.html.haml_spec.rb
Labels: pr-no-test

#7177 Fix balances order cycle report regression
  app/queries/outstanding_balance.rb
  spec/controllers/spree/admin/reports_controller_spec.rb
  spec/queries/outstanding_balance_spec.rb
Labels: bug-s2, pr-no-test

#7025 [Adjustments] Simplify order tax adjustments
  app/models/spree/order.rb
  app/models/spree/tax_rate.rb
  spec/models/spree/order_spec.rb
Labels: pr-staged-uk

#7189 [Rails 5.2] Fix validation problem in inventory items
  app/models/inventory_item.rb
Labels: pr-no-review

#7186 [Rails 5.2] Fix tax_category validation to work in rails 5.2
  app/models/spree/tax_rate.rb
Labels: pr-no-test

#7190 [rails 5.2] Fix more spec syntax
  spec/controllers/admin/bulk_line_items_controller_spec.rb
  spec/controllers/api/orders_controller_spec.rb
  spec/controllers/cart_controller_spec.rb
  spec/controllers/checkout_controller_spec.rb
  spec/controllers/enterprises_controller_spec.rb
  spec/controllers/line_items_controller_spec.rb
Labels: pr-no-test

#7187 [Rails 5.2] Relation#Uniq is deprecated, distinct is recommended instead
  app/models/spree/product.rb
Labels: pr-no-test

#7184 Update deprecated errors.set syntax
  lib/spree/localized_number.rb
Labels: pr-no-test

#7212 Fix multiple N+1s on /admin/customers.json
  app/controllers/admin/customers_controller.rb
Labels: pr-no-test

#7219 Refactor unit price i18n keys
  app/assets/javascripts/templates/shop_variant_with_unit_price.html.haml
  app/views/shared/menu/_cart_sidebar.html.haml
  app/views/spree/admin/products/new.html.haml
  app/views/spree/admin/variants/_form.html.haml
  config/locales/en.yml
Labels: pr-staged-uk

#7241 [rails 5-2] More fixes to rspec syntax
  lib/open_food_network/order_cycle_permissions.rb
  spec/controllers/admin/customers_controller_spec.rb
  spec/controllers/admin/enterprises_controller_spec.rb
  spec/controllers/admin/invoice_settings_controller_spec.rb
  spec/controllers/admin/order_cycles_controller_spec.rb
  spec/controllers/admin/proxy_orders_controller_spec.rb
  spec/controllers/admin/schedules_controller_spec.rb
  spec/controllers/admin/stripe_accounts_controller_spec.rb
  spec/controllers/admin/stripe_connect_settings_controller_spec.rb
  spec/controllers/admin/subscriptions_controller_spec.rb
  spec/controllers/admin/variant_overrides_controller_spec.rb
  spec/controllers/api/base_controller_spec.rb
  spec/controllers/api/shops_controller_spec.rb
  spec/controllers/spree/orders_controller_spec.rb
  spec/controllers/spree/users_controller_spec.rb
  spec/controllers/stripe/webhooks_controller_spec.rb
Labels: pr-no-test

#7261 Remove Semaphore CI badge
  README.md
Labels: pr-no-test

#7247 Upgrade to ruby 2.5.8
  .ruby-version
  Gemfile
  Gemfile.lock
Labels: pr-staged-es

#7255 Raise errors in specs with missing translations
  app/views/admin/variant_overrides/_hidden_products.html.haml
  app/views/spree/admin/orders/_filters.html.haml
  config/environments/test.rb
  config/locales/en.yml
  engines/order_management/spec/features/order_management/reports/bulk_coop_spec.rb
  spec/lib/spree/i18n_spec.rb
  spec/support/i18n_error_raising.rb
Labels: pr-no-test
