Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2021-09, with the labels that each got.

#8127 Strip subdomains from session cookie host
  .github/workflows/build.yml
  config/application.rb
  config/initializers/session_store.rb
Labels: pr-staged-uk

#8146 Make log_level more easily configurable in development
  config/environments/development.rb
Labels: pr-no-test

#7769 Stripe: payment status debugging
  app/models/spree/gateway/stripe_sca.rb
  app/services/process_payment_intent.rb
  app/services/stripe_payment_status.rb
  lib/stripe/payment_intent_validator.rb
  spec/controllers/spree/orders_controller_spec.rb
  spec/lib/stripe/payment_intent_validator_spec.rb
  spec/services/process_payment_intent_spec.rb
  spec/services/stripe_payment_status_spec.rb
Labels: dev-test

#8163 Remove problematic migration spec
  spec/migrations/migrate_enterprise_fee_tax_amounts_spec.rb
Labels: pr-no-test

#8207 Revert "Kill stripe connect"
  .rubocop_manual_todo.yml
  .rubocop_todo.yml
  app/assets/javascripts/admin/subscriptions/controllers/details_controller.js.coffee
  app/controllers/spree/admin/payment_methods_controller.rb
  app/models/spree/gateway/stripe_connect.rb
  app/models/subscription.rb
  app/serializers/api/admin/payment_method_serializer.rb
  app/views/spree/admin/payment_methods/_provider_settings.html.haml
  config/application.rb
  db/migrate/20210817100257_rename_stripe_connect_payment_methods_to_stripe_sca.rb
  db/schema.rb
  engines/order_management/app/services/order_management/subscriptions/stripe_payment_setup.rb
  engines/order_management/app/services/order_management/subscriptions/validator.rb
  engines/order_management/spec/services/order_management/subscriptions/stripe_payment_setup_spec.rb
  engines/order_management/spec/services/order_management/subscriptions/validator_spec.rb
  knapsack_rspec_report.json
  lib/open_food_network/available_payment_method_filter.rb
  lib/stripe/profile_storer.rb
  spec/controllers/admin/subscriptions_controller_spec.rb
  spec/controllers/spree/admin/orders/payments/payments_controller_refunds_spec.rb
  spec/controllers/spree/admin/orders/payments/payments_controller_spec.rb
  spec/controllers/spree/admin/payment_methods_controller_spec.rb
  spec/factories/payment_method_factory.rb
  spec/features/admin/subscriptions_spec.rb
  spec/features/consumer/shopping/checkout_stripe_spec.rb
  spec/helpers/enterprises_helper_spec.rb
  spec/jobs/subscription_confirm_job_spec.rb
  spec/lib/stripe/profile_storer_spec.rb
  spec/models/spree/gateway/stripe_connect_spec.rb
  spec/models/spree/gateway_tagging_spec.rb
  spec/models/spree/order_spec.rb
  spec/models/spree/payment_method_spec.rb
  spec/models/spree/payment_spec.rb
  spec/requests/checkout/stripe_connect_spec.rb
  spec/support/request/stripe_stubs.rb
Labels: pr-no-review, pr-no-test
