Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2021-06, with the labels that each got.

#7554 [Rails 6.0] Upgrade to rails 6.0
  Gemfile
  Gemfile.lock
  app/views/spree/admin/orders/bulk_management.html.haml
  config/application.rb
  config/initializers/devise.rb
  lib/spree/core.rb
  spec/controllers/admin/stripe_accounts_controller_spec.rb
  spec/controllers/admin/stripe_connect_settings_controller_spec.rb
  spec/controllers/checkout_controller_spec.rb
  spec/controllers/spree/admin/orders/payments/payments_controller_refunds_spec.rb
  spec/controllers/spree/credit_cards_controller_spec.rb
  spec/controllers/spree/orders_controller_spec.rb
  spec/features/admin/payment_method_spec.rb
  spec/features/consumer/account/cards_spec.rb
  spec/helpers/enterprises_helper_spec.rb
  spec/lib/stripe/account_connector_spec.rb
  spec/lib/stripe/credit_card_cloner_spec.rb
  spec/lib/stripe/payment_intent_validator_spec.rb
  spec/lib/stripe/profile_storer_spec.rb
  spec/models/spree/gateway/stripe_connect_spec.rb
  spec/models/spree/gateway/stripe_sca_spec.rb
  spec/models/stripe_account_spec.rb
  spec/requests/checkout/stripe_connect_spec.rb
  spec/requests/checkout/stripe_sca_spec.rb
  spec/support/request/stripe_helper.rb
  spec/support/request/stripe_stubs.rb
Labels: dev-test, feedback-needed

#7728 Remove papertrail initializer
  config/initializers/paper_trail.rb
Labels: pr-no-test

#7694 Split ConfirmOrderJob to avoid blocking DJ worker
  app/jobs/confirm_order_job.rb
  app/models/spree/order.rb
  spec/features/consumer/shopping/checkout_spec.rb
  spec/jobs/confirm_order_job_spec.rb
  spec/jobs/subscription_confirm_job_spec.rb
  spec/jobs/subscription_placement_job_spec.rb
  spec/models/spree/order_spec.rb
Labels: feedback-needed

#7766 Update schema file description
  db/schema.rb
Labels: pr-no-test

#7797 Upgrade to bundler 2
  Gemfile.lock
Labels: pr-staged-fr

#7808 Remove explicit dependency on sass gem
  Gemfile
  Gemfile.lock
Labels: dev-test

#7815 Move Rspec retries count to CI config and remove in local environment
  .github/workflows/build.yml
  spec/spec_helper.rb
Labels: pr-no-test

#7816 Add example script for importing customers
  script/import-customers.rb
Labels: pr-no-test
