Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2022-02, with the labels that each got.

#8640 Make split checkout buttons sticky on step 3
  app/views/split_checkout/_summary.html.haml
  app/views/split_checkout/edit.html.haml
  app/webpacker/controllers/sticky_controller.js
  app/webpacker/css/darkswarm/split-checkout.scss
Labels: pr-staged-fr, feedback-needed

#8829 Fix image uploads by patching aws-sdk
  config/initializers/aws_sdk.rb
  spec/models/spree/image_spec.rb
Labels: pr-staged-fr

#8813 Split checkout: fix loading of saved addresses
  app/controllers/concerns/checkout_callbacks.rb
  app/helpers/spree/base_helper.rb
  app/views/split_checkout/_details.html.haml
  app/webpacker/controllers/dependant_select_controller.js
  spec/system/consumer/split_checkout_spec.rb
Labels: pr-staged-fr

#8822 [Split Checkout] Move setting of payment total during checkout into OrderUpdater
  app/controllers/checkout_controller.rb
  app/models/spree/order.rb
  app/models/spree/order/checkout.rb
  engines/order_management/app/services/order_management/order/updater.rb
  spec/controllers/split_checkout_controller_spec.rb
  spec/controllers/spree/admin/return_authorizations_controller_spec.rb
  spec/models/spree/order_spec.rb
  spec/services/process_payment_intent_spec.rb
Labels: pr-staged-uk

#8857 Open modal on login/signup links for a "Visible to Registered Customers Only" shop page
  app/views/shop/messages/_customer_required.html.haml
Labels: pr-staged-uk

#8819 8694 improve subscriptions index perfomance by eager loading tags, suppliers and exchanges.
  app/controllers/admin/subscriptions_controller.rb
  app/serializers/api/admin/payment_method/base_serializer.rb
  app/serializers/api/admin/payment_method_serializer.rb
  app/views/admin/subscriptions/_data.html.haml
  package.json
Labels: pr-staged-fr

#8878 Use our defined rubocop version on CI
  .github/workflows/linters.yml
Labels: pr-no-test

#8874 Update puma to latest version
  Gemfile.lock
Labels: pr-staged-uk

#8873 Update checkout retry logic
  app/models/spree/payment.rb
  spec/models/spree/payment_spec.rb
Labels: feedback-needed

#8885 Modify assets builder to get CSS inside emails when running in development mode
  config/environments/development.rb
Labels: dev-test

#8871 SplitCheckout: preselect the shipping/payment method if the only one available
  app/views/split_checkout/_details.html.haml
  app/views/split_checkout/_payment.html.haml
  spec/system/consumer/split_checkout_spec.rb
Labels: pr-staged-fr

#8895 Sync subscriptions on newly-cloned order cycles
  app/models/order_cycle.rb
  spec/models/order_cycle_spec.rb
Labels: pr-staged-uk

#8565 Handle imperial units in the Bulk Order Management interface
  app/assets/javascripts/admin/line_items/controllers/line_items_controller.js.coffee
  app/views/spree/admin/orders/bulk_management.html.haml
  spec/javascripts/unit/admin/line_items/controllers/line_items_controller_spec.js.coffee
  spec/javascripts/unit/admin/services/variant_unit_manager_spec.js.coffee
Labels: pr-staged-uk

#8849 Create a new method pdf_stylesheet_pack_tag that actually include CSS in PDF files
  app/helpers/application_helper.rb
  app/views/spree/admin/orders/invoice.html.haml
  app/views/spree/admin/orders/invoice2.html.haml
Labels: dev-test

#8883 Backoffice order, using stripe payment: when card requires auth, send authorization email to guest user
  app/mailers/payment_mailer.rb
Labels: pr-staged-uk
