Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2022-05, with the labels that each got.

#9057 Split checkout: handle cards that throws any errors
  app/controllers/split_checkout_controller.rb
  app/webpacker/controllers/stripe_controller.js
  spec/system/consumer/split_checkout_spec.rb
Labels: pr-staged-uk

#9139 Split Checkout: Handle shipping/payment method description with no space
  app/views/split_checkout/_summary.html.haml
  app/views/spree/shared/_order_details.html.haml
  app/views/spree/shared/_shipment_delivery_details.html.haml
  app/webpacker/css/darkswarm/mixins.scss
  app/webpacker/css/darkswarm/split-checkout.scss
Labels: pr-staged-uk

#9138 Split checkout: Order shipping methods by name
  app/controllers/concerns/checkout_callbacks.rb
  spec/system/consumer/split_checkout_spec.rb
Labels: pr-staged-au

#9044 Optional restock items
  app/assets/javascripts/admin/spree/orders/variant_autocomplete.js.erb
  app/controllers/api/v0/shipments_controller.rb
  app/controllers/spree/admin/orders_controller.rb
  app/helpers/spree/admin/navigation_helper.rb
  app/helpers/spree/admin/orders_helper.rb
  app/models/spree/line_item.rb
  app/models/spree/order.rb
  app/models/spree/order_contents.rb
  app/models/spree/order_inventory.rb
  app/models/spree/shipment.rb
  config/locales/en.yml
  spec/controllers/api/v0/shipments_controller_spec.rb
  spec/models/spree/order_inventory_spec.rb
  spec/system/admin/order_spec.rb
Labels: feedback-needed

#9187 Add phone number and email address to alternative invoice
  app/views/spree/admin/orders/invoice2.html.haml
  spec/features/admin/invoice_print_spec.rb
Labels: pr-staged-uk

#9211 Revert "When creating an order, and assigning a customer, fill all the customer inputs in the shipping/billing address form"
  app/assets/javascripts/admin/orders/directives/customer_search_override.js.coffee
  app/views/spree/admin/orders/customer_details/_autocomplete.js.erb
  app/views/spree/admin/orders/customer_details/edit.html.haml
  app/webpacker/controllers/select_customer_controller.js
  app/webpacker/controllers/tom_select_controller.js
  spec/support/request/web_helper.rb
  spec/system/admin/order_spec.rb
Labels: pr-staged-uk
