Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2022-03, with the labels that each got.

#8869 Removes signup string from private shop login screen
  app/views/shop/messages/_customer_required.html.haml
  config/locales/en.yml
  spec/system/consumer/authentication_spec.rb
  spec/system/consumer/shopping/shopping_spec.rb
Labels: pr-staged-au

#8956 Fix Angular interpolation for translations with apostrophes
  app/views/shared/menu/_cart_sidebar.html.haml
Labels: pr-staged-uk

#8964 SplitCheckout: Display shipping options checkboxes on invalid form submit
  app/views/split_checkout/_details.html.haml
  spec/system/consumer/split_checkout_spec.rb
Labels: pr-staged-uk

#8926 Gracefully handle admin UI failure on updating enterprise notifications
  app/controllers/admin/enterprises_controller.rb
  spec/controllers/admin/enterprises_controller_spec.rb
Labels: pr-staged-uk

#8805 Replace inline JS for toggling order cycle advanced settings with StimulusJs controller
  app/views/admin/order_cycles/_order_cycle_top_buttons.html.haml
  app/webpacker/controllers/remote_toggle_controller.js
  spec/javascripts/stimulus/paymentmethod_controller_test.js
  spec/javascripts/stimulus/remote_toggle_controller_test.js
  spec/javascripts/stimulus/stripe_cards_controller_test.js
  spec/javascripts/stimulus/tabs_controller_test.js
  spec/javascripts/stimulus/toggle_controller_test.js
  spec/javascripts/stimulus/update_controller_test.js
Labels: pr-staged-uk

#9003 Remove old config comments
  config/environments/production.rb
  config/environments/staging.rb
Labels: pr-no-test

#9029 Added missing translation for model name.
  config/locales/en.yml
Labels: pr-staged-uk, prod-test

#9025 Fix untranslated flash message
  app/assets/javascripts/admin/resources/services/order_cycles.js.coffee
Labels: pr-staged-uk

#9013 Fix order cycle advanced settings close button so it uses new remote toggle StimulusJs controller instead of old toggleSettings method
  app/views/admin/order_cycles/_advanced_settings.html.haml
Labels: pr-staged-uk

#9004 SplitCheckout: filter shipping method with tag
  app/controllers/concerns/checkout_callbacks.rb
  spec/system/consumer/split_checkout_spec.rb
Labels: pr-staged-fr
