Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2022-01, with the labels that each got.

#8664 Rename admin css pack
  app/views/spree/admin/shared/_head.html.haml
  app/webpacker/packs/admin-styles.scss
Labels: pr-no-test

#8634 Clarify use of order tokens
  app/controllers/cart_controller.rb
  app/controllers/payment_gateways/paypal_controller.rb
  app/controllers/payments_controller.rb
  app/controllers/spree/admin/orders/customer_details_controller.rb
  app/controllers/spree/orders_controller.rb
  spec/controllers/spree/orders_controller_spec.rb
  spec/requests/checkout/paypal_spec.rb
  spec/system/consumer/shopping/orders_spec.rb
Labels: easy-test

#8660 Fix Foreman/Procfile environment loading issue
  .foreman
Labels: pr-no-test

#8675 Remove unused JS
  app/assets/javascripts/admin/all.js
  app/assets/javascripts/admin/spree_backend.js
  app/assets/javascripts/admin/spree_paypal_express.js
Labels: pr-no-test

#8615 Enable sorting orders by order full name
  app/jobs/bulk_invoice_job.rb
  app/services/search_orders.rb
  app/views/spree/admin/orders/index.html.haml
  app/views/spree/admin/shared/_sortable_header.html.haml
  config/locales/en.yml
  spec/controllers/api/v0/orders_controller_spec.rb
  spec/jobs/bulk_invoice_job_spec.rb
  spec/services/bulk_invoice_service_spec.rb
Labels: easy-test

#8541 Improve shipped email design
  app/views/spree/shipment_mailer/shipped_email.html.haml
  spec/mailers/previews/shipment_preview.rb
Labels: easy-test

#8467 Fix the issue with 'at' in enterprise twitter and instagram
  app/assets/javascripts/templates/partials/follow.html.haml
  app/models/enterprise.rb
  spec/models/enterprise_spec.rb
  spec/system/consumer/registration_spec.rb
Labels: easy-test

#8621 Update units when variant unit name is edited
  app/models/spree/product.rb
  spec/models/spree/product_spec.rb
Labels: pr-staged-fr

#8518 Fix Webpacker container configuration
  docker-compose.yml
Labels: dev-test

#8692 Validate the presence of first/last name if there is no company
  app/models/spree/address.rb
  spec/system/consumer/split_checkout_spec.rb
Labels: pr-staged-fr

#8681 Add flash message translation for log out
  config/locales/en.yml
  spec/controllers/spree/user_sessions_controller_spec.rb
Labels: easy-test

#8679 Drop jquery_ujs
  app/assets/javascripts/darkswarm/all.js.coffee
  app/assets/javascripts/darkswarm/controllers/credit_cards_controller.js.coffee
  app/controllers/spree/credit_cards_controller.rb
  app/views/spree/users/_saved_cards.html.haml
  app/webpacker/css/shared/variables/layout.scss
  spec/controllers/spree/credit_cards_controller_spec.rb
  spec/system/consumer/account/cards_spec.rb
Labels: pr-staged-uk

#8712 OC notifications
  app/jobs/order_cycle_notification_job.rb
  app/models/order_cycle.rb
  app/views/admin/order_cycles/edit.html.haml
  db/migrate/20220112102539_add_mails_sent_to_order_cycles.rb
  db/migrate/20220114110920_update_order_cycle_mails.rb
  db/schema.rb
  spec/jobs/order_cycle_notification_job_spec.rb
  spec/models/order_cycle_spec.rb
  spec/system/admin/order_cycles/simple_spec.rb
Labels: feedback-needed

#8754 Bump json gem back up to 2.6.1
  Gemfile.lock
Labels: pr-no-test

#8653 Split checkout T&Cs
  app/controllers/split_checkout_controller.rb
  app/helpers/terms_and_conditions_helper.rb
  app/services/terms_of_service.rb
  app/views/split_checkout/_summary.html.haml
  spec/controllers/split_checkout_controller_spec.rb
Labels: feedback-needed

#8731 Split checkout: default address saving
  app/models/spree/order.rb
  app/services/checkout/params.rb
  app/services/default_address_updater.rb
  app/views/split_checkout/_details.html.haml
  spec/controllers/split_checkout_controller_spec.rb
Labels: pr-staged-uk

#8739 Split checkout completion
  app/controllers/split_checkout_controller.rb
  spec/factories/order_factory.rb
  spec/system/consumer/split_checkout_spec.rb
Labels: pr-staged-uk

#8438 If an order has out of stock line items display them and let admins remove them
  app/views/spree/admin/orders/_form.html.haml
  app/views/spree/admin/orders/_insufficient_stock_lines.html.haml
  app/webpacker/css/admin/sections/orders.scss
  spec/system/admin/order_spec.rb
  spec/views/spree/admin/orders/edit.html.haml_spec.rb
Labels: pr-staged-uk

#8678 Remove outdated jsUri
  app/assets/javascripts/admin/spree/spree.js.coffee
  app/assets/javascripts/admin/spree/taxons/taxon_tree_menu.js.coffee
  app/assets/javascripts/admin/spree/taxons/taxonomy.js.coffee
  app/views/spree/admin/shared/_routes.html.erb
  app/views/spree/admin/taxonomies/edit.haml
  vendor/assets/javascripts/jsuri.js
Labels: pr-staged-uk, easy-test

#8789 Remove example system spec
  spec/system/first_system_spec.rb
Labels: pr-no-test

#8643 Split Checkout: Show "Save card for future use" checkbox only on "Enter new card details" option selected
  app/views/split_checkout/payment/_stripe_sca.html.haml
Labels: pr-staged-uk

#8717 SplitCheckout: adjust display of long shipping method or payment method label
  app/views/split_checkout/_details.html.haml
  app/views/split_checkout/_payment.html.haml
  app/webpacker/css/darkswarm/split-checkout.scss
Labels: pr-staged-uk

#8771 Missing translation: table headers in product import validation table #8458
  app/models/product_import/product_importer.rb
  config/locales/en.yml
  spec/system/admin/product_import_spec.rb
Labels: pr-staged-uk

#8738 Add locale to stripe elements options to display stripe error messages in globale interface chosen language
  app/assets/javascripts/darkswarm/directives/stripe_elements.js.coffee
  app/webpacker/controllers/stripe_controller.js
Labels: pr-staged-uk

#8722 Remove unused inline JavaScript from products/_form.html.haml
  app/views/spree/admin/products/_form.html.haml
Labels: easy-test

#8796 Remove embedded shopfronts code
  app/controllers/checkout_controller.rb
  app/controllers/enterprises_controller.rb
  app/controllers/home_controller.rb
  app/controllers/payment_gateways/paypal_controller.rb
  app/controllers/shop_controller.rb
  app/controllers/shops_controller.rb
  app/controllers/spree/orders_controller.rb
  app/controllers/spree/users_controller.rb
  spec/requests/embedded_shopfronts_headers_spec.rb
  spec/system/consumer/shopping/embedded_shopfronts_spec.rb
Labels: pr-no-test

#8803 Fix visual regression on filter buttons
  app/webpacker/css/admin/shared/forms.scss
Labels: pr-staged-uk

#8784 Convert variant.weight into decimal if integer or 0.0 if nil
  app/models/spree/variant.rb
  spec/models/spree/variant_spec.rb
Labels: pr-staged-au
