Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2022-06, with the labels that each got.

#9190 Destroy all adjustments on cart empty
  app/models/spree/order.rb
  spec/models/spree/order_spec.rb
Labels: pr-staged-uk

#9237 Fix shipped email tracking information font size
  app/views/spree/shipment_mailer/shipped_email.html.haml
  spec/mailers/previews/shipment_preview.rb
Labels: pr-staged-fr

#9270 Update `yarn.lock` file by running `yarn` command
  yarn.lock
Labels: pr-staged-fr

#9259 Reports, Order Cycle Customer Totals: Format date in summary row as it's formatted in a row
  lib/reporting/reports/orders_and_fulfillment/order_cycle_customer_totals.rb
  spec/lib/reports/orders_and_fulfillment/order_cycle_customer_totals_report_spec.rb
Labels: pr-staged-fr

#9122 Migration to remove addresses with empty phone number.
  db/migrate/20220425102039_remove_bill_addresses_with_null_phone.rb
  db/schema.rb
Labels: pr-staged-uk

#9286 Admin, print an invoice with alternative mode: fix an issue when enterprise has a logo
  app/views/spree/admin/orders/invoice2.html.haml
Labels: pr-staged-fr

#9288 Show order and admin page despite broken image
  app/views/spree/shared/_variant_thumbnail.html.haml
  spec/views/spree/orders/show.html.haml_spec.rb
Labels: prod-test

#9312 Splits results per supplier on OC Distributor Totals by Supplier report
  lib/reporting/reports/orders_and_fulfillment/order_cycle_supplier_totals.rb
Labels: pr-staged-fr

#9191 Admin, Reports: Inverting logic from "Columns to hide" to "Columns to show"
  app/controllers/admin/reports_controller.rb
  app/views/admin/reports/_rendering_options.html.haml
  app/views/admin/reports/_report_subtype.html.haml
  app/views/admin/reports/index.html.haml
  config/locales/en.yml
  lib/reporting/report_headers_builder.rb
  lib/reporting/report_row_builder.rb
  lib/reporting/report_rows_builder.rb
  lib/reporting/report_template.rb
  spec/controllers/admin/reports_controller_spec.rb
  spec/lib/reports/report_spec.rb
  spec/system/admin/reports_spec.rb
Labels: pr-staged-uk

#9272 On user confirmation, retrieve and link all orders to the new user that were already placed with the same email
  app/models/spree/user.rb
  spec/models/spree/user_spec.rb
Labels: pr-staged-uk

#9363 Admin, Orders list: new actions dropdown for bulk invoice printing
  app/assets/javascripts/admin/dropdown/directives/dropdown.js.coffee
  app/views/spree/admin/orders/_per_page_controls.html.haml
  app/views/spree/admin/orders/index.html.haml
  app/webpacker/css/admin/components/per_page_controls.scss
  app/webpacker/css/admin/dropdown.scss
  config/locales/en.yml
  spec/system/admin/orders_spec.rb
Labels: pr-staged-uk

#9348 Add boolean to specify if enterprise number (ABN, GST, SIRET, ...) is mandatory or not to generate invoices
  app/controllers/admin/invoice_settings_controller.rb
  app/helpers/spree/admin/orders_helper.rb
  app/models/enterprise.rb
  app/models/spree/app_configuration.rb
  app/views/admin/invoice_settings/edit.html.haml
  config/locales/en.yml
  spec/system/admin/order_spec.rb
Labels: feedback-needed
