Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2022-04, with the labels that each got.

#9071 Improve permissions query building
  lib/open_food_network/permissions.rb
  spec/lib/open_food_network/permissions_spec.rb
Labels: performance

#9088 Update setup script for removed callbacks
  lib/tasks/sample_data/order_factory.rb
  spec/lib/tasks/sample_data_rake_spec.rb
Labels: dev-test

#9098 Feature-toggle API also per API key
  app/controllers/api/v1/base_controller.rb
  config/routes/api.rb
Labels: pr-staged-uk

#8841 Display remaining stock in shopfront if enabled in shop preferences
  app/assets/javascripts/darkswarm/controllers/shop_variant_controller.js.coffee
  app/models/enterprise.rb
  app/serializers/api/admin/enterprise_serializer.rb
  app/serializers/api/enterprise_shopfront_serializer.rb
  app/services/permitted_attributes/enterprise.rb
  app/views/admin/enterprises/form/_shop_preferences.html.haml
  app/views/shop/products/_shop_variant_no_group_buy.html.haml
  app/webpacker/css/darkswarm/_shop-inputs.scss
  config/locales/en.yml
  spec/javascripts/unit/darkswarm/controllers/checkout/shop_variant_controller_spec.js.coffee
  spec/system/consumer/shopping/shopping_spec.rb
Labels: pr-staged-uk

#8991 Admin, editing order, on last item deletion modal: "Send a cancellation email to the customer" checked by default
  app/assets/javascripts/admin/spree/orders/variant_autocomplete.js.erb
  spec/system/admin/order_spec.rb
Labels: pr-staged-au

#8979 shipping fees on admin: avoid backend error when updating calculator type
  app/assets/javascripts/admin/enterprise_fees/directives/ensure_calculator_preferences_match_type.js.coffee
  app/assets/javascripts/admin/spree/calculator.js
  config/locales/en.yml
  spec/system/admin/enterprise_fees_spec.rb
  spec/system/admin/shipping_methods_spec.rb
Labels: pr-staged-uk

#9087 Change enterprise visibility scope
  app/models/enterprise.rb
  app/serializers/api/admin/enterprise_serializer.rb
  app/views/admin/enterprises/form/_primary_details.html.haml
  app/views/spree/admin/overview/single_enterprise_dashboard.html.haml
  config/locales/en.yml
  db/migrate/20220410162955_change_visible_data_type_for_enterprises.rb
  db/schema.rb
  lib/open_food_network/enterprise_issue_validator.rb
  spec/factories/enterprise_factory.rb
  spec/lib/open_food_network/enterprise_issue_validator_spec.rb
  spec/serializers/api/enterprise_shopfront_serializer_spec.rb
  spec/system/admin/enterprises_spec.rb
  spec/system/admin/overview_spec.rb
  spec/system/consumer/groups_spec.rb
Labels: pr-staged-uk

#9084 Fix an issue which prevented filtering by properties and sorting by category on a shopfront.
  app/models/spree/product.rb
  spec/controllers/api/v0/order_cycles_controller_spec.rb
  spec/services/products_renderer_spec.rb
  spec/system/consumer/shopping/products_spec.rb
Labels: pr-staged-uk

#9119 Store files with Active Storage in addition to Paperclip
  .gitignore
  Gemfile
  Gemfile.lock
  app/models/concerns/has_migrating_file.rb
  app/models/enterprise.rb
  app/models/enterprise_group.rb
  app/models/spree/image.rb
  app/models/spree/preferences/file_configuration.rb
  app/models/terms_of_service_file.rb
  config/application.rb
  config/environments/test.rb
  config/locales/en.yml
  config/storage.yml
  db/migrate/20220316055458_create_active_storage_tables.active_storage.rb
  db/schema.rb
  lib/tasks/from_paperclip_to_active_storage.rake
  spec/lib/tasks/from_paperclip_to_active_storage_rake_spec.rb
  spec/models/spree/image_spec.rb
Labels: feedback-needed
