Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2022-10, with the labels that each got.

#9711 Translation cleanup
  app/helpers/admin/enterprise_groups_helper.rb
  app/views/admin/enterprise_groups/_form_about.html.haml
  app/views/admin/enterprise_groups/_form_address.html.haml
  app/views/admin/enterprise_groups/_form_images.html.haml
  app/views/admin/enterprise_groups/_form_primary_details.html.haml
  app/views/admin/enterprise_groups/_form_users.html.haml
  app/views/admin/enterprise_groups/_form_web.html.haml
  app/views/admin/enterprises/_form.html.haml
  app/views/admin/enterprises/_new_form.html.haml
  app/views/admin/enterprises/form/_business_details.html.haml
  app/views/admin/enterprises/new.html.haml
  app/views/admin/shared/_side_menu.html.haml
  config/locales/en.yml
Labels: prod-test

#9749 Fix layout of 'Create a new product' button in dashboard overview
  app/views/spree/admin/overview/_products.html.haml
Labels: pr-staged-uk

#9816 Add pointer cursor when hovering a clickable product description
  app/webpacker/css/darkswarm/_shop-product-rows.scss
Labels: pr-staged-uk

#9828 Prevent users from changing API keys for others
  app/controllers/spree/api_keys_controller.rb
  spec/controllers/spree/api_keys_controller_spec.rb
Labels: feedback-needed

#9058 Add OIDC authentication for Les Communs
  .env.test
  Gemfile
  Gemfile.lock
  app/controllers/admin/oidc_settings_controller.rb
  app/controllers/omniauth_callbacks_controller.rb
  app/models/spree/ability.rb
  app/models/spree/user.rb
  app/views/admin/oidc_settings/index.html.haml
  app/views/admin/shared/_enterprises_sub_menu.html.haml
  app/views/devise/shared/_links.html.erb
  app/views/spree/admin/shared/_tabs.html.haml
  config/initializers/devise.rb
  config/locales/en.yml
  config/routes/admin.rb
  config/routes/spree.rb
  db/migrate/20210713165335_add_omniauth_to_users.rb
  db/schema.rb
  spec/models/spree/user_spec.rb
  spec/requests/omniauth_callbacks_controller_spec.rb
Labels: priority

#9791 Fix snail issue for all enterprise fees
  app/controllers/admin/enterprise_fees_controller.rb
  spec/system/admin/enterprise_fees_spec.rb
Labels: pr-staged-uk

#9737 Translate error messages when creating products
  config/locales/en.yml
Labels: pr-staged-au

#9808 Add sort by product name in order cycle supplier totals by distributor report
  lib/reporting/reports/orders_and_fulfillment/order_cycle_supplier_totals_by_distributor.rb
  spec/lib/reports/orders_and_fulfillment/order_cycle_supplier_totals_by_distributor_report_spec.rb
Labels: pr-staged-uk

#9823 Fix product duplication
  lib/spree/core/product_duplicator.rb
  spec/lib/spree/core/product_duplicator_spec.rb
Labels: pr-staged-uk

#9862 Format reports as list, even if only one sub-type available
  app/views/admin/reports/index.html.haml
Labels: pr-staged-fr

#9900 [9845] Make checkout terms and conditions label clickable
  app/views/checkout/_platform_terms_of_service.html.haml
Labels: pr-staged-uk
