Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2022-08, with the labels that each got.

#9196 Admin, Order creation: Change steps ordering
  app/controllers/spree/admin/orders_controller.rb
  app/views/spree/admin/orders/set_distribution.html.haml
  app/views/spree/admin/shared/_order_tabs.html.haml
  spec/controllers/spree/admin/orders_controller_spec.rb
  spec/system/admin/order_spec.rb
  spec/system/admin/variant_overrides_spec.rb
Labels: feedback-needed

#9525 Adds debug gem to the stack
  Gemfile
  Gemfile.lock
Labels: tech debt

#9533 Removes byebug and pry-byebug; keeps pry :broom:
  Gemfile
  Gemfile.lock
Labels: pr-no-test

#9437 User account, Credit cards: Do not allow to check "Allow charges" if no credit cards marked as default
  app/assets/javascripts/darkswarm/controllers/credit_cards_controller.js.coffee
  app/controllers/spree/credit_cards_controller.rb
  app/views/spree/users/_authorised_shops.html.haml
  config/locales/en.yml
  spec/controllers/spree/credit_cards_controller_spec.rb
  spec/system/consumer/account/cards_spec.rb
Labels: pr-staged-fr

#9165 [Split Checkout] Adds spec to test Tax charges (repoducing issue #9153)
  .rubocop_styleguide.yml
  app/controllers/split_checkout_controller.rb
  spec/controllers/split_checkout_controller_spec.rb
  spec/factories/zone_factory.rb
  spec/system/consumer/split_checkout_tax_incl_spec.rb
  spec/system/consumer/split_checkout_tax_not_incl_spec.rb
Labels: pr-staged-uk, priority

#9563 Disable header row bulk_coop report
  app/views/admin/reports/_rendering_options.html.haml
  app/webpacker/controllers/csv_select_controller.js
Labels: pr-staged-uk

#9407 Handle for invalid referer for embedded page service
  app/services/embedded_page_service.rb
  spec/services/embedded_page_service_spec.rb
Labels: pr-staged-uk

#9529 Make the shop url clickable
  app/views/admin/enterprises/form/_primary_details.html.haml
  spec/system/admin/enterprises_spec.rb
Labels: pr-staged-uk

#9532 Translate 404, 500, 422 errors pages
  app/controllers/errors_controller.rb
  app/views/errors/internal_server_error.html.haml
  app/views/errors/not_found.html.haml
  app/views/errors/unprocessable_entity.html.haml
  app/views/layouts/errors.html.haml
  config/application.rb
  config/locales/en.yml
  config/routes.rb
  public/404.html
  public/422.html
Labels: pr-staged-uk

#9414 Let users view and regenerates api key
  app/controllers/spree/admin/users_controller.rb
  app/controllers/spree/api_keys_controller.rb
  app/models/spree/user.rb
  app/views/spree/admin/users/_api_fields.html.haml
  app/views/spree/users/_api_keys.html.haml
  app/views/spree/users/_developer_settings.html.haml
  app/views/spree/users/show.html.haml
  config/locales/en.yml
  config/routes/spree.rb
  db/migrate/20220713195433_add_show_api_key_generation_view_to_spree_user.rb
  db/schema.rb
  lib/open_food_network/spree_api_key_loader.rb
  lib/spree/core/controller_helpers/auth.rb
  spec/controllers/spree/admin/users_controller_spec.rb
  spec/controllers/spree/api_keys_controller_spec.rb
  spec/requests/api/orders_spec.rb
  spec/system/admin/users_spec.rb
  spec/system/consumer/account/developer_settings_spec.rb
Labels: pr-staged-uk
