Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2023-03, with the labels that each got.

#10467 limit users who can update shipping/payment method of an order cycle
  app/services/order_cycle_form.rb
  spec/services/order_cycle_form_spec.rb
Labels: pr-staged-uk

#10497 SplitCheckout: Make label clickable to check/uncheck checkbox on step 2
  app/views/split_checkout/payment/_stripe_sca.html.haml
Labels: pr-staged-fr

#10513 SplitCheckout: Display special_instructions of the order as emphasized text if present on summary page
  app/views/split_checkout/_summary.html.haml
  spec/system/consumer/split_checkout_spec.rb
Labels: pr-staged-fr

#10447 Admin, BOM: can bulk delete line items of an order
  app/assets/javascripts/admin/line_items/controllers/line_items_controller.js.coffee
  app/assets/javascripts/admin/spree/orders/variant_autocomplete.js.erb
  config/locales/en.yml
  spec/system/admin/bulk_order_management_spec.rb
Labels: pr-staged-fr

#10496 [split checkout] Fix bug preventing user from reaching payment step
  app/controllers/split_checkout_controller.rb
  spec/system/consumer/split_checkout_spec.rb
Labels: pr-staged-fr

#10514 Do not update `estimate_price` of a variant that is not available for the shop on OrderCycle update
  app/controllers/admin/order_cycles_controller.rb
  spec/controllers/admin/order_cycles_controller_spec.rb
Labels: pr-staged-uk

#10232 [Enterprise->Create] Show correct error message when user inputs url in instagram field
  app/assets/javascripts/darkswarm/services/enterprise_registration_service.js.coffee
  app/models/enterprise.rb
  app/views/registration/steps/_about.html.haml
  app/views/registration/steps/_social.html.haml
  spec/models/enterprise_spec.rb
  spec/system/consumer/registration_spec.rb
Labels: pr-staged-au

#10458 Node install script
  script/nodenv-install.sh
Labels: dev-test

#10516 Fix Sorting entries in a taxonomy is broken
  app/assets/javascripts/admin/spree/taxons/taxonomy.js.coffee
  spec/controllers/spree/admin/taxons_controller_spec.rb
Labels: pr-staged-uk

#10437 Translate cookie policy into languages selected by the user
  engines/web/app/views/web/angular_templates/_cookies_policy_entry.html.haml
  engines/web/app/views/web/angular_templates/cookies_policy.html.haml
  spec/system/consumer/footer_links_spec.rb
Labels: pr-staged-fr

#9729 Admin, Enterprise Settings, Users tabs: remove tooltips directives + use reflex to invite user to be managers
  .rubocop_todo.yml
  app/assets/javascripts/admin/enterprises/controllers/enterprise_controller.js.coffee
  app/assets/javascripts/admin/utils/utils.js.coffee
  app/controllers/admin/manager_invitations_controller.rb
  app/controllers/concerns/manager_invitations.rb
  app/reflexes/application_reflex.rb
  app/reflexes/invite_manager_reflex.rb
  app/views/admin/enterprises/form/_add_new_unregistered_manager.html.haml
  app/views/admin/enterprises/form/_users.html.haml
  config/routes/admin.rb
  spec/controllers/admin/manager_invitations_controller_spec.rb
  spec/services/order_cycle_form_spec.rb
  spec/system/admin/enterprises_spec.rb
Labels: pr-staged-uk

#10241 Admin, edit variant: only allow numerical values for weight, height, width and depth fields
  app/views/spree/admin/variants/_form.html.haml
Labels: feedback-needed

#10547 Enable invoices config only controls Print bulk action
  app/views/spree/admin/orders/index.html.haml
  spec/views/spree/admin/orders/index.html.haml_spec.rb
Labels: pr-staged-au

#10616 Update DB schema to Rails 7.0
  db/schema.rb
Labels: dev-test

#10519 Removing 'none' from shipping categories from product edit page
  app/views/spree/admin/products/_form.html.haml
Labels: pr-staged-au

#10607 Sort zones by name again, in the admin panel
  app/controllers/spree/admin/zones_controller.rb
  spec/system/admin/configuration/zones_spec.rb
Labels: pr-staged-uk
