Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2023-11, with the labels that each got.

#11702 [BUU] Mark changed fields, when error
  app/assets/javascripts/admin/bulk_product_update.js.coffee
  app/helpers/bulk_form_builder.rb
  app/models/spree/price.rb
  app/models/spree/variant.rb
  app/services/sets/model_set.rb
  app/services/sets/product_set.rb
  app/views/admin/products_v3/_table.html.haml
  app/webpacker/controllers/bulk_form_controller.js
  app/webpacker/css/admin/products_v3.scss
  app/webpacker/css/admin_v3/globals/variables.scss
  app/webpacker/css/admin_v3/shared/forms.scss
  config/locales/en.yml
  spec/helpers/bulk_form_builder_spec.rb
  spec/javascripts/stimulus/bulk_form_controller_test.js
  spec/javascripts/unit/admin/bulk_product_update_spec.js.coffee
  spec/services/sets/product_set_spec.rb
  spec/system/admin/products_v3/products_spec.rb
Labels: pr-no-test, technical changes only

#11736 Print robots tag for registration layout
  app/views/layouts/registration.html.haml
Labels: technical changes only

#11755 Remove orphaned JSON data in admin pages
  app/helpers/admin/injection_helper.rb
  app/views/admin/enterprises/_form_data.html.haml
Labels: technical changes only

#11749 Clarify cuprite driver configuration
  spec/system/support/cuprite_setup.rb
Labels: technical changes only

#11701 Remove bogus gateways
  app/controllers/spree/admin/payment_methods_controller.rb
  app/models/spree/gateway/bogus.rb
  app/models/spree/gateway/bogus_simple.rb
  config/application.rb
  config/locales/ar.yml
  config/locales/ca.yml
  config/locales/cy.yml
  config/locales/de_CH.yml
  config/locales/de_DE.yml
  config/locales/el.yml
  config/locales/en.yml
  config/locales/en_CA.yml
  config/locales/en_FR.yml
  config/locales/en_GB.yml
  config/locales/en_IE.yml
  config/locales/en_NZ.yml
  config/locales/en_US.yml
  config/locales/es.yml
  config/locales/es_US.yml
  config/locales/fr.yml
  config/locales/fr_CA.yml
  config/locales/fr_CH.yml
  config/locales/fr_CM.yml
  config/locales/hu.yml
  config/locales/it.yml
  config/locales/it_CH.yml
  config/locales/ko.yml
  config/locales/nb.yml
  config/locales/pt_BR.yml
  config/locales/ru.yml
  config/locales/tr.yml
  config/locales/uk.yml
  lib/tasks/sample_data/payment_method_factory.rb
  spec/base_spec_helper.rb
  spec/controllers/admin/subscriptions_controller_spec.rb
  spec/controllers/spree/admin/payment_methods_controller_spec.rb
  spec/factories/payment_method_factory.rb
  spec/models/spree/gateway/stripe_sca_spec.rb
  spec/models/spree/order/payment_spec.rb
  spec/models/spree/payment_method_spec.rb
  spec/models/spree/payment_spec.rb
  spec/requests/checkout/failed_checkout_spec.rb
  spec/requests/checkout/routes_spec.rb
  spec/services/order_syncer_spec.rb
  spec/support/spree/payment_helper.rb
  spec/system/consumer/shopping/checkout_spec.rb
Labels: technical changes only

#11757 [BUU] Grey out disabled button
  app/webpacker/css/admin_v3/components/buttons.scss
  app/webpacker/css/admin_v3/globals/variables.scss
Labels: pr-no-test, technical changes only

#11756 [DFC API] add image to product
  engines/dfc_provider/app/services/supplied_product_builder.rb
  engines/dfc_provider/lib/dfc_provider/supplied_product.rb
  engines/dfc_provider/spec/requests/enterprises_spec.rb
  engines/dfc_provider/spec/requests/supplied_products_spec.rb
  engines/dfc_provider/spec/services/supplied_product_builder_spec.rb
  swagger/dfc.yaml
Labels: technical changes only

#11779 Stripe version in sync with vcr tests
  script/test-stripe-live
  spec/base_spec_helper.rb
  spec/controllers/spree/credit_cards_controller_spec.rb
  spec/fixtures/vcr_cassettes/Stripe-v10.1.0/Spree_CreditCardsController/using_VCR/_new_from_token/when_the_request_to_store_the_customer/card_with_Stripe_is_successful/saves_the_card_locally.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.1.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_contains_an_error/raises_Stripe_error_with_payment_intent_last_payment_error_as_message.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.1.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/returns_payment_intent_id_and_does_not_raise.yml
  spec/lib/stripe/payment_intent_validator_spec.rb
Labels: technical changes only

#11790 Check for .present? for ENV GOOGLE variables
  app/views/shared/_google_maps_js.html.haml
Labels: technical changes only

#11733 Fix bugsnag warning
  config/initializers/bugsnag.rb
Labels: technical changes only

#11802 Stabilise spec with sleep
  spec/system/admin/configuration/taxonomies_spec.rb
Labels: technical changes only

#11816 Add logo and contact info to DFC Enterprise API
  engines/dfc_provider/app/controllers/dfc_provider/application_controller.rb
  engines/dfc_provider/app/controllers/dfc_provider/enterprises_controller.rb
  engines/dfc_provider/app/controllers/dfc_provider/social_medias_controller.rb
  engines/dfc_provider/app/services/enterprise_builder.rb
  engines/dfc_provider/app/services/social_media_builder.rb
  engines/dfc_provider/config/routes.rb
  engines/dfc_provider/spec/requests/enterprises_spec.rb
  engines/dfc_provider/spec/requests/social_medias_spec.rb
  swagger/dfc.yaml
Labels: api changes

#11780 Fixes pending tests cases on invoices spec
  spec/services/order_invoice_comparator_spec.rb
Labels: technical changes only

#11661 Store report files on the local disk
  app/controllers/admin/reports_controller.rb
  app/jobs/application_job.rb
  app/jobs/report_job.rb
  app/models/report_blob.rb
  config/environments/test.rb
  config/storage.yml
  spec/jobs/report_job_spec.rb
  spec/mailers/report_mailer_spec.rb
  spec/models/report_blob_spec.rb
  spec/system/admin/reports_spec.rb
Labels: pr-staged-fr, technical changes only

#11776 Fix hidden input showing on Producer registration
  app/views/registration/steps/_type.html.haml
Labels: pr-staged-uk

#11659 Fixes un-localized Order date and time format on edit order page
  app/helpers/spree/base_helper.rb
  config/locales/de_CH.yml
  config/locales/de_DE.yml
  config/locales/en.yml
  config/locales/es_CO.yml
  config/locales/es_CR.yml
  config/locales/es_US.yml
  config/locales/fil_PH.yml
  config/locales/fr_BE.yml
  config/locales/fr_CA.yml
  config/locales/fr_CH.yml
  config/locales/fr_CM.yml
  config/locales/it_CH.yml
  config/locales/nl_BE.yml
  config/locales/pt_BR.yml
  spec/helpers/spree/base_helper_spec.rb
Labels: pr-staged-au

#11741 Fix product with ml unit display dl
  app/assets/javascripts/admin/products/services/variant_unit_manager.js.coffee
  app/helpers/spree/admin/general_settings_helper.rb
  app/services/weights_and_measures.rb
  spec/controllers/api/v0/order_cycles_controller_spec.rb
  spec/helpers/spree/admin/general_settings_helper_spec.rb
  spec/javascripts/unit/admin/services/variant_unit_manager_spec.js.coffee
  spec/models/spree/line_item_spec.rb
  spec/services/unit_prices_spec.rb
  spec/services/variant_units/option_value_namer_spec.rb
  spec/services/weights_and_measures_spec.rb
Labels: feedback-needed

#11819 Update browserslist caniuse db
  yarn.lock
Labels: dependencies

#11731 Fix Cloning Tags Issue for OrderCycle
  app/models/exchange.rb
  spec/models/exchange_spec.rb
Labels: pr-staged-uk

#11730 Fix Stripe payment flash rendering issue
  app/assets/javascripts/admin/payments/services/payment.js.coffee
  app/controllers/spree/admin/payments_controller.rb
  config/locales/ar.yml
  config/locales/ca.yml
  config/locales/cy.yml
  config/locales/de_CH.yml
  config/locales/de_DE.yml
  config/locales/el.yml
  config/locales/en.yml
  config/locales/en_CA.yml
  config/locales/en_FR.yml
  config/locales/en_GB.yml
  config/locales/en_IE.yml
  config/locales/en_US.yml
  config/locales/es.yml
  config/locales/es_CR.yml
  config/locales/es_US.yml
  config/locales/fr.yml
  config/locales/fr_BE.yml
  config/locales/fr_CA.yml
  config/locales/fr_CH.yml
  config/locales/fr_CM.yml
  config/locales/hu.yml
  config/locales/it.yml
  config/locales/it_CH.yml
  config/locales/ko.yml
  config/locales/nb.yml
  config/locales/pt_BR.yml
  config/locales/ru.yml
  config/locales/tr.yml
  config/locales/uk.yml
  spec/controllers/spree/admin/orders/payments/payments_controller_spec.rb
  spec/system/admin/payments_spec.rb
Labels: pr-staged-uk

#11732 Maintain date range values in the report forms
  app/views/admin/reports/_date_range_form.html.haml
  app/views/admin/reports/filters/_packing.html.haml
  spec/system/admin/reports/packing_report_spec.rb
Labels: pr-staged-au

#11831 Fully Enable Vouchers Feature Toggle by Default
  db/migrate/20231118125941_activate_voucher_by_default.rb
Labels: pr-staged-uk

#11821 Feature toggled specs
  spec/base_spec_helper.rb
  spec/jobs/bulk_invoice_job_spec.rb
  spec/lib/reports/sales_tax_totals_by_order_spec.rb
  spec/mailers/order_mailer_spec.rb
  spec/reflexes/products_reflex_spec.rb
  spec/requests/admin/vouchers_spec.rb
  spec/requests/api/v1/customers_spec.rb
  spec/services/order_available_shipping_methods_spec.rb
  spec/system/admin/invoice_print_spec.rb
  spec/system/admin/order_spec.rb
  spec/system/admin/orders/invoices_spec.rb
  spec/system/admin/products_v3/products_spec.rb
  spec/system/admin/reports_spec.rb
  spec/system/consumer/checkout/payment_spec.rb
  spec/system/consumer/checkout/tax_incl_spec.rb
  spec/system/consumer/checkout/tax_not_incl_spec.rb
Labels: technical changes only

#11785 Implement product clone
  app/controllers/spree/admin/products_controller.rb
  app/views/admin/products_v3/components/_product_actions.html.haml
  config/locales/en.yml
  spec/system/admin/products_v3/products_spec.rb
Labels: pr-staged-fr, technical changes only

#11844 [System specs, CI] Fixes blacklist/whitelist deprecation warning
  spec/system/support/cuprite_setup.rb
Labels: technical changes only

#11818 Bump DFC taxonomies to v1.0.2
  engines/dfc_provider/app/services/quantitative_value_builder.rb
  engines/dfc_provider/lib/data_food_consortium/connector/connector.rb
  engines/dfc_provider/script/update-dfc-vocabularies
  engines/dfc_provider/spec/lib/data_food_consortium/connector/importer_spec.rb
  engines/dfc_provider/spec/services/quantitative_value_builder_spec.rb
  engines/dfc_provider/vendor/facets.json
  engines/dfc_provider/vendor/measures.json
  engines/dfc_provider/vendor/productTypes.json
  swagger/dfc.yaml
Labels: api changes

#11847 Avoid precompiling assets unnecessarily
  spec/spec_helper.rb
  spec/support/precompile_assets.rb
  spec/system/support/precompile_assets.rb
Labels: technical changes only

#11836 Extends bulk print invoice spec to assert on file contents
  spec/system/admin/orders_spec.rb
Labels: technical changes only

#11853 Spec refactor
  spec/system/admin/orders_spec.rb
Labels: technical changes only

#11848 Vertical ellipsis menu component
  .rubocop_styleguide.yml
  app/components/vertical_ellipsis_menu_component.rb
  app/components/vertical_ellipsis_menu_component/vertical_ellipsis_menu_component.html.haml
  app/components/vertical_ellipsis_menu_component/vertical_ellipsis_menu_component.scss
  app/views/admin/products_v3/_table.html.haml
  app/views/admin/products_v3/components/_product_actions.html.haml
  app/webpacker/css/admin_v3/all.scss
  config/application.rb
  spec/components/vertical_ellipsis_menu_component_spec.rb
Labels: pr-no-test, technical changes only

#11857 Remove unnecessary host config in specs
  spec/base_spec_helper.rb
Labels: technical changes only

#11792 Adds a pending spec for legal invoices feature issue #11791
  spec/system/admin/orders_spec.rb
Labels: technical changes only
