Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2023-09, with the labels that each got.

#11454 Fix Rubocop Style Errors
  .rubocop_todo.yml
  app/controllers/admin/enterprises_controller.rb
  app/controllers/admin/order_cycles_controller.rb
  app/controllers/admin/product_import_controller.rb
  app/controllers/api/v0/shipments_controller.rb
  app/controllers/application_controller.rb
  app/controllers/home_controller.rb
  app/controllers/spree/orders_controller.rb
  app/models/enterprise.rb
  app/models/enterprise_group.rb
  app/models/producer_property.rb
  app/models/product_import/entry_processor.rb
  app/models/spree/order.rb
  app/models/spree/preferences/preferable_class_methods.rb
  app/services/order_syncer.rb
  engines/order_management/app/services/order_management/order/updater.rb
  lib/discourse/single_sign_on.rb
  lib/open_food_network/order_cycle_form_applicator.rb
  lib/reporting/reports/users_and_enterprises/base.rb
  lib/spree/core/controller_helpers/respond_with.rb
  lib/tasks/karma.rake
  spec/controllers/api/v0/shipments_controller_spec.rb
  spec/services/upload_sanitizer_spec.rb
  spec/support/request/distribution_helper.rb
  spec/support/request/shop_workflow.rb
  spec/system/support/precompile_assets.rb
Labels: technical changes only

#11477 Stabilise flaky enterprise fee spec
  spec/system/admin/enterprise_fees_spec.rb
Labels: technical changes only

#11468 [BUU] Editing - part 2 (product and variant text fields) 🚧
  app/models/spree/price.rb
  app/views/admin/products_v3/_table.html.haml
  spec/models/spree/price_spec.rb
  spec/reflexes/products_reflex_spec.rb
  spec/system/admin/products_v3/products_spec.rb
Labels: pr-no-test, technical changes only

#11471 [DFC API] Replace service class with simple AR association
  app/models/enterprise.rb
  engines/dfc_provider/app/controllers/dfc_provider/catalog_items_controller.rb
  engines/dfc_provider/app/controllers/dfc_provider/supplied_products_controller.rb
  engines/dfc_provider/app/services/enterprise_builder.rb
  engines/dfc_provider/app/services/variant_fetcher.rb
  engines/dfc_provider/spec/services/variant_fetcher_spec.rb
  spec/models/enterprise_spec.rb
Labels: pr-no-test, technical changes only

#11140 Admin, add trix editor to product description editor (both new and edit)
  app/serializers/api/product_serializer.rb
  app/services/trix_sanitizer.rb
  app/services/trix_scrubber.rb
  app/views/spree/admin/products/_form.html.haml
  app/views/spree/admin/products/new.html.haml
  app/webpacker/controllers/trixeditor_controller.js
  app/webpacker/css/admin/all.scss
  app/webpacker/css/admin/trix.scss
  app/webpacker/css/admin_v3/all.scss
  app/webpacker/css/darkswarm/_shop-modals.scss
  app/webpacker/css/darkswarm/_shop-product-rows.scss
  app/webpacker/css/darkswarm/all.scss
  app/webpacker/css/darkswarm/shop_tabs.scss
  app/webpacker/css/shared/trix.scss
  spec/system/admin/products_spec.rb
Labels: pr-staged-au

#11450 Activate vouchers feature per user or enterprise
  app/helpers/application_helper.rb
  app/views/admin/enterprises/_form.html.haml
  app/views/admin/shared/_side_menu.html.haml
  app/views/split_checkout/_payment.html.haml
  config/routes/admin.rb
  lib/open_food_network/feature_toggle.rb
  spec/helpers/application_helper_spec.rb
  spec/lib/open_food_network/feature_toggle_spec.rb
  spec/system/admin/vouchers_spec.rb
Labels: pr-staged-fr, feature toggled

#11489 Require associations on join model
  app/models/order_cycle_schedule.rb
Labels: no-staging-UK, technical changes only

#11490 Skip online validation of sample emails
  lib/tasks/sample_data.rake
Labels: technical changes only

#11309 [Invoices] Adds unit level test coverage order model attributes
  spec/services/order_invoice_comparator_spec.rb
Labels: technical changes only

#11396 fix If ToS file is not set, customer needs to accept Terms on each checkout
  app/models/spree/app_configuration.rb
  app/models/terms_of_service_file.rb
  app/services/terms_of_service.rb
  app/views/admin/terms_of_service_files/show.html.haml
  app/views/layouts/mailer.html.haml
  app/views/shared/_footer.html.haml
  config/locales/en.yml
  spec/helpers/terms_and_conditions_helper_spec.rb
  spec/models/terms_of_service_file_spec.rb
  spec/services/terms_of_service_spec.rb
  spec/system/admin/configuration/terms_of_service_files_spec.rb
  spec/system/consumer/split_checkout_spec.rb
Labels: pr-staged-au

#11349 chore(deps): bump foundation-sites from 5.5.2 to 5.5.3
  package.json
  yarn.lock
Labels: pr-staged-uk, dependencies

#11377 [DFC API] Import known units when creating new products
  app/services/weights_and_measures.rb
  engines/dfc_provider/app/controllers/dfc_provider/supplied_products_controller.rb
  engines/dfc_provider/app/services/quantitative_value_builder.rb
  engines/dfc_provider/app/services/supplied_product_builder.rb
  engines/dfc_provider/spec/fixtures/files/patch_supplied_product.json
  engines/dfc_provider/spec/fixtures/files/put_supplied_product.json
  engines/dfc_provider/spec/requests/supplied_products_spec.rb
  engines/dfc_provider/spec/services/quantitative_value_builder_spec.rb
  spec/services/variant_units/option_value_namer_spec.rb
  swagger/dfc-v1.7/swagger.yaml
Labels: feedback-needed, api changes

#11494 Group DFC API operations by endpoint in documentation
  .github/workflows/mapi.yml
  config/initializers/rswag_ui.rb
  config/routes/api.rb
  engines/dfc_provider/app/controllers/dfc_provider/supplied_products_controller.rb
  engines/dfc_provider/app/services/dfc_io.rb
  engines/dfc_provider/lib/data_food_consortium/connector/connector.rb
  engines/dfc_provider/lib/data_food_consortium/connector/context.rb
  engines/dfc_provider/lib/data_food_consortium/connector/importer.rb
  engines/dfc_provider/lib/data_food_consortium/connector/skos_parser.rb
  engines/dfc_provider/spec/lib/data_food_consortium/connector/connector_spec.rb
  engines/dfc_provider/spec/lib/data_food_consortium/connector/importer_spec.rb
  engines/dfc_provider/spec/requests/addresses_spec.rb
  engines/dfc_provider/spec/requests/catalog_items_spec.rb
  engines/dfc_provider/spec/requests/enterprises_spec.rb
  engines/dfc_provider/spec/requests/persons_spec.rb
  engines/dfc_provider/spec/requests/supplied_products_spec.rb
  engines/dfc_provider/spec/services/address_builder_spec.rb
  engines/dfc_provider/spec/services/authorization_control_spec.rb
  engines/dfc_provider/spec/services/catalog_item_builder_spec.rb
  engines/dfc_provider/spec/services/dfc_io_spec.rb
  engines/dfc_provider/spec/services/dfc_loader_spec.rb
  engines/dfc_provider/spec/services/enterprise_builder_spec.rb
  engines/dfc_provider/spec/services/offer_builder_spec.rb
  engines/dfc_provider/spec/services/quantitative_value_builder_spec.rb
  engines/dfc_provider/spec/services/supplied_product_builder_spec.rb
  engines/dfc_provider/spec/swagger_helper.rb
  spec/base_spec_helper.rb
  spec/requests/api/orders_spec.rb
  spec/requests/api/v1/customers_spec.rb
  spec/requests/api_docs_spec.rb
  spec/swagger_helper.rb
  swagger/dfc.yaml
  swagger/v1.yaml
Labels: pr-no-test, technical changes only

#11508 [DFC API] Add endpoint for enterprise groups
  engines/dfc_provider/app/controllers/dfc_provider/catalog_items_controller.rb
  engines/dfc_provider/app/controllers/dfc_provider/enterprise_groups_controller.rb
  engines/dfc_provider/app/controllers/dfc_provider/enterprises_controller.rb
  engines/dfc_provider/app/services/enterprise_builder.rb
  engines/dfc_provider/app/services/person_builder.rb
  engines/dfc_provider/config/routes.rb
  engines/dfc_provider/spec/requests/enterprise_groups_spec.rb
  engines/dfc_provider/spec/requests/enterprises_spec.rb
  swagger/dfc.yaml
Labels: pr-no-test, api changes

#11497 Fix error when importing entries with a tax category
  app/models/product_import/entry_validator.rb
  spec/models/product_importer_spec.rb
Labels: pr-staged-au

#11537 Renames product so it always appears first on the report results
  spec/lib/reports/orders_and_fulfillment/orders_cycle_supplier_totals_report_spec.rb
Labels: technical changes only

#11542 Update templates
  .github/ISSUE_TEMPLATE/release.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: pr-no-test, technical changes only

#11496 🚧 BUU: update and tweak UI and CSS to fit V3 style to legacy
  app/views/admin/shared/_stimulus_pagination.html.haml
  app/webpacker/css/admin/all.scss
  app/webpacker/css/admin/components/buttons.scss
  app/webpacker/css/admin/components/text-angular.scss
  app/webpacker/css/admin/openfoodnetwork.scss
  app/webpacker/css/admin_v3/all.scss
  app/webpacker/css/admin_v3/components/actions.scss
  app/webpacker/css/admin_v3/components/buttons.scss
  app/webpacker/css/admin_v3/components/date-picker.scss
  app/webpacker/css/admin_v3/components/dropdown.scss
  app/webpacker/css/admin_v3/components/navigation.scss
  app/webpacker/css/admin_v3/components/pagination.scss
  app/webpacker/css/admin_v3/components/select2.scss
  app/webpacker/css/admin_v3/components/sidebar-item.scss
  app/webpacker/css/admin_v3/components/sidebar.scss
  app/webpacker/css/admin_v3/components/text-angular.scss
  app/webpacker/css/admin_v3/dashboard/dashboard_item.scss
  app/webpacker/css/admin_v3/globals/variables.scss
  app/webpacker/css/admin_v3/mixins.scss
  app/webpacker/css/admin_v3/pages/change_type_form.scss
  app/webpacker/css/admin_v3/pages/dashboard-single-ent.scss
  app/webpacker/css/admin_v3/pages/enterprise_index_panels.scss
  app/webpacker/css/admin_v3/pages/product_import.scss
  app/webpacker/css/admin_v3/plugins/flatpickr-customization.scss
  app/webpacker/css/admin_v3/plugins/powertip.scss
  app/webpacker/css/admin_v3/sections/orders.scss
  app/webpacker/css/admin_v3/shared/forms.scss
  app/webpacker/css/admin_v3/shared/tables.scss
  app/webpacker/packs/admin-style-v3.scss
Labels: technical changes only

#11551 Install the current node version in setup
  bin/setup
Labels: technical changes only

#11562 Fix Style/HashSyntax 6/13
  .rubocop_todo.yml
  spec/controllers/admin/bulk_line_items_controller_spec.rb
  spec/controllers/admin/customers_controller_spec.rb
  spec/controllers/admin/enterprises_controller_spec.rb
  spec/controllers/admin/inventory_items_controller_spec.rb
  spec/controllers/admin/invoice_settings_controller_spec.rb
  spec/controllers/admin/matomo_settings_controller_spec.rb
  spec/controllers/admin/order_cycles_controller_spec.rb
  spec/controllers/admin/proxy_orders_controller_spec.rb
  spec/controllers/admin/reports_controller_spec.rb
  spec/controllers/admin/schedules_controller_spec.rb
  spec/controllers/admin/stripe_accounts_controller_spec.rb
  spec/controllers/admin/stripe_connect_settings_controller_spec.rb
  spec/controllers/admin/subscription_line_items_controller_spec.rb
  spec/controllers/admin/subscriptions_controller_spec.rb
  spec/controllers/admin/tag_rules_controller_spec.rb
  spec/controllers/admin/variant_overrides_controller_spec.rb
  spec/controllers/api/v0/customers_controller_spec.rb
  spec/controllers/api/v0/enterprises_controller_spec.rb
  spec/controllers/api/v0/order_cycles_controller_spec.rb
  spec/controllers/api/v0/orders_controller_spec.rb
  spec/controllers/api/v0/products_controller_spec.rb
  spec/controllers/api/v0/reports/packing_report_spec.rb
  spec/controllers/api/v0/shipments_controller_spec.rb
  spec/controllers/api/v0/taxonomies_controller_spec.rb
  spec/controllers/api/v0/taxons_controller_spec.rb
  spec/controllers/api/v0/variants_controller_spec.rb
  spec/controllers/base_controller_spec.rb
  spec/controllers/cart_controller_spec.rb
  spec/controllers/enterprises_controller_spec.rb
  spec/controllers/line_items_controller_spec.rb
Labels: technical changes only

#11509 [BUU] Bulk form editing features
  app/views/admin/products_v3/_content.html.haml
  app/views/admin/products_v3/_table.html.haml
  app/webpacker/controllers/bulk_form_controller.js
  app/webpacker/css/admin/products_v3.scss
  app/webpacker/css/admin_v3/globals/variables.scss
  app/webpacker/css/admin_v3/shared/forms.scss
  config/locales/en.yml
  spec/javascripts/stimulus/bulk_form_controller_test.js
  spec/system/admin/products_v3/products_spec.rb
Labels: technical changes only

#11572 [test] to be ignored
  .github/workflows/api-changes.yml
Labels: api changes

#11573 Compare adjustments in deterministic order for invoices
  app/serializers/invoice/order_serializer.rb
  spec/services/order_invoice_comparator_spec.rb
Labels: technical changes only

#11555 Remove duplicate association from Spree::User
  app/models/spree/user.rb
Labels: pr-staged-au, technical changes only

#11510 [Vouchers] add activate/deactivate feature
  app/controllers/admin/enterprises_controller.rb
  app/controllers/admin/vouchers_controller.rb
  app/models/voucher.rb
  app/views/admin/enterprises/form/_vouchers.html.haml
  config/locales/en.yml
  spec/controllers/admin/enterprises_controller_spec.rb
  spec/models/voucher_spec.rb
  spec/requests/admin/vouchers_spec.rb
  spec/system/consumer/split_checkout_spec.rb
Labels: pr-staged-uk

#11378 [DFC API] Add custom OFN product id to DFC SuppliedProduct
  .rubocop_styleguide.yml
  app/models/spree/product.rb
  engines/dfc_provider/app/controllers/dfc_provider/supplied_products_controller.rb
  engines/dfc_provider/app/services/dfc_io.rb
  engines/dfc_provider/app/services/dfc_loader.rb
  engines/dfc_provider/app/services/supplied_product_builder.rb
  engines/dfc_provider/lib/data_food_consortium/connector/importer.rb
  engines/dfc_provider/lib/dfc_provider.rb
  engines/dfc_provider/lib/dfc_provider/supplied_product.rb
  engines/dfc_provider/spec/lib/data_food_consortium/connector/connector_spec.rb
  engines/dfc_provider/spec/lib/data_food_consortium/connector/importer_spec.rb
  engines/dfc_provider/spec/requests/addresses_spec.rb
  engines/dfc_provider/spec/requests/catalog_items_spec.rb
  engines/dfc_provider/spec/requests/enterprises_spec.rb
  engines/dfc_provider/spec/requests/supplied_products_spec.rb
  engines/dfc_provider/spec/services/address_builder_spec.rb
  swagger/dfc.yaml
Labels: technical changes only

#11568 🚧 [BUU] Add `Edit` link into a small menu on the last Actions column to the right of the table
  app/views/admin/products_v3/_table.html.haml
  app/views/admin/products_v3/components/_product_actions.html.haml
  app/webpacker/controllers/vertical_ellipsis_menu_controller.js
  app/webpacker/css/admin_v3/all.scss
  app/webpacker/css/admin_v3/components/vertical_ellipsis_menu.scss
  config/locales/en.yml
  spec/javascripts/stimulus/vertical_ellipsis_menu_controller_test.js
  spec/system/admin/products_v3/products_spec.rb
Labels: pr-staged-fr, technical changes only
