Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2023-07, with the labels that each got.

#11144 Remove unused gem test-unit
  Gemfile
  Gemfile.lock
Labels: pr-no-test

#11137 Remove :permalink attribute from Product
  app/assets/javascripts/admin/bulk_product_update.js.coffee
  app/controllers/api/v0/products_controller.rb
  app/controllers/api/v0/variants_controller.rb
  app/controllers/spree/admin/images_controller.rb
  app/controllers/spree/admin/product_properties_controller.rb
  app/controllers/spree/admin/products_controller.rb
  app/controllers/spree/admin/variants_controller.rb
  app/models/spree/product.rb
  app/models/spree/variant.rb
  app/serializers/api/admin/product_serializer.rb
  app/serializers/api/product_serializer.rb
  app/services/permitted_attributes/product.rb
  app/views/spree/admin/products/_form.html.haml
  db/migrate/20230628131123_remove_product_permalink.rb
  db/schema.rb
  spec/controllers/api/v0/products_controller_spec.rb
  spec/controllers/api/v0/variants_controller_spec.rb
  spec/controllers/spree/admin/variants_controller_spec.rb
  spec/javascripts/unit/admin/bulk_product_update_spec.js.coffee
  spec/models/spree/product_spec.rb
  spec/serializers/api/product_serializer_spec.rb
  spec/services/sets/product_set_spec.rb
  spec/system/admin/bulk_product_update_spec.rb
  spec/system/admin/products_spec.rb
Labels: pr-staged-fr

#11138 Add timestamps to variants table
  db/migrate/20230628144825_variant_timestamps.rb
  db/schema.rb
Labels: pr-no-test

#11169 Fix container issues introduced by #11123
  app/views/spree/layouts/_admin_body.html.haml
Labels: pr-staged-uk, pr-staged-fr, priority

#11162 Drop unused Spree Promotion Tables
  db/migrate/20230706033212_drop_spree_promotion_tables.rb
  db/schema.rb
Labels: tech debt

#11135 Vouchers part 2
  app/controllers/admin/vouchers_controller.rb
  app/controllers/concerns/checkout_callbacks.rb
  app/controllers/split_checkout_controller.rb
  app/controllers/voucher_adjustments_controller.rb
  app/helpers/checkout_helper.rb
  app/helpers/spree/payment_methods_helper.rb
  app/models/spree/order.rb
  app/services/voucher_adjustments_service.rb
  app/views/split_checkout/_details.html.haml
  app/views/split_checkout/_form.html.haml
  app/views/split_checkout/_payment.html.haml
  app/views/split_checkout/_summary.html.haml
  app/views/split_checkout/_voucher_section.cable_ready.haml
  app/views/split_checkout/_voucher_section.html.haml
  app/views/split_checkout/payment/_stripe_sca.html.haml
  app/views/spree/admin/payments/_list.html.haml
  app/views/spree/orders/_totals_footer.html.haml
  app/views/spree/shared/_order_details.html.haml
  app/webpacker/css/darkswarm/split-checkout.scss
  config/locales/en.yml
  config/routes.rb
  lib/reporting/reports/payments/payment_totals.rb
  lib/reporting/reports/payments/payments_by_payment_type.rb
  spec/controllers/split_checkout_controller_spec.rb
  spec/models/spree/order/payment_spec.rb
  spec/requests/voucher_adjustments_spec.rb
  spec/system/consumer/split_checkout_spec.rb
  spec/system/consumer/split_checkout_tax_incl_spec.rb
  spec/system/consumer/split_checkout_tax_not_incl_spec.rb
Labels: pr-staged-uk, priority

#11145 DFC API return SuppliedProduct after creation
  .rubocop_styleguide.yml
  .rubocop_todo.yml
  engines/dfc_provider/README.md
  engines/dfc_provider/app/controllers/dfc_provider/supplied_products_controller.rb
  engines/dfc_provider/spec/fixtures/files/patch_catalog_item.json
  engines/dfc_provider/spec/fixtures/files/patch_supplied_product.json
  engines/dfc_provider/spec/requests/catalog_items_spec.rb
  engines/dfc_provider/spec/requests/enterprises_spec.rb
  engines/dfc_provider/spec/requests/persons_spec.rb
  engines/dfc_provider/spec/requests/supplied_products_spec.rb
  engines/dfc_provider/spec/support/example_json.rb
  engines/dfc_provider/spec/swagger_helper.rb
  lib/data_food_consortium/connector/importer.rb
  script/rswag
  spec/lib/data_food_consortium/connector/importer_spec.rb
  spec/swagger_helper.rb
  swagger/dfc-v1.7/swagger.yaml
  swagger/v1/swagger.yaml
Labels: pr-staged-uk, priority

#11187 Admin, White Label: check the custom tab checkbox if any errors on custom tab (ie. title is blank)
  app/views/admin/enterprises/form/_white_label.html.haml
  spec/system/admin/enterprises_spec.rb
Labels: pr-staged-uk

#11148 Don't return duplicate rows in the customer addresses report
  lib/reporting/report_rows_builder.rb
  lib/reporting/report_template.rb
  lib/reporting/reports/customers/addresses.rb
  spec/lib/reports/customers_report_spec.rb
  spec/lib/reports/report_spec.rb
Labels: pr-staged-au

#11115 authorize enterprise users to access invoices page
  app/controllers/spree/admin/invoices_controller.rb
  app/models/spree/ability.rb
  spec/controllers/spree/admin/orders/invoices_spec.rb
Labels: pr-staged-uk

#11184 [vouchers] fix delete voucher when tax excluded from price
  app/controllers/voucher_adjustments_controller.rb
  spec/requests/voucher_adjustments_spec.rb
Labels: priority

#11175 Checkout, Summary step: Display the ship/delivery address (instead of the billing one)
  app/views/split_checkout/_summary.html.haml
  spec/factories/address_factory.rb
  spec/services/order_syncer_spec.rb
  spec/system/consumer/split_checkout_spec.rb
Labels: pr-staged-uk

#11105 Checkout summary: avoid carriage return on price
  lib/spree/money.rb
  spec/lib/spree/money_spec.rb
Labels: pr-staged-au

#11251 Admin, Products & Inventory reports: add `on_hand` and `on_demand?` columns by default ; mark `Inventory (on hand)` report as deprecated
  app/views/admin/reports/_report_subtype.html.haml
  config/locales/en.yml
  lib/reporting/reports/list.rb
  lib/reporting/reports/products_and_inventory/all_products.rb
  spec/system/admin/reports_spec.rb
Labels: pr-staged-uk

#11292 Admin: improve platform version displaying on admin homepage
  app/views/spree/admin/overview/_version.html.haml
Labels: pr-staged-uk

#11282 White label: Customize rendering inside the trix-editor, to match the shopfront rendering
  app/views/shopping_shared/tabs/_custom.html.haml
  app/webpacker/css/admin/trix.scss
  app/webpacker/css/darkswarm/shop_tabs.scss
Labels: pr-staged-uk

#11247 Admin, Enterprise creation : set visibility to "Hidden" by default
  app/controllers/admin/enterprises_controller.rb
  app/controllers/api/v0/enterprises_controller.rb
  db/migrate/20230720080504_change_defaultvalue_for_visible_enterprise.rb
  db/schema.rb
  spec/controllers/admin/enterprises_controller_spec.rb
  spec/controllers/api/v0/enterprises_controller_spec.rb
  spec/factories/enterprise_factory.rb
  spec/system/admin/enterprises_spec.rb
  spec/system/consumer/registration_spec.rb
Labels: pr-staged-fr

#11278 Fix swagger-api integration after last update
  config/initializers/rswag_api.rb
  spec/requests/api_docs_spec.rb
Labels: pr-staged-uk
