Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2023-05, with the labels that each got.

#10768 Improve query logging in development
  .env.development
  Gemfile
  Gemfile.lock
  config/application.rb
Labels: dev-test

#10329 Improve input validation on new and edit Payment Method pages
  app/controllers/spree/admin/payment_methods_controller.rb
  app/helpers/spree/admin/base_helper.rb
  app/models/calculator/flat_percent_item_total.rb
  app/models/calculator/flat_percent_per_item.rb
  app/models/calculator/flat_rate.rb
  app/models/calculator/flexi_rate.rb
  app/models/calculator/per_item.rb
  app/models/calculator/price_sack.rb
  app/models/spree/payment_method.rb
  app/models/spree/preference.rb
  app/models/spree/preferences/preferable.rb
  app/views/spree/admin/payment_methods/_providers.html.haml
  config/locales/en.yml
  lib/spree/localized_number.rb
  lib/tasks/sample_data/payment_method_factory.rb
  spec/base_spec_helper.rb
  spec/lib/spree/localized_number_spec.rb
  spec/models/calculator/flat_percent_item_total_spec.rb
  spec/models/calculator/flat_percent_per_item_spec.rb
  spec/models/calculator/flat_rate_spec.rb
  spec/models/calculator/flexi_rate_spec.rb
  spec/models/calculator/per_item_spec.rb
  spec/models/calculator/price_sack_spec.rb
  spec/models/spree/preference_spec.rb
  spec/models/spree/preferences/preferable_spec.rb
  spec/spec_helper.rb
  spec/support/localized_number_helper.rb
  spec/system/admin/payment_method_spec.rb
Labels: pr-staged-au

#10762 Preserve encoding of stored reports
  app/models/report_blob.rb
  spec/models/report_blob_spec.rb
  spec/system/admin/reports_spec.rb
Labels: pr-staged-au

#10780 Enable prettier for Admin SCSS
  .prettierignore
  .prettierrc.json
  app/webpacker/css/admin/all.scss
  app/webpacker/css/admin/components/actions.scss
  app/webpacker/css/admin/components/alert_row.scss
  app/webpacker/css/admin/components/buttons.scss
  app/webpacker/css/admin/components/dialogs.scss
  app/webpacker/css/admin/components/input.scss
  app/webpacker/css/admin/components/jquery_dialog.scss
  app/webpacker/css/admin/components/messages.scss
  app/webpacker/css/admin/components/navigation.scss
  app/webpacker/css/admin/components/product_autocomplete.scss
  app/webpacker/css/admin/components/progress.scss
  app/webpacker/css/admin/components/simple_modal.scss
  app/webpacker/css/admin/components/states.scss
  app/webpacker/css/admin/components/stripe_connect_button.scss
  app/webpacker/css/admin/components/subscriptions_states.scss
  app/webpacker/css/admin/components/table-filter.scss
  app/webpacker/css/admin/components/table_loading.scss
  app/webpacker/css/admin/components/timepicker.scss
  app/webpacker/css/admin/components/todo.scss
  app/webpacker/css/admin/components/tom_select.scss
  app/webpacker/css/admin/components/wizard_progress.scss
Labels: pr-staged-au

#10792 Remove unknown (deleted) feature toggles at boot
  lib/open_food_network/feature_toggle.rb
  spec/lib/open_food_network/feature_toggle_spec.rb
Labels: pr-staged-au

#10820 Remove indirect JS dependencies
  package.json
  yarn.lock
Labels: pr-staged-fr

#10772 Locale-aware Fragment Caching
  app/controllers/admin/contents_controller.rb
  app/helpers/application_helper.rb
  app/models/content_configuration.rb
  app/views/components/_spinner.html.haml
  app/views/home/_tagline.html.haml
  app/views/producers/_fat.html.haml
  app/views/shared/_footer.html.haml
  app/views/shared/_register_call.html.haml
  app/views/shared/menu/_cart.html.haml
  app/views/shared/menu/_cart_sidebar.html.haml
  app/views/shared/menu/_language_selector.html.haml
  app/views/shared/menu/_large_menu.html.haml
  app/views/shared/menu/_mobile_menu.html.haml
  app/views/shared/menu/_offcanvas_menu.html.haml
  app/views/shared/menu/_signed_out.html.haml
  app/views/shop/products/_applied_filters_feedback.haml
  app/views/shop/products/_filters.html.haml
  app/views/shop/products/_form.html.haml
  app/views/shop/products/_search_feedback.haml
  app/views/shop/products/_searchbar.haml
  app/views/shop/products/_shop_variant.html.haml
  app/views/shop/products/_shop_variant_no_group_buy.html.haml
  app/views/shop/products/_shop_variant_with_group_buy.html.haml
  app/views/shop/products/_summary.html.haml
  app/views/shops/_fat.html.haml
  app/views/shops/_hubs.html.haml
  app/views/shops/_hubs_table.html.haml
  app/views/shops/_skinny.html.haml
  config/application.rb
  lib/i18n_digests.rb
  spec/helpers/application_helper_spec.rb
  spec/lib/i18n_digests_spec.rb
Labels: pr-staged-uk

#10805 Admin, Edit customer details for an order: when changing to another customer, update `customer_id` as well
  app/controllers/spree/admin/orders/customer_details_controller.rb
  app/views/spree/admin/orders/customer_details/edit.html.haml
  app/webpacker/controllers/select_customer_controller.js
  spec/system/admin/order_spec.rb
Labels: pr-staged-uk

#10732 [Hidden] Notify about completed report with download link via email
  app/controllers/admin/reports_controller.rb
  app/jobs/report_job.rb
  app/mailers/report_mailer.rb
  app/models/report_blob.rb
  app/views/report_mailer/report_ready.html.haml
  config/locales/en.yml
  spec/jobs/report_job_spec.rb
  spec/mailers/previews/report_mailer_preview.rb
  spec/mailers/report_mailer_spec.rb
  spec/system/admin/reports_spec.rb
Labels: feedback-needed

#10825 Activate white label feature
  app/controllers/concerns/white_label.rb
  app/helpers/admin/enterprises_helper.rb
  lib/open_food_network/feature_toggle.rb
  spec/controllers/spree/orders_controller_spec.rb
  spec/system/admin/enterprises_spec.rb
  spec/system/consumer/white_label_spec.rb
Labels: pr-staged-uk, priority

#10817 Scope orders before bulk actions
  app/reflexes/bulk_actions_in_orders_list_reflex.rb
  app/reflexes/cancel_orders_reflex.rb
  app/services/orders_bulk_cancel_service.rb
Labels: pr-staged-au

#10813 Fix searching issue with full name on bulk order management
  app/assets/javascripts/admin/line_items/controllers/line_items_controller.js.coffee
  app/models/spree/address.rb
  spec/models/spree/address_spec.rb
  spec/system/admin/orders_spec.rb
Labels: pr-staged-au

#10800 Also remove localized number logic from weight calculator
  app/models/calculator/weight.rb
  spec/models/calculator/weight_spec.rb
Labels: pr-staged-au

#10832 Clone all ExchangeVariant objects in bulk
  app/models/exchange.rb
Labels: pr-staged-au

#10761 [Vouchers] Flat rate of any amount
  app/controllers/admin/vouchers_controller.rb
  app/models/voucher.rb
  app/views/admin/vouchers/new.html.haml
  app/views/split_checkout/_voucher_section.cable_ready.haml
  db/migrate/20230418030646_add_amount_to_vouchers.rb
  db/schema.rb
  spec/controllers/split_checkout_controller_spec.rb
  spec/factories/voucher_factory.rb
  spec/models/spree/order_spec.rb
  spec/models/voucher_spec.rb
  spec/requests/admin/vouchers_controller_spec.rb
  spec/requests/voucher_adjustments_spec.rb
  spec/services/voucher_adjustments_service_spec.rb
  spec/system/admin/vouchers_spec.rb
  spec/system/consumer/split_checkout_spec.rb
  spec/system/consumer/split_checkout_tax_incl_spec.rb
  spec/system/consumer/split_checkout_tax_not_incl_spec.rb
Labels: pr-staged-au, priority

#10859 [Vouchers] Updates warning_forfeit_remaining_amount default message
  config/locales/en.yml
  spec/system/consumer/split_checkout_spec.rb
Labels: pr-staged-au

#10750 White Label: allow hide of groups tab in shop navigation
  app/helpers/shop_helper.rb
  app/services/permitted_attributes/enterprise.rb
  app/views/admin/enterprises/form/_white_label.html.haml
  config/locales/en.yml
  db/migrate/20230425135232_add_hide_groups_tab_to_enterprises.rb
  db/schema.rb
  spec/system/admin/enterprises_spec.rb
  spec/system/consumer/white_label_spec.rb
Labels: pr-staged-uk

#10893 [White Label] Small width screens: Hide OFN logo and use the customized logo if activated
  app/views/shared/menu/_offcanvas_menu.html.haml
Labels: pr-staged-au

#10791 [admin_v3] New brand colours in admin interface
  app/assets/javascripts/admin/utils/services/status_message.js.coffee
  app/assets/javascripts/templates/admin/save_bar.html.haml
  app/views/admin/enterprises/_actions.html.haml
  app/views/admin/enterprises/_admin_index.html.haml
  app/views/spree/admin/shared/_head.html.haml
  app/webpacker/css/admin/all.scss
  app/webpacker/css/admin/components/input.scss
  app/webpacker/css/admin/components/tooltip.scss
  app/webpacker/css/admin/enterprises.scss
  app/webpacker/css/admin/globals/palette.scss
  app/webpacker/css/admin/globals/variables.scss
  app/webpacker/css/admin/openfoodnetwork.scss
  app/webpacker/css/admin/plugins/flatpickr-customization.scss
  app/webpacker/css/admin/variables.scss
  app/webpacker/css/admin_v3/all.scss
  app/webpacker/css/admin_v3/globals/palette.scss
  app/webpacker/css/mail/all.scss
  app/webpacker/packs/admin-style-v3.scss
  lib/open_food_network/feature_toggle.rb
Labels: priority

#10861 Update products with DFC Prototype
  config/routes/api.rb
  engines/dfc_provider/app/controllers/dfc_provider/catalog_items_controller.rb
  engines/dfc_provider/app/controllers/dfc_provider/supplied_products_controller.rb
  engines/dfc_provider/config/routes.rb
  engines/dfc_provider/spec/controllers/dfc_provider/catalog_items_controller_spec.rb
  engines/dfc_provider/spec/controllers/dfc_provider/enterprises_spec.rb
  engines/dfc_provider/spec/controllers/dfc_provider/persons_controller_spec.rb
  engines/dfc_provider/spec/controllers/dfc_provider/supplied_products_controller_spec.rb
  engines/dfc_provider/spec/requests/catalog_items_spec.rb
  engines/dfc_provider/spec/requests/enterprises_spec.rb
  engines/dfc_provider/spec/requests/persons_spec.rb
  engines/dfc_provider/spec/requests/supplied_products_spec.rb
  engines/dfc_provider/spec/spec_helper.rb
  engines/dfc_provider/spec/support/authorization_helper.rb
  engines/dfc_provider/spec/support/patch_catalog_item.json
  engines/dfc_provider/spec/support/patch_supplied_product.json
  lib/open_food_network/feature_toggle.rb
Labels: priority
