Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2023-02, with the labels that each got.

#10339 Remove unnecessary SSL code
  Gemfile
  Gemfile.lock
  app/controllers/spree/admin/general_settings_controller.rb
  app/models/spree/app_configuration.rb
  app/views/spree/admin/general_settings/edit.html.haml
  config/locales/en.yml
  db/migrate/20230130032659_delete_ssl_preferences.rb
  db/schema.rb
Labels: pr-staged-uk

#10318 Remove unused currency from calculators
  app/models/calculator/flat_rate.rb
  app/models/calculator/flexi_rate.rb
  app/models/calculator/per_item.rb
  app/models/calculator/price_sack.rb
  app/services/permitted_attributes/calculator.rb
  spec/controllers/spree/admin/payment_methods_controller_spec.rb
  spec/controllers/spree/admin/shipping_methods_controller_spec.rb
Labels: pr-staged-uk

#10274 On `/cart` page, if consumer adds more quantity than available, use in-app flash message instead of native alert
  app/assets/javascripts/darkswarm/directives/flash.js.coffee
  app/assets/javascripts/darkswarm/directives/on_hand.js.coffee
  spec/system/consumer/shopping/cart_spec.rb
Labels: feedback-needed

#10257 Fix decimal display for imperial weight on Cart, Order Confirmation page and Confirmation emails
  app/services/variant_units/option_value_namer.rb
  spec/services/variant_units/option_value_namer_spec.rb
Labels: pr-staged-uk

#10375 BOM: Ensure orders informations are loaded for each line items
  app/assets/javascripts/admin/line_items/controllers/line_items_controller.js.coffee
  app/views/admin/shared/_angular_per_page_controls.html.haml
  app/views/spree/admin/orders/bulk_management.html.haml
  config/locales/en.yml
  spec/javascripts/unit/admin/line_items/controllers/line_items_controller_spec.js.coffee
Labels: priority

#10322 For super admin, add pagination on `/admin/enterprises`
  app/controllers/admin/enterprises_controller.rb
  app/views/admin/enterprises/_admin_index.html.haml
Labels: pr-staged-au

#10393 Bump ransack from 2.4.2 to 2.6.0
  Gemfile
  Gemfile.lock
Labels: pr-staged-uk

#10406 SplitCheckout: Fix an issue raised when first time checkout user submit form without selecting shipping method
  app/services/default_address_updater.rb
  spec/system/consumer/split_checkout_spec.rb
Labels: pr-staged-uk, pr-staged-au

#10411 Bump paper_trail from 12.1.0 to 12.3.0
  Gemfile
  Gemfile.lock
Labels: pr-staged-fr

#10423 Remove unused suburbs table
  db/migrate/20230213060209_drop_suburbs.rb
  db/schema.rb
Labels: feedback-needed

#10381 Update payment (cash/EFF) state on cancelled order
  app/models/spree/order.rb
  app/models/spree/payment.rb
  engines/order_management/spec/services/order_management/order/updater_spec.rb
  spec/models/spree/order_spec.rb
Labels: pr-staged-uk

#10428 SplitCheckout: improve error messages in flash banner to improve user experience
  app/controllers/split_checkout_controller.rb
  config/locales/en.yml
  spec/models/spree/order_spec.rb
  spec/system/consumer/split_checkout_spec.rb
Labels: pr-staged-fr

#10351 Order cycle creation, fix needless warning and add warning to prevent data loss
  app/assets/javascripts/admin/order_cycles/controllers/order_cycle_exchanges_controller.js.coffee
  app/views/admin/order_cycles/_exchange_form.html.haml
  app/views/admin/order_cycles/checkout_options.html.haml
  app/webpacker/controllers/unsaved_changes_controller.js
  spec/javascripts/stimulus/unsaved_changes_controller_test.js
Labels: pr-staged-uk

#10343 Notify bugsnag on 404 errors
  app/controllers/errors_controller.rb
Labels: feedback-needed

#10385 New product page, add missing column and handle formatting
  app/components/product_component.rb
  app/components/products_table_component.rb
  config/locales/en.yml
  spec/components/product_component_spec.rb
Labels: pr-staged-uk

#10420 Remove code generating receipts
  .rubocop_todo.yml
  Gemfile
  Gemfile.lock
  app/assets/javascripts/shared/jquery-1.8.0.js
  app/controllers/admin/invoice_settings_controller.rb
  app/controllers/spree/admin/orders_controller.rb
  app/helpers/spree/admin/orders_helper.rb
  app/models/spree/ability.rb
  app/models/spree/app_configuration.rb
  app/views/admin/invoice_settings/edit.html.haml
  app/views/spree/admin/orders/ticket.html.haml
  config/application.rb
  config/locales/en.yml
  config/ng-test.conf.js
  config/routes/spree.rb
  db/migrate/20230213160135_delete_receipt_printing_from_preferences.rb
  db/schema.rb
  spec/controllers/admin/invoice_settings_controller_spec.rb
  spec/helpers/spree/admin/orders_helper_spec.rb
  spec/javascripts/application_spec.js
  spec/system/admin/order_print_ticket_spec.rb
Labels: pr-staged-fr

#10297 Convert admin order cancellation workflow to stimulus reflex
  app/assets/javascripts/admin/orders/controllers/bulk_cancel_controller.js.coffee
  app/components/confirm_modal_component.rb
  app/components/confirm_modal_component/confirm_modal_component.html.haml
  app/controllers/spree/admin/orders_controller.rb
  app/reflexes/cancel_orders_reflex.rb
  app/services/orders_bulk_cancel_service.rb
  app/views/spree/admin/orders/index.html.haml
  app/views/spree/admin/orders/messages/_cancel_orders.html.haml
  app/webpacker/controllers/cancel_orders_controller.js
  config/routes/spree.rb
  spec/system/admin/bulk_order_cancellation_spec.rb
  spec/system/admin/orders_spec.rb
Labels: pr-staged-uk

#10451 Sort correctly in Bulk Order Managment
  app/serializers/api/admin/order_serializer.rb
  app/views/spree/admin/orders/bulk_management.html.haml
  spec/system/admin/bulk_order_management_spec.rb
Labels: pr-staged-uk

#10247 sales tax totals by order report
  app/services/order_fees_handler.rb
  app/views/admin/reports/filters/_sales_tax_totals_by_order.html.haml
  config/locales/en.yml
  lib/reporting/reports/list.rb
  lib/reporting/reports/sales_tax/sales_tax_totals_by_order.rb
  spec/controllers/admin/reports_controller_spec.rb
  spec/system/admin/reports/sales_tax/sales_tax_totals_by_order_spec.rb
Labels: pr-staged-uk

#10442 Report deleted fees in Enterprise Fee Summary
  lib/reporting/reports/enterprise_fee_summary/summarizer.rb
  spec/lib/reports/enterprise_fee_summary/summarizer_spec.rb
Labels: pr-staged-uk, pr-staged-au

#10438 Redesign old columns dropdown component to match the design of the new one
  app/assets/javascripts/templates/admin/columns_dropdown.html.haml
  app/webpacker/css/admin/dropdown.scss
  spec/support/request/admin_helper.rb
  spec/system/admin/bulk_product_update_spec.rb
Labels: pr-staged-uk

#10332 Shopfront: Allow product description with formatting and `<img />`
  app/services/content_sanitizer.rb
  app/services/content_scrubber.rb
  app/views/shop/products/_summary.html.haml
  app/views/spree/admin/products/_form.html.haml
  spec/system/consumer/shopping/products_spec.rb
Labels: feedback-needed
