Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2023-10, with the labels that each got.

#11543 [Vouchers] Fix Sales Tax Totals By Order report
  app/models/spree/adjustment.rb
  app/services/voucher_adjustments_service.rb
  lib/reporting/reports/sales_tax/sales_tax_totals_by_order.rb
  spec/lib/reports/sales_tax_totals_by_order_spec.rb
  spec/services/voucher_adjustments_service_spec.rb
  spec/system/admin/reports/sales_tax/sales_tax_totals_by_order_spec.rb
Labels: no-staging-UK, feature toggled

#11591 Redirect to admin users edit path on success
  app/controllers/spree/admin/users_controller.rb
  spec/controllers/spree/admin/users_controller_spec.rb
Labels: pr-staged-uk

#11579 Remove Deprecated delegate_belongs_to
  app/models/application_record.rb
  app/models/product_import/entry_validator.rb
  app/models/spree/gateway.rb
  app/models/spree/variant.rb
  lib/spree/core.rb
  lib/spree/core/delegate_belongs_to.rb
Labels: pr-staged-uk, technical changes only

#11479 Splits checkout files
  .rubocop_todo.yml
  spec/system/consumer/checkout/details_spec.rb
  spec/system/consumer/checkout/guest_spec.rb
  spec/system/consumer/checkout/payment_spec.rb
  spec/system/consumer/checkout/summary_spec.rb
  spec/system/consumer/checkout/tax_incl_spec.rb
  spec/system/consumer/checkout/tax_not_incl_spec.rb
  spec/system/consumer/split_checkout_spec.rb
Labels: technical changes only

#11586 Fix Style/HashSyntax 12/13
  .rubocop_todo.yml
  spec/services/tax_rate_finder_spec.rb
  spec/services/user_default_address_setter_spec.rb
  spec/services/variants_stock_levels_spec.rb
  spec/services/voucher_adjustments_service_spec.rb
  spec/support/controller_helper.rb
  spec/support/controller_requests_helper.rb
  spec/support/request/stripe_stubs.rb
  spec/support/request/ui_component_helper.rb
  spec/support/request/web_helper.rb
  spec/system/admin/adjustments_spec.rb
  spec/system/admin/bulk_product_update_spec.rb
  spec/system/admin/configuration/states_spec.rb
  spec/system/admin/configuration/tax_rates_spec.rb
  spec/system/admin/customers_spec.rb
  spec/system/admin/enterprises_spec.rb
  spec/system/admin/invoice_print_spec.rb
  spec/system/admin/order_cycles/complex_creating_specific_time_spec.rb
  spec/system/admin/order_cycles/complex_updating_specific_time_spec.rb
  spec/system/admin/order_cycles/simple_spec.rb
  spec/system/admin/order_spec.rb
  spec/system/admin/orders_spec.rb
  spec/system/admin/payments_stripe_spec.rb
  spec/system/admin/reports/enterprise_fee_summaries_spec.rb
  spec/system/admin/reports/enterprise_summary_fees/enterprise_summary_fee_with_tax_report_by_order_spec.rb
  spec/system/admin/reports/orders_and_fulfillment_spec.rb
  spec/system/admin/reports/packing_report_spec.rb
  spec/system/admin/reports/payments_report_spec.rb
  spec/system/admin/reports/revenues_by_hub_spec.rb
  spec/system/admin/reports/sales_tax/sales_tax_totals_by_order_spec.rb
  spec/system/admin/reports/sales_tax/sales_tax_totals_by_producer_spec.rb
Labels: technical changes only

#11588 Splits bottleneck system/admin/subscriptions_spec.rb
  .rubocop_todo.yml
  spec/support/subscription_helper.rb
  spec/system/admin/subscriptions/crud_spec.rb
  spec/system/admin/subscriptions/smoke_tests_spec.rb
Labels: technical changes only

#11571 [BUU] editing fixups
  app/views/admin/products_v3/_table.html.haml
  app/webpacker/controllers/application_controller.js
  app/webpacker/controllers/bulk_form_controller.js
  app/webpacker/css/admin/products_v3.scss
  config/locales/en.yml
Labels: technical changes only

#11624 [dev ENV only] Adds attribute to enterprise factory
  lib/tasks/sample_data/enterprise_factory.rb
Labels: technical changes only

#11625 Update README.md
  docker/README.md
Labels: technical changes only

#11565 [BUU] Inline error messages and validation
  Gemfile
  Gemfile.lock
  app/helpers/spree/admin/base_helper.rb
  app/models/spree/product.rb
  app/models/spree/variant.rb
  app/views/admin/products_v3/_table.html.haml
  app/webpacker/css/admin/products_v3.scss
  app/webpacker/css/admin/shared/forms.scss
  app/webpacker/css/admin_v3/shared/forms.scss
  spec/models/spree/product_spec.rb
  spec/system/admin/products_v3/products_spec.rb
Labels: technical changes only

#11619 Add ability to customers report to filter with open ended boundaries
  lib/reporting/reports/customers/base.rb
  spec/lib/reports/customers_report_spec.rb
Labels: pr-staged-au

#11623 Fix occurring time shift in customers report results
  lib/reporting/reports/customers/base.rb
Labels: pr-staged-au

#11603 Prevent customers from editing shipped orders
  app/models/spree/order.rb
  spec/models/spree/order_spec.rb
Labels: pr-staged-au

#11345 Support enabling invoices to individual users
  app/controllers/spree/admin/orders_controller.rb
  app/helpers/spree/admin/orders_helper.rb
  app/jobs/bulk_invoice_job.rb
  app/mailers/spree/order_mailer.rb
  app/reflexes/admin/orders_reflex.rb
  app/services/invoice_renderer.rb
  app/views/spree/admin/shared/_order_tabs.html.haml
  spec/mailers/order_mailer_spec.rb
  spec/system/admin/orders/invoices_spec.rb
Labels: pr-staged-au

#11441 Fix Rails/HasManyOrHasOneDependent
  .rubocop_todo.yml
  app/models/customer.rb
  app/models/enterprise.rb
  app/models/order_cycle.rb
  app/models/spree/adjustment.rb
  app/models/spree/country.rb
  app/models/spree/credit_card.rb
  app/models/spree/order.rb
  app/models/spree/payment.rb
  app/models/spree/payment_method.rb
  app/models/spree/property.rb
  app/models/spree/return_authorization.rb
  app/models/spree/shipment.rb
  app/models/spree/shipping_category.rb
  app/models/spree/shipping_method.rb
  app/models/spree/taxonomy.rb
  app/models/spree/user.rb
  app/models/spree/variant.rb
  spec/controllers/spree/admin/return_authorizations_controller_spec.rb
Labels: technical changes only

#11637 Test customer report filtering without sorting
  spec/lib/reports/customers_report_spec.rb
Labels: pr-no-test, technical changes only

#11641 Update feature toggle title
  .github/release.yml
Labels: technical changes only

#11646 Show only the new products page in the menu
  app/views/spree/admin/shared/_product_sub_menu.html.haml
Labels: pr-staged-au, technical changes only

#11647 Only validate image when changed
  app/models/spree/product.rb
  spec/models/spree/product_spec.rb
Labels: pr-staged-au, technical changes only

#11651 Display ordered lists uniform with unordered lists in Trix editor
  app/webpacker/css/darkswarm/lists.scss
Labels: pr-staged-au

#11219 fix Viewing an invoice with the instance's invoice setting set to alternative model leads to an error 500
  .rubocop_todo.yml
  app/models/invoice/data_presenter.rb
  app/models/invoice/data_presenter/adjustable.rb
  app/models/invoice/data_presenter/adjustment.rb
  app/models/invoice/data_presenter/adjustment_originator.rb
  app/models/invoice/data_presenter/base.rb
  app/models/invoice/data_presenter/line_item.rb
  app/models/invoice/data_presenter/tax_rate.rb
  app/models/invoice/data_presenter_attributes.rb
  app/serializers/invoice/adjustable_serializer.rb
  app/serializers/invoice/adjustment_originator_serializer.rb
  app/serializers/invoice/adjustment_serializer.rb
  app/serializers/invoice/line_item_serializer.rb
  app/serializers/invoice/tax_rate_serializer.rb
  app/views/spree/admin/orders/_invoice_table3.html.haml
  app/views/spree/admin/orders/_invoice_table4.html.haml
  spec/system/admin/invoice_print_spec.rb
Labels: pr-staged-uk

#11593 [Vouchers] Fix tax included in price amount
  app/helpers/admin/orders_helper.rb
  app/helpers/checkout_helper.rb
  config/locales/en.yml
  spec/helpers/admin/orders_helper_spec.rb
  spec/helpers/checkout_helper_spec.rb
  spec/system/consumer/checkout/tax_incl_spec.rb
Labels: pr-staged-au, feature toggled

#11114 Not paid order confirmations resemble paid orders 7603
  app/models/spree/order.rb
  app/views/spree/orders/_totals_footer.html.haml
  app/views/spree/shared/_order_details.html.haml
  app/webpacker/css/darkswarm/checkout.scss
  config/locales/en.yml
Labels: pr-staged-au

#11634 [BUU] Left-align headers of new orders table
  app/views/spree/admin/orders/_table_row.html.haml
  app/webpacker/css/admin_v3/shared/tables.scss
Labels: pr-staged-au, technical changes only

#11663 Update tag_release script
  .github/ISSUE_TEMPLATE/release.md
  script/tag_release
Labels: pr-no-test, technical changes only

#11660 Hide old products screen when admin_style_v3 enabled
  app/views/admin/products_v3/_table.html.haml
  app/views/spree/admin/shared/_product_sub_menu.html.haml
  config/routes/admin.rb
  config/routes/spree.rb
  spec/reflexes/products_reflex_spec.rb
  spec/system/admin/products_v3/products_spec.rb
Labels: technical changes only

#11657 Notify user about errors raised in reports
  app/jobs/report_job.rb
  config/locales/en.yml
  spec/jobs/report_job_spec.rb
Labels: feature toggled

#11668 Don't show credit owed when = 0 in order confirmation
  app/models/order_balance.rb
  app/views/spree/orders/_totals_footer.html.haml
Labels: pr-staged-uk

#11547 Adds coverage on order-associated attributes
  spec/services/order_invoice_comparator_spec.rb
Labels: technical changes only

#11682 Adds coverage on order confirmation page
  spec/system/consumer/checkout/summary_spec.rb
Labels: technical changes only

#11687 Moves assertions within before do block
  spec/system/consumer/checkout/payment_spec.rb
Labels: technical changes only

#11577 Admin, Orders list: when capturing an order, fix an issue that makes the tooltip invisible (+ errors in the console)
  app/views/admin/enterprises/form/_address.html.haml
  app/views/admin/enterprises/form/_business_details.html.haml
  app/views/admin/enterprises/form/_contact.html.haml
  app/views/admin/enterprises/form/_permalink.html.haml
  app/views/admin/enterprises/form/_primary_details.html.haml
  app/views/admin/enterprises/form/_users.html.haml
  app/views/admin/shared/_tooltip.html.haml
  app/views/admin/shared/_tooltip_button.html.haml
  app/views/admin/shared/_whats_this_tooltip.html.haml
  app/views/spree/admin/orders/_table_row.html.haml
  app/webpacker/controllers/tooltip_controller.js
  app/webpacker/css/admin/shared/tables.scss
  spec/system/admin/orders_spec.rb
Labels: pr-staged-au

#11700 Fix Style/HashSyntax 13/13
  .rubocop_todo.yml
  app/models/spree/order.rb
  spec/services/voucher_adjustments_service_spec.rb
  spec/system/admin/reports_spec.rb
  spec/system/admin/tag_rules_spec.rb
  spec/system/admin/variant_overrides_spec.rb
  spec/system/admin/vouchers_spec.rb
  spec/system/consumer/account/cards_spec.rb
  spec/system/consumer/account/developer_settings_spec.rb
  spec/system/consumer/account/payments_spec.rb
  spec/system/consumer/account_spec.rb
  spec/system/consumer/authentication_spec.rb
  spec/system/consumer/checkout/tax_incl_spec.rb
  spec/system/consumer/checkout/tax_not_incl_spec.rb
  spec/system/consumer/multilingual_spec.rb
  spec/system/consumer/shopping/cart_spec.rb
  spec/system/consumer/shopping/checkout_auth_spec.rb
  spec/system/consumer/shopping/checkout_paypal_spec.rb
  spec/system/consumer/shopping/checkout_spec.rb
  spec/system/consumer/shopping/checkout_stripe_spec.rb
  spec/system/consumer/shopping/orders_spec.rb
  spec/system/consumer/shopping/products_spec.rb
  spec/system/consumer/shopping/shopping_spec.rb
  spec/system/consumer/shopping/unit_price_spec.rb
  spec/system/consumer/shopping/variant_overrides_spec.rb
  spec/system/consumer/user_password_spec.rb
  spec/system/consumer/white_label_spec.rb
  spec/system/support/cuprite_setup.rb
  spec/views/spree/orders/edit.html.haml_spec.rb
  spec/views/spree/shared/_order_details.html.haml_spec.rb
Labels: technical changes only

#11695 Make update button on enterprises primary details form clickable upon input to name field
  app/views/admin/enterprises/_ng_form.html.haml
Labels: pr-staged-uk

#11694 add condition on warning_forfeit_remaining_amount note
  app/views/split_checkout/_voucher_section.html.haml
  spec/views/split_checkout/_voucher_section.html.haml_spec.rb
Labels: pr-staged-uk
