Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2023-01, with the labels that each got.

#10237 Remove report dependency on report controller
  app/controllers/admin/reports_controller.rb
  lib/reporting/report_renderer.rb
Labels: pr-staged-au

#10234 Remove unused Spree database tables
  db/migrate/20230104233913_drop_spree_product_groups_products.rb
  db/migrate/20230104234406_drop_spree_product_groups.rb
  db/schema.rb
Labels: pr-staged-au

#10229 Link relative report path instead of absolute URL
  app/views/admin/reports/_report_subtype.html.haml
  app/views/admin/reports/show.html.haml
Labels: pr-staged-au

#10278 Enable pg_stat_statements in development like prod
  db/migrate/20230117043628_enable_stats_extension.rb
  db/schema.rb
Labels: dev-test

#10243 Admin, BOM: add pagination, remove date range filtering on first load
  app/assets/javascripts/admin/line_items/controllers/line_items_controller.js.coffee
  app/views/admin/shared/_angular_per_page_controls.html.haml
  app/views/spree/admin/orders/bulk_management.html.haml
  app/views/spree/admin/orders/index.html.haml
  app/webpacker/controllers/flatpickr_controller.js
  spec/javascripts/unit/admin/line_items/controllers/line_items_controller_spec.js.coffee
  spec/system/admin/bulk_order_management_spec.rb
  vendor/assets/stylesheets/select2.css.scss
Labels: pr-staged-uk

#10319 Show new flash messages until discarded by user
  app/webpacker/controllers/flash_controller.js
  app/webpacker/css/darkswarm/animations.scss
Labels: pr-staged-uk

#10307 Add required asterisk in business details panel
  app/views/admin/enterprises/form/_business_address.html.haml
Labels: pr-staged-au

#10245 Admin, BOM: Don't display "group by size" if group by product value is actually null
  app/assets/javascripts/admin/line_items/controllers/line_items_controller.js.coffee
  spec/javascripts/unit/admin/line_items/controllers/line_items_controller_spec.js.coffee
Labels: pr-staged-uk

#10276 Split Checkout, increase input to 16px for small devices and iOS devices
  app/webpacker/css/darkswarm/split-checkout.scss
Labels: pr-staged-uk

#10208 Admin: Include a "None" option for calculator type user in shipping method and payment method forms
  app/models/calculator/none.rb
  app/models/spree/payment_method.rb
  app/models/spree/shipping_method.rb
  config/application.rb
  spec/lib/reports/enterprise_fee_summary/enterprise_fee_summary_report_spec.rb
  spec/system/admin/payment_method_spec.rb
  spec/system/admin/shipping_methods_spec.rb
Labels: pr-staged-uk
