Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2023-06, with the labels that each got.

#10911 [White Label] Small width screens : use the white label link if exists for logo in nav bar
  app/views/shared/menu/_mobile_menu.html.haml
  app/views/shared/menu/_offcanvas_menu.html.haml
Labels: pr-staged-uk

#10910 [White Label] Backoffice: improve design for logo used in shopfront
  app/views/admin/enterprises/form/_white_label.html.haml
Labels: pr-staged-au

#10896 BOM: Sort by order completed at desc for line items by default
  app/assets/javascripts/admin/line_items/controllers/line_items_controller.js.coffee
  app/controllers/admin/bulk_line_items_controller.rb
  spec/controllers/admin/bulk_line_items_controller_spec.rb
  spec/system/admin/bulk_order_management_spec.rb
Labels: pr-staged-au

#10922 [White Label] Make logo url link more tolerant in terms of format
  app/models/enterprise.rb
  spec/models/enterprise_spec.rb
  spec/system/admin/enterprises_spec.rb
Labels: pr-staged-uk

#10952 Improve nil-safety in variant naming methods
  app/services/variant_units/variant_and_line_item_naming.rb
  spec/models/spree/variant_spec.rb
Labels: pr-staged-uk

#10937 [White Label] Remove ofn navigation for small width screens as well when option is activated
  app/views/shared/menu/_offcanvas_menu.html.haml
  spec/support/request/ui_component_helper.rb
  spec/system/consumer/authentication_spec.rb
  spec/system/consumer/multilingual_spec.rb
  spec/system/consumer/white_label_spec.rb
  spec/system/support/cuprite_setup.rb
Labels: pr-staged-au

#10959 [WhiteLabel] Add some margin to custom tab content for a shop
  app/views/shopping_shared/tabs/_custom.html.haml
Labels: pr-staged-au

#10960 [White Label] Customize colors of custom content editor to have beautiful toolbar
  app/webpacker/css/admin/trix.scss
Labels: pr-staged-au

#10949 [`admin_style_v3`] As an enterprise user i can see the back office with new brand colours
  app/helpers/spree/admin/navigation_helper.rb
  app/webpacker/css/admin_v3/all.scss
  app/webpacker/css/admin_v3/components/navigation.scss
  app/webpacker/css/admin_v3/globals/palette.scss
  app/webpacker/css/admin_v3/shared/layout.scss
  spec/system/admin/bulk_order_management_spec.rb
  spec/system/admin/order_cycles/simple_spec.rb
  spec/system/admin/schedules_spec.rb
Labels: pr-staged-fr

#10961 [WhiteLabel] Make update button active when changing custom tab content
  app/views/admin/enterprises/form/_white_label.html.haml
  app/webpacker/controllers/trixeditor_controller.js
  spec/system/admin/enterprises_spec.rb
Labels: pr-staged-au

#10974 Ignore leading and trailing whitespace when importing products via a spreadsheet
  app/models/product_import/product_importer.rb
  spec/models/product_importer_spec.rb
Labels: pr-staged-au

#10907 Admin, Create an order, Select a product: translate some messages in the product selection search box
  app/assets/javascripts/admin/utils/directives/variant_autocomplete.js.coffee
  config/locales/en.yml
Labels: pr-staged-au

#10933 Fix ProcessPaymentIntent service
  app/services/process_payment_intent.rb
  spec/controllers/payment_gateways/stripe_controller_spec.rb
  spec/services/process_payment_intent_spec.rb
Labels: pr-staged-uk

#10850 Require belongs_to associations - part 1
  .rubocop_todo.yml
  app/models/adjustment_metadata.rb
  app/models/column_preference.rb
  app/models/coordinator_fee.rb
  app/models/customer.rb
  app/models/distributor_payment_method.rb
  app/models/distributor_shipping_method.rb
  app/models/enterprise.rb
  app/models/spree/shipping_method.rb
  db/migrate/20230503060530_require_adjustment_and_enterprise_on_adjustment_metadata.rb
  db/migrate/20230516052547_require_order_cycle_and_enterprise_fee_on_coordinator_fees.rb
  db/migrate/20230516054204_require_payment_method_and_distributor_on_distributor_payment_methods.rb
  db/migrate/20230516054745_require_shipping_method_and_distributor_on_distributor_shipping_methods.rb
  db/schema.rb
  spec/models/adjustment_metadata_spec.rb
  spec/models/column_preference_spec.rb
  spec/models/coordinator_fee_spec.rb
  spec/models/customer_spec.rb
Labels: feedback-needed

#10983 [OIDC] Translate 'Enterprises' > 'OIDC Settings' tab title
  config/locales/en.yml
Labels: pr-staged-fr

#10988 [White Label] Custom tab content editor: order and unordered list should have a margin-left set
  app/webpacker/css/admin/trix.scss
Labels: pr-staged-uk, pr-staged-au

#11004 Show current version at bottom of admin dashboard
  app/views/spree/admin/overview/_version.html.haml
  app/views/spree/admin/overview/multi_enterprise_dashboard.html.haml
  app/views/spree/admin/overview/single_enterprise_dashboard.html.haml
  config/locales/en.yml
Labels: pr-staged-uk

#11033 Revert "Fix `redis` and `hiredis-client` version requirements "
  Gemfile
  Gemfile.lock
Labels: pr-staged-au

#11008 Prototype: Import products via DFC Connector
  engines/dfc_provider/README.md
  engines/dfc_provider/app/controllers/dfc_provider/supplied_products_controller.rb
  engines/dfc_provider/app/services/dfc_builder.rb
  engines/dfc_provider/app/services/enterprise_builder.rb
  engines/dfc_provider/app/services/quantitative_value_builder.rb
  engines/dfc_provider/app/services/supplied_product_builder.rb
  engines/dfc_provider/config/routes.rb
  engines/dfc_provider/spec/requests/supplied_products_spec.rb
  engines/dfc_provider/spec/services/enterprise_builder_spec.rb
  engines/dfc_provider/spec/services/supplied_product_builder_spec.rb
  engines/dfc_provider/spec/spec_helper.rb
  lib/data_food_consortium/connector/connector.rb
  lib/data_food_consortium/connector/importer.rb
  lib/data_food_consortium/connector/skos_parser.rb
  spec/base_spec_helper.rb
  spec/lib/data_food_consortium/connector/connector_spec.rb
  spec/lib/data_food_consortium/connector/importer_spec.rb
Labels: pr-no-test

#11100 Revert "Fix json v1.8.6 common.rb warning"
  config/initializers/json.rb
Labels: pr-no-test

#11041 Add an OFN UID column to the Users & Enterprises report
  config/locales/en.yml
  lib/reporting/reports/users_and_enterprises/base.rb
  spec/system/admin/reports/users_and_enterprises_spec.rb
Labels: pr-staged-fr

#11014 Restore line item ordering
  app/controllers/admin/bulk_line_items_controller.rb
Labels: pr-staged-au

#11002 Vouchers part 1
  app/controllers/split_checkout_controller.rb
  app/controllers/spree/admin/orders/customer_details_controller.rb
  app/models/spree/adjustment.rb
  app/models/spree/order.rb
  app/models/spree/order/checkout.rb
  app/models/voucher.rb
  app/services/order_fees_handler.rb
  app/services/order_workflow.rb
  app/views/layouts/darkswarm.html.haml
  spec/controllers/spree/admin/orders_controller_spec.rb
  spec/models/proxy_order_spec.rb
  spec/models/spree/adjustment_spec.rb
  spec/models/spree/order_spec.rb
  spec/models/voucher_spec.rb
  spec/services/voucher_adjustments_service_spec.rb
  spec/system/admin/bulk_order_management_spec.rb
  spec/system/consumer/split_checkout_spec.rb
  spec/system/consumer/split_checkout_tax_not_incl_spec.rb
Labels: feedback-needed, priority

#10914 redirect user to payment when the card doesn't have enough credit
  app/controllers/concerns/order_completion.rb
  spec/controllers/payment_gateways/paypal_controller_spec.rb
  spec/controllers/payment_gateways/stripe_controller_spec.rb
Labels: pr-staged-uk

#10965 Fix Layout/LineLength - Bundle 2
  .rubocop_todo.yml
  spec/controllers/admin/stripe_connect_settings_controller_spec.rb
  spec/controllers/admin/subscription_line_items_controller_spec.rb
  spec/controllers/admin/subscriptions_controller_spec.rb
  spec/controllers/admin/variant_overrides_controller_spec.rb
  spec/controllers/api/v0/base_controller_spec.rb
  spec/controllers/api/v0/exchange_products_controller_spec.rb
  spec/controllers/api/v0/order_cycles_controller_spec.rb
  spec/controllers/api/v0/orders_controller_spec.rb
  spec/controllers/cart_controller_spec.rb
  spec/controllers/enterprises_controller_spec.rb
  spec/controllers/line_items_controller_spec.rb
  spec/controllers/shops_controller_spec.rb
  spec/controllers/spree/admin/orders/customer_details_controller_spec.rb
  spec/controllers/spree/admin/orders/invoices_spec.rb
  spec/controllers/spree/admin/orders_controller_spec.rb
  spec/controllers/spree/admin/payment_methods_controller_spec.rb
  spec/controllers/spree/admin/variants_controller_spec.rb
  spec/controllers/spree/credit_cards_controller_spec.rb
  spec/controllers/spree/orders_controller_spec.rb
  spec/controllers/stripe/webhooks_controller_spec.rb
  spec/factories/stock_location_factory.rb
  spec/helpers/injection_helper_spec.rb
  spec/helpers/order_cycles_helper_spec.rb
  spec/helpers/spree/admin/base_helper_spec.rb
  spec/jobs/subscription_confirm_job_spec.rb
  spec/jobs/subscription_placement_job_spec.rb
  spec/lib/open_food_network/enterprise_fee_calculator_spec.rb
  spec/lib/open_food_network/order_cycle_form_applicator_spec.rb
  spec/lib/open_food_network/order_cycle_permissions_spec.rb
  spec/lib/open_food_network/permissions_spec.rb
  spec/lib/open_food_network/scope_variant_to_hub_spec.rb
  spec/lib/open_food_network/tag_rule_applicator_spec.rb
  spec/lib/reports/customers_report_spec.rb
  spec/lib/reports/order_cycle_management_report_spec.rb
  spec/lib/reports/products_and_inventory_report_spec.rb
  spec/lib/reports/users_and_enterprises_report_spec.rb
  spec/mailers/order_mailer_spec.rb
  spec/mailers/producer_mailer_spec.rb
  spec/mailers/subscription_mailer_spec.rb
  spec/models/concerns/calculated_adjustments_spec.rb
  spec/models/concerns/order_shipment_spec.rb
  spec/models/concerns/product_stock_spec.rb
  spec/models/enterprise_relationship_spec.rb
  spec/models/enterprise_spec.rb
  spec/models/exchange_spec.rb
  spec/models/order_cycle_spec.rb
  spec/models/product_importer_spec.rb
  spec/models/spree/ability_spec.rb
  spec/models/spree/address_spec.rb
  spec/models/spree/classification_spec.rb
  spec/models/spree/inventory_unit_spec.rb
  spec/models/spree/order/checkout_spec.rb
  spec/models/spree/order_inventory_spec.rb
  spec/models/spree/order_spec.rb
  spec/models/spree/payment_method_spec.rb
  spec/models/spree/payment_spec.rb
  spec/models/spree/product_spec.rb
  spec/models/spree/shipping_method_spec.rb
Labels: pr-no-test

#11109 Gracefully deal with missing S3 config
  app/models/application_record.rb
  app/models/enterprise.rb
  app/models/spree/image.rb
  spec/models/spree/image_spec.rb
Labels: pr-staged-au

#11089 [Invoices] Actions dropdown menu disappears after creating the first invoice
  app/assets/javascripts/admin/dropdown/directives/links_dropdown.js.coffee
  app/assets/javascripts/templates/admin/links_dropdown.html.haml
  app/views/spree/admin/shared/_order_links.html.haml
  app/webpacker/controllers/dropdown_controller.js
  spec/javascripts/stimulus/dropdown_controller_test.js
  spec/system/admin/order_spec.rb
  spec/views/spree/admin/shared/_order_links.html.haml_spec.rb
Labels: pr-staged-uk

#11079 filter distributors before listing on checkout options
  app/helpers/order_cycles_helper.rb
  app/views/admin/order_cycles/checkout_options.html.haml
  spec/helpers/order_cycles_helper_spec.rb
Labels: pr-staged-uk
