Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2023-08, with the labels that each got.

#11281 White label: Update mobile variant size for white label logo to fit the same ratio
  app/models/enterprise.rb
Labels: pr-staged-au

#11263 Dfc connector context
  Gemfile.lock
  config/routes/api.rb
  engines/dfc_provider/app/controllers/dfc_provider/catalog_items_controller.rb
  engines/dfc_provider/app/controllers/dfc_provider/enterprises_controller.rb
  engines/dfc_provider/app/controllers/dfc_provider/persons_controller.rb
  engines/dfc_provider/app/controllers/dfc_provider/supplied_products_controller.rb
  engines/dfc_provider/app/services/dfc_io.rb
  engines/dfc_provider/spec/services/dfc_io_spec.rb
  engines/dfc_provider/spec/services/dfc_loader_spec.rb
  lib/data_food_consortium/connector/importer.rb
  spec/base_spec_helper.rb
  spec/fixtures/vcr_cassettes/DataFoodConsortium_Connector_Importer/imports_an_object_with_referenced_context.yml
  spec/fixtures/vcr_cassettes/dfc-context.yml
  spec/lib/data_food_consortium/connector/importer_spec.rb
  swagger/dfc-v1.7/swagger.yaml
Labels: pr-no-test

#11302 fix margin in guest checkout
  app/views/split_checkout/_guest.html.haml
Labels: pr-staged-au

#11299 Sort orders by last name, then first name i.e. the same way bulk order management works
  app/models/spree/order.rb
  app/views/spree/admin/orders/_table.html.haml
  app/views/spree/admin/orders/_table_row.html.haml
  config/locales/en.yml
  spec/system/admin/orders_spec.rb
Labels: pr-staged-au

#11234 Show vouchers panel only if enterprise sells products (own or any)
  app/helpers/admin/enterprises_helper.rb
  spec/system/admin/vouchers_spec.rb
Labels: pr-staged-uk

#11156 [Product Refactor] Tax category
  app/assets/javascripts/admin/bulk_product_update.js.coffee
  app/components/product_component.rb
  app/controllers/spree/admin/variants_controller.rb
  app/models/calculator/default_tax.rb
  app/models/spree/line_item.rb
  app/models/spree/product.rb
  app/models/spree/variant.rb
  app/serializers/api/admin/product_serializer.rb
  app/serializers/api/admin/variant_serializer.rb
  app/services/permitted_attributes/variant.rb
  app/services/tax_rate_finder.rb
  app/views/admin/products_v3/_table.html.haml
  app/views/spree/admin/products/_form.html.haml
  app/views/spree/admin/products/index/_products_product.html.haml
  app/views/spree/admin/products/index/_products_variant.html.haml
  app/views/spree/admin/variants/_form.html.haml
  db/migrate/20230703130854_add_tax_category_to_variants.rb
  db/migrate/20230714123324_migrate_tax_category.rb
  db/schema.rb
  lib/open_food_network/enterprise_fee_applicator.rb
  lib/reporting/reports/enterprise_fee_summary/scope.rb
  lib/reporting/reports/orders_and_fulfillment/base.rb
  lib/reporting/reports/products_and_inventory/lettuce_share.rb
  spec/controllers/admin/bulk_line_items_controller_spec.rb
  spec/controllers/api/v0/orders_controller_spec.rb
  spec/factories/order_factory.rb
  spec/factories/product_factory.rb
  spec/javascripts/unit/admin/bulk_product_update_spec.js.coffee
  spec/lib/open_food_network/enterprise_fee_applicator_spec.rb
  spec/lib/reports/enterprise_fee_summary/enterprise_fee_summary_report_spec.rb
  spec/lib/reports/orders_and_fulfillment/orders_cycle_supplier_totals_report_spec.rb
  spec/mailers/producer_mailer_spec.rb
  spec/models/spree/adjustment_spec.rb
  spec/models/spree/line_item_spec.rb
  spec/models/spree/product_spec.rb
  spec/models/spree/tax_rate_spec.rb
  spec/models/spree/variant_spec.rb
  spec/services/order_tax_adjustments_fetcher_spec.rb
  spec/system/admin/product_import_spec.rb
  spec/system/admin/products_spec.rb
  spec/system/admin/reports/sales_tax/sales_tax_totals_by_order_spec.rb
  spec/system/admin/reports/sales_tax/sales_tax_totals_by_producer_spec.rb
  spec/system/admin/reports_spec.rb
  spec/system/admin/variants_spec.rb
  spec/system/consumer/split_checkout_tax_not_incl_spec.rb
Labels: pr-staged-fr

#11126 Show invoice number on invoices
  app/models/invoice/data_presenter.rb
  app/views/spree/admin/orders/invoice3.html.haml
  app/views/spree/admin/orders/invoice4.html.haml
  config/locales/en.yml
  spec/system/admin/orders_spec.rb
Labels: pr-staged-uk

#11192 fix Bulk invoice printing/sending
  app/controllers/spree/admin/invoices_controller.rb
  app/jobs/bulk_invoice_job.rb
  app/mailers/spree/order_mailer.rb
  app/models/invoice/data_presenter/address.rb
  app/models/invoice/data_presenter/distributor.rb
  app/models/spree/order.rb
  app/reflexes/admin/orders_reflex.rb
  app/serializers/invoice/enterprise_serializer.rb
  app/services/order_invoice_generator.rb
  config/locales/en.yml
  spec/jobs/bulk_invoice_job_spec.rb
  spec/mailers/order_mailer_spec.rb
  spec/models/spree/order_spec.rb
  spec/services/order_invoice_generator_spec.rb
Labels: pr-staged-fr

#11320 SCSS cleanup
  .prettierignore
  app/components/pagination_component/pagination_component.scss
  app/components/search_input_component/search_input_component.scss
  app/components/selector_component/selector_component.scss
  app/components/selector_with_filter_component/selector_with_filter_component.scss
  app/webpacker/css/admin/alert.scss
  app/webpacker/css/admin/all.scss
  app/webpacker/css/admin/change_type_form.scss
  app/webpacker/css/admin/components/buttons.scss
  app/webpacker/css/admin/components/dialogs.scss
  app/webpacker/css/admin/components/input.scss
  app/webpacker/css/admin/components/jquery_dialog.scss
  app/webpacker/css/admin/components/messages.scss
  app/webpacker/css/admin/components/pagination.scss
  app/webpacker/css/admin/components/save_bar.scss
  app/webpacker/css/admin/components/simple_modal.scss
  app/webpacker/css/admin/components/table_loading.scss
  app/webpacker/css/admin/components/tom_select.scss
  app/webpacker/css/admin/dashboard-single-ent.scss
  app/webpacker/css/admin/dashboard_item.scss
  app/webpacker/css/admin/enterprise_index_panels.scss
  app/webpacker/css/admin/enterprises.scss
  app/webpacker/css/admin/globals/functions.scss
  app/webpacker/css/admin/globals/palette.scss
  app/webpacker/css/admin/globals/variables.scss
  app/webpacker/css/admin/index_panel_buttons.scss
  app/webpacker/css/admin/index_panels.scss
  app/webpacker/css/admin/openfoodnetwork.scss
  app/webpacker/css/admin/orders.scss
  app/webpacker/css/admin/pages/enterprise_form.scss
  app/webpacker/css/admin/pages/subscription_form.scss
  app/webpacker/css/admin/pages/subscription_review.scss
  app/webpacker/css/admin/product_import.scss
  app/webpacker/css/admin/products_v3.scss
  app/webpacker/css/admin/sections/orders.scss
  app/webpacker/css/admin/shared/forms.scss
  app/webpacker/css/admin/shared/typography.scss
  app/webpacker/css/admin/sidebar-item.scss
  app/webpacker/css/admin/trix.scss
  app/webpacker/css/admin/variant_overrides.scss
  app/webpacker/css/admin/welcome.scss
  app/webpacker/css/admin_v3/all.scss
  app/webpacker/css/admin_v3/components/buttons.scss
  app/webpacker/css/admin_v3/globals/palette.scss
  app/webpacker/css/admin_v3/globals/variables.scss
  app/webpacker/css/admin_v3/shared/typography.scss
  app/webpacker/css/admin_v3/variables.scss
  app/webpacker/css/mail/all.scss
Labels: pr-no-test

#11117 [vouchers] error moving between summary and cart pages
  app/controllers/spree/orders_controller.rb
  app/controllers/voucher_adjustments_controller.rb
  app/models/spree/order/checkout.rb
  app/models/voucher.rb
  app/services/voucher_adjustments_service.rb
  engines/order_management/app/services/order_management/order/updater.rb
  spec/models/voucher_spec.rb
  spec/requests/voucher_adjustments_spec.rb
  spec/services/voucher_adjustments_service_spec.rb
  spec/system/consumer/split_checkout_spec.rb
  spec/system/consumer/split_checkout_tax_incl_spec.rb
  spec/system/consumer/split_checkout_tax_not_incl_spec.rb
Labels: priority

#11346 [Product Refactor] Remove multiple taxons
  app/models/spree/ability.rb
  app/models/spree/classification.rb
  app/models/spree/product.rb
  app/models/spree/taxon.rb
  app/serializers/api/product_serializer.rb
  app/views/admin/products_v3/_table.html.haml
  db/migrate/20230807145022_remove_product_taxons_table.rb
  db/schema.rb
  lib/reporting/reports/products_and_inventory/base.rb
  lib/spree/core/product_duplicator.rb
  spec/components/product_component_spec.rb
  spec/factories.rb
  spec/lib/reports/products_and_inventory_report_spec.rb
  spec/lib/spree/core/product_duplicator_spec.rb
  spec/models/enterprise_caching_spec.rb
  spec/models/enterprise_spec.rb
  spec/models/spree/ability_spec.rb
  spec/models/spree/classification_spec.rb
  spec/models/spree/product_spec.rb
  spec/models/spree/taxon_spec.rb
  spec/serializers/api/enterprise_shopfront_serializer_spec.rb
  spec/serializers/api/product_serializer_spec.rb
  spec/system/admin/reports_spec.rb
  spec/system/consumer/caching/darkswarm_caching_spec.rb
  spec/system/consumer/caching/shops_caching_spec.rb
  spec/system/consumer/producers_spec.rb
  spec/system/consumer/shops_spec.rb
Labels: pr-staged-au, priority

#11327 Fix display invoice tab for completed, resumed and canceled orders only
  app/models/spree/order.rb
  app/views/spree/admin/shared/_order_tabs.html.haml
  spec/system/admin/order_spec.rb
Labels: pr-staged-fr

#11372 Remove unused variant :position attribute
  app/models/spree/product.rb
  app/models/spree/variant.rb
  db/migrate/20230809172206_remove_variant_position.rb
  db/schema.rb
  spec/models/spree/product_spec.rb
  spec/models/spree/variant_spec.rb
Labels: pr-no-test

#11376 Stabilise flaky checkout spec with voucher
  spec/system/consumer/split_checkout_tax_incl_spec.rb
Labels: pr-no-test

#11374 Drop :is_master column from variants table
  app/models/spree/variant.rb
  db/migrate/20230809195519_drop_variant_is_master.rb
  db/schema.rb
Labels: pr-no-test

#11375 Drop unused tables
  db/migrate/20230809201542_drop_unused_tables.rb
  db/schema.rb
Labels: pr-no-test

#11259 Don't allow multi-line voucher codes
  app/models/voucher.rb
  app/views/admin/vouchers/new.html.haml
  spec/models/voucher_spec.rb
Labels: pr-staged-uk

#11222 Reduce controller size
  app/controllers/concerns/checkout_steps.rb
  app/controllers/split_checkout_controller.rb
  app/models/spree/order.rb
  app/services/checkout/params.rb
  app/services/checkout/validation.rb
  config/locales/en.yml
  engines/order_management/app/services/order_management/order/updater.rb
  engines/order_management/spec/services/order_management/order/updater_spec.rb
  spec/models/spree/order_spec.rb
  spec/system/consumer/split_checkout_spec.rb
Labels: pr-staged-au

#11270 Fix removing customer tag when using search bar for said tag
  app/assets/javascripts/admin/index_utils/directives/obj_for_update.js.coffee
  app/views/admin/customers/index.html.haml
  spec/system/admin/customers_spec.rb
Labels: pr-staged-uk

#10821 [Vouchers] Percentage rate
  app/controllers/admin/vouchers_controller.rb
  app/models/voucher.rb
  app/models/vouchers/flat_rate.rb
  app/models/vouchers/percentage_rate.rb
  app/services/voucher_adjustments_service.rb
  app/views/admin/vouchers/new.html.haml
  config/locales/en.yml
  db/migrate/20230508035306_add_type_to_vouchers.rb
  db/schema.rb
  spec/factories/voucher_factory.rb
  spec/models/spree/order_spec.rb
  spec/models/voucher_spec.rb
  spec/models/vouchers/flat_rate_spec.rb
  spec/models/vouchers/percentage_rate_spec.rb
  spec/requests/admin/vouchers_controller_spec.rb
  spec/requests/voucher_adjustments_spec.rb
  spec/services/voucher_adjustments_service_spec.rb
  spec/system/admin/vouchers_spec.rb
  spec/system/consumer/split_checkout_spec.rb
  spec/system/consumer/split_checkout_tax_incl_spec.rb
  spec/system/consumer/split_checkout_tax_not_incl_spec.rb
Labels: feedback-needed, priority

#11382 🔧 Remove `new_products_page` and all associated controllers/components/...
  .rubocop_todo.yml
  app/components/pagination_component.rb
  app/components/pagination_component/pagination_component.html.haml
  app/components/pagination_component/pagination_component.scss
  app/components/product_component.rb
  app/components/product_component/product_component.html.haml
  app/components/product_component/product_component.scss
  app/components/products_table_component.rb
  app/components/products_table_component/products_table_component.html.haml
  app/components/products_table_component/products_table_component.scss
  app/components/search_input_component.rb
  app/components/search_input_component/search_input_component.html.haml
  app/components/search_input_component/search_input_component.scss
  app/components/selector_component.rb
  app/components/selector_component/selector_component.html.haml
  app/components/selector_component/selector_component.scss
  app/components/selector_with_filter_component.rb
  app/components/selector_with_filter_component/selector_with_filter_component.html.haml
  app/components/selector_with_filter_component/selector_with_filter_component.scss
  app/components/table_header_component.rb
  app/components/table_header_component/table_header_component.html.haml
  app/components/table_header_component/table_header_component.scss
  app/controllers/admin/products_controller.rb
  app/reflexes/products_reflex.rb
  app/views/admin/products/index.html.haml
  app/views/spree/admin/shared/_product_sub_menu.html.haml
  app/webpacker/controllers/products_table_controller.js
  app/webpacker/css/admin/all.scss
  app/webpacker/css/admin_v3/all.scss
  config/routes/admin.rb
  lib/open_food_network/feature_toggle.rb
  spec/components/product_component_spec.rb
Labels: pr-staged-fr

#11221 [Product Refactor] Shipping Category
  app/controllers/spree/admin/products_controller.rb
  app/controllers/spree/admin/variants_controller.rb
  app/models/product_import/entry_validator.rb
  app/models/spree/product.rb
  app/models/spree/variant.rb
  app/services/order_available_shipping_methods.rb
  app/services/permitted_attributes/product.rb
  app/services/permitted_attributes/variant.rb
  app/views/spree/admin/products/_form.html.haml
  app/views/spree/admin/variants/_form.html.haml
  db/migrate/20230715143122_add_shipping_category_to_variants.rb
  db/migrate/20230715145329_migrate_shipping_category.rb
  db/schema.rb
  engines/dfc_provider/app/services/supplied_product_builder.rb
  lib/reporting/queries/joins.rb
  lib/reporting/reports/order_cycle_management/delivery.rb
  lib/reporting/reports/packing/base.rb
  lib/tasks/sample_data/product_factory.rb
  spec/controllers/api/v0/products_controller_spec.rb
  spec/controllers/api/v0/reports/packing_report_spec.rb
  spec/factories/product_factory.rb
  spec/models/product_importer_spec.rb
  spec/models/spree/order/checkout_spec.rb
  spec/models/spree/product_spec.rb
  spec/services/order_available_shipping_methods_spec.rb
  spec/system/admin/product_import_spec.rb
  spec/system/admin/products_spec.rb
Labels: priority

#11323 Use known, statically cached DFC context
  engines/dfc_provider/app/controllers/dfc_provider/supplied_products_controller.rb
  engines/dfc_provider/app/services/dfc_io.rb
  engines/dfc_provider/app/services/dfc_loader.rb
  engines/dfc_provider/spec/services/dfc_io_spec.rb
  lib/data_food_consortium/connector/connector.rb
  lib/data_food_consortium/connector/context.rb
  spec/base_spec_helper.rb
  spec/fixtures/vcr_cassettes/dfc-context.yml
  spec/lib/data_food_consortium/connector/importer_spec.rb
  swagger/dfc-v1.7/swagger.yaml
Labels: pr-no-test, funded-feature

#11407 🚧 BUU: Pagination tweaks
  app/reflexes/products_reflex.rb
  app/views/admin/products_v3/_content.html.haml
  app/views/admin/shared/v3/_pagy.html.haml
  app/webpacker/css/admin_v3/components/pagination.scss
  spec/system/admin/products_v3/products_spec.rb
Labels: pr-no-test

#11387 Admin, White Label: add translation for invalid URL in white label context
  app/models/enterprise.rb
  config/locales/en.yml
  spec/system/admin/enterprises_spec.rb
Labels: pr-staged-au

#11347 fix cancel order button
  app/views/spree/admin/shared/_order_links.html.haml
  spec/system/admin/order_spec.rb
Labels: pr-staged-au

#11352 Remove dead code related to bulk invoice printing
  app/controllers/spree/admin/invoices_controller.rb
  app/services/bulk_invoice_service.rb
  spec/controllers/spree/admin/invoices_controller_spec.rb
  spec/services/bulk_invoice_service_spec.rb
Labels: pr-staged-uk

#11295 Remove product display_as cell
  app/views/spree/admin/products/index/_products_product.html.haml
Labels: pr-staged-au

#11395 Add Google map region parameter
  .env
  app/views/shared/_google_maps_js.html.haml
Labels: pr-staged-uk

#11383 🚧 Products V3: Do not display "Producers" selector if only one is possible
  app/views/admin/products_v3/_filters.html.haml
  spec/views/admin/products_v3/_filters.html.haml_spec.rb
Labels: blocked

#11426 Allow has_and_belongs_to_many to reduce code
  .rubocop_styleguide.yml
  .rubocop_todo.yml
Labels: pr-no-test

#11391 [Vouchers] fix error when creating a percentage voucher
  .rubocop_todo.yml
  app/controllers/admin/vouchers_controller.rb
  app/views/admin/vouchers/new.html.haml
  spec/requests/admin/vouchers_spec.rb
  spec/system/admin/vouchers_spec.rb
Labels: pr-staged-uk

#11415 fix Snail when setting "0" in the unit value field
  app/models/spree/product.rb
  lib/spree/core/product_duplicator.rb
  spec/lib/spree/core/product_duplicator_spec.rb
  spec/models/spree/product_spec.rb
  spec/system/admin/products_spec.rb
Labels: pr-staged-uk

#11418 Fix Rails and Style Autocorrect Rubocop Errors
  .rubocop_todo.yml
  app/controllers/spree/admin/products_controller.rb
  app/helpers/discourse_helper.rb
  app/models/concerns/permalink_generator.rb
  app/models/enterprise.rb
  app/models/enterprise_fee.rb
  app/models/enterprise_relationship.rb
  app/models/product_import/inventory_reset_strategy.rb
  app/models/proxy_order.rb
  app/models/spree/credit_card.rb
  app/models/spree/preferences/configuration.rb
  app/models/spree/preferences/preferable.rb
  app/models/spree/product.rb
  app/models/spree/variant.rb
  app/models/spree/zone.rb
  app/models/variant_override.rb
  app/services/cap_quantity.rb
  app/services/default_country.rb
  engines/catalog/app/services/catalog/product_import/products_reset_strategy.rb
  engines/order_management/app/services/order_management/subscriptions/proxy_order_syncer.rb
  lib/tasks/data/anonymize_data.rake
  spec/base_spec_helper.rb
  spec/controllers/spree/credit_cards_controller_spec.rb
  spec/jobs/subscription_placement_job_spec.rb
  spec/models/order_balance_spec.rb
  spec/services/cap_quantity_spec.rb
  spec/support/vcr_setup.rb
  spec/system/admin/tag_rules_spec.rb
Labels: pr-staged-au

#11439 Report customers in deterministic order
  lib/reporting/reports/customers/base.rb
Labels: technical changes only

#11425 Fix Rails/ActiveRecordOverride
  .rubocop_todo.yml
  app/models/spree/product.rb
Labels: pr-no-test

#11452 [Flaky] spec/system/admin/products_v3/products_spec.rb
  spec/system/admin/products_v3/products_spec.rb
Labels: pr-no-test, technical changes only

#11453 Buu labels
  app/views/admin/products_v3/_filters.html.haml
  app/webpacker/css/admin/products_v3.scss
  app/webpacker/css/admin_v3/all.scss
  app/webpacker/css/admin_v3/shared/forms.scss
  app/webpacker/css/admin_v3/v3_overrides.scss
  spec/system/admin/products_v3/products_spec.rb
Labels: pr-no-test, feature toggled

#11348 fix Non-empty orders in the cart state do not appear in orders page
  app/models/spree/order.rb
  app/services/search_orders.rb
  app/views/spree/admin/orders/_table_row.html.haml
  spec/controllers/api/v0/orders_controller_spec.rb
  spec/system/admin/orders_spec.rb
Labels: pr-staged-uk

#11475 Uncomments pluralize test
  spec/lib/open_food_network/i18n_inflections_spec.rb
Labels: technical changes only
