Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2024-11, with the labels that each got.

#12797 Fix supplier loading on Product & inventory report
  lib/reporting/frontend_data.rb
  lib/reporting/reports/xero_invoices/base.rb
  spec/lib/reports/frontend_data_spec.rb
Labels: user facing changes

#12953 Avoid collision of test secrets
  .env.test
  spec/fixtures/vcr_cassettes/ConnectAppJob/stores_connection_data_on_the_app.yml
Labels: technical changes only

#12967 Fix Bugsnag call to notify
  app/controllers/concerns/order_completion.rb
  app/controllers/concerns/order_stock_check.rb
  app/controllers/errors_controller.rb
  app/controllers/spree/admin/products_controller.rb
  app/jobs/backorder_job.rb
  app/jobs/stock_sync_job.rb
  app/jobs/subscription_confirm_job.rb
  app/services/place_proxy_order.rb
  app/services/sets/product_set.rb
Labels: technical changes only

#12972 Add Serbian lang: tx pull -l sr fix #12971
  config/locales/sr.yml
Labels: user facing changes

#12976 Update docker readme
  docker/README.md
Labels: technical changes only

#12960 Store link to open backorder
  app/jobs/amend_backorder_job.rb
  app/jobs/backorder_job.rb
  app/jobs/complete_backorder_job.rb
  app/jobs/stock_sync_job.rb
  app/models/exchange.rb
  app/models/semantic_link.rb
  app/models/spree/order.rb
  app/models/spree/variant.rb
  app/services/fdc_backorderer.rb
  db/migrate/20241030023153_add_subject_to_semantic_links.rb
  db/migrate/20241030025540_copy_subject_on_semantic_links.rb
  db/migrate/20241030033956_change_null_on_semantic_links.rb
  db/schema.rb
  spec/fixtures/vcr_cassettes/FdcBackorderer/creates_finds_and_updates_orders.yml
  spec/jobs/backorder_job_spec.rb
  spec/jobs/complete_backorder_job_spec.rb
  spec/migrations/20241030025540_copy_subject_on_semantic_links_spec.rb
  spec/models/exchange_spec.rb
  spec/models/semantic_link_spec.rb
  spec/models/spree/order_spec.rb
  spec/services/fdc_backorderer_spec.rb
Labels: technical changes only

#12962 Scroll to top when using pagination
  app/webpacker/controllers/search_controller.js
Labels: pr-staged-uk, user facing changes

#12950 Fix rounding issues by upgrading decimal maths library
  Gemfile
  Gemfile.lock
  app/services/variant_units/option_value_namer.rb
  spec/lib/reports/sales_tax_totals_by_order_spec.rb
Labels: user facing changes

#13003 [Orders Page] - Fix Pagination not working
  app/webpacker/controllers/search_controller.js
Labels: bug-s1, user facing changes

#12964 Add cities and countries to DFC affiliate sales data endpoint
  engines/dfc_provider/app/services/affiliate_sales_data_row_builder.rb
  engines/dfc_provider/app/services/affiliate_sales_query.rb
  engines/dfc_provider/spec/services/affiliate_sales_query_spec.rb
  spec/system/admin/reports/pay_your_suppliers_spec.rb
  swagger/dfc.yaml
Labels: pr-staged-fr, api changes

#12969 [Products] Empty option on unit scale dropdown
  app/views/admin/products_v3/_variant_row.html.haml
  config/locales/en.yml
Labels: bug-s3, pr-staged-uk, user facing changes

#12963 Show alert if map cannot load
  app/assets/javascripts/darkswarm/directives/map_search.js.coffee
  config/locales/en.yml
  spec/system/consumer/map_spec.rb
Labels: pr-staged-uk, user facing changes

#12862 Anonymise customer first and last names
  lib/tasks/data/anonymize_data.rake
Labels: technical changes only

#13005 Remove failing map spec
  spec/system/consumer/map_spec.rb
Labels: technical changes only
