Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2024-10, with the labels that each got.

#12856 Place backorders for linked products via DFC integration
  app/jobs/backorder_job.rb
  app/jobs/complete_backorder_job.rb
  app/mailers/backorder_mailer.rb
  app/models/spree/order.rb
  app/models/spree/variant.rb
  app/services/current_order_locker.rb
  app/services/fdc_backorderer.rb
  app/services/fdc_offer_broker.rb
  app/services/fdc_url_builder.rb
  app/services/order_locker.rb
  app/views/backorder_mailer/backorder_failed.haml
  app/views/backorder_mailer/backorder_incomplete.haml
  config/locales/en.yml
  engines/dfc_provider/app/services/catalog_item_builder.rb
  engines/dfc_provider/app/services/dfc_request.rb
  engines/dfc_provider/app/services/offer_builder.rb
  engines/dfc_provider/app/services/order_builder.rb
  engines/dfc_provider/app/services/order_line_builder.rb
  engines/dfc_provider/app/services/sale_session_builder.rb
  engines/dfc_provider/app/services/supplied_product_builder.rb
  engines/dfc_provider/lib/dfc_provider/supplied_product.rb
  engines/dfc_provider/spec/services/dfc_request_spec.rb
  engines/dfc_provider/spec/services/order_builder_spec.rb
  engines/dfc_provider/spec/services/supplied_product_builder_spec.rb
  spec/factories/user_factory.rb
  spec/fixtures/vcr_cassettes/BackorderJob/_best_offer/finds_a_linked_offer.yml
  spec/fixtures/vcr_cassettes/BackorderJob/_place_backorder/places_an_order.yml
  spec/fixtures/vcr_cassettes/CompleteBackorderJob/_perform/completes_an_order.yml
  spec/fixtures/vcr_cassettes/CompleteBackorderJob/_perform/removes_line_items.yml
  spec/fixtures/vcr_cassettes/DFC_Product_Import/imports_from_a_FDC_catalog.yml
  spec/fixtures/vcr_cassettes/FdcBackorderer/_find_or_build_order_line/add_quantity_to_an_existing_line_item.yml
  spec/fixtures/vcr_cassettes/FdcBackorderer/creates_finds_and_updates_orders.yml
  spec/fixtures/vcr_cassettes/fdc_catalog.yml
  spec/jobs/backorder_job_spec.rb
  spec/jobs/complete_backorder_job_spec.rb
  spec/mailers/backorder_mailer_spec.rb
  spec/mailers/previews/backorder_mailer_preview.rb
  spec/models/spree/variant_spec.rb
  spec/requests/checkout/concurrency_spec.rb
  spec/services/fdc_backorderer_spec.rb
  spec/services/fdc_offer_broker_spec.rb
  spec/services/fdc_url_builder_spec.rb
  spec/system/admin/dfc_product_import_spec.rb
Labels: pr-staged-fr, user facing changes

#12881 Fix date dependent spec
  spec/controllers/spree/credit_cards_controller_spec.rb
Labels: technical changes only

#12875 Use Dockerv2
  .github/workflows/mapi.yml
  docker/README.md
  docker/build-log
  docker/build-log.ps1
  docker/cop
  docker/cop.ps1
  docker/qtest-log
  docker/run
  docker/seed
  docker/seed.ps1
  docker/server-log
  docker/server.ps1
  docker/test
  docker/test.ps1
Labels: technical changes only

#12884 Add database index to order cycle dates
  db/migrate/20241002014059_add_index_on_order_cycles_orders_open_at_and_orders_close_at.rb
  db/schema.rb
Labels: technical changes only

#12885 Remove use of unnecessary backorderable default column
  app/models/concerns/variant_stock.rb
  app/models/spree/stock_location.rb
  spec/factories/stock_location_factory.rb
  spec/models/concerns/variant_stock_spec.rb
  spec/models/spree/stock_location_spec.rb
  spec/services/sets/product_set_spec.rb
  spec/system/admin/bulk_product_update_spec.rb
  spec/system/admin/products_spec.rb
  spec/system/admin/products_v3/create_spec.rb
  spec/system/admin/unit_price_spec.rb
Labels: technical changes only

#12860 [BUU] Fix Display ordering in shopfront field to allow re-ordering of the sequence
  app/webpacker/css/admin_v3/components/select2.scss
Labels: bug-s3, pr-staged-au, user facing changes

#12887 Remove unneeded StockLocation code
  app/models/spree/ability.rb
  app/models/spree/stock/quantifier.rb
  app/models/spree/stock_location.rb
  app/models/spree/variant.rb
  app/views/spree/admin/return_authorizations/_form.html.haml
  spec/controllers/api/v0/shipments_controller_spec.rb
  spec/factories/product_factory.rb
  spec/factories/shipment_factory.rb
  spec/factories/stock_location_factory.rb
  spec/factories/variant_factory.rb
  spec/models/spree/ability_spec.rb
  spec/models/spree/stock_location_spec.rb
Labels: technical changes only

#12888 [DFC Orders] Backorder stock controlled products
  app/controllers/cart_controller.rb
  app/jobs/backorder_job.rb
  app/jobs/complete_backorder_job.rb
  app/jobs/stock_sync_job.rb
  app/mailers/backorder_mailer.rb
  spec/fixtures/vcr_cassettes/BackorderJob/_best_offer/finds_a_linked_offer.yml
  spec/fixtures/vcr_cassettes/CompleteBackorderJob/_perform/completes_an_order.yml
  spec/jobs/backorder_job_spec.rb
  spec/jobs/complete_backorder_job_spec.rb
  spec/jobs/stock_sync_job_spec.rb
  spec/mailers/backorder_mailer_spec.rb
Labels: pr-staged-uk, user facing changes

#12899 DFC Orders update for pilot 1 and 2
  app/controllers/admin/dfc_product_imports_controller.rb
  app/controllers/concerns/checkout_callbacks.rb
  app/jobs/stock_sync_job.rb
  engines/dfc_provider/app/controllers/dfc_provider/supplied_products_controller.rb
  engines/dfc_provider/app/services/image_builder.rb
  engines/dfc_provider/app/services/quantitative_value_builder.rb
  engines/dfc_provider/app/services/supplied_product_builder.rb
  engines/dfc_provider/spec/fixtures/files/product.GET.json
  engines/dfc_provider/spec/services/affiliate_sales_query_spec.rb
  engines/dfc_provider/spec/services/supplied_product_builder_spec.rb
  spec/controllers/checkout_controller_spec.rb
  spec/jobs/stock_sync_job_spec.rb
  spec/system/admin/dfc_product_import_spec.rb
Labels: pr-staged-uk, user facing changes

#12904 Bump DFC connector from 1.0.0.pre.alpha.12 to 1.0.0.pre.alpha.13
  Gemfile.lock
  swagger/dfc.yaml
Labels: technical changes only

#12906 Fail gracefully on DFC product import errors
  app/controllers/admin/dfc_product_imports_controller.rb
  engines/dfc_provider/spec/services/supplied_product_builder_spec.rb
  spec/system/admin/dfc_product_import_spec.rb
Labels: pr-staged-uk, user facing changes

#12897 [Product Preview] Fix price currency display
  app/views/admin/products_v3/product_preview.turbo_stream.haml
Labels: bug-s2, pr-staged-fr, user facing changes

#12886 [Citi OFN Voucher] Add VINE connected app
  .env
  .env.development
  .env.test
  app/controllers/admin/connected_apps_controller.rb
  app/models/connected_app.rb
  app/models/connected_apps/vine.rb
  app/services/vine_api_service.rb
  app/services/vine_jwt_service.rb
  app/views/admin/enterprises/form/connected_apps/_vine.html.haml
  app/webpacker/css/admin/connected_apps.scss
  config/application.rb
  config/initializers/filter_parameter_logging.rb
  config/locales/en.yml
  spec/fixtures/vcr_cassettes/VineApiService/_my_team/when_a_request_succeed/returns_the_response.yml
  spec/models/connected_apps/vine_spec.rb
  spec/requests/admin/connected_apps_controller_spec.rb
  spec/services/vine_api_service_spec.rb
  spec/services/vine_jwt_service_spec.rb
  spec/support/vcr_setup.rb
Labels: pr-staged-au, feature toggled

#12898 [BUU] Add missing specs
  spec/system/admin/products_v3/index_spec.rb
  spec/system/admin/products_v3/update_spec.rb
Labels: technical changes only

#12914 Remove StockLocation from ReturnAuthorization
  app/controllers/spree/admin/return_authorizations_controller.rb
  app/models/spree/return_authorization.rb
  app/views/spree/admin/return_authorizations/_form.html.haml
Labels: technical changes only

#12913 Import product's invalid weight as 1 item
  engines/dfc_provider/app/services/quantitative_value_builder.rb
  engines/dfc_provider/spec/services/quantitative_value_builder_spec.rb
  engines/dfc_provider/spec/services/supplied_product_builder_spec.rb
Labels: pr-staged-uk, user facing changes

#12932 Request offline access when connecting OIDC account
  config/initializers/devise.rb
  spec/fixtures/vcr_cassettes/DfcRequest/refreshes_the_access_token_on_fail.yml
Labels: technical changes only

#12929 Handle case of BackorderJob having no work
  app/jobs/backorder_job.rb
  spec/jobs/backorder_job_spec.rb
Labels: technical changes only

#12927 Filter reports by last 3 months by default
  app/helpers/reports_helper.rb
  app/views/admin/reports/_date_range_form.html.haml
  app/views/admin/reports/filters/_packing.html.haml
  spec/support/features/datepicker_helper.rb
  spec/system/admin/order_cycles/edit_spec.rb
  spec/system/admin/order_cycles/list_spec.rb
  spec/system/admin/reports/customers_report_spec.rb
  spec/system/admin/reports_spec.rb
Labels: bug-s2, no-staging-AU, user facing changes

#12912 Remove the admin_style_v3 toggle from Production and Staging environments
  config/routes/spree.rb
  lib/open_food_network/feature_toggle.rb
  spec/system/admin/bulk_product_update_spec.rb
Labels: feature toggled

#12934 Use the correct spanish translation
  spec/system/admin/unit_price_spec.rb
Labels: user facing changes

#12935 Make DFC API docs deterministic
  engines/dfc_provider/spec/requests/affiliate_sales_data_spec.rb
  swagger/dfc.yaml
Labels: technical changes only

#12940 Bug 12939
  app/services/variant_units/option_value_namer.rb
  spec/services/variant_units/option_value_namer_spec.rb
Labels: bug-s1

#12938 Spec restock after order cancellation
  spec/models/spree/order_spec.rb
Labels: technical changes only

#12921 Add Bugsnag notification if we reach tax rate refund code
  app/models/spree/tax_rate.rb
  spec/models/spree/tax_rate_spec.rb
Labels: technical changes only

#12947 Add scripts to save and restore baseline data
  script/buildkite-archive/check_github_status.sh
  script/buildkite-archive/includes.sh
  script/buildkite-archive/merge_branch_to_master.sh
  script/buildkite-archive/merge_master_into_branch.sh
  script/buildkite-archive/push_to_production.sh
  script/buildkite-archive/push_to_staging.sh
  script/buildkite-archive/save_staging_baseline.sh
  script/ci/restore-staging-baseline.sh
  script/ci/save-staging-baseline.sh
Labels: technical changes only

#12943 Sanitise HTML attributes in the database
  app/models/custom_tab.rb
  app/models/enterprise_group.rb
  app/models/spree/product.rb
  db/migrate/20241023054951_sanitize_html_attributes.rb
  db/schema.rb
  spec/migrations/20241023054951_sanitize_html_attributes_spec.rb
  spec/models/custom_tab_spec.rb
  spec/models/enterprise_group_spec.rb
  spec/models/spree/product_spec.rb
Labels: pr-staged-fr, technical changes only

#12917 Ignores name column on customer model
  app/models/customer.rb
  spec/migrations/split_customer_names_spec.rb
Labels: pr-staged-au
