Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2024-02, with the labels that each got.

#12100 Remove background_reports feature toggle
  app/controllers/admin/reports_controller.rb
  app/views/admin/reports/show.html.haml
  lib/open_food_network/feature_toggle.rb
Labels: technical changes only

#12107 [BUU] Style and behaviour updates
  app/components/vertical_ellipsis_menu/component.scss
  app/views/admin/products_v3/_table.html.haml
  app/webpacker/controllers/popout_controller.js
  app/webpacker/css/admin/products_v3.scss
  app/webpacker/css/admin_v3/globals/variables.scss
  app/webpacker/css/admin_v3/shared/forms.scss
  spec/javascripts/stimulus/popout_controller_test.js
  spec/system/admin/products_v3/products_spec.rb
Labels: feature toggled

#12131 Fix gem dependency declaration
  Gemfile
  Gemfile.lock
Labels: technical changes only

#12135 Removes UnionPay (debit) from non-3DS card list
  spec/fixtures/vcr_cassettes/Stripe-v10.6.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_invalid/invalid_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Exceeding_velocity_limit_decline/raises_Stripe_error_with_payment_intent_last_payment_error_as_message.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.6.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_invalid/invalid_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Expired_card_decline/raises_Stripe_error_with_payment_intent_last_payment_error_as_message.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.6.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_invalid/invalid_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Generic_decline/raises_Stripe_error_with_payment_intent_last_payment_error_as_message.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.6.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_invalid/invalid_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Incorrect_CVC_decline/raises_Stripe_error_with_payment_intent_last_payment_error_as_message.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.6.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_invalid/invalid_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Insufficient_funds_decline/raises_Stripe_error_with_payment_intent_last_payment_error_as_message.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.6.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_invalid/invalid_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Lost_card_decline/raises_Stripe_error_with_payment_intent_last_payment_error_as_message.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.6.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_invalid/invalid_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Processing_error_decline/raises_Stripe_error_with_payment_intent_last_payment_error_as_message.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.6.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_invalid/invalid_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Stolen_card_decline/raises_Stripe_error_with_payment_intent_last_payment_error_as_message.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.6.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_American_Express/captures_the_payment.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.6.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_American_Express/returns_payment_intent_id_and_does_not_raise.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.6.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_BCcard_and_DinaCard/captures_the_payment.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.6.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_BCcard_and_DinaCard/returns_payment_intent_id_and_does_not_raise.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.6.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Diners_Club/captures_the_payment.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.6.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Diners_Club/returns_payment_intent_id_and_does_not_raise.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.6.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Diners_Club_14-digit_card_/captures_the_payment.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.6.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Diners_Club_14-digit_card_/returns_payment_intent_id_and_does_not_raise.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.6.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Discover/captures_the_payment.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.6.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Discover/returns_payment_intent_id_and_does_not_raise.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.6.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Discover_debit_/captures_the_payment.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.6.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Discover_debit_/returns_payment_intent_id_and_does_not_raise.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.6.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_JCB/captures_the_payment.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.6.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_JCB/returns_payment_intent_id_and_does_not_raise.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.6.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Mastercard/captures_the_payment.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.6.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Mastercard/returns_payment_intent_id_and_does_not_raise.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.6.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Mastercard_2-series_/captures_the_payment.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.6.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Mastercard_2-series_/returns_payment_intent_id_and_does_not_raise.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.6.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Mastercard_debit_/captures_the_payment.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.6.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Mastercard_debit_/returns_payment_intent_id_and_does_not_raise.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.6.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Mastercard_prepaid_/captures_the_payment.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.6.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Mastercard_prepaid_/returns_payment_intent_id_and_does_not_raise.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.6.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_UnionPay/captures_the_payment.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.6.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_UnionPay/returns_payment_intent_id_and_does_not_raise.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.6.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_UnionPay_19-digit_card_/captures_the_payment.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.6.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_UnionPay_19-digit_card_/returns_payment_intent_id_and_does_not_raise.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.6.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_UnionPay_debit_/captures_the_payment.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.6.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_UnionPay_debit_/returns_payment_intent_id_and_does_not_raise.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.6.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Visa/captures_the_payment.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.6.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Visa/returns_payment_intent_id_and_does_not_raise.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.6.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Visa_debit_/captures_the_payment.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.6.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Visa_debit_/returns_payment_intent_id_and_does_not_raise.yml
  spec/lib/stripe/payment_intent_validator_spec.rb
Labels: technical changes only

#12127 Corrects setup for setup in credit card cloner spec
  spec/fixtures/vcr_cassettes/Stripe-v10.6.0/Stripe_CreditCardCloner/_find_or_clone/when_called_with_a_card_without_a_customer_one_time_usage_card_/clones_the_payment_method_only.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.6.0/Stripe_CreditCardCloner/_find_or_clone/when_called_with_a_valid_customer_and_payment_method/clones_both_the_payment_method_and_the_customer.yml
  spec/lib/stripe/credit_card_cloner_spec.rb
Labels: technical changes only

#12128 Remove update script, use bin/setup instead
  bin/update
Labels: technical changes only

#12112 Fix Customer Search Autofill Issue
  app/webpacker/controllers/mixins/useSearchCustomer.js
  app/webpacker/controllers/select_customer_controller.js
Labels: pr-staged-uk, user facing changes

#12130 [BUU] Image modal styles
  app/components/confirm_modal_component/confirm_modal_component.scss
  app/components/modal_component.rb
  app/components/modal_component/modal_component.html.haml
  app/components/modal_component/modal_component.scss
  app/views/admin/products_v3/_edit_image.html.haml
  app/webpacker/css/admin/all.scss
  app/webpacker/css/admin/modals.scss
  app/webpacker/css/admin_v3/all.scss
  app/webpacker/css/darkswarm/all.scss
  spec/system/admin/products_v3/products_spec.rb
Labels: feature toggled

#12132 Fix capturing order payment ignore order changes
  engines/order_management/app/services/order_management/order/updater.rb
  engines/order_management/spec/services/order_management/order/updater_spec.rb
  spec/jobs/subscription_confirm_job_spec.rb
Labels: pr-staged-au

#12116 Make sure fees are applied when adding the first item to a back office order
  app/controllers/api/v0/shipments_controller.rb
  spec/controllers/api/v0/shipments_controller_spec.rb
Labels: pr-staged-au

#12126 Replace remote_toggle with method inside generic controller
  app/views/admin/order_cycles/_advanced_settings.html.haml
  app/views/admin/order_cycles/_order_cycle_top_buttons.html.haml
  app/webpacker/controllers/remote_toggle_controller.js
  app/webpacker/controllers/toggle_control_controller.js
  spec/javascripts/stimulus/remote_toggle_controller_test.js
  spec/javascripts/stimulus/toggle_control_controller_test.js
Labels: pr-staged-au

#12152 (Semi-)automatically commit new Stripe recordings
  script/test-stripe-live
Labels: technical changes only

#12159 Reduce Capybara wait time during development
  spec/system/support/capybara_setup.rb
Labels: technical changes only

#12162 Improve error message by not displaying the first part of the second …
  app/views/admin/products_v3/_table.html.haml
  spec/system/admin/products_v3/products_spec.rb
Labels: pr-staged-fr, feature toggled

#12103 Modify default hash tabs controller to redirect users to shopping panel when an OC is selected.
  app/helpers/shop_helper.rb
  app/views/shopping_shared/_tabs.html.haml
  app/webpacker/controllers/tabs_and_panels_controller.js
  spec/system/consumer/shopping/shopping_spec.rb
Labels: pr-staged-au

#12174 Simplify user factory around admin role
  spec/controllers/api/v0/reports_controller_spec.rb
  spec/factories/user_factory.rb
Labels: technical changes only

#12175 Add rubocop binstub for spring support
  Gemfile
  Gemfile.lock
  bin/rubocop
  bin/spring
Labels: technical changes only

#12204 Disable RSpec cops by default
  .rubocop.yml
  .rubocop_rspec_styleguide.yml
  .rubocop_styleguide.yml
  .rubocop_todo.yml
  app/models/spree/payment.rb
  spec/lib/spree/localized_number_spec.rb
  spec/system/admin/tag_rules_spec.rb
Labels: pr-no-test, technical changes only

#12210 on redirect, the body will no longer include the target link
  spec/controllers/user_confirmations_controller_spec.rb
Labels: technical changes only
