Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2024-06, with the labels that each got.

#12507 Allow only enterprise managers to connect apps
  app/helpers/admin/enterprises_helper.rb
  app/views/admin/enterprises/form/_connected_apps.html.haml
  config/locales/en.yml
  spec/system/admin/enterprises/connected_apps_spec.rb
Labels: feature toggled

#12519 Extracts BUU from branch in #11645
  spec/system/admin/products_v3/products_spec.rb
Labels: technical changes only

#12535 Restore enterprise edit form as manager
  app/jobs/connect_app_job.rb
  app/views/admin/enterprises/_form.html.haml
  app/views/admin/enterprises/_ng_form.html.haml
  app/views/admin/enterprises/edit.html.haml
  app/views/admin/enterprises/form/_connected_apps.html.haml
Labels: bug-s2, user facing changes

#12521 [BUU] Fix for blank dropdowns
  app/webpacker/controllers/bulk_form_controller.js
  spec/javascripts/stimulus/bulk_form_controller_test.js
Labels: pr-staged-au, feature toggled

#12511 Task/12398 remove reflex from product variant delete
  app/controllers/admin/products_v3_controller.rb
  app/models/spree/ability.rb
  app/reflexes/products_reflex.rb
  app/views/admin/products_v3/_delete_modal.html.haml
  app/views/admin/products_v3/_product_row.html.haml
  app/views/admin/products_v3/_table.html.haml
  app/views/admin/products_v3/_variant_row.html.haml
  app/views/admin/products_v3/destroy_product_variant.turbo_stream.haml
  app/webpacker/controllers/products_controller.js
  app/webpacker/css/admin/products_v3.scss
  config/routes/admin.rb
  spec/reflexes/products_reflex_spec.rb
  spec/system/admin/products_v3/products_spec.rb
Labels: pr-staged-fr, technical changes only

#12518 Sanitise HTML in product description [read-only]
  app/models/spree/product.rb
  app/services/html_sanitizer.rb
  spec/models/spree/product_spec.rb
  spec/services/html_sanitizer_spec.rb
Labels: pr-staged-fr, user facing changes

#12515 Do not commit to db unchanged products in bulk save
  app/models/spree/price.rb
  app/models/spree/variant.rb
  app/services/sets/product_set.rb
  spec/models/spree/variant_spec.rb
  spec/services/sets/product_set_spec.rb
Labels: technical changes only

#12427 Display additional tax total in order - fixes #11680
  app/helpers/admin/orders_helper.rb
  config/locales/en.yml
  spec/factories.rb
  spec/factories/calculator_factory.rb
  spec/helpers/admin/orders_helper_spec.rb
Labels: pr-staged-fr, user facing changes

#12094 Force start date before end date with range mode flatpickr
  app/views/admin/reports/_date_range_form.html.haml
  spec/system/admin/reports/orders_and_fulfillment_spec.rb
Labels: pr-staged-fr, user facing changes

#12548 Fix RedundantPresenceValidationOnBelongs on Spree::Order model
  .rubocop_todo.yml
  app/models/spree/order.rb
Labels: technical changes only

#12547 Fix cops StringConcatenation
  .rubocop_todo.yml
  app/controllers/admin/stripe_connect_settings_controller.rb
  app/helpers/enterprises_helper.rb
  app/helpers/spree/admin/base_helper.rb
  app/mailers/spree/user_mailer.rb
  app/models/enterprise.rb
  app/models/spree/credit_card.rb
  app/models/spree/payment_method.rb
  app/serializers/api/cached_enterprise_serializer.rb
  app/serializers/api/enterprise_shopfront_list_serializer.rb
  app/services/embedded_page_service.rb
  app/services/products_renderer.rb
  lib/spree/api/controller_setup.rb
  lib/spree/core/environment_extension.rb
  spec/models/spree/line_item_spec.rb
  spec/models/spree/product_spec.rb
  spec/services/embedded_page_service_spec.rb
  spec/support/features/datepicker_helper.rb
  spec/system/admin/products_spec.rb
Labels: technical changes only

#12458 notify the user if any order cannot be invoiced on bulk invoice sending
  app/reflexes/admin/orders_reflex.rb
  spec/system/admin/orders/bulk_actions_spec.rb
Labels: pr-staged-fr, feature toggled

#12525 Add compatibility to the DFC product import for FDC (Shopify) API
  app/controllers/admin/dfc_product_imports_controller.rb
  engines/dfc_provider/app/services/dfc_request.rb
  engines/dfc_provider/app/services/fdc_request.rb
  engines/dfc_provider/app/services/quantitative_value_builder.rb
  engines/dfc_provider/spec/services/dfc_request_spec.rb
  engines/dfc_provider/spec/services/fdc_request_spec.rb
  engines/dfc_provider/spec/services/quantitative_value_builder_spec.rb
  spec/fixtures/vcr_cassettes/DFC_Product_Import/imports_from_a_FDC_catalog.yml
  spec/fixtures/vcr_cassettes/FdcRequest/refreshes_the_access_token_and_retrieves_a_catalog.yml
  spec/support/vcr_setup.rb
  spec/system/admin/dfc_product_import_spec.rb
Labels: feedback-needed, technical changes only

#12536 Allow negative stock levels for on-demand products
  app/models/concerns/variant_stock.rb
  app/models/variant_override.rb
  lib/open_food_network/scope_variant_to_hub.rb
  spec/lib/open_food_network/scope_variant_to_hub_spec.rb
  spec/models/spree/line_item_spec.rb
  spec/system/consumer/shopping/variant_overrides_spec.rb
Labels: technical changes only

#12538 Update and Recalculate Fees after Order Adjusted in Backoffice
  app/models/spree/payment.rb
  app/views/spree/admin/orders/_form/_adjustments.html.haml
  spec/system/admin/order_spec.rb
Labels: user facing changes

#12557 Updating specs for BUU (feature parity)
  spec/system/admin/authentication_spec.rb
  spec/system/admin/products_spec.rb
  spec/system/admin/products_v3/products_spec.rb
Labels: technical changes only

#12558 BUU Display error messages when file not valid
  app/controllers/spree/admin/images_controller.rb
  app/views/spree/admin/images/edit.turbo_stream.haml
  public/invalid_image.jpg
  spec/requests/admin/images_spec.rb
  spec/system/admin/products_v3/products_spec.rb
Labels: pr-staged-fr, feature toggled

#12546 [BUU] Change product columns to be shown
  app/assets/javascripts/admin/index_utils/services/columns.js.coffee
  app/assets/javascripts/templates/admin/columns_dropdown.html.haml
  app/components/multiple_checked_select_component/multiple_checked_select_component.html.haml
  app/controllers/admin/column_preferences_controller.rb
  app/views/admin/column_preferences/_form.html.haml
  app/views/admin/column_preferences/bulk_update.turbo_stream.haml
  app/views/admin/products_v3/_product_row.html.haml
  app/views/admin/products_v3/_sort.html.haml
  app/views/admin/products_v3/_table.html.haml
  app/views/admin/products_v3/_variant_row.html.haml
  app/views/spree/admin/shared/_stimulus_sortable_header.html.haml
  app/webpacker/controllers/column_preferences_controller.js
  app/webpacker/controllers/dropdown_controller.js
  app/webpacker/css/admin/components/input.scss
  app/webpacker/css/admin/products_v3.scss
  app/webpacker/css/admin_v3/components/dropdown.scss
  config/locales/en.yml
  config/routes/admin.rb
  lib/open_food_network/column_preference_defaults.rb
  spec/controllers/admin/column_preferences_controller_spec.rb
  spec/support/request/admin_helper.rb
  spec/system/admin/products_v3/products_spec.rb
Labels: feedback-needed, feature toggled

#12575 Solve Rubocop RedundantInterpolation cops
  .rubocop_todo.yml
  lib/tasks/karma.rake
  spec/base_spec_helper.rb
Labels: technical changes only

#12582 Fixes offenses raised by Rails/UnusedRenderContent
  .rubocop_todo.yml
  app/controllers/admin/bulk_line_items_controller.rb
  app/controllers/admin/tag_rules_controller.rb
  app/controllers/api/v0/enterprise_fees_controller.rb
  app/controllers/api/v0/products_controller.rb
  app/controllers/api/v0/taxons_controller.rb
  app/controllers/api/v0/variants_controller.rb
Labels: technical changes only

#12583 Add translation key for Spree::Image#attachment
  config/locales/en.yml
Labels: technical changes only

#12554 Add enterprise logo and contact name to DFC API with standard attributes
  engines/dfc_provider/app/controllers/dfc_provider/enterprises_controller.rb
  engines/dfc_provider/app/services/enterprise_builder.rb
  swagger/dfc.yaml
Labels: api changes

#12581 Cache yarn global package data in CI
  .github/workflows/build.yml
Labels: technical changes only

#12590 Update message logged when a product is deleted
  app/controllers/admin/products_v3_controller.rb
  app/models/concerns/log_destroy_performer.rb
Labels: technical changes only

#12584 Update spec for quotation mark replacement
  spec/mailers/subscription_mailer_spec.rb
Labels: technical changes only

#12577 Update button should change status on modified white label
  app/helpers/admin/enterprises_helper.rb
  spec/helpers/admin/enterprises_helper_spec.rb
  spec/system/admin/enterprise_roles_spec.rb
  spec/system/admin/enterprises_spec.rb
Labels: pr-staged-au

#12567 Error messages don't block bottom of page clicks
  app/webpacker/css/admin_v3/components/messages.scss
Labels: pr-staged-au, feature toggled

#12542 Sanitize HTML in custom tab content [read only]
  app/models/custom_tab.rb
  spec/models/custom_tab_spec.rb
Labels: feedback-needed, user facing changes

#12571 Adds test case to assure acceptance criteria from #12374 and #12373
  spec/system/admin/orders/bulk_actions_spec.rb
Labels: technical changes only

#12585 Ensure all assets are compiled on test page visit
  spec/system/consumer/caching/shops_caching_spec.rb
Labels: technical changes only

#12593 Adds regression spec for #12591
  spec/system/admin/products_spec.rb
Labels: technical changes only

#12605 [Invoices] Notify if any order cannot be invoiced on bulk invoice printing (update the behavior only when invoice flag enabled )
  app/reflexes/admin/orders_reflex.rb
  spec/system/admin/orders/bulk_actions_spec.rb
Labels: technical changes only

#12606 [BUU] Enable admin_style_v3 for new users from 3/07/2024
  config/initializers/flipper.rb
  db/migrate/20240625024328_activate_admin_style_v3_for_new_users.rb
  db/schema.rb
  spec/migrations/20240625024328_activate_admin_style_v3_for_new_users_spec.rb
Labels: user facing changes

#12616 Add Auto Author Assign Workflow for Pull Requests
  .github/workflows/auto-author-assign.yml
Labels: technical changes only

#12618 [BUU] Add translation for "Products V3" page title
  config/locales/en.yml
Labels: feature toggled

#12592 Load large on-screen reports on demand
  app/jobs/report_job.rb
  app/views/admin/reports/_display.html.haml
  config/locales/en.yml
  spec/system/admin/reports_spec.rb
Labels: prod-test, user facing changes

#12619 [Reports] Disable GO button once clicked
  app/controllers/admin/reports_controller.rb
  app/jobs/report_job.rb
  app/views/admin/reports/show.html.haml
  spec/support/reports_helper.rb
Labels: pr-staged-au, user facing changes
