Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2024-07, with the labels that each got.

#12630 Remove unused spec code
  spec/system/admin/enterprises_spec.rb
Labels: technical changes only

#11645 [BUU] Activate admin_style_v3 for most system specs
  config/locales/en.yml
  spec/base_spec_helper.rb
  spec/migrations/20240625024328_activate_admin_style_v3_for_new_users_spec.rb
  spec/support/features/datepicker_helper.rb
  spec/support/overlapping_elements_helper.rb
  spec/support/tom_select_helper.rb
  spec/system/admin/authentication_spec.rb
  spec/system/admin/bulk_order_cancellation_spec.rb
  spec/system/admin/bulk_order_management_spec.rb
  spec/system/admin/bulk_product_update_spec.rb
  spec/system/admin/configuration/general_settings_spec.rb
  spec/system/admin/customers_spec.rb
  spec/system/admin/enterprise_roles_spec.rb
  spec/system/admin/enterprises_spec.rb
  spec/system/admin/flatpickr_spec.rb
  spec/system/admin/order_cycles/complex_editing_multiple_product_pages_spec.rb
  spec/system/admin/order_cycles/complex_editing_multiple_updation_spec.rb
  spec/system/admin/order_cycles/complex_editing_spec.rb
  spec/system/admin/order_cycles/list_spec.rb
  spec/system/admin/order_cycles/simple_spec.rb
  spec/system/admin/order_spec.rb
  spec/system/admin/orders/bulk_actions_spec.rb
  spec/system/admin/orders/invoices_spec.rb
  spec/system/admin/orders_spec.rb
  spec/system/admin/overview_spec.rb
  spec/system/admin/product_import_spec.rb
  spec/system/admin/products_spec.rb
  spec/system/admin/products_v3/products_spec.rb
  spec/system/admin/reports/enterprise_summary_fees/enterprise_summary_fee_with_tax_report_by_order_spec.rb
  spec/system/admin/reports/enterprise_summary_fees/enterprise_summary_fee_with_tax_report_by_producer_spec.rb
  spec/system/admin/reports/orders_and_fulfillment_spec.rb
  spec/system/admin/reports/packing_report_spec.rb
  spec/system/admin/reports/payments_report_spec.rb
  spec/system/admin/reports/revenues_by_hub_spec.rb
  spec/system/admin/reports/sales_tax/sales_tax_totals_by_order_spec.rb
  spec/system/admin/reports/sales_tax/sales_tax_totals_by_producer_spec.rb
  spec/system/admin/reports/users_and_enterprises_spec.rb
  spec/system/admin/reports_spec.rb
  spec/system/admin/schedules_spec.rb
  spec/system/admin/subscriptions/crud_spec.rb
  spec/system/admin/subscriptions/smoke_tests_spec.rb
  spec/system/admin/variant_overrides_spec.rb
Labels: technical changes only

#12595 [BUU] Refactors products_v3 system specs
  spec/base_spec_helper.rb
  spec/support/products_helper.rb
  spec/system/admin/products_v3/index_spec.rb
  spec/system/admin/products_v3/products_spec.rb
  spec/system/admin/products_v3/update_spec.rb
Labels: technical changes only

#12594 Hide customer data on orders_and_distributors report
  lib/reporting/reports/orders_and_distributors/base.rb
  spec/lib/reports/orders_and_distributors_report_spec.rb
Labels: bug-s2, feedback-needed, user facing changes

#12640 Poll to check when invoice file finished
  app/controllers/spree/admin/invoices_controller.rb
  app/reflexes/admin/orders_reflex.rb
  app/views/spree/admin/orders/bulk/_invoice_link.html.haml
  app/views/spree/admin/orders/bulk/_invoice_modal.html.haml
  app/webpacker/controllers/file_loading_controller.js
  spec/system/admin/orders/bulk_actions_spec.rb
Labels: bug-s2, pr-staged-au, user facing changes

#12641 Fixes Rails/SelectMap offense
  .rubocop_todo.yml
  app/models/enterprise.rb
Labels: technical changes only

#12644 Fix orders and distributors report after product refactor
  lib/reporting/reports/orders_and_distributors/base.rb
  spec/lib/reports/orders_and_distributors_report_spec.rb
Labels: user facing changes

#12634 Fix Voucher Code Field Focus Issue
  app/webpacker/controllers/toggle_control_controller.js
  spec/javascripts/stimulus/toggle_control_controller_test.js
Labels: bug-s2, user facing changes

#12635 (Fix) Product description not correctly truncated
  app/webpacker/css/darkswarm/_shop-product-rows.scss
Labels: pr-staged-au, user facing changes

#12639 Redirect successful user signup request to main home page [OFN-11597]
  app/controllers/spree/users_controller.rb
Labels: pr-staged-au, user facing changes

#12647 Fixes Rails/SkipsModelValidations offenses
  .rubocop_todo.yml
  app/models/concerns/line_item_stock_changes.rb
  app/models/spree/line_item.rb
  app/models/variant_override.rb
  spec/models/spree/line_item_spec.rb
Labels: technical changes only

#12657 [BUU] Activate admin_style_v3 for all super admins
  db/migrate/20240710013128_enable_feature_admin_style_v3_for_admins.rb
  db/schema.rb
Labels: feature toggled

#12652 [BUU] Prepares specs for enabling admin_style_v3 by default
  spec/support/overlapping_elements_helper.rb
  spec/system/admin/enterprise_roles_spec.rb
  spec/system/admin/order_cycles/complex_editing_multiple_updation_spec.rb
  spec/system/admin/order_cycles/complex_editing_spec.rb
  spec/system/admin/order_cycles/list_spec.rb
  spec/system/admin/order_cycles/simple_spec.rb
  spec/system/admin/order_spec.rb
  spec/system/admin/product_import_spec.rb
  spec/system/admin/products_spec.rb
  spec/system/admin/products_v3/actions_spec.rb
  spec/system/admin/subscriptions/smoke_tests_spec.rb
Labels: technical changes only

#12649 Use application tmp dir for product import
  app/controllers/admin/product_import_controller.rb
  app/models/product_import/product_importer.rb
  spec/controllers/admin/product_import_controller_spec.rb
Labels: pr-staged-au, technical changes only

#12662 Improve spec for Spree::Order#finalize!
  spec/models/spree/order_spec.rb
Labels: technical changes only

#12680 [inventory] Fix product sorting
  app/queries/product_scope_query.rb
  spec/queries/product_scope_query_spec.rb
Labels: bug-s3, pr-staged-fr, user facing changes

#12663 Replace product by variant to see producer name on views
  app/views/admin/variant_overrides/_hidden_products.html.haml
  app/views/admin/variant_overrides/_new_products.html.haml
  spec/system/admin/variant_overrides_spec.rb
Labels: pr-staged-fr, user facing changes

#12675 Changed a single line in turbo to insert cloned products after the original product
  app/views/admin/products_v3/clone.turbo_stream.haml
Labels: pr-staged-au, feature toggled

#12683 [BUU] Handle corrupt data and troubleshooting
  app/services/weights_and_measures.rb
  spec/services/weights_and_measures_spec.rb
Labels: bug-s2, pr-staged-fr, prod-test, user facing changes

#12602 12570 - Fix Variant Unit field is Out of Sync with the Pop-out
  app/helpers/admin/products_helper.rb
  app/views/admin/products_v3/_product_variant_row.html.haml
  app/views/admin/products_v3/_variant_row.html.haml
  spec/system/admin/products_v3/create_spec.rb
  spec/system/admin/products_v3/update_spec.rb
Labels: pr-staged-au

#12668 Prepare product_import_spec.rb for BUU as default
  db/migrate/20240715103415_enable_admin_style_v3_by_default.rb
  db/schema.rb
  lib/open_food_network/feature_toggle.rb
  spec/base_spec_helper.rb
  spec/system/admin/product_import_spec.rb
  spec/system/admin/products_spec.rb
  spec/system/admin/products_v3/actions_spec.rb
  spec/system/admin/products_v3/create_spec.rb
  spec/system/admin/products_v3/index_spec.rb
  spec/system/admin/products_v3/update_spec.rb
  spec/system/admin/subscriptions/smoke_tests_spec.rb
Labels: technical changes only

#12686 Activates admin_style_v3 for 25 per cent users
  db/migrate/20240718150852_activate_admin_style_v3_for_25_p_cent_users.rb
  db/schema.rb
Labels: feature toggled

#12684 Fix flaky spec
  spec/system/admin/products_v3/index_spec.rb
Labels: technical changes only

#12694 Revert product description truncation fix
  app/webpacker/css/darkswarm/_shop-product-rows.scss
Labels: bug-s2, pr-staged-fr, user facing changes

#12700 [BUU] fix error 500 on hungary instance
  app/models/spree/product.rb
Labels: feature toggled

#12678 Fix URL State management on the Products page
  app/views/admin/products_v3/_filters.html.haml
  app/views/admin/products_v3/_sort.html.haml
  app/views/spree/admin/shared/_head.html.haml
Labels: bug-s3, user facing changes

#12654 Use public contact email at the bottom of order confirmation email [OFN-12509]
  app/helpers/mailer_helper.rb
  app/views/spree/order_mailer/_signoff.html.haml
Labels: user facing changes

#12655 (Fix) [User->New] Language is displayed twice [OFN-11513]
  app/helpers/i18n_helper.rb
Labels: pr-staged-au, user facing changes

#12664 Remove SR from clear search button [OFN-12551]
  app/reflexes/products_reflex.rb
  app/views/admin/products_v3/_no_products.html.haml
  spec/system/admin/products_v3/index_spec.rb
Labels: technical changes only

#12691 Use vertical transitions for cloning and deleting products
  app/webpacker/css/admin/products_v3.scss
Labels: pr-staged-au

#12676 Add "Affiliate Sales Data" connected app option
  app/controllers/admin/connected_apps_controller.rb
  app/jobs/connect_app_job.rb
  app/models/connected_app.rb
  app/models/connected_apps/affiliate_sales_data.rb
  app/models/spree/user.rb
  app/views/admin/enterprises/form/_connected_apps.html.haml
  app/views/admin/enterprises/form/connected_apps/_affiliate_sales_data.html.haml
  app/views/admin/enterprises/form/connected_apps/_discover_regen.html.haml
  app/webpacker/css/admin/connected_apps.scss
  config/locales/en.yml
  db/migrate/20240715072649_add_type_to_connected_apps.rb
  db/schema.rb
  lib/tasks/enterprises.rake
  spec/fixtures/vcr_cassettes/Connected_Apps/Discover_Regenerative/can_be_enabled_and_disabled.yml
  spec/lib/tasks/enterprises_rake_spec.rb
  spec/models/spree/user_spec.rb
  spec/system/admin/enterprises/connected_apps_spec.rb
Labels: pr-staged-fr, feature toggled

#12690 Require variant category and supplier when creating new product variants [OFN-12666]
  app/assets/javascripts/admin/bulk_product_update.js.coffee
  app/models/spree/variant.rb
  app/views/admin/products_v3/_variant_row.html.haml
  config/locales/en.yml
  spec/javascripts/unit/admin/bulk_product_update_spec.js.coffee
  spec/services/sets/product_set_spec.rb
  spec/system/admin/products_v3/actions_spec.rb
  spec/system/admin/products_v3/create_spec.rb
  spec/system/admin/products_v3/update_spec.rb
Labels: pr-staged-au, user facing changes

#12719 [BUU] Activate admin_style_v3 for ~50% of users
  db/migrate/20240731065321_activate_admin_style_v3_for50_pc_users.rb
  db/schema.rb
Labels: user facing changes
