Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2024-08, with the labels that each got.

#12715 Add request_id to logs for production and staging
  config/environments/production.rb
  config/environments/staging.rb
Labels: pr-staged-au, technical changes only

#12563 Display only per_item fees for oc incoming exchange #11326
  app/assets/javascripts/admin/order_cycles/controllers/edit.js.coffee
  app/assets/javascripts/admin/order_cycles/controllers/incoming_controller.js.coffee
  app/assets/javascripts/admin/order_cycles/services/enterprise_fee.js.coffee
  app/controllers/admin/enterprise_fees_controller.rb
  spec/controllers/admin/enterprise_fees_controller_spec.rb
  spec/javascripts/unit/admin/order_cycles/controllers/incoming_controller_spec.js.coffee
  spec/system/admin/order_cycles/simple_spec.rb
Labels: bug-s3, feedback-needed

#12728 Fix flaky spec with fixed order of products
  spec/system/admin/order_cycles/complex_editing_multiple_product_pages_spec.rb
Labels: technical changes only

#12711 Make Item column wider and tax and quantity columns narrower in invoice PDF
  app/views/spree/admin/orders/_invoice_table4.html.haml
  spec/system/admin/invoice_print_spec.rb
Labels: user facing changes

#12723 Preload enterprise logos and promo images for /shops page
  app/services/shops_list_service.rb
  spec/services/shops_list_service_spec.rb
Labels: technical changes only

#12671 Ensure product category error message is shown when creating new product [OFN-12591]
  .rubocop_todo.yml
  app/models/product_import/entry_processor.rb
  app/models/product_import/entry_validator.rb
  app/models/spree/product.rb
  app/views/spree/admin/products/new.html.haml
  config/locales/en.yml
  engines/dfc_provider/app/services/supplied_product_builder.rb
  engines/dfc_provider/spec/services/supplied_product_builder_spec.rb
  spec/controllers/api/v0/products_controller_spec.rb
  spec/controllers/spree/admin/products_controller_spec.rb
  spec/system/admin/products_spec.rb
Labels: pr-staged-au, user facing changes

#12725 (Fix) chore(deps): bump invisible_captcha from 2.2.0 to 2.3.0
  Gemfile.lock
  spec/base_spec_helper.rb
Labels: pr-staged-au, dependencies

#12738 Stabilise spec by not relying on record ids
  spec/system/admin/order_cycles/complex_editing_multiple_product_pages_spec.rb
Labels: technical changes only

#12747 Stabilise flaky spec with unique taxons
  engines/dfc_provider/spec/services/supplied_product_builder_spec.rb
Labels: technical changes only

#12710 [BUU] Fixes Products Page ActionView::Template::Error
  app/helpers/admin/products_helper.rb
  app/views/admin/products_v3/_variant_row.html.haml
  spec/helpers/admin/products_helper_spec.rb
  spec/system/admin/products_v3/create_spec.rb
  spec/system/admin/products_v3/update_spec.rb
Labels: bug-s3, pr-staged-fr, feature toggled

#12748 Fix NoMethodError in Admin::ProductsV3#index - Only when using the hu.yml locale
  app/helpers/admin/products_helper.rb
Labels: bug-s3, feedback-needed

#12754 Load MiniMagick before use
  app/models/enterprise.rb
  app/models/spree/image.rb
Labels: bug-s1, user facing changes

#12729 Remove now unneeded FDC compatibility code from product import
  app/controllers/admin/dfc_product_imports_controller.rb
  engines/dfc_provider/app/services/fdc_request.rb
  engines/dfc_provider/spec/services/dfc_request_spec.rb
  engines/dfc_provider/spec/services/fdc_request_spec.rb
  spec/fixtures/vcr_cassettes/DFC_Product_Import/imports_from_a_FDC_catalog.yml
  spec/fixtures/vcr_cassettes/DfcRequest/refreshes_the_access_token_and_retrieves_the_FDC_catalog.yml
  spec/fixtures/vcr_cassettes/FdcRequest/refreshes_the_access_token_and_retrieves_a_catalog.yml
  spec/system/admin/dfc_product_import_spec.rb
Labels: technical changes only

#12759 [BUU] Activate admin_style_v3 for 75% of users
  db/migrate/20240810150912_activate_admin_style_v3_for75_pc_users.rb
  db/schema.rb
Labels: user facing changes

#12757 update artifact v3 to v4
  .github/workflows/build.yml
Labels: technical changes only

#12749 Remove awesome nested set gem and dependencies [OFN-11636]
  Gemfile
  Gemfile.lock
  app/assets/javascripts/admin/all.js
  app/assets/javascripts/admin/spree/taxons/taxon_tree_menu.js.coffee
  app/assets/javascripts/admin/spree/taxons/taxonomy.js.coffee
  app/controllers/api/v0/taxonomies_controller.rb
  app/controllers/api/v0/taxons_controller.rb
  app/controllers/spree/admin/taxonomies_controller.rb
  app/controllers/spree/admin/taxons_controller.rb
  app/helpers/spree/admin/taxons_helper.rb
  app/models/spree/ability.rb
  app/models/spree/taxon.rb
  app/models/spree/taxonomy.rb
  app/serializers/api/admin/taxon_serializer.rb
  app/serializers/api/taxon_serializer.rb
  app/views/spree/admin/shared/_configuration_menu.html.haml
  app/views/spree/admin/shared/_tabs.html.haml
  app/views/spree/admin/taxonomies/_form.html.haml
  app/views/spree/admin/taxonomies/_js_head.html.erb
  app/views/spree/admin/taxonomies/_list.html.haml
  app/views/spree/admin/taxonomies/_taxon.html.haml
  app/views/spree/admin/taxonomies/edit.haml
  app/views/spree/admin/taxonomies/index.html.haml
  app/views/spree/admin/taxonomies/new.html.haml
  app/views/spree/admin/taxons/_form.html.haml
  app/views/spree/admin/taxons/destroy_taxon.turbo_stream.haml
  app/views/spree/admin/taxons/edit.html.haml
  app/views/spree/admin/taxons/index.html.haml
  app/views/spree/admin/taxons/new.html.haml
  app/webpacker/css/admin/all.scss
  app/webpacker/css/admin/plugins/jstree.scss
  app/webpacker/css/admin_v3/all.scss
  config/locales/en.yml
  config/routes/api.rb
  config/routes/spree.rb
  db/migrate/20240806135838_drop_spree_taxonomies_table.rb
  db/schema.rb
  lib/spree/core.rb
  lib/tasks/sample_data/taxon_factory.rb
  spec/controllers/api/v0/taxonomies_controller_spec.rb
  spec/controllers/api/v0/taxons_controller_spec.rb
  spec/controllers/spree/admin/taxons_controller_spec.rb
  spec/factories/taxon_factory.rb
  spec/factories/taxonomy_factory.rb
  spec/models/spree/ability_spec.rb
  spec/models/spree/taxon_spec.rb
  spec/models/spree/taxonomy_spec.rb
  spec/queries/product_scope_query_spec.rb
  spec/system/admin/configuration/taxonomies_spec.rb
  spec/system/consumer/shopping/products_spec.rb
  vendor/assets/javascripts/jquery.jstree/jquery.jstree.js
  vendor/assets/javascripts/jquery.jstree/themes/apple/bg.jpg
  vendor/assets/javascripts/jquery.jstree/themes/apple/d.png
  vendor/assets/javascripts/jquery.jstree/themes/apple/dot_for_ie.gif
  vendor/assets/javascripts/jquery.jstree/themes/apple/style.css
  vendor/assets/javascripts/jquery.jstree/themes/apple/throbber.gif
Labels: pr-staged-au, api changes, user facing changes

#12653 Add warning modal to order cycle with attached schedule general setting form [OFN-11613]
  app/assets/javascripts/admin/order_cycles/controllers/edit.js.coffee
  app/assets/javascripts/admin/order_cycles/controllers/simple_edit.js.coffee
  app/assets/javascripts/admin/order_cycles/services/order_cycle.js.coffee
  app/assets/javascripts/admin/utils/services/status_message.js.coffee
  app/assets/javascripts/templates/admin/save_bar.html.haml
  app/components/modal_component/modal_component.scss
  app/controllers/admin/order_cycles_controller.rb
  app/models/order_cycle.rb
  app/views/admin/order_cycles/_date_time_warning_modal_content.html.haml
  app/views/admin/order_cycles/edit.html.haml
  app/webpacker/controllers/mixins/useOpenAndCloseAsAModal.js
  app/webpacker/controllers/order_cycle_form_controller.js
  app/webpacker/css/admin/order_cycles.scss
  config/locales/en.yml
  spec/system/admin/order_cycles/edit_spec.rb
Labels: feedback-needed, user facing changes

#12735 Fix 'Back to products list' stateful navigation
  app/controllers/admin/products_v3_controller.rb
  app/controllers/spree/admin/products_controller.rb
  app/helpers/admin/products_helper.rb
  app/views/spree/admin/products/edit.html.haml
  spec/system/admin/products_spec.rb
Labels: pr-staged-au

#12778 [BUU] Fix Messy flash notifications on new products page
  app/controllers/spree/admin/base_controller.rb
  spec/system/admin/order_cycles/complex_editing_multiple_updation_spec.rb
  spec/system/admin/order_spec.rb
  spec/system/admin/overview_spec.rb
Labels: bug-s4, user facing changes

#12740 Pluralize admin products search result [OFN-12532-v1]
  app/views/admin/products_v3/_sort.html.haml
  config/locales/en.yml
  spec/system/admin/products_v3/index_spec.rb
Labels: user facing changes

#12733 Update product variant unit display name, price, and total price width on different screen sizes [OFN-6567]
  app/views/shop/products/_shop_variant.html.haml
Labels: user facing changes

#12745 Improve effiency of OrderCycle.earliest_closing_times
  app/models/order_cycle.rb
  app/serializers/api/uncached_enterprise_serializer.rb
  spec/serializers/api/uncached_enterprise_serializer_spec.rb
Labels: pr-staged-uk, technical changes only

#12762 change colour of "complete order"
  app/webpacker/css/darkswarm/split-checkout.scss
Labels: pr-staged-au

#12766 Remove direct dependency on MiniMagick
  app/models/enterprise.rb
  app/models/spree/image.rb
Labels: pr-staged-au, technical changes only

#12785 Reproduces S2 bug #12768
  spec/system/admin/order_cycles/edit_spec.rb
  spec/system/admin/reports_spec.rb
Labels: technical changes only

#12789 Fix Artifact Upload Conflicts with Unique Node-Based Names
  .github/workflows/build.yml
Labels: technical changes only

#12726 Track (negative) stock for on-demand products and overrides
  app/models/concerns/stock_settings_override_validation.rb
  app/models/concerns/variant_stock.rb
  app/models/variant_override.rb
  config/locales/en.yml
  lib/open_food_network/scope_variant_to_hub.rb
  spec/lib/open_food_network/scope_variant_to_hub_spec.rb
  spec/models/spree/line_item_spec.rb
  spec/models/spree/shipment_spec.rb
  spec/models/spree/variant_stock_spec.rb
  spec/models/variant_override_spec.rb
  spec/system/admin/product_import_spec.rb
  spec/system/consumer/shopping/variant_overrides_spec.rb
Labels: feedback-needed, technical changes only

#12780 Optimise subscriptions admin
  engines/order_management/app/services/order_management/subscriptions/variants_list.rb
  lib/open_food_network/scope_variants_for_search.rb
  spec/lib/open_food_network/scope_variants_for_search_spec.rb
Labels: technical changes only

#12743 (Fix) chore(deps): bump wicked_pdf from 2.6.3 to 2.8.0 [OFN-12214]
  Gemfile.lock
  app/assets/stylesheets/mail.scss
  app/assets/stylesheets/mail/all.scss
  app/assets/stylesheets/mail/email.scss
  app/assets/stylesheets/mail/payments_list.scss
  app/helpers/application_helper.rb
  app/views/layouts/mailer.html.haml
  app/views/spree/admin/orders/invoice.html.haml
  app/views/spree/admin/orders/invoice2.html.haml
  app/views/spree/admin/orders/invoice4.html.haml
  app/webpacker/css/mail/all.scss
  app/webpacker/packs/mail.scss
  config/application.rb
  spec/system/admin/invoice_print_spec.rb
Labels: pr-staged-au

#12779 Clearer error message and clean up for Product Categories
  config/locales/en.yml
Labels: pr-staged-fr, user facing changes

#12772 Display admin order page instead of shopfront order page to avoid error 500
  app/views/subscription_mailer/_summary_detail.html.haml
Labels: pr-staged-fr

#12781 Add warning popup to order cycle list [OFN-12775]
  app/assets/javascripts/admin/order_cycles/controllers/order_cycles_controller.js.coffee
  app/assets/javascripts/admin/resources/services/order_cycles.js.coffee
  app/controllers/admin/order_cycles_controller.rb
  app/models/order_cycle.rb
  app/services/order_cycles/form_service.rb
  app/services/sets/order_cycle_set.rb
  app/views/admin/order_cycles/_date_time_warning_modal_content.html.haml
  app/views/admin/order_cycles/edit.html.haml
  app/views/admin/order_cycles/index.html.haml
  config/locales/en.yml
  spec/controllers/admin/order_cycles_controller_spec.rb
  spec/models/order_cycle_spec.rb
  spec/system/admin/order_cycles/list_spec.rb
Labels: user facing changes

#12782 Add fallback report loading in case websockets fail
  Gemfile
  Gemfile.lock
  app/controllers/admin/reports_controller.rb
  app/controllers/concerns/reports_actions.rb
  app/jobs/report_job.rb
  app/models/report_blob.rb
  app/models/spree/ability.rb
  app/views/admin/reports/_fallback_display.html.haml
  app/views/admin/reports/create.turbo_stream.haml
  app/views/admin/reports/show.html.haml
  app/webpacker/js/turbo.js
  config/routes/admin.rb
  package.json
  spec/controllers/admin/reports_controller_spec.rb
  spec/jobs/report_job_spec.rb
  spec/mailers/report_mailer_spec.rb
  spec/models/report_blob_spec.rb
  spec/system/admin/reports/enterprise_fee_summaries_spec.rb
  spec/system/admin/reports/orders_and_fulfillment_spec.rb
  spec/system/admin/reports_spec.rb
  yarn.lock
Labels: user facing changes

#12755 Optimise shops page: Enable injected enterprise data to be scoped to specific enterprise ids
  app/helpers/injection_helper.rb
  app/models/order_cycle.rb
  app/models/spree/shipping_method.rb
  app/models/spree/taxon.rb
  lib/open_food_network/enterprise_injection_data.rb
  spec/helpers/injection_helper_spec.rb
  spec/lib/open_food_network/enterprise_injection_data_spec.rb
  spec/models/order_cycle_spec.rb
  spec/models/spree/taxon_spec.rb
Labels: pr-staged-uk, feedback-needed, technical changes only

#12800 Adds retry option to flaky edit_spec.rb
  spec/system/admin/order_cycles/edit_spec.rb
Labels: technical changes only

#12798 Set up code coverage metrics with simplecov
  .github/workflows/build.yml
  .simplecov
  lib/tasks/simplecov.rake
  spec/base_spec_helper.rb
  spec/fixtures/simplecov/customer/.resultset.json
  spec/fixtures/simplecov/voucher/.resultset.json
  spec/lib/tasks/simplecov_spec.rb
Labels: technical changes only

#12812 [BUU] Fix Table width not responsive to the amount of selected columns
  app/views/admin/products_v3/_product_row.html.haml
Labels: bug-s3, pr-staged-au, user facing changes

#12807 Fix broken column after cloning product
  app/webpacker/controllers/column_preferences_controller.js
Labels: user facing changes

#12814 Increase column space in bulk products table
  app/views/admin/products_v3/_table.html.haml
  app/webpacker/css/admin/products_v3.scss
  app/webpacker/css/admin_v3/globals/variables.scss
Labels: user facing changes

#12805 Update deprecated WickedPdf config syntax
  config/initializers/wicked_pdf.rb
Labels: pr-staged-uk, technical changes only

#12813 [BUU] Fix the too Narrow Price field
  app/views/admin/products_v3/_table.html.haml
Labels: pr-staged-au, user facing changes

#12806 Fix typos in "category" and unify capitals on "Back To Xyz List" buttons
  config/locales/en.yml
  spec/models/enterprise_fee_spec.rb
  spec/system/admin/enterprise_fees_spec.rb
  spec/system/admin/products_spec.rb
Labels: user facing changes

#12793 Fix bulk coop report
  lib/reporting/reports/bulk_coop/supplier_report.rb
  spec/system/admin/reports_spec.rb
Labels: pr-staged-fr, user facing changes

#12826 Fix Inconsistent Behavior When Editing Products to mg Units in Hungarian Locale
  app/models/spree/product.rb
  app/services/weights_and_measures.rb
Labels: bug-s2, pr-staged-uk

#12824 [BUU] Fully enable admin_style_v3
  db/migrate/20240828203544_fully_enable_admin_style_v3_flag.rb
  db/schema.rb
Labels: blocked
