Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2024-05, with the labels that each got.

#12414 Fix RedundantPresenceValidationOnBelongs on some files (part II)
  .rubocop_todo.yml
  app/models/spree/product_property.rb
  app/models/spree/return_authorization.rb
  app/models/spree/state.rb
  db/migrate/20240424075646_require_property_on_product_property.rb
  db/migrate/20240424113354_require_order_on_return_authorization.rb
  db/migrate/20240424121221_require_country_on_state.rb
  db/migrate/20240430075133_require_product_on_product_property.rb
  db/schema.rb
  lib/tasks/data/check_missing_country_id_in_state.rake
  lib/tasks/data/check_missing_order_id_in_return_authorization.rake
  lib/tasks/data/check_missing_property_in_joint_table_product_property.rake
Labels: technical changes only

#12418 Optimise CI
  .github/workflows/build.yml
Labels: technical changes only

#12433 Explicitely require all rubocop extensions
  .rubocop.yml
Labels: technical changes only

#12430 Remove tag template from link to draft release
  .github/ISSUE_TEMPLATE/release.md
Labels: technical changes only

#12432 Update links to n8n server
  db/migrate/20240502035220_update_n8n_url.rb
  spec/migrations/20240502035220_update_n8n_url_spec.rb
Labels: technical changes only

#12423 Updates checkout tests to cover for out of stock variant
  spec/support/checkout_helper.rb
  spec/system/consumer/checkout/guest_spec.rb
  spec/system/consumer/shopping/checkout_spec.rb
Labels: technical changes only

#12401 [BUU] Change Producer, Category and Tax Category
  app/components/searchable_dropdown_component.rb
  app/components/searchable_dropdown_component/searchable_dropdown_component.html.haml
  app/controllers/admin/products_v3_controller.rb
  app/reflexes/products_reflex.rb
  app/views/admin/products_v3/_content.html.haml
  app/views/admin/products_v3/_product_row.html.haml
  app/views/admin/products_v3/_table.html.haml
  app/views/admin/products_v3/_variant_row.html.haml
  app/views/admin/products_v3/index.html.haml
  app/webpacker/controllers/bulk_form_controller.js
  app/webpacker/css/admin/products_v3.scss
  config/locales/en.yml
  spec/support/request/tomselect_helper.rb
  spec/support/request/web_helper.rb
  spec/system/admin/products_v3/products_spec.rb
Labels: feature toggled

#12447 Knapsack pro 7.1.0
  .rspec
  Gemfile.lock
  spec/support/precompile_assets.rb
Labels: technical changes only

#12417 Removes unused spec related to legacy checkout
  app/models/spree/payment_method/check.rb
  spec/controllers/checkout_controller_spec.rb
  spec/requests/checkout/failed_checkout_spec.rb
Labels: user facing changes

#12464 Updates tests on a regular checkout
  spec/system/consumer/shopping/variant_overrides_spec.rb
Labels: technical changes only

#12441 [BUU] Delete Button missing before saving variant
  app/views/admin/products_v3/_table.html.haml
  app/views/admin/products_v3/_variant_row.html.haml
  app/webpacker/controllers/bulk_form_controller.js
  config/locales/en.yml
  spec/system/admin/products_v3/products_spec.rb
Labels: technical changes only

#12376 Fix Ship Order menu choice not working
  .rubocop_todo.yml
  app/helpers/spree/admin/orders_helper.rb
  app/reflexes/admin/orders_reflex.rb
  app/views/spree/admin/shared/_order_links.html.haml
  spec/system/admin/order_spec.rb
Labels: technical changes only

#12428 Fix RedundantPresenceValidationOnBelongs on two files
  .rubocop_todo.yml
  app/models/spree/stock_item.rb
  app/models/spree/stock_movement.rb
  db/migrate/20240501072547_require_variant_and_stock_location_on_stock_item.rb
  db/migrate/20240501075735_require_stock_item_and_quantity_on_stock_movement.rb
  db/schema.rb
  lib/tasks/data/check_missing_required_ids_in_stock_items.rake
  lib/tasks/data/check_missing_required_ids_in_stock_movements.rake
Labels: technical changes only

#12443 Remove "ready for" info from shipping method description area at checkout #12395 (solved)
  app/views/checkout/_details.html.haml
Labels: pr-staged-fr, user facing changes

#12454 12372-[Admin] Missing translations page titles
  app/views/spree/admin/shared/_head.html.haml
  config/locales/en.yml
Labels: pr-staged-fr, user facing changes

#12470 Sanitise HTML in long description of enterprise [read-only]
  app/models/enterprise.rb
  app/services/html_sanitizer.rb
  spec/models/enterprise_spec.rb
  spec/services/html_sanitizer_spec.rb
Labels: pr-staged-fr, user facing changes

#12490 Move mail spec precompile assets for it
  spec/mailers/mail_interceptor_spec.rb
Labels: technical changes only

#12486 Show any tax category errors when saving variants
  app/views/admin/products_v3/_variant_row.html.haml
  app/views/spree/admin/tax_settings/edit.html.haml
  app/views/spree/admin/variants/_form.html.haml
  app/webpacker/css/admin_v3/components/tom_select.scss
Labels: feedback-needed, feature toggled

#12494 Updates Paypal system spec to consider new checkout flow
  spec/system/consumer/shopping/checkout_paypal_spec.rb
Labels: technical changes only

#12502 Break up large spec files
  .github/workflows/build.yml
  spec/system/admin/order_spec.rb
  spec/system/admin/orders/bulk_actions_spec.rb
  spec/system/admin/orders/invoices_spec.rb
  spec/system/admin/orders_spec.rb
Labels: technical changes only

#12460 Clean up unused enterprise fields
  app/models/order_cycle.rb
  app/views/spree/orders/edit.html.haml
  db/migrate/20240510040639_remove_distributor_info_from_enterprises.rb
  db/migrate/20240510041114_remove_pickup_times_from_enterprises.rb
  db/migrate/20240510041829_remove_next_collection_at_from_enterprises.rb
  db/schema.rb
  lib/tasks/enterprises.rake
  spec/models/order_cycle_spec.rb
Labels: pr-staged-fr, user facing changes

#12472 Bump stimulus_reflex to 3.5.1 and cable_ready to 5.0.5
  Gemfile
  Gemfile.lock
  package.json
  spec/reflexes/products_reflex_spec.rb
  yarn.lock
Labels: pr-staged-au, dependencies

#12481 Avoid submitting duplicate Connected Apps
  app/controllers/admin/connected_apps_controller.rb
  app/reflexes/admin/connected_app_reflex.rb
  app/views/admin/enterprises/form/_connected_apps.html.haml
  config/routes/admin.rb
Labels: feedback-needed, technical changes only

#12465 Allow return or line break in shipping / payment method description
  app/views/checkout/_details.html.haml
  app/views/checkout/_payment.html.haml
Labels: user facing changes

#12505 Removes deprecation strikethrough from tax report (by producer)
  lib/reporting/reports/list.rb
Labels: pr-staged-fr

#12504 [BUU] Remove StimulusReflex from Image Edit
  Gemfile
  Gemfile.lock
  app/controllers/admin/products_v3_controller.rb
  app/controllers/spree/admin/images_controller.rb
  app/helpers/admin/products_helper.rb
  app/reflexes/products_reflex.rb
  app/views/admin/products_v3/_edit_image.html.haml
  app/views/admin/products_v3/_product_image.html.haml
  app/views/admin/products_v3/_product_row.html.haml
  app/views/admin/products_v3/index.html.haml
  app/views/spree/admin/images/edit.turbo_stream.haml
  app/views/spree/admin/images/update.turbo_stream.haml
  app/webpacker/controllers/form_controller.js
  config/locales/en.yml
Labels: feature toggled

#12496 [12355] Remove discourse
  .env
  .rubocop_todo.yml
  app/controllers/application_controller.rb
  app/controllers/discourse_sso_controller.rb
  app/helpers/discourse_helper.rb
  app/views/shared/menu/_signed_in.html.haml
  app/views/shared/menu/_signed_in_offcanvas.html.haml
  config/locales/en.yml
  config/routes.rb
  lib/discourse/single_sign_on.rb
Labels: user facing changes

#12510 Deleting some used one-shot rake tasks
  lib/tasks/data/check_missing_country_id_in_state.rake
  lib/tasks/data/check_missing_order_id_in_return_authorization.rake
  lib/tasks/data/check_missing_property_in_joint_table_product_property.rake
  lib/tasks/data/check_missing_required_ids_in_stock_items.rake
  lib/tasks/data/check_missing_required_ids_in_stock_movements.rake
Labels: technical changes only

#12514 Fix redundant presence validation on belongs part V
  .rubocop_todo.yml
  app/models/subscription_line_item.rb
  app/models/tag_rule.rb
  spec/models/subscription_line_item_spec.rb
  spec/models/tag_rule_spec.rb
Labels: technical changes only

#12506 Sanitise HTML in long description of enterprise group [read-only]
  app/models/enterprise_group.rb
  spec/models/enterprise_group_spec.rb
Labels: pr-staged-fr, user facing changes

#12489 More realistic test env for translations
  .env
  .env.development
  .env.test
  config/locales/en_TEST.yml
  spec/base_spec_helper.rb
Labels: technical changes only

#12495 Get registration location map working with OSM
  app/assets/javascripts/darkswarm/controllers/registration/registration_controller.js.coffee
  app/helpers/map_helper.rb
  app/views/registration/steps/_details.html.haml
  app/views/registration/steps/_location_map_google.html.haml
  app/views/registration/steps/_location_map_osm.html.haml
  app/webpacker/controllers/open_street_map_controller.js
  package.json
  spec/helpers/map_helper_spec.rb
  spec/views/registration/steps/_details.html.haml_spec.rb
  yarn.lock
Labels: user facing changes
