Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2024-03, with the labels that each got.

#12221 Use new rspec-sql gem
  .rubocop_todo.yml
  Gemfile
  Gemfile.lock
  spec/controllers/admin/order_cycles_controller_spec.rb
  spec/support/query_counter.rb
Labels: pr-no-test, technical changes only

#12208 add for every serialized attribute a coder
  app/models/invoice.rb
  app/models/report_rendering_options.rb
  app/models/spree/preference.rb
Labels: pr-staged-uk, technical changes only

#12194 Re-implement dropdown controller with html details element
  app/views/spree/admin/orders/_bulk_actions.html.haml
  app/views/spree/admin/shared/_order_links.html.haml
  app/webpacker/controllers/checked_controller.js
  app/webpacker/controllers/dropdown_controller.js
  app/webpacker/css/admin/dropdown.scss
  app/webpacker/css/admin_v3/components/dropdown.scss
  spec/javascripts/stimulus/dropdown_controller_test.js
  spec/system/admin/order_spec.rb
  spec/system/admin/orders_spec.rb
Labels: pr-staged-uk

#12189 hide alternative invoice checkbox if invoices feature is enabled
  app/views/admin/invoice_settings/edit.html.haml
Labels: pr-staged-fr, technical changes only

#12224 Add Rubocop negation matcher
  .rubocop_rspec_styleguide.yml
  spec/mailers/producer_mailer_spec.rb
  spec/support/reports_helper.rb
  spec/system/admin/authentication_spec.rb
  spec/system/admin/bulk_order_management_spec.rb
  spec/system/admin/bulk_product_update_spec.rb
  spec/system/admin/customers_spec.rb
  spec/system/admin/enterprise_fees_spec.rb
  spec/system/admin/enterprise_groups_spec.rb
  spec/system/admin/enterprise_roles_spec.rb
  spec/system/admin/enterprises/images_spec.rb
  spec/system/admin/enterprises/index_spec.rb
  spec/system/admin/enterprises_spec.rb
  spec/system/admin/invoice_print_spec.rb
  spec/system/admin/order_cycles/list_spec.rb
  spec/system/admin/order_spec.rb
  spec/system/admin/orders/invoices_spec.rb
  spec/system/admin/orders_spec.rb
  spec/system/admin/overview_spec.rb
  spec/system/admin/product_import_spec.rb
  spec/system/admin/reports/enterprise_fee_summaries_spec.rb
  spec/system/admin/reports_spec.rb
  spec/system/admin/schedules_spec.rb
  spec/system/admin/shipping_methods_spec.rb
  spec/system/admin/subscriptions/crud_spec.rb
  spec/system/admin/tag_rules_spec.rb
  spec/system/admin/users_spec.rb
  spec/system/admin/variant_overrides_spec.rb
  spec/system/consumer/account/cards_spec.rb
  spec/system/consumer/account_spec.rb
  spec/system/consumer/checkout/guest_spec.rb
  spec/system/consumer/cookies_spec.rb
  spec/system/consumer/footer_links_spec.rb
  spec/system/consumer/multilingual_spec.rb
  spec/system/consumer/registration_spec.rb
  spec/system/consumer/shopping/cart_spec.rb
  spec/system/consumer/shopping/checkout_auth_spec.rb
  spec/system/consumer/shopping/checkout_spec.rb
  spec/system/consumer/shopping/embedded_groups_spec.rb
  spec/system/consumer/shopping/orders_spec.rb
  spec/system/consumer/shopping/shopping_spec.rb
  spec/system/consumer/shopping/unit_price_spec.rb
  spec/system/consumer/shops_spec.rb
  spec/system/consumer/user_password_spec.rb
  spec/system/consumer/white_label_spec.rb
  spec/views/admin/products_v3/_filters.html.haml_spec.rb
Labels: pr-no-test, technical changes only

#12172 fix invoice render multiple tax rates
  app/models/invoice/data_presenter.rb
  app/models/invoice/data_presenter/line_item.rb
  app/models/spree/line_item.rb
  app/serializers/invoice/line_item_serializer.rb
  app/views/spree/admin/orders/_invoice_table4.html.haml
  spec/models/invoice/data_presenter_spec.rb
  spec/system/admin/invoice_print_spec.rb
Labels: pr-staged-uk

#12233 [BUU] Unit Scale - basic implementation
  app/helpers/spree/admin/base_helper.rb
  app/models/spree/product.rb
  app/services/permitted_attributes/product.rb
  app/services/weights_and_measures.rb
  app/views/admin/products_v3/_product_row.html.haml
  app/views/admin/products_v3/_table.html.haml
  app/views/admin/products_v3/_variant_row.html.haml
  app/views/spree/admin/taxonomies/_form.html.haml
  app/views/spree/admin/taxons/_form.html.haml
  app/webpacker/controllers/bulk_form_controller.js
  app/webpacker/controllers/toggle_control_controller.js
  app/webpacker/css/admin/products_v3.scss
  app/webpacker/css/admin_v3/components/tom_select.scss
  app/webpacker/css/admin_v3/shared/forms.scss
  config/locales/en.yml
  spec/javascripts/stimulus/bulk_form_controller_test.js
  spec/javascripts/stimulus/toggle_control_controller_test.js
  spec/reflexes/products_reflex_spec.rb
  spec/services/weights_and_measures_spec.rb
  spec/support/request/web_helper.rb
  spec/system/admin/products_v3/products_spec.rb
Labels: pr-staged-uk, feature toggled

#12206 Fix incorrect results for multiple tax rates in report
  lib/reporting/reports/sales_tax/sales_tax_totals_by_producer.rb
  spec/system/admin/reports/sales_tax/sales_tax_totals_by_producer_spec.rb
Labels: user facing changes

#12248 Add dev script to run rubocop on changed files
  script/rubocop-diff.sh
Labels: technical changes only

#12249 Set known default password for sample users
  lib/tasks/sample_data/user_factory.rb
Labels: technical changes only

#12254 [DFC] Add spree_product_uri to SuppliedProduct
  engines/dfc_provider/app/controllers/dfc_provider/supplied_products_controller.rb
  engines/dfc_provider/app/services/supplied_product_builder.rb
  engines/dfc_provider/lib/dfc_provider/supplied_product.rb
  engines/dfc_provider/spec/requests/supplied_products_spec.rb
  engines/dfc_provider/spec/services/supplied_product_builder_spec.rb
  swagger/dfc.yaml
Labels: api changes

#11918 Bulk printing/sending should show warning if ABN is required but not set.
  app/reflexes/admin/orders_reflex.rb
  spec/system/admin/orders_spec.rb
Labels: feedback-needed, technical changes only

#12247 [BUU] Enqueue actions to perform at end of reflex
  app/reflexes/products_reflex.rb
Labels: technical changes only

#12207 fix route to Admin#order#invoice#generate
  config/routes/spree.rb
Labels: pr-staged-uk, technical changes only

#12273 Rubocop
  .rubocop_todo.yml
  engines/dfc_provider/spec/requests/enterprises_spec.rb
  engines/dfc_provider/spec/requests/persons_spec.rb
  engines/order_management/spec/services/order_management/order/stripe_sca_payment_authorize_spec.rb
  engines/order_management/spec/services/order_management/order/updater_spec.rb
  engines/order_management/spec/services/order_management/stock/package_spec.rb
  engines/order_management/spec/services/order_management/subscriptions/payment_setup_spec.rb
  engines/order_management/spec/services/order_management/subscriptions/proxy_order_syncer_spec.rb
  engines/order_management/spec/services/order_management/subscriptions/stripe_payment_setup_spec.rb
  engines/order_management/spec/services/order_management/subscriptions/summary_spec.rb
  engines/order_management/spec/services/order_management/subscriptions/validator_spec.rb
  engines/order_management/spec/services/order_management/subscriptions/variants_list_spec.rb
  engines/web/spec/helpers/cookies_policy_helper_spec.rb
  lib/open_food_network/order_cycle_permissions.rb
  spec/system/admin/orders_spec.rb
Labels: technical changes only

#12284 Limit enterprise image sizes on DFC API
  engines/dfc_provider/app/services/enterprise_builder.rb
  swagger/dfc.yaml
Labels: api changes

#12285 Add placeholder file with comments
  app/webpacker/channels/scoped_channel.js
Labels: technical changes only

#12229 [BO Orders] Update Entreprise fees when decreasing quantity
  app/controllers/api/v0/shipments_controller.rb
  spec/controllers/api/v0/shipments_controller_spec.rb
Labels: feedback-needed, api changes

#12271 set variant_processor to mini_magick
  config/application.rb
Labels: pr-staged-uk, technical changes only

#12289 Fix Rubocop Rails issue: Rails/FindEach
  .rubocop_todo.yml
  app/controllers/admin/order_cycles_controller.rb
  app/jobs/subscription_confirm_job.rb
  app/services/orders/bulk_cancel_service.rb
  app/services/products_renderer.rb
  lib/tasks/data.rake
  lib/tasks/subscriptions/debug.rake
  spec/system/admin/bulk_order_management_spec.rb
  spec/system/admin/enterprise_relationships_spec.rb
Labels: technical changes only

#12299 Publish full URLs of social media links on DFC API
  engines/dfc_provider/app/services/social_media_builder.rb
  engines/dfc_provider/spec/services/social_media_builder_spec.rb
Labels: api changes

#12274 Import products from DFC catalog
  .env.test
  app/controllers/admin/dfc_product_imports_controller.rb
  app/controllers/admin/product_import_controller.rb
  app/models/semantic_link.rb
  app/models/spree/ability.rb
  app/models/spree/variant.rb
  app/views/admin/dfc_product_imports/index.html.haml
  app/views/admin/product_import/_dfc_import_form.html.haml
  app/views/admin/product_import/index.html.haml
  config/locales/en.yml
  config/routes/admin.rb
  db/migrate/20240105043228_create_semantic_links.rb
  db/schema.rb
  engines/dfc_provider/app/services/dfc_request.rb
  engines/dfc_provider/app/services/supplied_product_builder.rb
  engines/dfc_provider/spec/services/dfc_request_spec.rb
  engines/dfc_provider/spec/services/supplied_product_builder_spec.rb
  spec/fixtures/vcr_cassettes/DfcRequest/refreshes_the_access_token_on_fail.yml
  spec/models/semantic_link_spec.rb
  spec/models/spree/variant_spec.rb
  spec/support/vcr_setup.rb
  spec/system/admin/dfc_product_import_spec.rb
Labels: feedback-needed, user facing changes

#12298 Remove unused Devise login links partial
  app/views/devise/shared/_links.html.erb
Labels: technical changes only

#12308 chore(deps): update rails-nested-form from fork to v5.0.0
  app/views/admin/products_v3/_table.html.haml
  app/webpacker/controllers/index.js
  package.json
  yarn.lock
Labels: dependencies, javascript

#12307 Don't generate packing reports twice just to show the form
  lib/reporting/report_headers_builder.rb
  lib/reporting/report_template.rb
  lib/reporting/reports/packing/customer.rb
  lib/reporting/reports/packing/product.rb
  lib/reporting/reports/packing/supplier.rb
Labels: technical changes only

#12306 Reduce unnecessary avalanches of Redis queries
  app/helpers/admin/injection_helper.rb
  app/models/current_config.rb
  app/models/spree/adjustment.rb
  app/models/spree/order.rb
  app/models/spree/price.rb
  app/models/spree/return_authorization.rb
  app/models/spree/shipment.rb
  app/models/spree/variant.rb
  app/serializers/api/admin/customer_with_balance_serializer.rb
  app/serializers/api/currency_config_serializer.rb
  app/services/weights_and_measures.rb
  app/views/spree/admin/general_settings/edit.html.haml
  app/views/spree/admin/payments/paypal_refund.html.haml
  lib/reporting/reports/xero_invoices/base.rb
  lib/spree/core/controller_helpers/order.rb
  lib/spree/money.rb
  spec/base_spec_helper.rb
  spec/lib/spree/money_spec.rb
Labels: technical changes only

#12305 Feat/12297 rvm support script setup
  GETTING_STARTED.md
  script/setup
Labels: dev-test, technical changes only
