Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2024-01, with the labels that each got.

#11963 Tests app/services/stripe_payment_status.rb
  spec/base_spec_helper.rb
  spec/fixtures/vcr_cassettes/Stripe-v10.3.0/StripePaymentStatus/_stripe_captured_/when_the_Stripe_payment_has_been_captured/returns_true.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.3.0/StripePaymentStatus/_stripe_captured_/when_the_payment_is_not_a_Stripe_payment_or_does_not_have_a_payment_intent/returns_false.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.3.0/StripePaymentStatus/_stripe_status/when_the_payment_has_a_payment_intent/and_the_last_action_on_the_Stripe_payment_failed/returns_failed_response.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.3.0/StripePaymentStatus/_stripe_status/when_the_payment_has_a_payment_intent/fetches_the_status_with_Stripe_PaymentIntentValidator.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.3.0/StripePaymentStatus/_stripe_status/when_the_payment_is_not_a_Stripe_payment_or_does_not_have_a_payment_intent/returns_nil.yml
  spec/services/stripe_payment_status_spec.rb
Labels: technical changes only

#11954 Enterprise user can remove Connected Apps
  app/models/connected_app.rb
  app/reflexes/admin/connected_app_reflex.rb
  app/views/admin/enterprises/form/_connected_apps.html.haml
  app/webpacker/css/admin/connected_apps.scss
  app/webpacker/css/admin_v3/globals/variables.scss
  app/webpacker/css/admin_v3/shared/layout.scss
  config/locales/en.yml
  spec/fixtures/vcr_cassettes/Connected_Apps/can_be_enabled_and_disabled.yml
  spec/system/admin/enterprises/connected_apps_spec.rb
Labels: technical changes only

#11956 Use full product and variant name on DFC API
  engines/dfc_provider/app/services/supplied_product_builder.rb
  engines/dfc_provider/spec/services/enterprise_builder_spec.rb
  engines/dfc_provider/spec/services/supplied_product_builder_spec.rb
  swagger/dfc.yaml
Labels: api changes

#11959 Send semantic id when connecting enterprise to app
  app/jobs/connect_app_job.rb
  spec/fixtures/vcr_cassettes/ConnectAppJob/stores_connection_data_on_the_app.yml
  spec/jobs/connect_app_job_spec.rb
Labels: api changes

#11972 Moves test introduced by #11799 to avoid non-explicit modal acceptance
  spec/system/admin/enterprises_spec.rb
Labels: technical changes only

#11977 Fixes minor styling issues of admin and admin v3 in the dashboard
  app/views/spree/admin/overview/_enterprises.html.haml
  app/views/spree/admin/overview/_enterprises_header.html.haml
  app/views/spree/admin/overview/_order_cycles.html.haml
  app/views/spree/admin/overview/_products.html.haml
  app/webpacker/css/admin/dashboard_item.scss
  app/webpacker/css/admin_v3/dashboard/dashboard_item.scss
Labels: pr-staged-fr

#11998 remove unnecessary require instructions
  app/controllers/admin/schedules_controller.rb
  app/controllers/api/v0/enterprise_attachment_controller.rb
  app/jobs/subscription_confirm_job.rb
  app/jobs/subscription_placement_job.rb
  app/models/spree/adjustment.rb
  app/models/spree/gateway.rb
  app/models/spree/line_item.rb
  app/models/spree/order.rb
  app/models/spree/payment_method.rb
  app/models/spree/product.rb
  app/models/spree/variant.rb
  app/services/order_available_payment_methods.rb
  app/services/order_available_shipping_methods.rb
  app/services/order_cycle_clone.rb
  app/services/order_cycle_form.rb
  app/services/shop/order_cycles_list.rb
  app/services/variant_units/variant_and_line_item_naming.rb
  engines/order_management/app/services/order_management/subscriptions/form.rb
  spec/lib/reports/enterprise_fee_summary/parameters_spec.rb
  spec/models/spree/variant_spec.rb
  spec/services/invoice_renderer_spec.rb
  spec/services/order_cycle_form_spec.rb
Labels: pr-staged-au

#12004 Cache default country simply in memory
  app/models/spree/country.rb
  app/services/default_country.rb
Labels: technical changes only

#11981 Fix flash type when updating entreprise fees
  app/controllers/admin/enterprise_fees_controller.rb
Labels: pr-staged-au

#11994 upgrade paper-trail to 15.1
  Gemfile
  Gemfile.lock
  config/application.rb
Labels: technical changes only

#11921 show warning when a new invoice can be generated
  app/views/spree/admin/invoices/index.html.haml
  config/locales/en.yml
  spec/system/admin/order_spec.rb
Labels: pr-staged-fr, technical changes only

#11990 Add keyboard shortcut to submit forms
  app/webpacker/js/hotkeys.js
  app/webpacker/packs/admin.js
  app/webpacker/packs/application.js
  package.json
  yarn.lock
Labels: pr-staged-au

#11999 Add Vouchers to OC Customer Total Report
  app/views/admin/reports/_rendering_options.html.haml
  config/locales/en.yml
  lib/reporting/reports/orders_and_fulfillment/order_cycle_customer_totals.rb
  spec/lib/reports/orders_and_fulfillment/order_cycle_customer_totals_report_spec.rb
  spec/system/admin/reports/orders_and_fulfillment_spec.rb
Labels: pr-staged-au

#12014 Remove feature toggle for vouchers, they are always on
  app/views/admin/enterprises/_form.html.haml
  app/views/admin/shared/_side_menu.html.haml
  app/views/checkout/_payment.html.haml
  app/webpacker/css/admin/side_menu.scss
  lib/open_food_network/feature_toggle.rb
  spec/lib/reports/sales_tax_totals_by_order_spec.rb
  spec/requests/admin/vouchers_spec.rb
  spec/system/admin/enterprises_spec.rb
  spec/system/admin/reports/orders_and_fulfillment_spec.rb
  spec/system/admin/vouchers_spec.rb
  spec/system/consumer/checkout/payment_spec.rb
  spec/system/consumer/checkout/tax_incl_spec.rb
  spec/system/consumer/checkout/tax_not_incl_spec.rb
Labels: technical changes only

#12013 DRY specs with fixture_file_upload helper
  spec/controllers/api/v0/logos_controller_spec.rb
  spec/controllers/api/v0/product_images_controller_spec.rb
  spec/controllers/api/v0/products_controller_spec.rb
  spec/controllers/api/v0/promo_images_controller_spec.rb
  spec/controllers/api/v0/terms_and_conditions_controller_spec.rb
  spec/factories/order_cycle_factory.rb
  spec/fixtures/files/thinking-cat.jpg
  spec/models/terms_of_service_file_spec.rb
  spec/support/api_helper.rb
  spec/support/file_helper.rb
  spec/system/admin/products_spec.rb
  spec/system/admin/tos_banner_spec.rb
  spec/system/consumer/checkout/summary_spec.rb
  spec/system/consumer/shopping/checkout_spec.rb
Labels: technical changes only

#12009 Fix ToS Position Issue
  app/webpacker/css/admin_v3/components/messages.scss
  app/webpacker/css/admin_v3/globals/variables.scss
Labels: pr-staged-uk, pr-staged-fr

#11983 Improve `admin/enterprise_roles` page performance
  app/controllers/admin/enterprise_roles_controller.rb
  app/helpers/admin/injection_helper.rb
  app/queries/admin/enterprise_roles_query.rb
  app/views/admin/enterprise_roles/_data.html.haml
Labels: pr-staged-uk, pr-staged-fr

#12026 Autocorrect Rubocop issues
  .rubocop_todo.yml
  app/helpers/shop_helper.rb
  app/models/spree/app_configuration.rb
  app/models/spree/preferences/preferable_class_methods.rb
  app/models/spree/product.rb
  app/services/sets/product_set.rb
  lib/spree/core/environment_extension.rb
  spec/system/admin/configuration/content_spec.rb
Labels: technical changes only

#12032 Show DFC API first in documentation
  config/initializers/rswag_ui.rb
  engines/dfc_provider/spec/swagger_helper.rb
  spec/swagger_helper.rb
Labels: pr-no-test, technical changes only

#12023 [BUU] Sticky table header and saving banner - alternate solution
  app/views/admin/products_v3/_table.html.haml
  app/webpacker/css/admin/products_v3.scss
Labels: pr-staged-fr

#11982 Make hint for logo size translatable and adjust to 300 px
  app/views/admin/enterprises/form/_images.html.haml
  config/locales/en.yml
Labels: pr-staged-uk

#12024 [DFC] add/delete enterprise to enterprise group
  engines/dfc_provider/app/controllers/dfc_provider/application_controller.rb
  engines/dfc_provider/app/controllers/dfc_provider/enterprise_groups/affiliated_by_controller.rb
  engines/dfc_provider/config/routes.rb
  engines/dfc_provider/spec/requests/enterprise_groups/affiliated_by_spec.rb
  swagger/dfc.yaml
Labels: api changes

#11932 [BUU] Dropdown UI tweaks (tom-select)
  app/views/admin/products_v3/_filters.html.haml
  app/views/admin/products_v3/_sort.html.haml
  app/webpacker/controllers/tom_select_controller.js
  app/webpacker/css/admin/products_v3.scss
  app/webpacker/css/admin_v3/components/select2.scss
  app/webpacker/css/admin_v3/components/tom_select.scss
  app/webpacker/css/admin_v3/globals/palette.scss
  app/webpacker/css/admin_v3/globals/variables.scss
  app/webpacker/css/admin_v3/shared/forms.scss
  config/locales/en.yml
Labels: pr-staged-fr, feature toggled

#12030 Show Connected Apps only to enterprise managers
  app/helpers/admin/enterprises_helper.rb
  app/models/spree/ability.rb
  spec/helpers/admin/enterprises_helper_spec.rb
Labels: pr-no-test, technical changes only

#11942 [BUU] See product images
  app/views/admin/products_v3/_table.html.haml
  app/webpacker/css/admin/products_v3.scss
  app/webpacker/css/admin_v3/components/buttons.scss
  config/locales/en.yml
Labels: feedback-needed, feature toggled

#12031 [BUU] Update product images
  app/components/confirm_modal_component/confirm_modal_component.html.haml
  app/components/help_modal_component/help_modal_component.html.haml
  app/components/modal_component.rb
  app/components/modal_component/modal_component.html.haml
  app/components/modal_component/modal_component.scss
  app/components/vertical_ellipsis_menu/component.scss
  app/controllers/spree/admin/images_controller.rb
  app/reflexes/products_reflex.rb
  app/views/admin/products_v3/_edit_image.html.haml
  app/views/admin/products_v3/_table.html.haml
  app/views/admin/products_v3/index.html.haml
  app/views/spree/admin/orders/bulk/_invoice_modal.html.haml
  app/webpacker/controllers/form_controller.js
  app/webpacker/css/admin/all.scss
  app/webpacker/css/admin/products_v3.scss
  app/webpacker/css/admin_v3/all.scss
  app/webpacker/css/admin_v3/components/buttons.scss
  app/webpacker/css/admin_v3/globals/variables.scss
  app/webpacker/css/darkswarm/all.scss
  config/locales/en.yml
  spec/javascripts/stimulus/help_modal_controller_test.js
  spec/system/admin/enterprise_roles_spec.rb
Labels: feature toggled

#12037 Update variant name, price and stock through the DFC API
  engines/dfc_provider/app/controllers/dfc_provider/application_controller.rb
  engines/dfc_provider/app/controllers/dfc_provider/offers_controller.rb
  engines/dfc_provider/app/controllers/dfc_provider/supplied_products_controller.rb
  engines/dfc_provider/app/services/dfc_builder.rb
  engines/dfc_provider/app/services/offer_builder.rb
  engines/dfc_provider/app/services/supplied_product_builder.rb
  engines/dfc_provider/config/routes.rb
  engines/dfc_provider/spec/requests/offers_spec.rb
  engines/dfc_provider/spec/requests/supplied_products_spec.rb
  engines/dfc_provider/spec/services/offer_builder_spec.rb
  swagger/dfc.yaml
Labels: api changes

#11762 send-shipment-email-optionally
  app/assets/javascripts/admin/spree/orders/shipments.js.erb
  app/components/ship_order_component.html.haml
  app/components/ship_order_component.rb
  app/helpers/spree/admin/orders_helper.rb
  app/models/spree/order.rb
  app/models/spree/shipment.rb
  app/reflexes/admin/orders_reflex.rb
  app/views/admin/shared/_tooltip_button.html.haml
  app/views/spree/admin/orders/_shipment.html.haml
  app/views/spree/admin/orders/_table_row.html.haml
  app/views/spree/admin/shared/_order_links.html.haml
  config/locales/en.yml
  spec/models/spree/shipment_spec.rb
  spec/system/admin/order_spec.rb
  spec/system/admin/orders_spec.rb
Labels: pr-staged-uk

#12035 Removes default selection for User facing changes
  .github/PULL_REQUEST_TEMPLATE.md
  .github/release.yml
Labels: technical changes only

#12058 Filter out Stripe client_id
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/Spree_CreditCardsController/using_VCR/_new_from_token/when_the_request_to_store_the_customer/card_with_Stripe_is_successful/saves_the_card_locally.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/Spree_Gateway_StripeSCA/_error_message/when_payment_intent_state_is_not_in_requires_capture_state/does_not_succeed_if_payment_intent_state_is_not_requires_capture.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/Spree_Gateway_StripeSCA/_purchase/completes_the_purchase.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/Spree_Gateway_StripeSCA/_purchase/provides_an_error_message_to_help_developer_debug.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/StripeAccount/deauthorize_and_destroy/when_the_Stripe_API_disconnect_fails/destroys_the_record_and_notifies_Bugsnag.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/StripeAccount/deauthorize_and_destroy/when_the_Stripe_API_disconnect_succeeds/destroys_the_record.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/StripePaymentStatus/_stripe_captured_/when_the_Stripe_payment_has_been_captured/returns_true.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/StripePaymentStatus/_stripe_captured_/when_the_payment_is_not_a_Stripe_payment_or_does_not_have_a_payment_intent/returns_false.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/StripePaymentStatus/_stripe_status/when_the_payment_has_a_payment_intent/and_the_last_action_on_the_Stripe_payment_failed/returns_failed_response.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/StripePaymentStatus/_stripe_status/when_the_payment_has_a_payment_intent/fetches_the_status_with_Stripe_PaymentIntentValidator.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/StripePaymentStatus/_stripe_status/when_the_payment_is_not_a_Stripe_payment_or_does_not_have_a_payment_intent/returns_nil.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_invalid/invalid_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Exceeding_velocity_limit_decline/raises_Stripe_error_with_payment_intent_last_payment_error_as_message.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_invalid/invalid_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Expired_card_decline/raises_Stripe_error_with_payment_intent_last_payment_error_as_message.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_invalid/invalid_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Generic_decline/raises_Stripe_error_with_payment_intent_last_payment_error_as_message.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_invalid/invalid_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Incorrect_CVC_decline/raises_Stripe_error_with_payment_intent_last_payment_error_as_message.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_invalid/invalid_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Insufficient_funds_decline/raises_Stripe_error_with_payment_intent_last_payment_error_as_message.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_invalid/invalid_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Lost_card_decline/raises_Stripe_error_with_payment_intent_last_payment_error_as_message.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_invalid/invalid_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Processing_error_decline/raises_Stripe_error_with_payment_intent_last_payment_error_as_message.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_invalid/invalid_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Stolen_card_decline/raises_Stripe_error_with_payment_intent_last_payment_error_as_message.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_American_Express/captures_the_payment.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_American_Express/returns_payment_intent_id_and_does_not_raise.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_BCcard_and_DinaCard/captures_the_payment.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_BCcard_and_DinaCard/returns_payment_intent_id_and_does_not_raise.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Diners_Club/captures_the_payment.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Diners_Club/returns_payment_intent_id_and_does_not_raise.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Diners_Club_14-digit_card_/captures_the_payment.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Diners_Club_14-digit_card_/returns_payment_intent_id_and_does_not_raise.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Discover/captures_the_payment.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Discover/returns_payment_intent_id_and_does_not_raise.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Discover_debit_/captures_the_payment.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Discover_debit_/returns_payment_intent_id_and_does_not_raise.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_JCB/captures_the_payment.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_JCB/returns_payment_intent_id_and_does_not_raise.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Mastercard/captures_the_payment.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Mastercard/returns_payment_intent_id_and_does_not_raise.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Mastercard_2-series_/captures_the_payment.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Mastercard_2-series_/returns_payment_intent_id_and_does_not_raise.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Mastercard_debit_/captures_the_payment.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Mastercard_debit_/returns_payment_intent_id_and_does_not_raise.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Mastercard_prepaid_/captures_the_payment.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Mastercard_prepaid_/returns_payment_intent_id_and_does_not_raise.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_UnionPay/captures_the_payment.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_UnionPay/returns_payment_intent_id_and_does_not_raise.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_UnionPay_19-digit_card_/captures_the_payment.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_UnionPay_19-digit_card_/returns_payment_intent_id_and_does_not_raise.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_UnionPay_debit_/captures_the_payment.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_UnionPay_debit_/returns_payment_intent_id_and_does_not_raise.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Visa/captures_the_payment.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Visa/returns_payment_intent_id_and_does_not_raise.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Visa_debit_/captures_the_payment.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.5.0/Stripe_PaymentIntentValidator/_call/when_payment_intent_is_valid/valid_non-3D_credit_cards_are_correctly_handled/behaves_like_payments_intents/from_Visa_debit_/returns_payment_intent_id_and_does_not_raise.yml
  spec/support/vcr_setup.rb
Labels: technical changes only

#12064 Bump prettier and pretty-quick
  package.json
  yarn.lock
Labels: dependencies, dev-test, technical changes only

#12038 Spec requiring tax category when creating products
  app/models/spree/variant.rb
  engines/dfc_provider/spec/requests/supplied_products_spec.rb
  spec/base_spec_helper.rb
  spec/controllers/api/v0/products_controller_spec.rb
  spec/models/spree/variant_spec.rb
  spec/support/products_helper.rb
  spec/system/admin/products_spec.rb
Labels: pr-staged-au, technical changes only

#12050 Replace toggle_button_disable controller with generic toggle_control controller
  app/views/checkout/_voucher_section.html.haml
  app/webpacker/controllers/toggle_button_disabled_controller.js
  app/webpacker/controllers/toggle_control_controller.js
  spec/javascripts/stimulus/toggle_button_disabled_controller_test.js
  spec/javascripts/stimulus/toggle_control_controller_test.js
Labels: pr-staged-uk

#11985 Include vouchers in report: Enterprise Fees With Tax Report By Order
  app/models/spree/order.rb
  lib/reporting/reports/enterprise_fee_summary/enterprise_fees_with_tax_report_by_order.rb
  spec/models/spree/order_spec.rb
Labels: pr-staged-au

#11817 [DFC] match taxons to dfc product types
  app/controllers/spree/admin/taxons_controller.rb
  app/views/spree/admin/taxons/_form.html.haml
  config/locales/en.yml
  db/migrate/20231027041224_add_dfc_name_to_spree_taxons.rb
  db/schema.rb
  engines/dfc_provider/app/services/dfc_product_type_factory.rb
  engines/dfc_provider/app/services/supplied_product_builder.rb
  engines/dfc_provider/lib/data_food_consortium/connector/importer.rb
  engines/dfc_provider/spec/fixtures/files/put_supplied_product.json
  engines/dfc_provider/spec/lib/data_food_consortium/connector/importer_spec.rb
  engines/dfc_provider/spec/requests/catalog_items_spec.rb
  engines/dfc_provider/spec/requests/enterprises_spec.rb
  engines/dfc_provider/spec/requests/supplied_products_spec.rb
  engines/dfc_provider/spec/services/dfc_product_type_factory_spec.rb
  engines/dfc_provider/spec/services/supplied_product_builder_spec.rb
  swagger/dfc.yaml
Labels: pr-staged-uk, api changes

#12041 Remove migrations with faulty ids
  db/bad_migrations/20231002000136871_add_foreign_key_to_spree_stock_items_spree_stock_locations.rb
  db/bad_migrations/20231002000136872_add_foreign_key_to_spree_stock_items_spree_variants.rb
  db/bad_migrations/20231002000136876_add_foreign_key_to_spree_shipping_method_categories_spree_shipping_methods.rb
  db/bad_migrations/20231002000136877_add_foreign_key_to_spree_shipping_method_categories_spree_shipping_categories.rb
  db/bad_migrations/20231002000136879_add_foreign_key_to_report_rendering_options_spree_users.rb
  db/bad_migrations/20231002000136926_add_foreign_key_to_tag_rules_enterprises.rb
  db/bad_migrations/20231002000136952_add_foreign_key_to_spree_stock_movements_spree_stock_items.rb
  db/bad_migrations/20231002000136955_add_foreign_key_to_spree_stock_locations_spree_states.rb
  db/bad_migrations/20231002000136959_add_foreign_key_to_spree_stock_locations_spree_countries.rb
  db/bad_migrations/20231002000136976_add_foreign_key_to_spree_shipments_spree_stock_locations.rb
  db/bad_migrations/20231002000137115_add_foreign_key_to_inventory_items_enterprises.rb
  db/bad_migrations/20231002000137116_add_foreign_key_to_inventory_items_spree_variants.rb
  db/bad_migrations/20231003000823494_add_foreign_key_to_spree_orders_spree_users_created_by_id.rb
  db/migrate/20240115022359_rename_offending_migrations.rb
  db/schema.rb
  spec/models/database_spec.rb
Labels: technical changes only

#12048 [BUU] Add new product images
  app/controllers/spree/admin/images_controller.rb
  app/reflexes/products_reflex.rb
  app/views/admin/products_v3/_edit_image.html.haml
  app/views/admin/products_v3/_table.html.haml
  config/locales/en.yml
  spec/requests/admin/images_spec.rb
  spec/system/admin/products_v3/products_spec.rb
Labels: feature toggled

#12079 Remove automatic pre-commit hook
  .husky/pre-commit
  package.json
  yarn.lock
Labels: technical changes only

#12074 [Stripe, VCR] Updates credit_card_cloner_spec.rb
  spec/fixtures/vcr_cassettes/Stripe-v10.3.0/Stripe_CreditCardCloner/_find_or_clone/when_called_with_a_card_without_a_customer_one_time_usage_card_/clones_the_payment_method_only.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.6.0/Stripe_CreditCardCloner/_find_or_clone/when_called_with_a_card_without_a_customer_one_time_usage_card_/clones_the_payment_method_only.yml
  spec/fixtures/vcr_cassettes/Stripe-v10.6.0/Stripe_CreditCardCloner/_find_or_clone/when_called_with_a_valid_customer_and_payment_method/clones_both_the_payment_method_and_the_customer.yml
  spec/lib/stripe/credit_card_cloner_spec.rb
Labels: technical changes only

#12098 [Pending spec] Updates distributor to have a shopfront message (reproduces #12076)
  spec/system/consumer/shopping/shopping_spec.rb
Labels: technical changes only

#12068 Add promo image to DFC Enterprise API
  engines/dfc_provider/app/services/enterprise_builder.rb
  engines/dfc_provider/spec/requests/enterprises_spec.rb
  spec/factories/enterprise_factory.rb
  swagger/dfc.yaml
Labels: api changes

#12078 Prompt for nodenv when missing
  script/nodenv-install.sh
Labels: technical changes only

#12047 Include Tax on enterprise fees on the invoice
  app/helpers/tax_helper.rb
  app/models/enterprise_fee_adjustments.rb
  app/models/invoice/data_presenter/line_item.rb
  app/models/spree/line_item.rb
  app/serializers/invoice/line_item_serializer.rb
  spec/helpers/tax_helper_spec.rb
  spec/models/enterprise_fee_adjustments_spec.rb
  spec/models/invoice/data_presenter/line_item_spec.rb
Labels: pr-staged-au

#12075 Actions dropdown should stay closed after shipping order
  app/views/spree/admin/shared/_order_links.html.haml
Labels: pr-staged-au

#12084 Replace toggle_controller with method inside generic controller
  app/views/checkout/_details.html.haml
  app/webpacker/controllers/toggle_control_controller.js
  app/webpacker/controllers/toggle_controller.js
  spec/javascripts/stimulus/toggle_control_controller_test.js
  spec/javascripts/stimulus/toggle_controller_test.js
Labels: pr-staged-au

#12093 Display a warning when clicking the generate invoice button if an ABN is required but not present
  app/helpers/spree/admin/orders_helper.rb
  app/views/spree/admin/invoices/index.html.haml
  config/locales/en.yml
  spec/controllers/spree/admin/orders/invoices_spec.rb
  spec/system/admin/order_spec.rb
Labels: pr-staged-uk, technical changes only
