Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2025-05, with the labels that each got.

#13252 [Variant tags] Add variant tag on Bulk Edit Product screen
  app/components/example_component/example_component.html.haml
  app/components/example_component/example_controller.js
  app/components/tag_list_input_component.rb
  app/components/tag_list_input_component/tag_list_input_component.html.haml
  app/components/tag_list_input_component/tag_list_input_component.scss
  app/components/tag_list_input_component/tag_list_input_controller.js
  app/models/spree/variant.rb
  app/services/permitted_attributes/variant.rb
  app/views/admin/products_v3/_product_row.html.haml
  app/views/admin/products_v3/_product_variant_row.html.haml
  app/views/admin/products_v3/_table.html.haml
  app/views/admin/products_v3/_variant_row.html.haml
  app/webpacker/controllers/bulk_form_controller.js
  app/webpacker/controllers/column_preferences_controller.js
  app/webpacker/css/admin/products_v3.scss
  app/webpacker/css/admin_v3/all.scss
  config/locales/en.yml
  lib/open_food_network/column_preference_defaults.rb
  lib/open_food_network/feature_toggle.rb
  spec/javascripts/stimulus/bulk_form_controller_test.js
  spec/javascripts/stimulus/tag_list_input_controller_test.js
  spec/jobs/open_order_cycle_job_spec.rb
Labels: pr-staged-fr, feature toggled

#13285 Fixes Rubocop Naming NamingMemoizedInstanceVariableName cop
  .rubocop_styleguide.yml
  .rubocop_todo.yml
  app/mailers/producer_mailer.rb
  app/models/concerns/balance.rb
Labels: feedback-needed, technical changes only

#13286 Rubocop Style corrections
  .rubocop_todo.yml
  app/controllers/admin/column_preferences_controller.rb
  app/controllers/admin/enterprises_controller.rb
  app/controllers/admin/variant_overrides_controller.rb
  app/controllers/spree/admin/products_controller.rb
  app/controllers/spree/admin/shipping_methods_controller.rb
  app/forms/enterprise_fees_bulk_update.rb
  app/models/product_import/entry_processor.rb
  app/models/product_import/product_importer.rb
  app/models/spree/preferences/configuration.rb
  app/models/tag_rule/filter_order_cycles.rb
  app/models/tag_rule/filter_payment_methods.rb
  app/models/tag_rule/filter_products.rb
  app/models/tag_rule/filter_shipping_methods.rb
  app/serializers/api/admin/exchange_serializer.rb
  app/services/sets/model_set.rb
  app/services/variants_stock_levels.rb
  lib/open_food_network/tag_rule_applicator.rb
  lib/reporting/reports/sales_tax/sales_tax_totals_by_producer.rb
  spec/controllers/admin/inventory_items_controller_spec.rb
  spec/controllers/admin/variant_overrides_controller_spec.rb
  spec/models/product_importer_spec.rb
  spec/support/cancan_helper.rb
  spec/support/matchers/select2_matchers.rb
Labels: technical changes only

#13279 Reproduces bug #12933, setting the test case as pending
  spec/system/admin/product_import_spec.rb
Labels: technical changes only

#13298 Cleanup AddressFinder
  .rubocop_styleguide.yml
  app/controllers/concerns/checkout_callbacks.rb
  app/serializers/api/admin/subscription_customer_serializer.rb
  app/serializers/api/admin/user_serializer.rb
  lib/open_food_network/address_finder.rb
  spec/lib/open_food_network/address_finder_spec.rb
Labels: technical changes only

#13299 Fixes NamingMethodParameterName rubocop offense
  .rubocop_todo.yml
  app/controllers/payment_gateways/stripe_controller.rb
  app/services/process_payment_intent.rb
  spec/services/process_payment_intent_spec.rb
Labels: technical changes only

#13300 Adds tests to toggle the css sections (distributed products)
  spec/system/admin/order_cycles/simple_spec.rb
Labels: technical changes only

#13305 Split system specs
  spec/system/admin/fees_on_orders_spec.rb
  spec/system/admin/order_spec.rb
  spec/system/consumer/shopping/shopfront_order_cycles_spec.rb
  spec/system/consumer/shopping/shopping_spec.rb
Labels: technical changes only

#13292 Process order cycle emails individually to avoid duplicates
  app/jobs/order_cycle_notification_job.rb
  spec/jobs/order_cycle_notification_job_spec.rb
Labels: prod-test, user facing changes

#13291 Fix #11967 - limit variant unit name input
  app/views/admin/products_v3/_variant_row.html.haml
  app/views/spree/admin/products/new.html.haml
Labels: pr-staged-fr, user facing changes

#13293 Fixes StimulusJS error on printing w bulk action
  app/webpacker/controllers/file_loading_controller.js
Labels: pr-staged-fr, technical changes only

#13311 Remove useless method
  app/models/spree/stock_item.rb
Labels: technical changes only

#13303 Remove old integrations and rebalance specs
  .github/workflows/brakeman-analysis.yml
  .github/workflows/build.yml
  .github/workflows/linters.yml
  .github/workflows/mapi.yml
Labels: technical changes only

#13306 Fixes Rubocop naming variable number
  .rubocop_styleguide.yml
  .rubocop_todo.yml
  app/controllers/spree/orders_controller.rb
  lib/spree/core/controller_helpers/common.rb
  spec/controllers/spree/admin/search_controller_spec.rb
  spec/models/spree/stock_item_spec.rb
  spec/requests/api/orders_spec.rb
Labels: technical changes only

#13325 Fixes RSpecRails HaveHttpStatus rubocop offenses
  .rubocop_todo.yml
  spec/controllers/admin/bulk_line_items_controller_spec.rb
  spec/controllers/admin/order_cycles_controller_spec.rb
  spec/controllers/admin/subscriptions_controller_spec.rb
  spec/controllers/api/v0/base_controller_spec.rb
  spec/controllers/api/v0/customers_controller_spec.rb
  spec/controllers/api/v0/enterprises_controller_spec.rb
  spec/controllers/api/v0/logos_controller_spec.rb
  spec/controllers/api/v0/order_cycles_controller_spec.rb
  spec/controllers/api/v0/orders_controller_spec.rb
  spec/controllers/api/v0/product_images_controller_spec.rb
  spec/controllers/api/v0/products_controller_spec.rb
  spec/controllers/api/v0/promo_images_controller_spec.rb
  spec/controllers/api/v0/reports/packing_report_spec.rb
  spec/controllers/api/v0/reports_controller_spec.rb
  spec/controllers/api/v0/shipments_controller_spec.rb
  spec/controllers/api/v0/statuses_controller_spec.rb
  spec/controllers/api/v0/taxons_controller_spec.rb
  spec/controllers/api/v0/terms_and_conditions_controller_spec.rb
  spec/controllers/api/v0/variants_controller_spec.rb
  spec/controllers/cart_controller_spec.rb
  spec/controllers/checkout_controller_spec.rb
  spec/controllers/enterprises_controller_spec.rb
  spec/controllers/line_items_controller_spec.rb
  spec/controllers/shop_controller_spec.rb
  spec/controllers/spree/admin/orders/payments/payments_controller_spec.rb
  spec/controllers/spree/admin/orders_controller_spec.rb
  spec/controllers/spree/admin/products_controller_spec.rb
  spec/controllers/spree/credit_cards_controller_spec.rb
  spec/controllers/spree/orders_controller_spec.rb
  spec/controllers/stripe/callbacks_controller_spec.rb
  spec/controllers/stripe/webhooks_controller_spec.rb
  spec/controllers/user_passwords_controller_spec.rb
  spec/controllers/user_registrations_controller_spec.rb
  spec/requests/api/routes_spec.rb
  spec/requests/checkout/stripe_sca_spec.rb
  spec/requests/home_controller_spec.rb
  spec/requests/omniauth_callbacks_controller_spec.rb
  spec/services/embedded_page_service_spec.rb
  spec/support/api_helper.rb
Labels: technical changes only

#13328 Fix typo in yml files: exiting vs. existing
  config/locales/en.yml
  config/locales/en_AU.yml
  config/locales/en_BE.yml
  config/locales/en_CA.yml
  config/locales/en_DE.yml
  config/locales/en_FR.yml
  config/locales/en_GB.yml
  config/locales/en_IE.yml
  config/locales/en_IN.yml
  config/locales/en_NZ.yml
  config/locales/en_PH.yml
  config/locales/en_ZA.yml
Labels: user facing changes

#13263 Fix Order Cycle search on BOM page is not working for more than 5 OCs
  app/assets/javascripts/admin/line_items/controllers/line_items_controller.js.coffee
  spec/system/admin/bulk_order_management_spec.rb
Labels: bug-s3, pr-staged-fr, user facing changes

#13310 Fix product reset on import
  engines/catalog/app/services/catalog/product_import/products_reset_strategy.rb
  spec/system/admin/product_import_spec.rb
Labels: bug-s2, user facing changes

#13313 Fixes dotted shipping method names bad display in select (filters)
  app/views/spree/admin/orders/_filters.html.haml
  config/locales/ar.yml
  config/locales/ca.yml
  config/locales/cy.yml
  config/locales/de_CH.yml
  config/locales/de_DE.yml
  config/locales/el.yml
  config/locales/en.yml
  config/locales/en_CA.yml
  config/locales/en_FR.yml
  config/locales/en_GB.yml
  config/locales/en_IE.yml
  config/locales/en_US.yml
  config/locales/es.yml
  config/locales/eu.yml
  config/locales/fr.yml
  config/locales/fr_CA.yml
  config/locales/fr_CH.yml
  config/locales/fr_CM.yml
  config/locales/hi.yml
  config/locales/hu.yml
  config/locales/it.yml
  config/locales/it_CH.yml
  config/locales/ko.yml
  config/locales/ml.yml
  config/locales/mr.yml
  config/locales/nb.yml
  config/locales/pa.yml
  config/locales/ru.yml
  config/locales/sr.yml
  config/locales/uk.yml
  spec/system/admin/orders/bulk_actions_spec.rb
  spec/system/admin/orders_spec.rb
Labels: pr-staged-uk, user facing changes

#13318 Prevent error on inventory page when logged out
  app/controllers/admin/variant_overrides_controller.rb
  spec/controllers/admin/variant_overrides_controller_spec.rb
Labels: user facing changes

#13312 Stop creating stock movements
  app/models/concerns/variant_stock.rb
  app/models/spree/ability.rb
  app/models/spree/order_inventory.rb
  app/models/spree/return_authorization.rb
  app/models/spree/shipment.rb
  app/models/spree/stock_item.rb
  app/models/spree/stock_movement.rb
  lib/open_food_network/scope_variant_to_hub.rb
  spec/factories/stock_movement_factory.rb
  spec/models/spree/ability_spec.rb
  spec/models/spree/inventory_unit_spec.rb
  spec/models/spree/order_inventory_spec.rb
  spec/models/spree/product_spec.rb
  spec/models/spree/shipment_spec.rb
  spec/models/spree/stock_item_spec.rb
  spec/models/spree/stock_movement_spec.rb
Labels: pr-staged-fr, technical changes only

#13262 Remove Angular from the Settings > Images section
  app/assets/javascripts/admin/enterprises/controllers/enterprise_controller.js.coffee
  app/assets/javascripts/admin/resources/resources/enterprise_resource.js.coffee
  app/assets/javascripts/admin/resources/services/enterprises.js.coffee
  app/controllers/admin/enterprises_controller.rb
  app/helpers/admin/enterprises_helper.rb
  app/models/enterprise.rb
  app/reflexes/concerns/enterprise_concern.rb
  app/reflexes/white_label_reflex.rb
  app/services/permitted_attributes/enterprise.rb
  app/views/admin/enterprises/form/_images.html.haml
  app/views/admin/enterprises/form/_white_label.html.haml
  app/views/admin/enterprises/update.turbo_stream.haml
  app/views/admin/shared/_attachment_field.html.haml
  config/locales/en.yml
  spec/javascripts/unit/admin/enterprises/controllers/enterprise_controller_spec.js.coffee
  spec/javascripts/unit/admin/enterprises/services/enterprises_spec.js.coffee
  spec/system/admin/enterprises/images_spec.rb
  spec/views/admin/shared/_attachment_field.html.haml_spec.rb
Labels: technical changes only

#13326 Change the layout for instance configuration options
  app/views/spree/admin/general_settings/edit.html.haml
  app/webpacker/css/admin_v3/shared/forms.scss
Labels: pr-staged-uk, user facing changes
