Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2025-08, with the labels that each got.

#13440 Remove unused test helper
  spec/base_spec_helper.rb
  spec/support/request/distribution_helper.rb
Labels: technical changes only

#13441 Check more code for coverage
  .github/workflows/build.yml
  .rubocop_styleguide.yml
  .simplecov
  .undercover
  Gemfile
  Gemfile.lock
  lib/tasks/simplecov.rake
  spec/lib/tasks/simplecov_spec.rb
Labels: technical changes only

#13436 Decommission Old Products UI and Related Code
  app/assets/javascripts/admin/bulk_product_update.js.coffee
  app/assets/javascripts/admin/products/controllers/product_image_controller.js.coffee
  app/assets/javascripts/admin/products/directives/image_modal.js.coffee
  app/assets/javascripts/admin/resources/resources/product_resource.js.coffee
  app/assets/javascripts/admin/services/bulk_products.js.coffee
  app/controllers/spree/admin/products_controller.rb
  app/helpers/admin/products_helper.rb
  app/helpers/spree/admin/navigation_helper.rb
  app/views/admin/products_v3/_table.html.haml
  app/views/admin/shared/_stimulus_pagination.html.haml
  app/views/spree/admin/products/edit.html.haml
  app/views/spree/admin/products/index.html.haml
  app/views/spree/admin/products/index/_actions.html.haml
  app/views/spree/admin/products/index/_data.html.haml
  app/views/spree/admin/products/index/_filters.html.haml
  app/views/spree/admin/products/index/_header.html.haml
  app/views/spree/admin/products/index/_indicators.html.haml
  app/views/spree/admin/products/index/_products.html.haml
  app/views/spree/admin/products/index/_products_head.html.haml
  app/views/spree/admin/products/index/_products_product.html.haml
  app/views/spree/admin/products/index/_products_variant.html.haml
  app/views/spree/admin/products/index/_save_button_row.html.haml
  app/views/spree/admin/shared/_head.html.haml
  app/views/spree/admin/shared/_product_sub_menu.html.haml
  app/views/spree/admin/shared/_tabs.html.haml
  app/webpacker/css/admin/all.scss
  app/webpacker/css/admin/components/actions.scss
  app/webpacker/css/admin/components/buttons.scss
  app/webpacker/css/admin/components/date-picker.scss
  app/webpacker/css/admin/components/messages.scss
  app/webpacker/css/admin/components/navigation.scss
  app/webpacker/css/admin/components/pagination.scss
  app/webpacker/css/admin/components/sidebar.scss
  app/webpacker/css/admin/components/tom_select.scss
  app/webpacker/css/admin/globals/variables.scss
  app/webpacker/css/admin/plugins/flatpickr-customization.scss
  app/webpacker/css/admin/plugins/powertip.scss
  app/webpacker/css/admin/sections/orders.scss
  app/webpacker/css/admin/shared/forms.scss
  app/webpacker/css/admin/shared/icons.scss
  app/webpacker/css/admin/shared/layout.scss
  app/webpacker/css/admin/shared/tables.scss
  app/webpacker/css/admin/shared/typography.scss
  app/webpacker/css/admin/terms_of_service_banner.scss
  app/webpacker/packs/admin-styles.scss
  config/routes/admin.rb
  config/routes/spree.rb
  db/migrate/20240625024328_activate_admin_style_v3_for_new_users.rb
  db/migrate/20240710013128_enable_feature_admin_style_v3_for_admins.rb
  db/migrate/20240715103415_enable_admin_style_v3_by_default.rb
  db/migrate/20240718150852_activate_admin_style_v3_for_25_p_cent_users.rb
  db/migrate/20240731065321_activate_admin_style_v3_for50_pc_users.rb
  db/migrate/20240810150912_activate_admin_style_v3_for75_pc_users.rb
  db/migrate/20240828203544_fully_enable_admin_style_v3_flag.rb
  lib/open_food_network/feature_toggle.rb
  spec/controllers/spree/admin/products_controller_spec.rb
  spec/javascripts/unit/admin/bulk_product_update_spec.js.coffee
  spec/javascripts/unit/admin/services/bulk_products_spec.js.coffee
Labels: tech debt, pr-staged-au, technical changes only

#13232 Bump Rails to 7.1
  Gemfile.lock
  app/controllers/api/v1/base_controller.rb
  config/environments/test.rb
  spec/jobs/open_order_cycle_job_spec.rb
  spec/services/orders/generate_invoice_service_spec.rb
Labels: pr-staged-fr, technical changes only

#13447 Report code coverage on rake tasks
  .simplecov
  lib/tasks/simplecov.rake
  spec/lib/tasks/data/truncate_data_rake_spec.rb
  spec/lib/tasks/enterprises_rake_spec.rb
  spec/lib/tasks/import_product_images_rake_spec.rb
  spec/lib/tasks/reset_spec.rb
  spec/lib/tasks/sample_data_rake_spec.rb
  spec/lib/tasks/simplecov_spec.rb
  spec/lib/tasks/users_rake_spec.rb
  spec/support/shared_contexts/rake.rb
Labels: technical changes only

#13450 Losen engine gemspec requirement for Dependabot
  engines/catalog/catalog.gemspec
  engines/dfc_provider/dfc_provider.gemspec
  engines/order_management/order_management.gemspec
  engines/web/web.gemspec
Labels: technical changes only

#13453 Allow only existing deprecations in Rails 7.1
  config/environments/test.rb
  spec/base_spec_helper.rb
Labels: technical changes only

#13444 Added cmake dep to dockerfile and added script for db:schema:load tha…
  Dockerfile
  Dockerfile.ubuntu
  compose.yaml
Labels: technical changes only

#13480 Replace Timecop with Rails' time helpers
  Gemfile
  Gemfile.lock
  engines/dfc_provider/spec/services/affiliate_sales_query_spec.rb
  spec/base_spec_helper.rb
  spec/jobs/heartbeat_job_spec.rb
  spec/jobs/open_order_cycle_job_spec.rb
  spec/jobs/webhook_delivery_job_spec.rb
  spec/lib/reports/enterprise_fee_summary/renderers/csv_renderer_spec.rb
  spec/lib/reports/xero_invoices_report_spec.rb
  spec/models/enterprise_caching_spec.rb
  spec/models/order_cycle_spec.rb
  spec/models/proxy_order_spec.rb
  spec/models/terms_of_service_file_spec.rb
  spec/services/vine/jwt_service_spec.rb
  spec/support/timecop.rb
  spec/system/admin/enterprises/terms_and_conditions_spec.rb
  spec/system/admin/reports/orders_and_distributors_spec.rb
  spec/system/admin/reports/orders_and_fulfillment_spec.rb
  spec/system/admin/reports/packing_report_spec.rb
  spec/system/admin/reports_spec.rb
  spec/system/consumer/authentication_spec.rb
  spec/system/consumer/caching/shops_caching_spec.rb
Labels: technical changes only

#13468 Add Rails 7.0 and 7.1 framework defaults
  app/models/application_record.rb
  config/application.rb
  config/boot.rb
  config/environment.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/assets.rb
  config/initializers/content_security_policy.rb
  config/initializers/filter_parameter_logging.rb
  config/initializers/inflections.rb
  config/initializers/new_framework_defaults_7_0.rb
  config/initializers/new_framework_defaults_7_1.rb
  config/initializers/permissions_policy.rb
Labels: pr-staged-uk, technical changes only

#13503 Fix missed I18n translations for enterprises sells options
  app/helpers/admin/enterprises_helper.rb
  app/views/admin/enterprises/_admin_index.html.haml
  config/locales/en.yml
  spec/helpers/admin/enterprises_helper_spec.rb
Labels: pr-staged-au, user facing changes

#13512 Remove remaining Timecop usage
  engines/dfc_provider/spec/services/authorization_control_spec.rb
  engines/dfc_provider/spec/support/shared_contexts/authenticated_as_platform.rb
Labels: technical changes only
