Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2025-09, with the labels that each got.

#13404 Fixes Save button does not enable when removing only tag in OC
  app/assets/javascripts/templates/admin/panels/exchange_tags.html.haml
  app/views/admin/order_cycles/_exchange_form.html.haml
  spec/system/admin/order_cycles/tags_spec.rb
Labels: user facing changes

#13487 Fix url sanitization for Stripe authorisation URL
  lib/stripe/authorize_response_patcher.rb
  spec/lib/stripe/authorize_response_patcher_spec.rb
Labels: technical changes only

#13530 Remove retired hub_address feature
  app/views/checkout/_summary.html.haml
  lib/open_food_network/feature_toggle.rb
Labels: pr-staged-au, technical changes only
