Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2025-06, with the labels that each got.

#13341 Rubocop Style corrections for Style/NestedModifier and Style/ReturnNilInPredicateMethodDefinition
  .rubocop_todo.yml
  app/models/order_cycle.rb
  app/serializers/api/admin/customer_serializer.rb
  engines/order_management/app/services/order_management/subscriptions/validator.rb
  spec/controllers/admin/subscriptions_controller_spec.rb
  spec/controllers/line_items_controller_spec.rb
  spec/controllers/spree/admin/orders_controller_spec.rb
  spec/controllers/spree/orders_controller_spec.rb
  spec/factories/order_factory.rb
  spec/models/proxy_order_spec.rb
  spec/models/spree/line_item_spec.rb
  spec/services/place_proxy_order_spec.rb
  spec/system/admin/payments_stripe_spec.rb
  spec/system/admin/reports_spec.rb
Labels: technical changes only

#13349 Clarify voucher code not found can mean fully redeemed
  app/controllers/voucher_adjustments_controller.rb
  config/locales/en.yml
  spec/requests/voucher_adjustments_spec.rb
  spec/system/consumer/checkout/payment_spec.rb
Labels: pr-staged-au, user facing changes

#13367 Bump stimulus_reflex gem to 3.5.5
  Gemfile.lock
Labels: technical changes only

#13163 Fixes Rails/UniqueValidationWithoutIndex (part of #11482)
  .rubocop_todo.yml
  db/migrate/20250214192930_add_unique_index_email_entreprise_to_customers.rb
  db/migrate/20250214200526_add_unique_index_sender_id_and_others_to_exchanges.rb
  db/migrate/20250215083320_add_unique_index_variant_id_and_deleted_at_to_stock_items.rb
  db/migrate/20250215085838_add_unique_index_name_and_deleted_at_to_tax_categories.rb
  db/migrate/20250215091227_add_unique_index_name_to_zones.rb
  db/schema.rb
Labels: technical changes only, breaking change

#13362 Add Finnish to flatpickr controller
  app/webpacker/controllers/flatpickr_controller.js
Labels: pr-staged-au, user facing changes

#13374 Adds Unit price checks
  spec/system/admin/unit_price_spec.rb
  spec/system/consumer/shopping/orders_spec.rb
  spec/system/consumer/shopping/unit_price_spec.rb
Labels: technical changes only

#13379 Map currency to DFC codes
  engines/dfc_provider/app/services/offer_builder.rb
  engines/dfc_provider/lib/dfc_provider.rb
  engines/dfc_provider/lib/semantic_object_inspect.rb
  engines/dfc_provider/spec/lib/semantic_object_inspect_spec.rb
  engines/dfc_provider/spec/services/offer_builder_spec.rb
  swagger/dfc.yaml
Labels: api changes

#13384 Fixes offenses Metrics/ModuleLength in engines spec
  .rubocop_todo.yml
  engines/catalog/spec/services/catalog/product_import/products_reset_strategy_spec.rb
  engines/order_management/spec/services/order_management/order/updater_spec.rb
  engines/order_management/spec/services/order_management/stock/package_spec.rb
  engines/order_management/spec/services/order_management/subscriptions/estimator_spec.rb
  engines/order_management/spec/services/order_management/subscriptions/form_spec.rb
  engines/order_management/spec/services/order_management/subscriptions/proxy_order_syncer_spec.rb
  engines/order_management/spec/services/order_management/subscriptions/summarizer_spec.rb
  engines/order_management/spec/services/order_management/subscriptions/summary_spec.rb
  engines/order_management/spec/services/order_management/subscriptions/validator_spec.rb
  engines/order_management/spec/services/order_management/subscriptions/variants_list_spec.rb
  spec/lib/open_food_network/address_finder_spec.rb
  spec/lib/open_food_network/order_cycle_form_applicator_spec.rb
  spec/lib/open_food_network/order_cycle_permissions_spec.rb
  spec/lib/open_food_network/permissions_spec.rb
  spec/lib/open_food_network/scope_variant_to_hub_spec.rb
  spec/lib/open_food_network/tag_rule_applicator_spec.rb
  spec/lib/reports/all_products_spec.rb
  spec/lib/reports/customers_report_spec.rb
  spec/lib/reports/enterprise_fee_summary/authorizer_spec.rb
  spec/lib/reports/order_cycle_management_report_spec.rb
  spec/lib/reports/products_and_inventory_report_spec.rb
  spec/lib/reports/users_and_enterprises_report_spec.rb
  spec/models/spree/adjustment_spec.rb
  spec/models/spree/credit_card_spec.rb
  spec/models/spree/line_item_spec.rb
  spec/models/spree/order/tax_spec.rb
  spec/models/spree/product_spec.rb
  spec/models/spree/shipping_method_spec.rb
  spec/models/spree/tax_rate_spec.rb
  spec/services/permissions/order_spec.rb
  spec/services/variant_units/option_value_namer_spec.rb
Labels: technical changes only

#13342 refactor: move unit price formatting logic out of model into helper
  app/helpers/spree/orders_helper.rb
  app/models/invoice/data_presenter/line_item.rb
  app/models/spree/line_item.rb
  app/serializers/invoice/line_item_serializer.rb
  app/views/spree/admin/orders/_invoice/_line_item_name.html.haml
  app/views/spree/orders/_bought.html.haml
  app/views/spree/orders/_line_item.html.haml
Labels: pr-staged-fr, technical changes only
