Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2025-02, with the labels that each got.

#13109 DFC import: Find broader taxon if we don't have a specific one
  engines/dfc_provider/app/services/dfc_product_type_factory.rb
  engines/dfc_provider/app/services/product_type_importer.rb
  engines/dfc_provider/app/services/supplied_product_builder.rb
  engines/dfc_provider/spec/services/dfc_product_type_factory_spec.rb
  engines/dfc_provider/spec/services/product_type_importer_spec.rb
Labels: technical changes only

#13120 Update caniuse-lite
  yarn.lock
Labels: technical changes only

#13037 Add columns to "pay your supplier" report
  config/locales/en.yml
  lib/reporting/reports/suppliers/base.rb
  lib/reporting/reports/suppliers/helpers/columns_helper.rb
  lib/reporting/reports/suppliers/helpers/line_items_access_helper.rb
  spec/lib/reports/suppliers/pay_your_suppliers_report_spec.rb
  spec/system/admin/reports/pay_your_suppliers_spec.rb
Labels: user facing changes

#13122 Add option to define your own rubocop command
  script/rubocop-diff.sh
Labels: technical changes only

#13135 Fix flaky payment method spec
  spec/system/admin/payment_method_spec.rb
Labels: technical changes only

#13136 Hopefully fix flaky OC spec
  spec/system/admin/order_cycles/simple_spec.rb
Labels: technical changes only

#13141 Report DFC server errors to Bugsnag
  app/services/alert.rb
  config/initializers/bugsnag.rb
  engines/dfc_provider/app/services/dfc_request.rb
  engines/dfc_provider/spec/services/dfc_request_spec.rb
  spec/services/alert_spec.rb
Labels: technical changes only

#12621 Keep stock selection when error on saving
  .rubocop_todo.yml
  app/models/concerns/variant_stock.rb
  app/models/spree/variant.rb
  app/services/permitted_attributes/variant.rb
  app/services/sets/product_set.rb
  app/views/admin/products_v3/_variant_row.html.haml
  spec/system/admin/products_v3/create_spec.rb
  spec/system/admin/products_v3/update_spec.rb
Labels: feature toggled

#13115 Catch error and provide message
  app/controllers/omniauth_callbacks_controller.rb
  config/locales/en.yml
  spec/requests/omniauth_callbacks_controller_spec.rb
Labels: pr-staged-uk, feedback-needed, technical changes only

#13131 Updating form field borders for better contrast
  app/webpacker/css/admin/globals/variables.scss
  app/webpacker/css/admin/tag_rules.scss
  app/webpacker/css/admin_v3/components/select2.scss
  app/webpacker/css/admin_v3/components/tom_select.scss
  app/webpacker/css/admin_v3/globals/variables.scss
  app/webpacker/css/admin_v3/shared/forms.scss
Labels: pr-staged-fr, user facing changes

#13125 [DFC Orders] List products to import on screen
  app/controllers/admin/dfc_product_imports_controller.rb
  app/models/spree/ability.rb
  app/views/admin/dfc_product_imports/import.html.haml
  app/views/admin/dfc_product_imports/index.html.haml
  app/views/admin/product_import/_dfc_import_form.html.haml
  config/locales/en.yml
  config/routes/admin.rb
  spec/system/admin/dfc_product_import_spec.rb
Labels: pr-staged-fr, user facing changes

#13146 Bump datafoodconsortium-connector to support product variants
  Gemfile.lock
  engines/dfc_provider/app/services/dfc_loader.rb
  engines/dfc_provider/spec/requests/offers_spec.rb
  engines/dfc_provider/vendor/context_1.8.2.json
Labels: technical changes only

#13158 Quick beautification of test email
  app/views/spree/test_mailer/test_email.html.haml
Labels: user facing changes

#13162 Delete old, unused script/rails
  script/rails
Labels: technical changes only

#13154 Fix order of line item based report rows
  lib/reporting/line_items.rb
Labels: pr-staged-au, user facing changes

#13165 Fix base urls for assets in development
  .env.development
  app/mailers/application_mailer.rb
  app/views/layouts/mailer.html.haml
  config/environments/development.rb
Labels: bug-s4

#13148 Add DFC product groups with variants
  app/controllers/admin/dfc_product_imports_controller.rb
  app/models/spree/product.rb
  engines/dfc_provider/app/controllers/dfc_provider/catalog_items_controller.rb
  engines/dfc_provider/app/controllers/dfc_provider/product_groups_controller.rb
  engines/dfc_provider/app/controllers/dfc_provider/supplied_products_controller.rb
  engines/dfc_provider/app/services/dfc_catalog.rb
  engines/dfc_provider/app/services/product_group_builder.rb
  engines/dfc_provider/app/services/supplied_product_builder.rb
  engines/dfc_provider/app/services/supplied_product_importer.rb
  engines/dfc_provider/config/routes.rb
  engines/dfc_provider/spec/requests/addresses_spec.rb
  engines/dfc_provider/spec/requests/affiliate_sales_data_spec.rb
  engines/dfc_provider/spec/requests/catalog_items_spec.rb
  engines/dfc_provider/spec/requests/enterprise_groups/affiliated_by_spec.rb
  engines/dfc_provider/spec/requests/enterprise_groups_spec.rb
  engines/dfc_provider/spec/requests/enterprises_spec.rb
  engines/dfc_provider/spec/requests/offers_spec.rb
  engines/dfc_provider/spec/requests/persons_spec.rb
  engines/dfc_provider/spec/requests/product_groups_spec.rb
  engines/dfc_provider/spec/requests/social_medias_spec.rb
  engines/dfc_provider/spec/requests/supplied_products_spec.rb
  engines/dfc_provider/spec/services/supplied_product_builder_spec.rb
  engines/dfc_provider/spec/services/supplied_product_importer_spec.rb
  spec/base_spec_helper.rb
  spec/requests/api/v1/customers_spec.rb
  spec/swagger_helper.rb
  swagger/dfc.yaml
Labels: api changes

#13160 Add shipping method and shipment state to packing reports
  app/jobs/report_job.rb
  config/locales/en.yml
  lib/reporting/queries/joins.rb
  lib/reporting/queries/tables.rb
  lib/reporting/reports/packing/base.rb
  lib/reporting/reports/packing/customer.rb
  lib/reporting/reports/packing/product.rb
  lib/reporting/reports/packing/supplier.rb
  spec/controllers/api/v0/reports/packing_report_spec.rb
  spec/lib/reports/packing/packing_report_spec.rb
  spec/system/admin/reports/packing_report_spec.rb
Labels: pr-staged-au, user facing changes

#13164 Fix user controlled method execution
  app/controllers/spree/admin/orders_controller.rb
  config/locales/en.yml
  spec/controllers/spree/admin/orders_controller_spec.rb
Labels: pr-staged-uk, user facing changes

#13139 Add a 'reply to' email address where it makes sense and has been missing
  app/mailers/enterprise_mailer.rb
  app/mailers/payment_mailer.rb
  app/mailers/spree/order_mailer.rb
  app/mailers/spree/shipment_mailer.rb
Labels: pr-staged-au, user facing changes

#13126 Direct people to refresh OIDC connection when needed
  app/controllers/admin/dfc_product_imports_controller.rb
  app/webpacker/css/admin_v3/components/messages.scss
  config/locales/en.yml
  engines/dfc_provider/app/services/dfc_request.rb
  engines/dfc_provider/spec/services/dfc_request_spec.rb
  spec/fixtures/vcr_cassettes/DFC_Product_Import/prompts_to_refresh_OIDC_connection.yml
  spec/fixtures/vcr_cassettes/DfcRequest/clears_invalid_refresh_tokens.yml
  spec/system/admin/dfc_product_import_spec.rb
Labels: user facing changes

#13151 Fix reset stock when importing DFC products
  engines/dfc_provider/app/services/catalog_item_builder.rb
  engines/dfc_provider/spec/services/catalog_item_builder_spec.rb
Labels: user facing changes

#13156 Align inputs on orders list and adjust position of checkboxes for reports
  app/webpacker/css/admin/orders.scss
  app/webpacker/css/admin_v3/shared/forms.scss
Labels: pr-staged-fr, user facing changes

#13168 [DFC Orders] Select/deselect all on DFC Product Import
  app/views/admin/dfc_product_imports/index.html.haml
  app/views/admin/order_cycles/checkout_options.html.haml
  app/views/spree/admin/orders/_table.html.haml
  app/views/spree/admin/orders/_table_row.html.haml
  app/webpacker/controllers/checked_controller.js
  app/webpacker/css/admin_v3/all.scss
  app/webpacker/css/admin_v3/pages/dfc_product_imports.scss
  config/locales/en.yml
  spec/javascripts/stimulus/checked_controller_test.js
  spec/system/admin/dfc_product_import_spec.rb
Labels: pr-staged-fr, user facing changes

#13157 Create styled email for reset password instructions
  app/views/spree/user_mailer/reset_password_instructions.html.haml
  config/locales/en.yml
  spec/mailers/user_mailer_spec.rb
Labels: user facing changes

#13178 Fixes some rubocop linting offenses
  .rubocop_todo.yml
  app/models/spree/gateway.rb
  app/models/spree/order/checkout.rb
  app/models/spree/payment.rb
Labels: technical changes only
