Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2025-01, with the labels that each got.

#12867 Alert user when error requesting a report
  app/webpacker/js/turbo.js
  config/locales/en.yml
Labels: technical changes only

#13029 Add timepicker helper with added expectation to reduce flakiness
  spec/support/features/datepicker_helper.rb
  spec/system/admin/order_cycles/edit_spec.rb
Labels: technical changes only

#12998 Add 'Voucher:' before voucher code on order confirmation emails
  app/views/spree/order_mailer/_order_summary.html.haml
  config/locales/en.yml
  spec/mailers/order_mailer_spec.rb
Labels: pr-staged-au, user facing changes

#12979 Remove unused renderSvg, ofnDisableScroll, integer, ofnScrollTo angular directives
  app/assets/javascripts/darkswarm/directives/disable_scroll.js.coffee
  app/assets/javascripts/darkswarm/directives/integer.js.coffee
  app/assets/javascripts/darkswarm/directives/render_svg.js.coffee
  app/assets/javascripts/darkswarm/directives/scrollto.js.coffee
  app/webpacker/css/darkswarm/active_table_search.scss
  app/webpacker/css/darkswarm/shop_partials/_shop-filters.scss
  app/webpacker/css/darkswarm/taxons.scss
Labels: pr-staged-au, technical changes only

#13044 Remove old, replaced backorder lookup
  app/services/fdc_backorderer.rb
  spec/fixtures/vcr_cassettes/FdcBackorderer/_find_or_build_order_line/add_quantity_to_an_existing_line_item.yml
  spec/fixtures/vcr_cassettes/FdcBackorderer/creates_finds_and_updates_orders.yml
  spec/services/fdc_backorderer_spec.rb
Labels: technical changes only

#13057 Remove local storage
  app/assets/javascripts/admin/all.js
  app/assets/javascripts/admin/services/key_value_map_store.js.coffee
  app/assets/javascripts/darkswarm/all.js.coffee
  app/assets/javascripts/darkswarm/darkswarm.js.coffee
  app/assets/javascripts/darkswarm/services/cart.js.coffee
  app/assets/javascripts/shared/angular-local-storage.js
  app/assets/javascripts/shared/shared.js.coffee
  config/ng-test.conf.js
  spec/javascripts/unit/admin/services/key_value_map_store_spec.js.coffee
Labels: technical changes only

#12983 Back Office Product List - Hide search field and filters when there are no products in list
  app/views/admin/products_v3/_content.html.haml
  app/views/admin/products_v3/index.html.haml
Labels: pr-staged-au, technical changes only

#13011 Make Connected Apps links available in Transifex
  app/views/admin/enterprises/form/connected_apps/_affiliate_sales_data.html.haml
  app/views/admin/enterprises/form/connected_apps/_discover_regen.html.haml
  app/views/admin/enterprises/form/connected_apps/_vine.html.haml
  config/locales/en.yml
Labels: pr-staged-au, technical changes only

#13009 Added the :selected option with the default tax category #12989
  app/controllers/spree/admin/products_controller.rb
  app/helpers/spree/admin/tax_categories_helper.rb
  app/views/spree/admin/products/_tax_category_form.html.haml
  spec/helpers/spree/admin/tax_categories_helper_spec.rb
Labels: pr-staged-au, user facing changes

#12991 Remove product SKU from product pages and report
  app/assets/javascripts/admin/bulk_product_update.js.coffee
  app/views/admin/products_v3/_product_row.html.haml
  lib/reporting/reports/orders_and_distributors/base.rb
  spec/lib/reports/orders_and_distributors_report_spec.rb
  spec/system/admin/products_v3/update_spec.rb
  spec/system/admin/reports/orders_and_distributors_spec.rb
Labels: pr-staged-au, user facing changes

#13049 Calculate stock from DFC wholesale variants
  app/controllers/admin/dfc_product_imports_controller.rb
  app/jobs/backorder_job.rb
  app/jobs/stock_sync_job.rb
  app/services/backorder_updater.rb
  app/services/fdc_offer_broker.rb
  engines/dfc_provider/app/services/dfc_catalog.rb
  engines/dfc_provider/spec/services/dfc_catalog_spec.rb
  spec/jobs/complete_backorder_job_spec.rb
  spec/services/fdc_backorderer_spec.rb
  spec/services/fdc_offer_broker_spec.rb
Labels: pr-staged-uk, user facing changes

#13036 Fix DFC catalog syncs for blank cart
  app/controllers/cart_controller.rb
  app/jobs/stock_sync_job.rb
  spec/jobs/stock_sync_job_spec.rb
Labels: bugsnag, pr-staged-uk, technical changes only

#13066 Fix flaky admin order spec
  spec/system/admin/order_spec.rb
Labels: technical changes only

#13074 Sync prod database schema
  db/migrate/20241211060023_remove_variant_default_value.rb
  db/migrate/20250113055412_customers_created_manually_remove_null.rb
  db/schema.rb
Labels: technical changes only

#13038 Add plural form for flower farming variant unit names
  config/locales/en.yml
Labels: pr-staged-fr, prod-test, user facing changes

#13047 Clarify that our only user role is "admin" and simplify code
  app/controllers/admin/products_v3_controller.rb
  app/controllers/api/v0/variants_controller.rb
  app/controllers/spree/admin/users_controller.rb
  app/helpers/shared_helper.rb
  app/models/enterprise.rb
  app/models/enterprise_fee.rb
  app/models/enterprise_group.rb
  app/models/exchange.rb
  app/models/order_cycle.rb
  app/models/spree/ability.rb
  app/models/spree/line_item.rb
  app/models/spree/order.rb
  app/models/spree/product.rb
  app/models/spree/role.rb
  app/models/spree/shipping_method.rb
  app/models/spree/user.rb
  app/queries/product_scope_query.rb
  app/views/spree/admin/users/_form.html.haml
  db/default/users.rb
  db/seeds.rb
  spec/controllers/admin/order_cycles_controller_spec.rb
  spec/controllers/api/v0/products_controller_spec.rb
  spec/controllers/spree/admin/mail_methods_controller_spec.rb
  spec/controllers/spree/admin/users_controller_spec.rb
  spec/lib/reports/orders_and_distributors_report_spec.rb
  spec/models/spree/ability_spec.rb
  spec/services/permissions/order_spec.rb
Labels: user facing changes

#13068 New variants should inherit tax category in UI
  app/helpers/admin/products_helper.rb
  spec/helpers/admin/products_helper_spec.rb
Labels: pr-staged-fr, user facing changes

#13077 Fix artifact download for Simplecov collation
  .github/workflows/build.yml
Labels: technical changes only

#13064 Don't show stock for on-demand inventory items
  app/controllers/admin/variant_overrides_controller.rb
  app/serializers/api/admin/variant_override_serializer.rb
  app/serializers/api/admin/variant_simple_serializer.rb
  spec/system/admin/variant_overrides_spec.rb
Labels: feedback-needed, user facing changes

#13076 Police migrations
  .rubocop_styleguide.yml
  db/default/countries.rb
  db/default/users.rb
  db/default/zones.rb
  db/seeds.rb
Labels: technical changes only

#13079 Publish price as in new DFC standard
  engines/dfc_provider/app/services/offer_builder.rb
  engines/dfc_provider/spec/services/offer_builder_spec.rb
  swagger/dfc.yaml
Labels: api changes

#13085 Reduce parallel CI runs from 45 to 27
  .github/workflows/build.yml
Labels: technical changes only

#13065 Admin updates can trigger new backorders until the order cycle is closed
  app/controllers/checkout_controller.rb
  app/jobs/amend_backorder_job.rb
  app/models/spree/order.rb
  app/services/backorder_updater.rb
  spec/jobs/amend_backorder_job_spec.rb
  spec/services/backorder_updater_spec.rb
  spec/system/consumer/checkout/backorder_spec.rb
Labels: pr-staged-uk, user facing changes

#13058 Remove unused app config options
  app/helpers/spree/base_helper.rb
  app/models/spree/app_configuration.rb
  config/application.rb
  db/migrate/20250103043626_delete_checkout_zone_and_currency_preferences.rb
  spec/base_spec_helper.rb
  spec/helpers/spree/base_helper_spec.rb
  spec/lib/spree/money_spec.rb
  spec/models/spree/adjustment_spec.rb
  spec/models/spree/order_spec.rb
  spec/models/spree/variant_spec.rb
  spec/system/admin/reports_spec.rb
Labels: pr-staged-au, technical changes only

#13023 [Checkout] Shipping fees update, remove order callback
  app/models/spree/order.rb
  app/views/spree/orders/_totals_footer.html.haml
  spec/controllers/admin/customers_controller_spec.rb
  spec/models/spree/order/payment_spec.rb
  spec/models/spree/order_contents_spec.rb
  spec/models/spree/order_spec.rb
  spec/system/admin/orders_spec.rb
  spec/system/consumer/shopping/checkout_paypal_spec.rb
  spec/system/consumer/shopping/checkout_stripe_spec.rb
Labels: pr-staged-fr, user facing changes

#13072 Update ActionCable config
  .env.development
  config/cable.yml
Labels: technical changes only

#13088 Remove unused helper module
  app/controllers/spree/api_keys_controller.rb
  app/controllers/spree/users_controller.rb
  lib/spree/core/controller_helpers.rb
Labels: technical changes only

#13089 Remove unneeded HAML upgrade script
  lib/haml_up.rb
  script/haml-up.rb
  spec/lib/haml_up_spec.rb
Labels: technical changes only

#13091 Fix flaky spec of order shipment
  spec/system/admin/order_spec.rb
Labels: technical changes only

#13087 Remove class Spree::StockLocation
  .rubocop_todo.yml
  app/assets/javascripts/admin/spree/orders/variant_autocomplete.js.erb
  app/controllers/api/v0/shipments_controller.rb
  app/models/concerns/variant_stock.rb
  app/models/spree/inventory_unit.rb
  app/models/spree/order_inventory.rb
  app/models/spree/shipment.rb
  app/models/spree/stock_item.rb
  app/models/spree/stock_location.rb
  app/models/spree/variant.rb
  app/queries/product_scope_query.rb
  app/serializers/api/admin/product_serializer.rb
  app/serializers/api/admin/variant_serializer.rb
  app/serializers/api/shipment_serializer.rb
  app/services/default_stock_location.rb
  app/services/products_renderer.rb
  app/views/spree/admin/orders/_form.html.haml
  app/views/spree/admin/variants/_autocomplete.js.erb
  db/migrate/20190313142051_set_default_stock_location_on_shipments.rb
  db/migrate/20250108234658_allow_null_stock_location_id_on_spree_stock_items.rb
  db/schema.rb
  db/seeds.rb
  engines/dfc_provider/app/services/catalog_item_builder.rb
  engines/dfc_provider/spec/services/supplied_product_builder_spec.rb
  engines/order_management/app/services/order_management/stock/coordinator.rb
  engines/order_management/app/services/order_management/stock/package.rb
  engines/order_management/app/services/order_management/stock/packer.rb
  engines/order_management/spec/services/order_management/stock/package_spec.rb
  engines/order_management/spec/services/order_management/stock/packer_spec.rb
  engines/order_management/spec/services/order_management/stock/prioritizer_spec.rb
  spec/controllers/api/v0/products_controller_spec.rb
  spec/controllers/api/v0/shipments_controller_spec.rb
  spec/controllers/spree/admin/products_controller_spec.rb
  spec/factories/product_factory.rb
  spec/factories/shipment_factory.rb
  spec/factories/stock_factory.rb
  spec/factories/stock_location_factory.rb
  spec/factories/variant_factory.rb
  spec/lib/tasks/sample_data_rake_spec.rb
  spec/models/concerns/variant_stock_spec.rb
  spec/models/spree/inventory_unit_spec.rb
  spec/models/spree/order_inventory_spec.rb
  spec/models/spree/product_spec.rb
  spec/models/spree/shipment_spec.rb
  spec/models/spree/stock_item_spec.rb
  spec/models/spree/stock_location_spec.rb
  spec/models/spree/stock_movement_spec.rb
  spec/models/spree/variant_spec.rb
  spec/models/spree/variant_stock_spec.rb
  spec/serializers/api/admin/variant_serializer_spec.rb
  spec/services/default_stock_location_spec.rb
  spec/services/sets/product_set_spec.rb
  spec/system/admin/bulk_order_management_spec.rb
  spec/system/admin/order_spec.rb
  spec/system/admin/products_spec.rb
  spec/system/admin/products_v3/create_spec.rb
  spec/system/admin/unit_price_spec.rb
Labels: pr-staged-au, technical changes only

#13093 Handle wrong OIDC tokens gracefully
  engines/dfc_provider/app/services/authorization_control.rb
  engines/dfc_provider/spec/services/authorization_control_spec.rb
Labels: technical changes only

#13096 Compile assets on demand in test local environment
  .github/workflows/build.yml
  config/webpacker.yml
  spec/support/precompile_assets.rb
Labels: technical changes only

#13098 Specify OpenStreetMap marker size and tip position so they are positioned correctly at all zoom levels
  app/assets/javascripts/darkswarm/directives/open_street_map.js.coffee
Labels: user facing changes

#13103 Simplify default country code lookup
  .github/workflows/build.yml
  app/services/default_country.rb
Labels: technical changes only

#13108 Log rack-timeout ready and completed messages in DEBUG mode
  config/initializers/rack_timeout.rb
Labels: technical changes only

#13090 Replace spree roles
  app/controllers/spree/admin/users_controller.rb
  app/models/spree/role.rb
  app/models/spree/user.rb
  app/views/spree/admin/users/_form.html.haml
  config/locales/en.yml
  db/default/users.rb
  db/migrate/20250107013958_add_admin_to_spree_users.rb
  db/migrate/20250107014617_copy_admin_attribute_to_users.rb
  db/schema.rb
  spec/controllers/admin/order_cycles_controller_spec.rb
  spec/controllers/spree/admin/payment_methods_controller_spec.rb
  spec/controllers/spree/admin/users_controller_spec.rb
  spec/factories/user_factory.rb
  spec/lib/reports/customers_report_spec.rb
  spec/lib/reports/order_cycle_management_report_spec.rb
  spec/lib/reports/products_and_inventory_report_spec.rb
  spec/models/enterprise_group_spec.rb
  spec/models/enterprise_spec.rb
  spec/models/exchange_spec.rb
  spec/models/order_cycle_spec.rb
  spec/models/spree/ability_spec.rb
  spec/models/spree/product_spec.rb
  spec/models/spree/user_spec.rb
  spec/support/controller_helper.rb
  spec/system/admin/configuration/shipping_categories_spec.rb
  spec/system/admin/multilingual_spec.rb
Labels: technical changes only

#13086 Remove tax rate refund code path
  app/models/spree/tax_rate.rb
  app/models/spree/zone.rb
  app/views/spree/admin/zones/index.html.haml
  app/views/spree/admin/zones/new.html.haml
  db/default/zones.rb
  lib/tasks/sample_data/addressing.rb
  spec/factories/zone_factory.rb
  spec/helpers/spree/base_helper_spec.rb
  spec/models/invoice/data_presenter_spec.rb
  spec/models/spree/tax_rate_spec.rb
  spec/models/spree/zone_spec.rb
  spec/system/admin/adjustments_spec.rb
  spec/system/admin/configuration/tax_rates_spec.rb
  spec/system/admin/configuration/zones_spec.rb
Labels: pr-staged-au

#13104 Remove unused preference default_country_id
  app/models/spree/app_configuration.rb
  db/migrate/20250128031518_delete_default_country_id_preference.rb
  db/schema.rb
  spec/base_spec_helper.rb
  spec/support/seeds.rb
Labels: technical changes only
