Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2025-03, with the labels that each got.

#13183 Add task to reset database with sample data
  lib/tasks/reset.rake
Labels: technical changes only

#13171 Remove true as select default first option
  app/views/admin/enterprise_fees/index.html.haml
Labels: pr-staged-au, user facing changes

#13187 Add shipment state to OC customer totals report
  lib/reporting/reports/orders_and_fulfillment/order_cycle_customer_totals.rb
  spec/lib/reports/orders_and_fulfillment/order_cycle_customer_totals_report_spec.rb
Labels: pr-staged-au

#13189 Page is redirected to root after login from shopfront page
  app/controllers/enterprises_controller.rb
Labels: bug-s4, pr-staged-uk, pr-staged-au, user facing changes

#13196 Fail Reviewdog Rubocop check on any found issues
  .github/workflows/linters.yml
Labels: technical changes only

#13200 Make sure the first page load is complete before updating database
  spec/system/consumer/caching/shops_caching_spec.rb
Labels: technical changes only

#13202 Ensure we test for the right text after AJAX loads filters
  spec/system/consumer/caching/shops_caching_spec.rb
Labels: technical changes only

#13144 Update line items enterprise fee instead of deleting and recreating
  app/models/enterprise_fee.rb
  app/models/spree/order.rb
  app/services/orders/handle_fees_service.rb
  lib/open_food_network/enterprise_fee_calculator.rb
  spec/lib/open_food_network/enterprise_fee_calculator_spec.rb
  spec/models/enterprise_fee_spec.rb
  spec/models/spree/order_spec.rb
  spec/services/orders/handle_fees_service_spec.rb
Labels: bug-s2, pr-staged-fr, feedback-needed, user facing changes

#13209 Fixes some rubocop linting offenses - part IV
  .rubocop_todo.yml
  engines/catalog/config/routes.rb
  spec/components/distributor_title_component_spec.rb
  spec/components/example_component_spec.rb
  spec/controllers/admin/subscription_line_items_controller_spec.rb
  spec/controllers/api/v0/shipments_controller_spec.rb
  spec/controllers/concerns/extra_fields_spec.rb
  spec/factories.rb
  spec/factories/enterprise_factory.rb
  spec/jobs/order_cycle_opened_job_spec.rb
  spec/jobs/subscription_placement_job_spec.rb
  spec/models/product_import/entry_validator_spec.rb
Labels: technical changes only

#13182 Rescue from invalid DFC catalog URLs
  app/controllers/admin/dfc_product_imports_controller.rb
  config/locales/en.yml
  engines/dfc_provider/app/services/dfc_catalog.rb
  spec/system/admin/dfc_product_import_spec.rb
Labels: user facing changes

#13197 Fix obscure issue when choosing payment method in checkout
  app/services/orders/workflow_service.rb
  app/views/checkout/_tabs.html.haml
  spec/controllers/checkout_controller_spec.rb
Labels: pr-staged-fr, user facing changes

#13201 Categorise breaking-change labels in release notes
  .github/ISSUE_TEMPLATE/release.md
  .github/release.yml
Labels: technical changes only, major breaking change

#13207 Gracefully handle product missing from catalog
  app/jobs/backorder_job.rb
  spec/jobs/backorder_job_spec.rb
Labels: technical changes only

#13167 [DFC Orders] Sync remote products when order cycle opens
  .env.test
  app/jobs/open_order_cycle_job.rb
  app/jobs/order_cycle_closing_job.rb
  app/jobs/order_cycle_opened_job.rb
  app/jobs/trigger_order_cycles_to_open_job.rb
  app/jobs/webhook_delivery_job.rb
  app/services/order_cycles/webhook_service.rb
  config/sidekiq.yml
  spec/factories/oidc_account_factory.rb
  spec/fixtures/vcr_cassettes/OpenOrderCycleJob/syncing_remote_products/synchronises_products_from_a_FDC_catalog.yml
  spec/jobs/open_order_cycle_job_spec.rb
  spec/jobs/order_cycle_opened_job_spec.rb
  spec/jobs/trigger_order_cycles_to_open_job_spec.rb
  spec/jobs/webhook_delivery_job_spec.rb
  spec/services/order_cycles/webhook_service_spec.rb
Labels: user facing changes

#13176 Add a 'reply to' email address to some more emails
  app/mailers/payment_mailer.rb
  app/mailers/spree/order_mailer.rb
  app/views/payment_mailer/authorization_required.html.haml
  app/views/payment_mailer/authorization_required.text.haml
Labels: pr-staged-au, user facing changes

#13227 Autocorrect rubocop offenses Style/RedundantAssignment and Style/RedundantArgument
  .rubocop_todo.yml
  engines/dfc_provider/app/services/authorization_control.rb
  spec/models/database_spec.rb
Labels: technical changes only

#13228 [Enterprise fees] Add system testing for various enterprise fees
  spec/system/admin/order_spec.rb
Labels: technical changes only

#13214 Fix expand notes field when editing order
  app/views/spree/admin/orders/_note.html.haml
Labels: bug-s4, pr-staged-fr, user facing changes

#13230 Adds tests to recent reply_to email changes
  spec/base_spec_helper.rb
  spec/mailers/enterprise_mailer_spec.rb
  spec/mailers/order_mailer_spec.rb
  spec/mailers/payment_mailer_spec.rb
  spec/mailers/producer_mailer_spec.rb
  spec/mailers/shipment_mailer_spec.rb
  spec/support/mailers_helper.rb
Labels: technical changes only

#13229 Add basque language
  config/locales/eu.yml
Labels: user facing changes

#13234 Bump rspec-sql from 0.0.2 to 0.0.3
  Gemfile.lock
Labels: technical changes only

#13235 [API change] Remove unused ProductStock concern
  app/models/concerns/product_stock.rb
  app/models/spree/product.rb
  app/serializers/api/admin/product_serializer.rb
  spec/controllers/api/v0/products_controller_spec.rb
  spec/models/concerns/product_stock_spec.rb
  spec/models/product_importer_spec.rb
  spec/system/admin/product_import_spec.rb
Labels: api changes

#13236 Alert us to deprecation warnings
  config/environments/test.rb
  config/initializers/deprecations.rb
  lib/reporting/reports/bulk_coop/customer_payments.rb
Labels: technical changes only

#13239 Fixes rubocop offense inverse_of on payment model
  .rubocop_todo.yml
  app/models/spree/payment.rb
  spec/models/spree/payment_spec.rb
Labels: technical changes only
