Repository openfoodfoundation/openfoodnetwork, pull requests merged in 2025-07, with the labels that each got.

#13407 CI - Do not run undercover CI step on the master branch
  .github/workflows/build.yml
Labels: technical changes only

#13338 Allow producer who are also seller to edit their products on hubs' orders
  app/assets/javascripts/admin/line_items/controllers/line_items_controller.js.coffee
  app/assets/javascripts/admin/orders/controllers/order_controller.js.coffee
  app/assets/javascripts/admin/utils/directives/variant_autocomplete.js.coffee
  app/controllers/spree/admin/variants_controller.rb
  app/helpers/spree/admin/orders_helper.rb
  app/models/spree/ability.rb
  app/models/spree/line_item.rb
  app/models/spree/order.rb
  app/serializers/api/admin/order_serializer.rb
  app/services/permissions/order.rb
  app/views/spree/admin/orders/_form.html.haml
  app/views/spree/admin/orders/_table_row.html.haml
  app/views/spree/admin/orders/edit.html.haml
  lib/open_food_network/scope_variants_for_search.rb
  lib/reporting/line_items.rb
  spec/controllers/spree/admin/variants_controller_spec.rb
  spec/lib/open_food_network/scope_variants_for_search_spec.rb
  spec/lib/reports/orders_and_distributors_report_spec.rb
  spec/system/admin/orders/having_producer_products/hub_actions_spec.rb
  spec/system/admin/orders/having_producer_products/producer_actions_spec.rb
  spec/views/spree/admin/orders/edit.html.haml_spec.rb
Labels: pr-staged-au, user facing changes

#13403 Do not try to generate a URL for unpersisted blobs in development/test environment
  app/models/application_record.rb
  engines/dfc_provider/spec/services/supplied_product_importer_spec.rb
Labels: technical changes only

#13431 Bump undercover to 0.7.4
  Gemfile.lock
Labels: dependencies

#13414 Remove unused instance variable
  lib/open_food_network/scope_variant_to_hub.rb
Labels: technical changes only

#13434 Provide open port for private address test
  spec/jobs/webhook_delivery_job_spec.rb
Labels: technical changes only
